# BLOK 6 — Panel dyspozytora i rekomendacje relokacji rowerów

**Struktura notebooka**

- Opis otwierający — Operacyjny panel dyspozytora, rekomendacje relokacji i warstwa decyzyjna dla systemu rowerowego

- Dział 6.1 — Definicja decyzji dyspozytora
  - 6.1.1 — Definicja decyzji dyspozytora
  - 6.1.2 — Wczytanie i kontrola źródeł decyzji dyspozytora
  - 6.1.3 — Inspekcja kandydatów źródeł i kolumn operacyjnych
  - 6.1.4 — Identyfikacja pełnej warstwy godzinowej
  - 6.1.5 — Wybór kanonicznych źródeł BLOKU 6
  - 6.1.6 — Kontrola schematów kanonicznych źródeł operacyjnych
  - 6.1.7 — Zamknięcie kontraktu decyzji dyspozytora

- Dział 6.2 — Warstwa kierunku problemu: brak czy nadmiar rowerów
  - 6.2.1 — Definicja kontraktu kierunku problemu
  - 6.2.2 — Kontrola kolumn źródła kierunku problemu
  - 6.2.3 — Wczytanie kolumn kierunku problemu
  - 6.2.4 — Budowa godzinowego kierunku problemu
  - 6.2.5 — Agregacja kierunku problemu do poziomu dzień-stacja
  - 6.2.6 — Kontrola spójności dziennego kierunku problemu
  - 6.2.7 — Zamknięcie kontraktu kierunku problemu

- Dział 6.3 — Warstwa rekomendacji: dowieź / zabierz / sprawdź
  - 6.3.1 — Definicja kontraktu rekomendacji operacyjnej
  - 6.3.2 — Budowa rekomendacji operacyjnej
  - 6.3.3 — Kontrola spójności rekomendacji operacyjnej
  - 6.3.4 — Zamknięcie kontraktu rekomendacji operacyjnej

- Dział 6.4 — Godzina największego ryzyka
  - 6.4.1 — Definicja kontraktu godziny największego ryzyka
  - 6.4.2 — Budowa rankingu godzin ryzyka
  - 6.4.3 — Wybór godziny największego ryzyka
  - 6.4.4 — Zamknięcie kontraktu godziny największego ryzyka

- Dział 6.5 — Szacowana relokacja rowerów
  - 6.5.1 — Definicja kontraktu szacowanej relokacji
  - 6.5.2 — Budowa szacowanej relokacji
  - 6.5.3 — Kontrola spójności szacowanej relokacji
  - 6.5.4 — Zamknięcie kontraktu szacowanej relokacji

- Dział 6.6 — Priorytetyzacja stacji i plan dnia
  - 6.6.1 — Definicja kontraktu priorytetyzacji stacji
  - 6.6.2 — Budowa wskaźników priorytetyzacji stacji
  - 6.6.3 — Budowa planu dnia dyspozytora
  - 6.6.4 — Kontrola spójności planu dnia dyspozytora
  - 6.6.5 — Zamknięcie kontraktu priorytetyzacji stacji

- Dział 6.7 — Mikrostrefy i lokalne balansowanie
  - 6.7.1 — Definicja kontraktu mikrostref i lokalnego balansowania
  - 6.7.2 — Dołączenie identyfikatora mikrostrefy do planu dnia
  - 6.7.3 — Budowa podsumowania mikrostref
  - 6.7.4 — Budowa lokalnych par kompensacyjnych w mikrostrefach
  - 6.7.5 — Kontrola spójności mikrostref i lokalnego balansowania
  - 6.7.6 — Zamknięcie warstwy mikrostref i lokalnego balansowania

- Dział 6.8 — Pewność rekomendacji
  - 6.8.1 — Definicja kontraktu pewności rekomendacji
  - 6.8.2 — Budowa wskaźnika pewności rekomendacji
  - 6.8.3 — Kontrola spójności pewności rekomendacji
  - 6.8.4 — Zamknięcie warstwy pewności rekomendacji

- Dział 6.9 — Mapa działań i mapa relokacji
  - 6.9.1 — Definicja kontraktu mapy działań i mapy relokacji
  - 6.9.2 — Weryfikacja źródeł współrzędnych stacji
  - 6.9.3 — Weryfikacja schematów źródeł współrzędnych stacji
  - 6.9.4 — Wybór źródła współrzędnych stacji
  - 6.9.5 — Dołączenie współrzędnych do planu mapy
  - 6.9.6 — Budowa pól mapowych dla stacji
  - 6.9.7 — Przygotowanie dziennego widoku mapy
  - 6.9.8 — Budowa mapy działań dla wybranego dnia
  - 6.9.9 — Weryfikacja zapisanego pliku mapy działań
  - 6.9.10 — Przygotowanie warstwy linii relokacji

- Dział 6.10 — Aplikacja dyspozytorska
  - 6.10.1 — Definicja kontraktu aplikacji dyspozytorskiej
  - 6.10.2 — Weryfikacja artefaktów wejściowych aplikacji
  - 6.10.3 — Definicja pól widocznych w aplikacji
  - 6.10.4 — Definicja etykiet użytkownika aplikacji
  - 6.10.5 — Definicja statusów i komunikatów aplikacji
  - 6.10.6 — Definicja filtrów i KPI aplikacji

- Dział 6.11 — Karta pracy dla kierowcy
  - 6.11.1 — Kontrakt karty pracy kierowcy
  - 6.11.2 — Weryfikacja źródła danych karty kierowcy
  - 6.11.3 — Budowa warstwy zadań kierowcy
  - 6.11.4 — Przygotowanie dziennego widoku kart kierowcy

- Dział 6.12 — Feedback loop / data flywheel
  - 6.12.1 — Kontrakt pętli zwrotnej z operacji
  - 6.12.2 — Weryfikacja źródła zadań i statusów feedbacku
  - 6.12.3 — Budowa przykładowego wpisu feedbacku
  - 6.12.4 — Walidacja zapisu logu feedbacku
  - 6.12.5 — Przygotowanie agregacji feedbacku operacyjnego
  - 6.12.6 — Przygotowanie kontraktu zapisu feedbacku w aplikacji

- Dział 6.13 — Mikro-interakcje i postęp dnia
  - 6.13.1 — Kontrakt mikro-interakcji i postępu dnia
  - 6.13.2 — Symulacja postępu dnia po zmianie statusu zadania
  - 6.13.3 — Symulacja statusów niewykonujących zadania
  - 6.13.4 — Walidacja końcowa mikro-interakcji i postępu dnia

- Dział 6.14 — Odbiór końcowy BLOKU 6
  - 6.14.1 — Inwentaryzacja artefaktów odbioru końcowego
  - 6.14.2 — Walidacja języka decyzji i czytelności rekomendacji
  - 6.14.3 — Walidacja ilości relokacji i sanity check
  - 6.14.4 — Walidacja mikrostref, par kompensacyjnych i mapy
  - 6.14.5 — Walidacja kart kierowcy, feedbacku i postępu dnia
  - 6.14.6 — Walidacja spójności aplikacji technicznej i operacyjnej
  - 6.14.7 — Odbiór końcowy warstwy operacyjnej
  - 6.14.8 — Finalny status odbioru i lista artefaktów przekazania

## Executive Summary (Główne założenia biznesowe i inżynieryjne)

Niniejszy notatnik stanowi warstwę operacyjną systemu relokacji floty rowerowej. Celem BLOKU 6 jest budowa panelu dyspozytorskiego wykorzystującego wyniki inferencyjne oraz warstwę aplikacyjną przygotowaną wcześniej w BLOKU 5. BLOK 6 odpowiada za przełożenie predykcji modelowych na realne decyzje operacyjne dotyczące relokacji rowerów, priorytetyzacji stacji oraz organizacji pracy dyspozytora i kierowców.

**Kluczowe założenia analityczne i architektoniczne:**

1. **Warstwa operacyjna systemu:** BLOK 6 korzysta z gotowych artefaktów scoringowych i aplikacyjnych przygotowanych w BLOKU 5. Etap nie obejmuje treningu modeli ani budowy nowych pipeline'ów inferencyjnych.

2. **Logika decyzji dyspozytora:** System tłumaczy wyniki modelu klasyfikacyjnego na konkretne działania operacyjne: dowieź rowery, zabierz rowery lub sprawdź sytuację na stacji.

3. **Priorytetyzacja operacyjna:** Ranking stacji uwzględnia poziom ryzyka, znaczenie biznesowe stacji, kierunek problemu, wpływ na mikro-strefę oraz szacowaną skalę relokacji.

4. **Explainability operacyjne:** System prezentuje użytkownikowi interpretowalne komunikaty, poziomy pilności, godziny największego ryzyka oraz uzasadnienie rekomendacji relokacyjnych.

5. **Warstwa wizualna i workflow:** BLOK 6 odpowiada za budowę dashboardów operacyjnych, map relokacji, kart pracy kierowców, statusów realizacji oraz logiki postępu dnia operacyjnego.

6. **Feedback loop:** System przygotowuje warstwę sprzężenia zwrotnego umożliwiającą rejestrowanie wykonanych działań operacyjnych i przyszłą integrację z kolejnymi iteracjami pipeline'u ML.

---

## Struktura Notatnika

**6.1 Definicja decyzji dyspozytora**  
Budowa kontraktu operacyjnego BLOKU 6. Etap obejmuje identyfikację źródeł danych operacyjnych, wybór kanonicznych warstw godzinowych oraz definicję logiki decyzji dyspozytora.

**6.2 Warstwa kierunku problemu: brak czy nadmiar rowerów**  
Budowa logiki kierunku problemu operacyjnego. Etap obejmuje identyfikację stacji zagrożonych brakiem lub nadmiarem rowerów oraz agregację problemu do poziomu dzień–stacja.

**6.3 Warstwa rekomendacji: dowieź / zabierz / sprawdź**  
Budowa rekomendacji relokacyjnych dla dyspozytora. Etap obejmuje logikę rekomendowanych działań operacyjnych oraz walidację spójności rekomendacji.

**6.4 Godzina największego ryzyka**  
Budowa warstwy ryzyka czasowego. Etap obejmuje ranking godzin ryzyka oraz identyfikację najbardziej krytycznych momentów operacyjnych dla stacji.

**6.5 Szacowana relokacja rowerów**  
Budowa logiki szacowanej relokacji. Etap obejmuje określenie przybliżonej liczby rowerów wymagających relokacji oraz kontrolę spójności rekomendacji.

**6.6 Priorytetyzacja stacji i plan dnia**  
Budowa rankingu operacyjnego stacji. Etap obejmuje wyznaczenie priorytetów działań, planu dnia dyspozytora oraz kolejności obsługi stacji.

**6.7 Mikrostrefy i lokalne balansowanie**  
Budowa logiki mikro-stref i kompensacji lokalnej. Etap obejmuje identyfikację lokalnych przepływów rowerów, budowę par kompensacyjnych oraz analizę równowagi operacyjnej.

**6.8 Pewność rekomendacji**  
Budowa warstwy confidence score dla rekomendacji operacyjnych. Etap obejmuje ocenę stabilności sygnałów oraz poziomu pewności rekomendowanych działań.

**6.9 Mapa działań i mapa relokacji**  
Budowa operacyjnej warstwy mapowej. Etap obejmuje integrację współrzędnych stacji, budowę map działań oraz wizualizację relokacji i przepływów operacyjnych.

**6.10 Aplikacja dyspozytorska**  
Budowa finalnej warstwy aplikacyjnej panelu dyspozytora. Etap obejmuje konfigurację widoków, KPI, filtrów, komunikatów użytkownika oraz logiki działania aplikacji.

**6.11 Karta pracy dla kierowcy**  
Budowa warstwy operacyjnej dla kierowców relokacyjnych. Etap obejmuje generowanie list zadań, dziennych tras oraz kart realizacyjnych.

**6.12 Feedback loop / data flywheel**  
Budowa warstwy sprzężenia zwrotnego systemu. Etap obejmuje zapis wykonanych działań, statusów operacyjnych oraz przygotowanie logiki future retraining pipeline.

**6.13 Mikro-interakcje i postęp dnia**  
Budowa logiki statusów realizacji i postępu operacyjnego. Etap obejmuje obsługę workflow zadań, zmian statusów oraz monitoring przebiegu dnia operacyjnego.

**6.14 Odbiór końcowy BLOKU 6**  
Finalna walidacja warstwy operacyjnej systemu. Etap obejmuje kontrolę spójności aplikacji, sanity check rekomendacji, walidację map, workflow kierowców oraz przygotowanie finalnych artefaktów odbiorowych.

## Dział 6.1 — Definicja decyzji dyspozytora

In [1]:
# 6.1.1 Definicja decyzji dyspozytora

from pathlib import Path
import json

import pandas as pd


step6_11_current_dir = Path.cwd().resolve()

step6_11_search_roots = [
    step6_11_current_dir,
    step6_11_current_dir.parent,
    step6_11_current_dir.parent.parent,
    Path("/root/projects/6_samodzielny_projekt_koncowy_wsl"),
    Path("/mnt/c/Users/User/Desktop/6_samodzielny_projekt_koncowy"),
]

step6_11_search_roots = [
    root_path.resolve()
    for root_path in step6_11_search_roots
    if root_path.exists()
]

step6_11_required_source_files = {
    "hourly_station_alert_view": "hourly_station_alert_view.parquet",
    "hourly_station_alert_prediction_view": "hourly_station_alert_prediction_view.parquet",
    "station_capacity_reference": "station_capacity_reference.parquet",
}

step6_11_source_records = []

for source_role, file_name in step6_11_required_source_files.items():
    path_candidates = []

    for root_order, root_path in enumerate(step6_11_search_roots):
        for file_path in sorted(root_path.rglob(file_name)):
            resolved_file_path = file_path.resolve()

            path_candidates.append(
                {
                    "source_role": source_role,
                    "file_name": file_name,
                    "root_order": root_order,
                    "path_depth": len(resolved_file_path.parts),
                    "resolved_path": str(resolved_file_path),
                }
            )

    candidate_df = pd.DataFrame(path_candidates)

    if candidate_df.empty:
        step6_11_source_records.append(
            {
                "source_role": source_role,
                "file_name": file_name,
                "candidate_count": 0,
                "status": "missing",
                "selected_path": None,
            }
        )
        continue

    candidate_df = (
        candidate_df.drop_duplicates(subset=["resolved_path"])
        .sort_values(["root_order", "path_depth", "resolved_path"])
        .reset_index(drop=True)
    )

    selected_path = candidate_df.loc[0, "resolved_path"]

    step6_11_source_records.append(
        {
            "source_role": source_role,
            "file_name": file_name,
            "candidate_count": int(candidate_df.shape[0]),
            "status": "ok",
            "selected_path": selected_path,
        }
    )

step6_11_source_inventory_df = pd.DataFrame(step6_11_source_records)

step6_11_missing_files = step6_11_source_inventory_df.loc[
    step6_11_source_inventory_df["status"] == "missing",
    "file_name",
].tolist()

assert not step6_11_missing_files, f"Missing required source files: {step6_11_missing_files}"

step6_11_source_paths = {
    row["source_role"]: Path(row["selected_path"])
    for _, row in step6_11_source_inventory_df.iterrows()
}

step6_11_outputs_dir = step6_11_current_dir / "outputs_dispatcher_panel"
step6_11_reports_dir = step6_11_current_dir / "reports_dispatcher_panel"
step6_11_runtime_dir = step6_11_current_dir / "runtime_dispatcher_panel"

for directory_path in [
    step6_11_outputs_dir,
    step6_11_reports_dir,
    step6_11_runtime_dir,
]:
    directory_path.mkdir(parents=True, exist_ok=True)

step6_11_dispatcher_decision_fields = [
    {
        "field_name": "priority_level",
        "display_name": "priority",
        "allowed_values": ["very_high", "high", "medium", "low"],
        "main_screen": True,
    },
    {
        "field_name": "problem_type",
        "display_name": "risk_type",
        "allowed_values": ["bike_shortage_risk", "dock_shortage_risk", "mixed_risk"],
        "main_screen": True,
    },
    {
        "field_name": "recommended_action",
        "display_name": "recommended_action",
        "allowed_values": ["deliver_bikes", "remove_bikes", "check_station_state"],
        "main_screen": True,
    },
    {
        "field_name": "highest_risk_hour",
        "display_name": "highest_risk_hour",
        "allowed_values": ["hour_or_hour_window"],
        "main_screen": True,
    },
    {
        "field_name": "estimated_relocation",
        "display_name": "estimated_relocation",
        "allowed_values": ["estimated_range"],
        "main_screen": True,
    },
    {
        "field_name": "recommendation_confidence",
        "display_name": "recommendation_confidence",
        "allowed_values": ["high", "medium", "low"],
        "main_screen": True,
    },
    {
        "field_name": "decision_reason",
        "display_name": "decision_reason",
        "allowed_values": ["business_explanation"],
        "main_screen": True,
    },
]

step6_11_dispatcher_decision_fields_df = pd.DataFrame(step6_11_dispatcher_decision_fields)

step6_11_dispatcher_decision_fields_df["allowed_values"] = (
    step6_11_dispatcher_decision_fields_df["allowed_values"]
    .apply(lambda value: json.dumps(value, ensure_ascii=False))
    .astype("string")
)

step6_11_dispatcher_decision_fields_df["field_name"] = (
    step6_11_dispatcher_decision_fields_df["field_name"].astype("string")
)

step6_11_dispatcher_decision_fields_df["display_name"] = (
    step6_11_dispatcher_decision_fields_df["display_name"].astype("string")
)

step6_11_dispatcher_decision_fields_df["main_screen"] = (
    step6_11_dispatcher_decision_fields_df["main_screen"].astype("bool")
)

step6_11_decision_contract = {
    "block_name": "block_6",
    "section_name": "6.1",
    "section_scope": "dispatcher_decision_definition",
    "grain": "station_decision_view",
    "builds_new_model": False,
    "uses_raw_model_fields_on_main_screen": False,
    "uses_exact_live_station_inventory": False,
    "uses_estimated_relocation": True,
    "main_sources": {
        source_role: str(source_path)
        for source_role, source_path in step6_11_source_paths.items()
    },
    "main_decision_fields": step6_11_dispatcher_decision_fields,
    "technical_fields_hidden_from_main_screen": [
        "predicted_probability",
        "predicted_label",
    ],
}

step6_11_source_inventory_path = step6_11_reports_dir / "b6_01_source_inventory.parquet"
step6_11_decision_fields_path = step6_11_reports_dir / "b6_01_dispatcher_decision_fields.parquet"
step6_11_decision_contract_path = step6_11_reports_dir / "b6_01_dispatcher_decision_contract.json"

step6_11_source_inventory_df.to_parquet(step6_11_source_inventory_path, index=False)
step6_11_dispatcher_decision_fields_df.to_parquet(step6_11_decision_fields_path, index=False)

with open(step6_11_decision_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_11_decision_contract, file, ensure_ascii=False, indent=2)

step6_11_summary_df = pd.DataFrame(
    [
        {
            "check_area": "required_sources",
            "status": "ok",
            "value": int(step6_11_source_inventory_df.shape[0]),
        },
        {
            "check_area": "dispatcher_fields",
            "status": "ok",
            "value": int(step6_11_dispatcher_decision_fields_df.shape[0]),
        },
        {
            "check_area": "raw_model_fields_on_main_screen",
            "status": "ok",
            "value": False,
        },
        {
            "check_area": "exact_live_inventory_claim",
            "status": "ok",
            "value": False,
        },
        {
            "check_area": "source_inventory_path",
            "status": "ok",
            "value": str(step6_11_source_inventory_path),
        },
        {
            "check_area": "decision_fields_path",
            "status": "ok",
            "value": str(step6_11_decision_fields_path),
        },
        {
            "check_area": "decision_contract_path",
            "status": "ok",
            "value": str(step6_11_decision_contract_path),
        },
    ]
)

display(step6_11_summary_df)
display(step6_11_source_inventory_df)
display(step6_11_dispatcher_decision_fields_df)

,check_area,status,value
0,required_sources,ok,3
1,dispatcher_fields,ok,7
2,raw_model_fields_on_main_screen,ok,False
3,exact_live_inventory_claim,ok,False
4,source_inventory_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,decision_fields_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,decision_contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,source_role,file_name,candidate_count,status,selected_path
0,hourly_station_alert_view,hourly_station_alert_view.parquet,5,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
1,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,4,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
2,station_capacity_reference,station_capacity_reference.parquet,5,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,field_name,display_name,allowed_values,main_screen
0,priority_level,priority,"[""very_high"", ""high"", ""medium"", ""low""]",True
1,problem_type,risk_type,"[""bike_shortage_risk"", ""dock_shortage_risk"", ""...",True
2,recommended_action,recommended_action,"[""deliver_bikes"", ""remove_bikes"", ""check_stati...",True
3,highest_risk_hour,highest_risk_hour,"[""hour_or_hour_window""]",True
4,estimated_relocation,estimated_relocation,"[""estimated_range""]",True
5,recommendation_confidence,recommendation_confidence,"[""high"", ""medium"", ""low""]",True
6,decision_reason,decision_reason,"[""business_explanation""]",True

In [2]:
# 6.1.2 Wczytanie i kontrola źródeł decyzji dyspozytora

import pandas as pd


step6_12_required_objects = [
    "step6_11_source_paths",
    "step6_11_reports_dir",
]

step6_12_missing_objects = [
    object_name
    for object_name in step6_12_required_objects
    if object_name not in globals()
]

assert not step6_12_missing_objects, f"Missing required objects: {step6_12_missing_objects}"

step6_12_hourly_alert_df = pd.read_parquet(
    step6_11_source_paths["hourly_station_alert_view"]
)

step6_12_hourly_prediction_df = pd.read_parquet(
    step6_11_source_paths["hourly_station_alert_prediction_view"]
)

step6_12_capacity_df = pd.read_parquet(
    step6_11_source_paths["station_capacity_reference"]
)

step6_12_loaded_sources = {
    "hourly_station_alert_view": step6_12_hourly_alert_df,
    "hourly_station_alert_prediction_view": step6_12_hourly_prediction_df,
    "station_capacity_reference": step6_12_capacity_df,
}

step6_12_source_profile_records = []

for source_name, source_df in step6_12_loaded_sources.items():
    duplicate_columns_count = int(source_df.columns.duplicated().sum())
    missing_columns_count = int(source_df.columns.isna().sum())
    memory_usage_mb = float(source_df.memory_usage(deep=True).sum() / 1024**2)

    date_columns = [
        column_name
        for column_name in source_df.columns
        if "date" in column_name.lower() or "time" in column_name.lower() or "hour" in column_name.lower()
    ]

    station_columns = [
        column_name
        for column_name in source_df.columns
        if "station" in column_name.lower()
    ]

    capacity_columns = [
        column_name
        for column_name in source_df.columns
        if "capacity" in column_name.lower()
    ]

    step6_12_source_profile_records.append(
        {
            "source_name": source_name,
            "row_count": int(source_df.shape[0]),
            "column_count": int(source_df.shape[1]),
            "duplicate_columns_count": duplicate_columns_count,
            "missing_columns_count": missing_columns_count,
            "memory_usage_mb": round(memory_usage_mb, 3),
            "date_like_columns": ", ".join(date_columns),
            "station_like_columns": ", ".join(station_columns),
            "capacity_like_columns": ", ".join(capacity_columns),
        }
    )

step6_12_source_profile_df = pd.DataFrame(step6_12_source_profile_records)

step6_12_required_column_candidates = {
    "hourly_station_alert_view": {
        "station_id": ["station_id", "representative_station_id"],
        "hour": ["hour", "activity_hour", "hour_start", "timestamp", "datetime"],
        "capacity": ["estimated_capacity"],
        "bike_shortage_signal": [
            "departure_stockout_flag",
            "bike_shortage_flag",
            "stockout_departure_flag",
            "is_departure_stockout",
        ],
        "dock_shortage_signal": [
            "return_stockout_flag",
            "dock_shortage_flag",
            "stockout_return_flag",
            "is_return_stockout",
        ],
    },
    "hourly_station_alert_prediction_view": {
        "station_id": ["station_id", "representative_station_id"],
        "hour": ["hour", "activity_hour", "hour_start", "timestamp", "datetime"],
    },
    "station_capacity_reference": {
        "station_id": ["station_id", "representative_station_id"],
        "capacity": ["estimated_capacity"],
    },
}

step6_12_column_resolution_records = []

for source_name, expected_groups in step6_12_required_column_candidates.items():
    source_columns = set(step6_12_loaded_sources[source_name].columns)

    for semantic_role, candidate_columns in expected_groups.items():
        matched_columns = [
            column_name
            for column_name in candidate_columns
            if column_name in source_columns
        ]

        step6_12_column_resolution_records.append(
            {
                "source_name": source_name,
                "semantic_role": semantic_role,
                "matched_column": matched_columns[0] if matched_columns else None,
                "candidate_columns": json.dumps(candidate_columns, ensure_ascii=False),
                "status": "ok" if matched_columns else "missing",
            }
        )

step6_12_column_resolution_df = pd.DataFrame(step6_12_column_resolution_records)

step6_12_missing_required_roles = step6_12_column_resolution_df.loc[
    step6_12_column_resolution_df["status"] == "missing",
    ["source_name", "semantic_role", "candidate_columns"],
].copy()

step6_12_source_profile_path = step6_11_reports_dir / "b6_02_source_profile.parquet"
step6_12_column_resolution_path = step6_11_reports_dir / "b6_02_column_resolution.parquet"

step6_12_source_profile_df.to_parquet(step6_12_source_profile_path, index=False)
step6_12_column_resolution_df.to_parquet(step6_12_column_resolution_path, index=False)

step6_12_summary_df = pd.DataFrame(
    [
        {
            "check_area": "loaded_sources",
            "status": "ok",
            "value": int(len(step6_12_loaded_sources)),
        },
        {
            "check_area": "hourly_alert_rows",
            "status": "ok",
            "value": int(step6_12_hourly_alert_df.shape[0]),
        },
        {
            "check_area": "hourly_prediction_rows",
            "status": "ok",
            "value": int(step6_12_hourly_prediction_df.shape[0]),
        },
        {
            "check_area": "capacity_rows",
            "status": "ok",
            "value": int(step6_12_capacity_df.shape[0]),
        },
        {
            "check_area": "missing_required_roles",
            "status": "ok" if step6_12_missing_required_roles.empty else "review",
            "value": int(step6_12_missing_required_roles.shape[0]),
        },
        {
            "check_area": "source_profile_path",
            "status": "ok",
            "value": str(step6_12_source_profile_path),
        },
        {
            "check_area": "column_resolution_path",
            "status": "ok",
            "value": str(step6_12_column_resolution_path),
        },
    ]
)

display(step6_12_summary_df)
display(step6_12_source_profile_df)
display(step6_12_column_resolution_df)

if not step6_12_missing_required_roles.empty:
    display(step6_12_missing_required_roles)

,check_area,status,value
0,loaded_sources,ok,3
1,hourly_alert_rows,ok,5
2,hourly_prediction_rows,ok,5
3,capacity_rows,ok,344
4,missing_required_roles,review,3
5,source_profile_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,column_resolution_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,source_name,row_count,column_count,duplicate_columns_count,missing_columns_count,memory_usage_mb,date_like_columns,station_like_columns,capacity_like_columns
0,hourly_station_alert_view,5,45,0,0,0.002,"activity_hour, activity_date, hour_of_day, hou...","representative_station_id, station_name, activ...","estimated_capacity, free_capacity_proxy, daily..."
1,hourly_station_alert_prediction_view,5,79,0,0,0.003,"activity_hour, activity_date, hour_of_day, hou...","representative_station_id, station_name, activ...","estimated_capacity, free_capacity_proxy, daily..."
2,station_capacity_reference,344,5,0,0,0.012,"peak_hourly_departures, peak_hourly_returns",,estimated_capacity

,source_name,semantic_role,matched_column,candidate_columns,status
0,hourly_station_alert_view,station_id,representative_station_id,"[""station_id"", ""representative_station_id""]",ok
1,hourly_station_alert_view,hour,activity_hour,"[""hour"", ""activity_hour"", ""hour_start"", ""times...",ok
2,hourly_station_alert_view,capacity,estimated_capacity,"[""estimated_capacity""]",ok
3,hourly_station_alert_view,bike_shortage_signal,NaN,"[""departure_stockout_flag"", ""bike_shortage_fla...",missing
4,hourly_station_alert_view,dock_shortage_signal,NaN,"[""return_stockout_flag"", ""dock_shortage_flag"",...",missing
5,hourly_station_alert_prediction_view,station_id,representative_station_id,"[""station_id"", ""representative_station_id""]",ok
6,hourly_station_alert_prediction_view,hour,activity_hour,"[""hour"", ""activity_hour"", ""hour_start"", ""times...",ok
7,station_capacity_reference,station_id,NaN,"[""station_id"", ""representative_station_id""]",missing
8,station_capacity_reference,capacity,estimated_capacity,"[""estimated_capacity""]",ok

,source_name,semantic_role,candidate_columns
3,hourly_station_alert_view,bike_shortage_signal,"[""departure_stockout_flag"", ""bike_shortage_fla..."
4,hourly_station_alert_view,dock_shortage_signal,"[""return_stockout_flag"", ""dock_shortage_flag"",..."
7,station_capacity_reference,station_id,"[""station_id"", ""representative_station_id""]"

In [3]:
# 6.1.3 Inspekcja kandydatów źródeł i kolumn operacyjnych

import pandas as pd


step6_13_required_objects = [
    "step6_11_search_roots",
    "step6_11_required_source_files",
    "step6_11_reports_dir",
]

step6_13_missing_objects = [
    object_name
    for object_name in step6_13_required_objects
    if object_name not in globals()
]

assert not step6_13_missing_objects, f"Missing required objects: {step6_13_missing_objects}"

step6_13_candidate_records = []
step6_13_column_records = []

step6_13_keyword_groups = {
    "station_key": ["station", "representative"],
    "time_key": ["date", "hour", "time"],
    "capacity": ["capacity"],
    "shortage_signal": ["shortage", "deficit", "departure", "stockout"],
    "overflow_signal": ["overflow", "dock", "return", "free"],
    "flow_signal": ["flow", "net", "cumulative"],
    "risk_signal": ["risk", "alert", "severity", "probability", "prediction"],
}

for source_role, file_name in step6_11_required_source_files.items():
    path_candidates = []

    for root_order, root_path in enumerate(step6_11_search_roots):
        for file_path in sorted(root_path.rglob(file_name)):
            resolved_file_path = file_path.resolve()

            path_candidates.append(
                {
                    "source_role": source_role,
                    "file_name": file_name,
                    "root_order": root_order,
                    "path_depth": len(resolved_file_path.parts),
                    "resolved_path": str(resolved_file_path),
                }
            )

    candidate_df = pd.DataFrame(path_candidates)

    if candidate_df.empty:
        continue

    candidate_df = (
        candidate_df.drop_duplicates(subset=["resolved_path"])
        .sort_values(["root_order", "path_depth", "resolved_path"])
        .reset_index(drop=True)
    )

    for candidate_rank, candidate_row in candidate_df.iterrows():
        candidate_path = Path(candidate_row["resolved_path"])

        candidate_parquet_df = pd.read_parquet(candidate_path)

        row_count = int(candidate_parquet_df.shape[0])
        column_count = int(candidate_parquet_df.shape[1])
        memory_usage_mb = float(candidate_parquet_df.memory_usage(deep=True).sum() / 1024**2)

        step6_13_candidate_records.append(
            {
                "source_role": source_role,
                "file_name": file_name,
                "candidate_rank": int(candidate_rank),
                "row_count": row_count,
                "column_count": column_count,
                "memory_usage_mb": round(memory_usage_mb, 3),
                "resolved_path": str(candidate_path),
            }
        )

        for column_name in candidate_parquet_df.columns:
            column_lower = str(column_name).lower()

            matched_groups = [
                group_name
                for group_name, keywords in step6_13_keyword_groups.items()
                if any(keyword in column_lower for keyword in keywords)
            ]

            if matched_groups:
                step6_13_column_records.append(
                    {
                        "source_role": source_role,
                        "file_name": file_name,
                        "candidate_rank": int(candidate_rank),
                        "column_name": str(column_name),
                        "matched_groups": ", ".join(matched_groups),
                        "dtype": str(candidate_parquet_df[column_name].dtype),
                        "non_null_count": int(candidate_parquet_df[column_name].notna().sum()),
                        "null_count": int(candidate_parquet_df[column_name].isna().sum()),
                        "nunique_count": int(candidate_parquet_df[column_name].nunique(dropna=True)),
                        "resolved_path": str(candidate_path),
                    }
                )

step6_13_candidate_profile_df = pd.DataFrame(step6_13_candidate_records)
step6_13_operational_columns_df = pd.DataFrame(step6_13_column_records)

step6_13_selected_candidate_df = (
    step6_13_candidate_profile_df
    .sort_values(
        ["source_role", "row_count", "column_count", "candidate_rank"],
        ascending=[True, False, False, True],
    )
    .groupby("source_role", as_index=False)
    .head(1)
    .reset_index(drop=True)
)

step6_13_candidate_profile_path = step6_11_reports_dir / "b6_03_source_candidate_profile.parquet"
step6_13_operational_columns_path = step6_11_reports_dir / "b6_03_operational_columns.parquet"
step6_13_selected_candidate_path = step6_11_reports_dir / "b6_03_selected_source_candidates.parquet"

step6_13_candidate_profile_df.to_parquet(step6_13_candidate_profile_path, index=False)
step6_13_operational_columns_df.to_parquet(step6_13_operational_columns_path, index=False)
step6_13_selected_candidate_df.to_parquet(step6_13_selected_candidate_path, index=False)

step6_13_summary_df = pd.DataFrame(
    [
        {
            "check_area": "source_candidates",
            "status": "ok",
            "value": int(step6_13_candidate_profile_df.shape[0]),
        },
        {
            "check_area": "operational_columns",
            "status": "ok",
            "value": int(step6_13_operational_columns_df.shape[0]),
        },
        {
            "check_area": "selected_sources",
            "status": "ok",
            "value": int(step6_13_selected_candidate_df.shape[0]),
        },
        {
            "check_area": "candidate_profile_path",
            "status": "ok",
            "value": str(step6_13_candidate_profile_path),
        },
        {
            "check_area": "operational_columns_path",
            "status": "ok",
            "value": str(step6_13_operational_columns_path),
        },
        {
            "check_area": "selected_candidate_path",
            "status": "ok",
            "value": str(step6_13_selected_candidate_path),
        },
    ]
)

display(step6_13_summary_df)
display(step6_13_candidate_profile_df.sort_values(["source_role", "row_count"], ascending=[True, False]))
display(step6_13_selected_candidate_df)
display(step6_13_operational_columns_df.sort_values(["source_role", "candidate_rank", "column_name"]))

,check_area,status,value
0,source_candidates,ok,14
1,operational_columns,ok,374
2,selected_sources,ok,3
3,candidate_profile_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,operational_columns_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,selected_candidate_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,source_role,file_name,candidate_rank,row_count,column_count,memory_usage_mb,resolved_path
5,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,0,5,79,0.003,/root/projects/6_samodzielny_projekt_koncowy_w...
6,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,1,5,79,0.003,/root/projects/6_samodzielny_projekt_koncowy_w...
7,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,2,5,79,0.003,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
8,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,3,5,79,0.003,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
0,hourly_station_alert_view,hourly_station_alert_view.parquet,0,5,45,0.002,/root/projects/6_samodzielny_projekt_koncowy_w...
1,hourly_station_alert_view,hourly_station_alert_view.parquet,1,5,45,0.002,/root/projects/6_samodzielny_projekt_koncowy_w...
2,hourly_station_alert_view,hourly_station_alert_view.parquet,2,5,45,0.002,/root/projects/6_samodzielny_projekt_koncowy_w...
3,hourly_station_alert_view,hourly_station_alert_view.parquet,3,5,45,0.002,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
4,hourly_station_alert_view,hourly_station_alert_view.parquet,4,5,45,0.002,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
9,station_capacity_reference,station_capacity_reference.parquet,0,344,5,0.012,/root/projects/6_samodzielny_projekt_koncowy_w...
10,station_capacity_reference,station_capacity_reference.parquet,1,344,5,0.012,/root/projects/6_samodzielny_projekt_koncowy_w...
11,station_capacity_reference,station_capacity_reference.parquet,2,344,5,0.012,/root/projects/6_samodzielny_projekt_koncowy_w...
12,station_capacity_reference,station_capacity_reference.parquet,3,344,5,0.012,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
13,station_capacity_reference,station_capacity_reference.parquet,4,344,5,0.012,/mnt/c/Users/User/Desktop/6_samodzielny_projek...

,source_role,file_name,candidate_rank,row_count,column_count,memory_usage_mb,resolved_path
0,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,0,5,79,0.003,/root/projects/6_samodzielny_projekt_koncowy_w...
1,hourly_station_alert_view,hourly_station_alert_view.parquet,0,5,45,0.002,/root/projects/6_samodzielny_projekt_koncowy_w...
2,station_capacity_reference,station_capacity_reference.parquet,0,344,5,0.012,/root/projects/6_samodzielny_projekt_koncowy_w...

,source_role,file_name,candidate_rank,column_name,matched_groups,dtype,non_null_count,null_count,nunique_count,resolved_path
141,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,0,active_station_ids,station_key,Int32,5,0,1,/root/projects/6_samodzielny_projekt_koncowy_w...
136,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,0,activity_date,time_key,datetime64[ns],5,0,1,/root/projects/6_samodzielny_projekt_koncowy_w...
135,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,0,activity_hour,time_key,datetime64[ns],5,0,5,/root/projects/6_samodzielny_projekt_koncowy_w...
188,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,0,alert_target_more_departures_than_returns,"shortage_signal, overflow_signal, risk_signal",Int32,5,0,1,/root/projects/6_samodzielny_projekt_koncowy_w...
189,hourly_station_alert_prediction_view,hourly_station_alert_prediction_view.parquet,0,alert_target_net_outflow,"flow_signal, risk_signal",Int32,5,0,1,/root/projects/6_samodzielny_projekt_koncowy_w...
...,...,...,...,...,...,...,...,...,...,...
369,station_capacity_reference,station_capacity_reference.parquet,3,peak_hourly_departures,"time_key, shortage_signal",int16,344,0,75,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
370,station_capacity_reference,station_capacity_reference.parquet,3,peak_hourly_returns,"time_key, overflow_signal",int16,344,0,72,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
371,station_capacity_reference,station_capacity_reference.parquet,4,estimated_capacity,capacity,float32,344,0,150,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
372,station_capacity_reference,station_capacity_reference.parquet,4,peak_hourly_departures,"time_key, shortage_signal",int16,344,0,75,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
373,station_capacity_reference,station_capacity_reference.parquet,4,peak_hourly_returns,"time_key, overflow_signal",int16,344,0,72,/mnt/c/Users/User/Desktop/6_samodzielny_projek...

In [4]:
# 6.1.4 Identyfikacja pełnej warstwy godzinowej

from pathlib import Path
import json

import pandas as pd
import pyarrow.parquet as pq


step6_14_required_objects = [
    "step6_11_search_roots",
    "step6_11_reports_dir",
]

step6_14_missing_objects = [
    object_name
    for object_name in step6_14_required_objects
    if object_name not in globals()
]

assert not step6_14_missing_objects, f"Missing required objects: {step6_14_missing_objects}"

step6_14_name_keywords = [
    "hour",
    "hourly",
    "alert",
    "station",
    "stockout",
    "flow",
    "prediction",
]

step6_14_column_keyword_groups = {
    "station_key": ["station", "representative"],
    "time_key": ["date", "hour", "time"],
    "capacity": ["capacity"],
    "flow": ["flow", "net", "cumulative"],
    "alert": ["alert", "risk", "severity", "stockout"],
    "shortage": ["departure", "deficit", "shortage"],
    "overflow": ["return", "overflow", "dock", "free"],
}

step6_14_candidate_records = []
step6_14_seen_paths = set()

for root_path in step6_11_search_roots:
    for file_path in sorted(root_path.rglob("*.parquet")):
        resolved_file_path = file_path.resolve()

        if str(resolved_file_path) in step6_14_seen_paths:
            continue

        step6_14_seen_paths.add(str(resolved_file_path))

        file_name_lower = resolved_file_path.name.lower()

        name_keyword_count = sum(
            keyword in file_name_lower
            for keyword in step6_14_name_keywords
        )

        if name_keyword_count == 0:
            continue

        parquet_file = pq.ParquetFile(resolved_file_path)
        parquet_schema_names = parquet_file.schema.names

        row_count = int(parquet_file.metadata.num_rows)
        column_count = int(len(parquet_schema_names))

        matched_column_groups = {}

        for group_name, keywords in step6_14_column_keyword_groups.items():
            matched_columns = [
                column_name
                for column_name in parquet_schema_names
                if any(keyword in column_name.lower() for keyword in keywords)
            ]

            matched_column_groups[group_name] = matched_columns

        matched_group_count = sum(
            len(columns) > 0
            for columns in matched_column_groups.values()
        )

        operational_score = (
            int(name_keyword_count) * 10
            + int(matched_group_count) * 20
            + min(row_count // 1000, 100)
            + min(column_count, 100)
        )

        step6_14_candidate_records.append(
            {
                "file_name": resolved_file_path.name,
                "row_count": row_count,
                "column_count": column_count,
                "name_keyword_count": int(name_keyword_count),
                "matched_group_count": int(matched_group_count),
                "operational_score": int(operational_score),
                "has_station_key": bool(len(matched_column_groups["station_key"]) > 0),
                "has_time_key": bool(len(matched_column_groups["time_key"]) > 0),
                "has_capacity": bool(len(matched_column_groups["capacity"]) > 0),
                "has_flow": bool(len(matched_column_groups["flow"]) > 0),
                "has_alert": bool(len(matched_column_groups["alert"]) > 0),
                "has_shortage": bool(len(matched_column_groups["shortage"]) > 0),
                "has_overflow": bool(len(matched_column_groups["overflow"]) > 0),
                "station_columns": json.dumps(matched_column_groups["station_key"], ensure_ascii=False),
                "time_columns": json.dumps(matched_column_groups["time_key"], ensure_ascii=False),
                "capacity_columns": json.dumps(matched_column_groups["capacity"], ensure_ascii=False),
                "flow_columns": json.dumps(matched_column_groups["flow"], ensure_ascii=False),
                "alert_columns": json.dumps(matched_column_groups["alert"], ensure_ascii=False),
                "shortage_columns": json.dumps(matched_column_groups["shortage"], ensure_ascii=False),
                "overflow_columns": json.dumps(matched_column_groups["overflow"], ensure_ascii=False),
                "resolved_path": str(resolved_file_path),
            }
        )

step6_14_candidate_df = pd.DataFrame(step6_14_candidate_records)

assert not step6_14_candidate_df.empty, "No hourly operational parquet candidates found."

step6_14_candidate_df = (
    step6_14_candidate_df
    .sort_values(
        ["operational_score", "row_count", "column_count", "file_name"],
        ascending=[False, False, False, True],
    )
    .reset_index(drop=True)
)

step6_14_candidate_df["candidate_rank"] = range(1, len(step6_14_candidate_df) + 1)

step6_14_selected_hourly_source_df = (
    step6_14_candidate_df.loc[
        (step6_14_candidate_df["has_station_key"])
        & (step6_14_candidate_df["has_time_key"])
        & (
            step6_14_candidate_df["has_alert"]
            | step6_14_candidate_df["has_flow"]
            | step6_14_candidate_df["has_shortage"]
            | step6_14_candidate_df["has_overflow"]
        )
    ]
    .sort_values(
        ["row_count", "operational_score", "column_count", "file_name"],
        ascending=[False, False, False, True],
    )
    .head(10)
    .reset_index(drop=True)
)

step6_14_candidate_path = step6_11_reports_dir / "b6_04_hourly_source_candidates.parquet"
step6_14_selected_path = step6_11_reports_dir / "b6_04_selected_hourly_source_candidates.parquet"

step6_14_candidate_df.to_parquet(step6_14_candidate_path, index=False)
step6_14_selected_hourly_source_df.to_parquet(step6_14_selected_path, index=False)

step6_14_summary_df = pd.DataFrame(
    [
        {
            "check_area": "hourly_source_candidates",
            "status": "ok",
            "value": int(step6_14_candidate_df.shape[0]),
        },
        {
            "check_area": "selected_hourly_candidates",
            "status": "ok" if not step6_14_selected_hourly_source_df.empty else "review",
            "value": int(step6_14_selected_hourly_source_df.shape[0]),
        },
        {
            "check_area": "largest_candidate_rows",
            "status": "ok",
            "value": int(step6_14_candidate_df["row_count"].max()),
        },
        {
            "check_area": "candidate_path",
            "status": "ok",
            "value": str(step6_14_candidate_path),
        },
        {
            "check_area": "selected_path",
            "status": "ok",
            "value": str(step6_14_selected_path),
        },
    ]
)

display(step6_14_summary_df)

display(
    step6_14_candidate_df[
        [
            "candidate_rank",
            "file_name",
            "row_count",
            "column_count",
            "operational_score",
            "has_station_key",
            "has_time_key",
            "has_capacity",
            "has_flow",
            "has_alert",
            "has_shortage",
            "has_overflow",
            "resolved_path",
        ]
    ].head(20)
)

display(
    step6_14_selected_hourly_source_df[
        [
            "file_name",
            "row_count",
            "column_count",
            "operational_score",
            "station_columns",
            "time_columns",
            "capacity_columns",
            "flow_columns",
            "alert_columns",
            "shortage_columns",
            "overflow_columns",
            "resolved_path",
        ]
    ]
)

,check_area,status,value
0,hourly_source_candidates,ok,144
1,selected_hourly_candidates,ok,10
2,largest_candidate_rows,ok,5257704
3,candidate_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,selected_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,candidate_rank,file_name,row_count,column_count,operational_score,has_station_key,has_time_key,has_capacity,has_flow,has_alert,has_shortage,has_overflow,resolved_path
0,1,station_alert_prediction_df.parquet,5257704,79,349,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
1,2,station_alert_prediction_df.parquet,5257704,79,349,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
2,3,station_alert_prediction_df.parquet,5257704,79,349,True,True,True,True,True,True,True,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
3,4,station_alert_prediction_df.parquet,5257704,79,349,True,True,True,True,True,True,True,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
4,5,station_alert_prediction_df_2020.parquet,1824984,79,349,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
5,6,station_alert_prediction_df_2020.parquet,1824984,79,349,True,True,True,True,True,True,True,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
6,7,station_alert_prediction_df_2019.parquet,1701528,79,349,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
7,8,station_alert_prediction_df_2019.parquet,1701528,79,349,True,True,True,True,True,True,True,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
8,9,station_alert_prediction_df_2018.parquet,1106184,79,349,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
9,10,station_alert_prediction_df_2018.parquet,1106184,79,349,True,True,True,True,True,True,True,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
10,11,station_alert_prediction_df_2017.parquet,625008,79,349,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
11,12,station_alert_prediction_df_2017.parquet,625008,79,349,True,True,True,True,True,True,True,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
12,13,station_alert_hour_df.parquet,5257704,45,315,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
13,14,station_alert_hour_df.parquet,5257704,45,315,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
14,15,station_alert_hour_df.parquet,5257704,45,315,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
15,16,station_alert_hour_df.parquet,5257704,45,315,True,True,True,True,True,True,True,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
16,17,station_alert_hour_df.parquet,5257704,45,315,True,True,True,True,True,True,True,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
17,18,station_alert_hour_df_2020.parquet,1824984,45,315,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
18,19,station_alert_hour_df_2020.parquet,1824984,45,315,True,True,True,True,True,True,True,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
19,20,station_alert_hour_df_2019.parquet,1701528,45,315,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...

,file_name,row_count,column_count,operational_score,station_columns,time_columns,capacity_columns,flow_columns,alert_columns,shortage_columns,overflow_columns,resolved_path
0,station_alert_prediction_df.parquet,5257704,79,349,"[""representative_station_id"", ""station_name"", ...","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy"", ...","[""net_flow_hour"", ""cumulative_net_flow"", ""cumu...","[""is_stockout_departure"", ""is_stockout_return""...","[""departures_hourly"", ""is_stockout_departure"",...","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/root/projects/6_samodzielny_projekt_koncowy_w...
1,station_alert_prediction_df.parquet,5257704,79,349,"[""representative_station_id"", ""station_name"", ...","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy"", ...","[""net_flow_hour"", ""cumulative_net_flow"", ""cumu...","[""is_stockout_departure"", ""is_stockout_return""...","[""departures_hourly"", ""is_stockout_departure"",...","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/root/projects/6_samodzielny_projekt_koncowy_w...
2,station_alert_prediction_df.parquet,5257704,79,349,"[""representative_station_id"", ""station_name"", ...","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy"", ...","[""net_flow_hour"", ""cumulative_net_flow"", ""cumu...","[""is_stockout_departure"", ""is_stockout_return""...","[""departures_hourly"", ""is_stockout_departure"",...","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/mnt/c/Users/User/Desktop/6_samodzielny_projek...
3,station_alert_prediction_df.parquet,5257704,79,349,"[""representative_station_id"", ""station_name"", ...","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy"", ...","[""net_flow_hour"", ""cumulative_net_flow"", ""cumu...","[""is_stockout_departure"", ""is_stockout_return""...","[""departures_hourly"", ""is_stockout_departure"",...","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/mnt/c/Users/User/Desktop/6_samodzielny_projek...
4,station_alert_hour_df.parquet,5257704,45,315,"[""representative_station_id"", ""station_name"", ...","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy"", ...","[""net_flow_hour"", ""cumulative_net_flow"", ""cumu...","[""is_stockout_departure"", ""is_stockout_return""]","[""departures_hourly"", ""is_stockout_departure""]","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/root/projects/6_samodzielny_projekt_koncowy_w...
5,station_alert_hour_df.parquet,5257704,45,315,"[""representative_station_id"", ""station_name"", ...","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy"", ...","[""net_flow_hour"", ""cumulative_net_flow"", ""cumu...","[""is_stockout_departure"", ""is_stockout_return""]","[""departures_hourly"", ""is_stockout_departure""]","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/root/projects/6_samodzielny_projekt_koncowy_w...
6,station_alert_hour_df.parquet,5257704,45,315,"[""representative_station_id"", ""station_name"", ...","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy"", ...","[""net_flow_hour"", ""cumulative_net_flow"", ""cumu...","[""is_stockout_departure"", ""is_stockout_return""]","[""departures_hourly"", ""is_stockout_departure""]","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/root/projects/6_samodzielny_projekt_koncowy_w...
7,station_alert_hour_df.parquet,5257704,45,315,"[""representative_station_id"", ""station_name"", ...","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy"", ...","[""net_flow_hour"", ""cumulative_net_flow"", ""cumu...","[""is_stockout_departure"", ""is_stockout_return""]","[""departures_hourly"", ""is_stockout_departure""]","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/mnt/c/Users/User/Desktop/6_samodzielny_projek...
8,station_alert_hour_df.parquet,5257704,45,315,"[""representative_station_id"", ""station_name"", ...","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy"", ...","[""net_flow_hour"", ""cumulative_net_flow"", ""cumu...","[""is_stockout_departure"", ""is_stockout_return""]","[""departures_hourly"", ""is_stockout_departure""]","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/mnt/c/Users/User/Desktop/6_samodzielny_projek...
9,b6_11_problem_direction_hourly.parquet,5257704,19,279,"[""representative_station_id"", ""station_name""]","[""activity_hour"", ""activity_date"", ""hour_of_da...","[""estimated_capacity"", ""free_capacity_proxy""]","[""net_flow_hour"", ""cumulative_net_flow""]","[""is_stockout_departure"", ""is_stockout_return""]","[""departures_hourly"", ""is_stockout_departure"",...","[""returns_hourly"", ""free_capacity_proxy"", ""is_...",/root/projects/6_samodzielny_projekt_koncowy_w...

In [5]:
# 6.1.5 Wybór kanonicznych źródeł BLOKU 6

from pathlib import Path
import json

import pandas as pd


step6_15_required_objects = [
    "step6_14_candidate_df",
    "step6_11_reports_dir",
]

step6_15_missing_objects = [
    object_name
    for object_name in step6_15_required_objects
    if object_name not in globals()
]

assert not step6_15_missing_objects, f"Missing required objects: {step6_15_missing_objects}"

step6_15_required_file_roles = {
    "main_hourly_alert_source": "station_alert_hour_df.parquet",
    "auxiliary_hourly_prediction_source": "station_alert_prediction_df.parquet",
    "microzone_hourly_alert_source": "microzone_alert_hour_df.parquet",
}

step6_15_source_records = []

for source_role, file_name in step6_15_required_file_roles.items():
    source_candidate_df = step6_14_candidate_df.loc[
        step6_14_candidate_df["file_name"] == file_name
    ].copy()

    assert not source_candidate_df.empty, f"Missing canonical source candidate: {file_name}"

    source_candidate_df["root_priority"] = source_candidate_df["resolved_path"].apply(
        lambda path_value: 0 if str(path_value).startswith("/root/projects/") else 1
    )

    source_candidate_df = (
        source_candidate_df
        .sort_values(
            ["row_count", "operational_score", "root_priority", "resolved_path"],
            ascending=[False, False, True, True],
        )
        .reset_index(drop=True)
    )

    selected_row = source_candidate_df.iloc[0]

    step6_15_source_records.append(
        {
            "source_role": source_role,
            "file_name": file_name,
            "row_count": int(selected_row["row_count"]),
            "column_count": int(selected_row["column_count"]),
            "operational_score": int(selected_row["operational_score"]),
            "has_station_key": bool(selected_row["has_station_key"]),
            "has_time_key": bool(selected_row["has_time_key"]),
            "has_capacity": bool(selected_row["has_capacity"]),
            "has_flow": bool(selected_row["has_flow"]),
            "has_alert": bool(selected_row["has_alert"]),
            "has_shortage": bool(selected_row["has_shortage"]),
            "has_overflow": bool(selected_row["has_overflow"]),
            "selected_path": str(selected_row["resolved_path"]),
        }
    )

step6_15_canonical_sources_df = pd.DataFrame(step6_15_source_records)

step6_15_required_checks = [
    "has_station_key",
    "has_time_key",
    "has_alert",
]

step6_15_failed_checks = []

for _, source_row in step6_15_canonical_sources_df.iterrows():
    for check_name in step6_15_required_checks:
        if not bool(source_row[check_name]):
            step6_15_failed_checks.append(
                {
                    "source_role": source_row["source_role"],
                    "file_name": source_row["file_name"],
                    "failed_check": check_name,
                }
            )

step6_15_failed_checks_df = pd.DataFrame(step6_15_failed_checks)

assert step6_15_failed_checks_df.empty, "Canonical source checks failed."

step6_15_canonical_source_paths = {
    row["source_role"]: Path(row["selected_path"])
    for _, row in step6_15_canonical_sources_df.iterrows()
}

step6_15_canonical_source_contract = {
    "block_name": "block_6",
    "section_name": "6.1",
    "contract_scope": "canonical_operational_sources",
    "main_hourly_alert_source": str(step6_15_canonical_source_paths["main_hourly_alert_source"]),
    "auxiliary_hourly_prediction_source": str(step6_15_canonical_source_paths["auxiliary_hourly_prediction_source"]),
    "microzone_hourly_alert_source": str(step6_15_canonical_source_paths["microzone_hourly_alert_source"]),
    "main_grain": "hour_station",
    "microzone_grain": "hour_microzone",
    "uses_exact_live_inventory": False,
    "uses_estimated_relocation": True,
    "builds_new_model": False,
}

step6_15_canonical_sources_path = step6_11_reports_dir / "b6_05_canonical_operational_sources.parquet"
step6_15_canonical_contract_path = step6_11_reports_dir / "b6_05_canonical_operational_sources_contract.json"

step6_15_canonical_sources_df.to_parquet(step6_15_canonical_sources_path, index=False)

with open(step6_15_canonical_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_15_canonical_source_contract, file, ensure_ascii=False, indent=2)

step6_15_summary_df = pd.DataFrame(
    [
        {
            "check_area": "canonical_sources",
            "status": "ok",
            "value": int(step6_15_canonical_sources_df.shape[0]),
        },
        {
            "check_area": "main_hourly_alert_rows",
            "status": "ok",
            "value": int(
                step6_15_canonical_sources_df.loc[
                    step6_15_canonical_sources_df["source_role"] == "main_hourly_alert_source",
                    "row_count",
                ].iloc[0]
            ),
        },
        {
            "check_area": "auxiliary_prediction_rows",
            "status": "ok",
            "value": int(
                step6_15_canonical_sources_df.loc[
                    step6_15_canonical_sources_df["source_role"] == "auxiliary_hourly_prediction_source",
                    "row_count",
                ].iloc[0]
            ),
        },
        {
            "check_area": "microzone_hourly_rows",
            "status": "ok",
            "value": int(
                step6_15_canonical_sources_df.loc[
                    step6_15_canonical_sources_df["source_role"] == "microzone_hourly_alert_source",
                    "row_count",
                ].iloc[0]
            ),
        },
        {
            "check_area": "canonical_sources_path",
            "status": "ok",
            "value": str(step6_15_canonical_sources_path),
        },
        {
            "check_area": "canonical_contract_path",
            "status": "ok",
            "value": str(step6_15_canonical_contract_path),
        },
    ]
)

display(step6_15_summary_df)
display(step6_15_canonical_sources_df)

,check_area,status,value
0,canonical_sources,ok,3
1,main_hourly_alert_rows,ok,5257704
2,auxiliary_prediction_rows,ok,5257704
3,microzone_hourly_rows,ok,4602648
4,canonical_sources_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,canonical_contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,source_role,file_name,row_count,column_count,operational_score,has_station_key,has_time_key,has_capacity,has_flow,has_alert,has_shortage,has_overflow,selected_path
0,main_hourly_alert_source,station_alert_hour_df.parquet,5257704,45,315,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
1,auxiliary_hourly_prediction_source,station_alert_prediction_df.parquet,5257704,79,349,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...
2,microzone_hourly_alert_source,microzone_alert_hour_df.parquet,4602648,14,274,True,True,True,True,True,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...

In [6]:
# 6.1.6 Kontrola schematów kanonicznych źródeł operacyjnych

import json

import pandas as pd
import pyarrow.parquet as pq


step6_16_required_objects = [
    "step6_15_canonical_source_paths",
    "step6_11_reports_dir",
]

step6_16_missing_objects = [
    object_name
    for object_name in step6_16_required_objects
    if object_name not in globals()
]

assert not step6_16_missing_objects, f"Missing required objects: {step6_16_missing_objects}"

step6_16_source_schema_records = []
step6_16_required_column_contract = {
    "main_hourly_alert_source": {
        "station_id": ["representative_station_id"],
        "time": ["activity_hour", "activity_date", "hour_of_day"],
        "capacity": ["estimated_capacity", "free_capacity_proxy"],
        "flow": ["departures_hourly", "returns_hourly", "net_flow_hour", "cumulative_net_flow"],
        "alert": ["is_stockout_departure", "is_stockout_return"],
    },
    "auxiliary_hourly_prediction_source": {
        "station_id": ["representative_station_id"],
        "time": ["activity_hour", "activity_date", "hour_of_day"],
        "capacity": ["estimated_capacity", "free_capacity_proxy"],
        "flow": ["departures_hourly", "returns_hourly", "net_flow_hour", "cumulative_net_flow"],
        "alert": ["is_stockout_departure", "is_stockout_return"],
    },
    "microzone_hourly_alert_source": {
        "microzone": ["microzone_id"],
        "time": ["activity_hour", "activity_date", "hour_of_day"],
        "capacity": ["microzone_estimated_capacity", "microzone_free_capacity_proxy"],
        "flow": ["microzone_departures_hourly", "microzone_returns_hourly", "microzone_net_flow_hour"],
        "alert": ["microzone_is_stockout_departure", "microzone_is_stockout_return"],
    },
}

step6_16_schema_records = []
step6_16_contract_records = []

for source_role, source_path in step6_15_canonical_source_paths.items():
    parquet_file = pq.ParquetFile(source_path)
    schema_arrow = parquet_file.schema_arrow

    column_names = parquet_file.schema.names
    row_count = int(parquet_file.metadata.num_rows)
    row_group_count = int(parquet_file.metadata.num_row_groups)

    step6_16_source_schema_records.append(
        {
            "source_role": source_role,
            "file_name": source_path.name,
            "row_count": row_count,
            "column_count": int(len(column_names)),
            "row_group_count": row_group_count,
            "selected_path": str(source_path),
        }
    )

    for field in schema_arrow:
        step6_16_schema_records.append(
            {
                "source_role": source_role,
                "file_name": source_path.name,
                "column_name": field.name,
                "arrow_dtype": str(field.type),
                "nullable": bool(field.nullable),
            }
        )

    source_columns = set(column_names)

    for semantic_group, required_columns in step6_16_required_column_contract[source_role].items():
        present_columns = [
            column_name
            for column_name in required_columns
            if column_name in source_columns
        ]

        missing_columns = [
            column_name
            for column_name in required_columns
            if column_name not in source_columns
        ]

        step6_16_contract_records.append(
            {
                "source_role": source_role,
                "semantic_group": semantic_group,
                "required_columns": json.dumps(required_columns, ensure_ascii=False),
                "present_columns": json.dumps(present_columns, ensure_ascii=False),
                "missing_columns": json.dumps(missing_columns, ensure_ascii=False),
                "present_count": int(len(present_columns)),
                "missing_count": int(len(missing_columns)),
                "status": "ok" if len(missing_columns) == 0 else "review",
            }
        )

step6_16_source_schema_df = pd.DataFrame(step6_16_source_schema_records)
step6_16_schema_columns_df = pd.DataFrame(step6_16_schema_records)
step6_16_contract_check_df = pd.DataFrame(step6_16_contract_records)

step6_16_review_count = int((step6_16_contract_check_df["status"] == "review").sum())

step6_16_source_schema_path = step6_11_reports_dir / "b6_06_canonical_source_schema_profile.parquet"
step6_16_schema_columns_path = step6_11_reports_dir / "b6_06_canonical_source_columns.parquet"
step6_16_contract_check_path = step6_11_reports_dir / "b6_06_canonical_source_column_contract.parquet"

step6_16_source_schema_df.to_parquet(step6_16_source_schema_path, index=False)
step6_16_schema_columns_df.to_parquet(step6_16_schema_columns_path, index=False)
step6_16_contract_check_df.to_parquet(step6_16_contract_check_path, index=False)

step6_16_summary_df = pd.DataFrame(
    [
        {
            "check_area": "canonical_sources",
            "status": "ok",
            "value": int(step6_16_source_schema_df.shape[0]),
        },
        {
            "check_area": "schema_columns",
            "status": "ok",
            "value": int(step6_16_schema_columns_df.shape[0]),
        },
        {
            "check_area": "contract_groups",
            "status": "ok",
            "value": int(step6_16_contract_check_df.shape[0]),
        },
        {
            "check_area": "contract_review_groups",
            "status": "ok" if step6_16_review_count == 0 else "review",
            "value": step6_16_review_count,
        },
        {
            "check_area": "source_schema_path",
            "status": "ok",
            "value": str(step6_16_source_schema_path),
        },
        {
            "check_area": "schema_columns_path",
            "status": "ok",
            "value": str(step6_16_schema_columns_path),
        },
        {
            "check_area": "contract_check_path",
            "status": "ok",
            "value": str(step6_16_contract_check_path),
        },
    ]
)

display(step6_16_summary_df)
display(step6_16_source_schema_df)
display(step6_16_contract_check_df)
display(step6_16_schema_columns_df)

,check_area,status,value
0,canonical_sources,ok,3
1,schema_columns,ok,138
2,contract_groups,ok,15
3,contract_review_groups,review,1
4,source_schema_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,schema_columns_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,contract_check_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,source_role,file_name,row_count,column_count,row_group_count,selected_path
0,main_hourly_alert_source,station_alert_hour_df.parquet,5257704,45,7,/root/projects/6_samodzielny_projekt_koncowy_w...
1,auxiliary_hourly_prediction_source,station_alert_prediction_df.parquet,5257704,79,7,/root/projects/6_samodzielny_projekt_koncowy_w...
2,microzone_hourly_alert_source,microzone_alert_hour_df.parquet,4602648,14,6,/root/projects/6_samodzielny_projekt_koncowy_w...

,source_role,semantic_group,required_columns,present_columns,missing_columns,present_count,missing_count,status
0,main_hourly_alert_source,station_id,"[""representative_station_id""]","[""representative_station_id""]",[],1,0,ok
1,main_hourly_alert_source,time,"[""activity_hour"", ""activity_date"", ""hour_of_day""]","[""activity_hour"", ""activity_date"", ""hour_of_day""]",[],3,0,ok
2,main_hourly_alert_source,capacity,"[""estimated_capacity"", ""free_capacity_proxy""]","[""estimated_capacity"", ""free_capacity_proxy""]",[],2,0,ok
3,main_hourly_alert_source,flow,"[""departures_hourly"", ""returns_hourly"", ""net_f...","[""departures_hourly"", ""returns_hourly"", ""net_f...",[],4,0,ok
4,main_hourly_alert_source,alert,"[""is_stockout_departure"", ""is_stockout_return""]","[""is_stockout_departure"", ""is_stockout_return""]",[],2,0,ok
5,auxiliary_hourly_prediction_source,station_id,"[""representative_station_id""]","[""representative_station_id""]",[],1,0,ok
6,auxiliary_hourly_prediction_source,time,"[""activity_hour"", ""activity_date"", ""hour_of_day""]","[""activity_hour"", ""activity_date"", ""hour_of_day""]",[],3,0,ok
7,auxiliary_hourly_prediction_source,capacity,"[""estimated_capacity"", ""free_capacity_proxy""]","[""estimated_capacity"", ""free_capacity_proxy""]",[],2,0,ok
8,auxiliary_hourly_prediction_source,flow,"[""departures_hourly"", ""returns_hourly"", ""net_f...","[""departures_hourly"", ""returns_hourly"", ""net_f...",[],4,0,ok
9,auxiliary_hourly_prediction_source,alert,"[""is_stockout_departure"", ""is_stockout_return""]","[""is_stockout_departure"", ""is_stockout_return""]",[],2,0,ok
10,microzone_hourly_alert_source,microzone,"[""microzone_id""]","[""microzone_id""]",[],1,0,ok
11,microzone_hourly_alert_source,time,"[""activity_hour"", ""activity_date"", ""hour_of_day""]","[""activity_hour"", ""activity_date""]","[""hour_of_day""]",2,1,review
12,microzone_hourly_alert_source,capacity,"[""microzone_estimated_capacity"", ""microzone_fr...","[""microzone_estimated_capacity"", ""microzone_fr...",[],2,0,ok
13,microzone_hourly_alert_source,flow,"[""microzone_departures_hourly"", ""microzone_ret...","[""microzone_departures_hourly"", ""microzone_ret...",[],3,0,ok
14,microzone_hourly_alert_source,alert,"[""microzone_is_stockout_departure"", ""microzone...","[""microzone_is_stockout_departure"", ""microzone...",[],2,0,ok

,source_role,file_name,column_name,arrow_dtype,nullable
0,main_hourly_alert_source,station_alert_hour_df.parquet,activity_hour,timestamp[ns],True
1,main_hourly_alert_source,station_alert_hour_df.parquet,activity_date,timestamp[ns],True
2,main_hourly_alert_source,station_alert_hour_df.parquet,hour_of_day,int32,True
3,main_hourly_alert_source,station_alert_hour_df.parquet,hour_season_segment_id,int32,True
4,main_hourly_alert_source,station_alert_hour_df.parquet,physical_location_id,string,True
...,...,...,...,...,...
133,microzone_hourly_alert_source,microzone_alert_hour_df.parquet,microzone_longitude,double,True
134,microzone_hourly_alert_source,microzone_alert_hour_df.parquet,microzone_net_flow_hour,int32,True
135,microzone_hourly_alert_source,microzone_alert_hour_df.parquet,microzone_free_capacity_proxy,double,True
136,microzone_hourly_alert_source,microzone_alert_hour_df.parquet,microzone_is_stockout_departure,int32,True
137,microzone_hourly_alert_source,microzone_alert_hour_df.parquet,microzone_is_stockout_return,int32,True

In [7]:
# 6.1.7 Zamknięcie kontraktu decyzji dyspozytora

import json

import pandas as pd


step6_17_required_objects = [
    "step6_11_dispatcher_decision_fields_df",
    "step6_11_decision_contract",
    "step6_15_canonical_sources_df",
    "step6_15_canonical_source_contract",
    "step6_16_contract_check_df",
    "step6_11_reports_dir",
]

step6_17_missing_objects = [
    object_name
    for object_name in step6_17_required_objects
    if object_name not in globals()
]

assert not step6_17_missing_objects, f"Missing required objects: {step6_17_missing_objects}"

step6_17_decision_field_count = int(step6_11_dispatcher_decision_fields_df.shape[0])
step6_17_main_screen_field_count = int(step6_11_dispatcher_decision_fields_df["main_screen"].sum())
step6_17_canonical_source_count = int(step6_15_canonical_sources_df.shape[0])
step6_17_contract_review_count = int((step6_16_contract_check_df["status"] == "review").sum())

step6_17_required_decision_fields = [
    "priority_level",
    "problem_type",
    "recommended_action",
    "highest_risk_hour",
    "estimated_relocation",
    "recommendation_confidence",
    "decision_reason",
]

step6_17_available_decision_fields = (
    step6_11_dispatcher_decision_fields_df["field_name"]
    .astype("string")
    .tolist()
)

step6_17_missing_decision_fields = [
    field_name
    for field_name in step6_17_required_decision_fields
    if field_name not in step6_17_available_decision_fields
]

assert not step6_17_missing_decision_fields, f"Missing decision fields: {step6_17_missing_decision_fields}"

step6_17_dispatcher_decision_contract = {
    "block_name": "block_6",
    "section_name": "6.1",
    "section_scope": "dispatcher_decision_contract",
    "main_goal": "define_operational_decision_fields_for_dispatcher_panel",
    "builds_new_model": False,
    "uses_exact_live_station_inventory": False,
    "uses_estimated_relocation": True,
    "uses_raw_model_fields_on_main_screen": False,
    "decision_grain": "station_decision_view",
    "main_hourly_grain": "hour_station",
    "microzone_hourly_grain": "hour_microzone",
    "required_decision_fields": step6_17_required_decision_fields,
    "technical_fields_hidden_from_main_screen": [
        "predicted_probability",
        "predicted_label",
    ],
    "canonical_sources": step6_15_canonical_source_contract,
    "known_schema_notes": [
        {
            "source_role": "microzone_hourly_alert_source",
            "note": "hour_of_day can be derived from activity_hour",
        }
    ],
}

step6_17_section_status_records = [
    {
        "section_item": "decision_fields_defined",
        "status": "ok",
        "value": step6_17_decision_field_count,
    },
    {
        "section_item": "main_screen_fields_defined",
        "status": "ok",
        "value": step6_17_main_screen_field_count,
    },
    {
        "section_item": "canonical_sources_defined",
        "status": "ok",
        "value": step6_17_canonical_source_count,
    },
    {
        "section_item": "raw_model_fields_on_main_screen",
        "status": "ok",
        "value": False,
    },
    {
        "section_item": "exact_live_inventory_claim",
        "status": "ok",
        "value": False,
    },
    {
        "section_item": "estimated_relocation_policy",
        "status": "ok",
        "value": True,
    },
    {
        "section_item": "schema_review_groups",
        "status": "ok" if step6_17_contract_review_count <= 1 else "review",
        "value": step6_17_contract_review_count,
    },
]

step6_17_section_status_df = pd.DataFrame(step6_17_section_status_records)

step6_17_section_status_df["section_item"] = (
    step6_17_section_status_df["section_item"].astype("string")
)

step6_17_section_status_df["status"] = (
    step6_17_section_status_df["status"].astype("string")
)

step6_17_section_status_df["value"] = (
    step6_17_section_status_df["value"]
    .apply(lambda value: json.dumps(value, ensure_ascii=False))
    .astype("string")
)

step6_17_section_contract_path = step6_11_reports_dir / "b6_07_dispatcher_decision_section_contract.json"
step6_17_section_status_path = step6_11_reports_dir / "b6_07_dispatcher_decision_section_status.parquet"

with open(step6_17_section_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_17_dispatcher_decision_contract, file, ensure_ascii=False, indent=2)

step6_17_section_status_df.to_parquet(step6_17_section_status_path, index=False)

step6_17_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_6_1_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "check_area": "decision_fields",
            "status": "ok",
            "value": str(step6_17_decision_field_count),
        },
        {
            "check_area": "canonical_sources",
            "status": "ok",
            "value": str(step6_17_canonical_source_count),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_17_section_contract_path),
        },
        {
            "check_area": "status_path",
            "status": "ok",
            "value": str(step6_17_section_status_path),
        },
    ]
)

step6_17_summary_df["check_area"] = step6_17_summary_df["check_area"].astype("string")
step6_17_summary_df["status"] = step6_17_summary_df["status"].astype("string")
step6_17_summary_df["value"] = step6_17_summary_df["value"].astype("string")

display(step6_17_summary_df)
display(step6_17_section_status_df)

,check_area,status,value
0,section_6_1_status,ok,closed
1,decision_fields,ok,7
2,canonical_sources,ok,3
3,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,status_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                      section_item status  value
0          decision_fields_defined     ok      7
1       main_screen_fields_defined     ok      7
2        canonical_sources_defined     ok      3
3  raw_model_fields_on_main_screen     ok  false
4       exact_live_inventory_claim     ok  false
5      estimated_relocation_policy     ok   true
6             schema_review_groups     ok      1

## Podsumowanie działu 6.1 Definicja decyzji dyspozytora

**Kontekst inżynieryjny:** W dziale `6.1` zdefiniowano kontrakt decyzji operacyjnej dla BLOKU 6, którego celem jest przygotowanie warstwy pośredniej między technicznymi sygnałami alertowymi a docelowym panelem dyspozytora. Najpierw zdefiniowano zestaw pól decyzyjnych, które będą wykorzystywane w dalszych etapach aplikacji operacyjnej: `priority_level`, `problem_type`, `recommended_action`, `highest_risk_hour`, `estimated_relocation`, `recommendation_confidence` oraz `decision_reason`. Następnie przeprowadzono kontrolę dostępnych źródeł danych, inspekcję kandydatów operacyjnych oraz identyfikację pełnej warstwy godzinowej. Na tej podstawie wybrano kanoniczne źródła BLOKU 6: `station_alert_hour_df.parquet` jako główne źródło godzinowej warstwy alertowej, `station_alert_prediction_df.parquet` jako pomocnicze źródło predykcyjno-operacyjne oraz `microzone_alert_hour_df.parquet` jako źródło godzinowej warstwy mikrostrefowej. Na końcu zweryfikowano schematy źródeł kanonicznych, obecność wymaganych grup kolumn oraz zapisano kontrakt zamykający dział `6.1`.

**Interpretacja wyniku:** Dział `6.1` został poprawnie domknięty statusem `closed`. Zdefiniowano `7` pól decyzyjnych, z czego wszystkie `7` zostało oznaczonych jako pola głównego widoku operacyjnego. Ustalono `3` kanoniczne źródła danych. Główne źródło `station_alert_hour_df.parquet` zawiera `5 257 704` rekordy i `45` kolumn, pomocnicze źródło `station_alert_prediction_df.parquet` zawiera `5 257 704` rekordy i `79` kolumn, a źródło mikrostrefowe `microzone_alert_hour_df.parquet` zawiera `4 602 648` rekordów i `14` kolumn. Kontrola schematów objęła łącznie `138` kolumn oraz `15` grup kontraktowych. Dla źródeł stacyjnych potwierdzono obecność kluczowych kolumn, takich jak `representative_station_id`, `activity_hour`, `activity_date`, `hour_of_day`, `estimated_capacity`, `free_capacity_proxy`, `departures_hourly`, `returns_hourly`, `net_flow_hour`, `cumulative_net_flow`, `is_stockout_departure` oraz `is_stockout_return`. Dla źródła mikrostrefowego potwierdzono obecność m.in. `microzone_id`, `activity_hour`, `activity_date`, `microzone_estimated_capacity`, `microzone_free_capacity_proxy`, `microzone_departures_hourly`, `microzone_returns_hourly`, `microzone_net_flow_hour`, `microzone_is_stockout_departure` oraz `microzone_is_stockout_return`. Jedna grupa schematowa została oznaczona jako `review`, ponieważ w źródle mikrostrefowym nie występuje kolumna `hour_of_day`, natomiast informacja godzinowa jest dostępna przez `activity_hour`.

**Znaczenie biznesowe:** Dział `6.1` przygotowuje fundament pod przejście od technicznej warstwy alertowej do języka decyzji operacyjnej. Zamiast opierać główny widok panelu na surowych polach modelowych, takich jak `predicted_probability` i `predicted_label`, dalsze etapy BLOKU 6 będą pracować na polach opisujących priorytet stacji, typ problemu, rekomendowane działanie, godzinę największego ryzyka, szacowaną relokację, pewność rekomendacji oraz uzasadnienie decyzji. Dzięki temu BLOK 6 może rozwijać się jako warstwa operacyjna dla dyspozytora i kierowcy, a nie jako kolejna tabela techniczna. Ustalenie pełnych źródeł godzinowych pozwala w kolejnych działach budować logikę kierunku problemu, rekomendacji relokacji, rankingu stacji, mikrostref, par kompensacyjnych oraz mapy działań na podstawie danych o przepływach, pojemności, alertach i mikrostrefach.

**Wniosek:** Dział `6.1` został domknięty poprawnie. BLOK 6 ma zdefiniowany kontrakt decyzji dyspozytora, ustalone pola operacyjne, wybrane kanoniczne źródła godzinowe oraz zweryfikowaną strukturę danych wejściowych. Oznacza to, że można przejść do kolejnego etapu, czyli `6.2 Warstwa kierunku problemu: brak czy nadmiar rowerów`, mając przygotowaną podstawę do rozróżniania ryzyka braku rowerów, ryzyka nadmiaru rowerów oraz sytuacji mieszanej.

## 6.2 Warstwa kierunku problemu: brak czy nadmiar rowerów

In [8]:
# 6.2.1 Definicja kontraktu kierunku problemu

import json

import pandas as pd


step6_21_required_objects = [
    "step6_15_canonical_source_paths",
    "step6_11_reports_dir",
]

step6_21_missing_objects = [
    object_name
    for object_name in step6_21_required_objects
    if object_name not in globals()
]

assert not step6_21_missing_objects, f"Missing required objects: {step6_21_missing_objects}"

step6_21_problem_direction_contract = {
    "block_name": "block_6",
    "section_name": "6.2",
    "section_scope": "problem_direction_layer",
    "main_source_role": "main_hourly_alert_source",
    "main_source_path": str(step6_15_canonical_source_paths["main_hourly_alert_source"]),
    "grain": "hour_station_to_station_direction",
    "output_field": "problem_type",
    "allowed_values": [
        "bike_shortage_risk",
        "dock_shortage_risk",
        "mixed_risk",
        "no_clear_signal",
    ],
    "direction_rules": [
        {
            "problem_type": "bike_shortage_risk",
            "primary_signal": "is_stockout_departure",
            "supporting_signals": [
                "departures_hourly",
                "net_flow_hour",
                "cumulative_net_flow",
                "occupancy_proxy",
            ],
        },
        {
            "problem_type": "dock_shortage_risk",
            "primary_signal": "is_stockout_return",
            "supporting_signals": [
                "returns_hourly",
                "net_flow_hour",
                "cumulative_net_flow",
                "free_capacity_proxy",
            ],
        },
        {
            "problem_type": "mixed_risk",
            "primary_signal": "is_stockout_departure_and_is_stockout_return",
            "supporting_signals": [
                "departures_hourly",
                "returns_hourly",
                "net_flow_hour",
                "free_capacity_proxy",
            ],
        },
        {
            "problem_type": "no_clear_signal",
            "primary_signal": "weak_or_missing_direction_signal",
            "supporting_signals": [],
        },
    ],
    "main_screen_mapping_later_in_app": {
        "bike_shortage_risk": "bike shortage",
        "dock_shortage_risk": "dock shortage",
        "mixed_risk": "mixed risk",
        "no_clear_signal": "check station state",
    },
}

step6_21_required_columns = [
    "activity_hour",
    "activity_date",
    "hour_of_day",
    "representative_station_id",
    "station_name",
    "departures_hourly",
    "returns_hourly",
    "net_flow_hour",
    "cumulative_net_flow",
    "estimated_capacity",
    "occupancy_proxy",
    "free_capacity_proxy",
    "is_stockout_departure",
    "is_stockout_return",
]

step6_21_problem_type_values_df = pd.DataFrame(
    [
        {
            "problem_type": "bike_shortage_risk",
            "direction_priority": 1,
            "requires_departure_signal": True,
            "requires_return_signal": False,
            "dispatcher_action_family": "deliver_bikes",
        },
        {
            "problem_type": "dock_shortage_risk",
            "direction_priority": 2,
            "requires_departure_signal": False,
            "requires_return_signal": True,
            "dispatcher_action_family": "remove_bikes",
        },
        {
            "problem_type": "mixed_risk",
            "direction_priority": 3,
            "requires_departure_signal": True,
            "requires_return_signal": True,
            "dispatcher_action_family": "check_station_state",
        },
        {
            "problem_type": "no_clear_signal",
            "direction_priority": 4,
            "requires_departure_signal": False,
            "requires_return_signal": False,
            "dispatcher_action_family": "check_station_state",
        },
    ]
)

step6_21_problem_type_values_df["problem_type"] = (
    step6_21_problem_type_values_df["problem_type"].astype("string")
)

step6_21_problem_type_values_df["dispatcher_action_family"] = (
    step6_21_problem_type_values_df["dispatcher_action_family"].astype("string")
)

step6_21_problem_direction_contract_path = step6_11_reports_dir / "b6_08_problem_direction_contract.json"
step6_21_problem_type_values_path = step6_11_reports_dir / "b6_08_problem_type_values.parquet"

with open(step6_21_problem_direction_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_21_problem_direction_contract, file, ensure_ascii=False, indent=2)

step6_21_problem_type_values_df.to_parquet(step6_21_problem_type_values_path, index=False)

step6_21_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_scope",
            "status": "ok",
            "value": "problem_direction_layer",
        },
        {
            "check_area": "allowed_problem_types",
            "status": "ok",
            "value": str(step6_21_problem_type_values_df.shape[0]),
        },
        {
            "check_area": "required_columns",
            "status": "ok",
            "value": str(len(step6_21_required_columns)),
        },
        {
            "check_area": "main_source_role",
            "status": "ok",
            "value": "main_hourly_alert_source",
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_21_problem_direction_contract_path),
        },
        {
            "check_area": "problem_type_values_path",
            "status": "ok",
            "value": str(step6_21_problem_type_values_path),
        },
    ]
)

step6_21_summary_df["check_area"] = step6_21_summary_df["check_area"].astype("string")
step6_21_summary_df["status"] = step6_21_summary_df["status"].astype("string")
step6_21_summary_df["value"] = step6_21_summary_df["value"].astype("string")

display(step6_21_summary_df)
display(step6_21_problem_type_values_df)

,check_area,status,value
0,section_scope,ok,problem_direction_layer
1,allowed_problem_types,ok,4
2,required_columns,ok,14
3,main_source_role,ok,main_hourly_alert_source
4,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,problem_type_values_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,problem_type,direction_priority,requires_departure_signal,requires_return_signal,dispatcher_action_family
0,bike_shortage_risk,1,True,False,deliver_bikes
1,dock_shortage_risk,2,False,True,remove_bikes
2,mixed_risk,3,True,True,check_station_state
3,no_clear_signal,4,False,False,check_station_state

In [9]:
# 6.2.2 Kontrola kolumn źródła kierunku problemu

import json

import pandas as pd
import pyarrow.parquet as pq


step6_22_required_objects = [
    "step6_15_canonical_source_paths",
    "step6_21_required_columns",
    "step6_11_reports_dir",
]

step6_22_missing_objects = [
    object_name
    for object_name in step6_22_required_objects
    if object_name not in globals()
]

assert not step6_22_missing_objects, f"Missing required objects: {step6_22_missing_objects}"

step6_22_main_source_path = step6_15_canonical_source_paths["main_hourly_alert_source"]

step6_22_parquet_file = pq.ParquetFile(step6_22_main_source_path)
step6_22_source_columns = step6_22_parquet_file.schema.names

step6_22_column_check_records = []

for column_name in step6_21_required_columns:
    step6_22_column_check_records.append(
        {
            "column_name": column_name,
            "required_for": "problem_direction_layer",
            "is_present": column_name in step6_22_source_columns,
        }
    )

step6_22_column_check_df = pd.DataFrame(step6_22_column_check_records)

step6_22_missing_columns = step6_22_column_check_df.loc[
    ~step6_22_column_check_df["is_present"],
    "column_name",
].tolist()

assert not step6_22_missing_columns, f"Missing required columns: {step6_22_missing_columns}"

step6_22_selected_schema_records = []

for field in step6_22_parquet_file.schema_arrow:
    if field.name in step6_21_required_columns:
        step6_22_selected_schema_records.append(
            {
                "column_name": field.name,
                "arrow_dtype": str(field.type),
                "nullable": bool(field.nullable),
            }
        )

step6_22_selected_schema_df = pd.DataFrame(step6_22_selected_schema_records)

step6_22_source_contract = {
    "block_name": "block_6",
    "section_name": "6.2",
    "contract_scope": "problem_direction_source_columns",
    "source_role": "main_hourly_alert_source",
    "source_file": step6_22_main_source_path.name,
    "source_path": str(step6_22_main_source_path),
    "row_count": int(step6_22_parquet_file.metadata.num_rows),
    "column_count": int(len(step6_22_source_columns)),
    "required_columns": step6_21_required_columns,
}

step6_22_column_check_path = step6_11_reports_dir / "b6_09_problem_direction_column_check.parquet"
step6_22_selected_schema_path = step6_11_reports_dir / "b6_09_problem_direction_selected_schema.parquet"
step6_22_source_contract_path = step6_11_reports_dir / "b6_09_problem_direction_source_contract.json"

step6_22_column_check_df.to_parquet(step6_22_column_check_path, index=False)
step6_22_selected_schema_df.to_parquet(step6_22_selected_schema_path, index=False)

with open(step6_22_source_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_22_source_contract, file, ensure_ascii=False, indent=2)

step6_22_summary_df = pd.DataFrame(
    [
        {
            "check_area": "source_file",
            "status": "ok",
            "value": step6_22_main_source_path.name,
        },
        {
            "check_area": "source_rows",
            "status": "ok",
            "value": str(step6_22_parquet_file.metadata.num_rows),
        },
        {
            "check_area": "required_columns",
            "status": "ok",
            "value": str(len(step6_21_required_columns)),
        },
        {
            "check_area": "missing_columns",
            "status": "ok",
            "value": str(len(step6_22_missing_columns)),
        },
        {
            "check_area": "column_check_path",
            "status": "ok",
            "value": str(step6_22_column_check_path),
        },
        {
            "check_area": "selected_schema_path",
            "status": "ok",
            "value": str(step6_22_selected_schema_path),
        },
        {
            "check_area": "source_contract_path",
            "status": "ok",
            "value": str(step6_22_source_contract_path),
        },
    ]
)

step6_22_summary_df["check_area"] = step6_22_summary_df["check_area"].astype("string")
step6_22_summary_df["status"] = step6_22_summary_df["status"].astype("string")
step6_22_summary_df["value"] = step6_22_summary_df["value"].astype("string")

display(step6_22_summary_df)
display(step6_22_column_check_df)
display(step6_22_selected_schema_df)

,check_area,status,value
0,source_file,ok,station_alert_hour_df.parquet
1,source_rows,ok,5257704
2,required_columns,ok,14
3,missing_columns,ok,0
4,column_check_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,selected_schema_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,source_contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                  column_name             required_for  is_present
0               activity_hour  problem_direction_layer        True
1               activity_date  problem_direction_layer        True
2                 hour_of_day  problem_direction_layer        True
3   representative_station_id  problem_direction_layer        True
4                station_name  problem_direction_layer        True
5           departures_hourly  problem_direction_layer        True
6              returns_hourly  problem_direction_layer        True
7               net_flow_hour  problem_direction_layer        True
8         cumulative_net_flow  problem_direction_layer        True
9          estimated_capacity  problem_direction_layer        True
10            occupancy_proxy  problem_direction_layer        True
11        free_capacity_proxy  problem_direction_layer        True
12      is_stockout_departure  problem_direction_layer        True
13         is_stockout_return  problem_direction_layer        True

                  column_name    arrow_dtype  nullable
0               activity_hour  timestamp[ns]      True
1               activity_date  timestamp[ns]      True
2                 hour_of_day          int32      True
3   representative_station_id         string      True
4                station_name         string      True
5           departures_hourly          int32      True
6              returns_hourly          int32      True
7               net_flow_hour          int32      True
8         cumulative_net_flow          int32      True
9             occupancy_proxy          int32      True
10         estimated_capacity         double      True
11        free_capacity_proxy         double      True
12      is_stockout_departure          int32      True
13         is_stockout_return          int32      True

In [10]:
# 6.2.3 Wczytanie kolumn kierunku problemu

import pandas as pd


step6_23_required_objects = [
    "step6_22_main_source_path",
    "step6_21_required_columns",
    "step6_11_reports_dir",
]

step6_23_missing_objects = [
    object_name
    for object_name in step6_23_required_objects
    if object_name not in globals()
]

assert not step6_23_missing_objects, f"Missing required objects: {step6_23_missing_objects}"

step6_23_problem_direction_hourly_df = pd.read_parquet(
    step6_22_main_source_path,
    columns=step6_21_required_columns,
)

step6_23_problem_direction_hourly_df["activity_hour"] = pd.to_datetime(
    step6_23_problem_direction_hourly_df["activity_hour"],
    errors="coerce",
)

step6_23_problem_direction_hourly_df["activity_date"] = pd.to_datetime(
    step6_23_problem_direction_hourly_df["activity_date"],
    errors="coerce",
).dt.normalize()

step6_23_problem_direction_hourly_df["representative_station_id"] = (
    step6_23_problem_direction_hourly_df["representative_station_id"].astype("string")
)

step6_23_problem_direction_hourly_df["station_name"] = (
    step6_23_problem_direction_hourly_df["station_name"].astype("string")
)

step6_23_numeric_columns = [
    "hour_of_day",
    "departures_hourly",
    "returns_hourly",
    "net_flow_hour",
    "cumulative_net_flow",
    "estimated_capacity",
    "occupancy_proxy",
    "free_capacity_proxy",
    "is_stockout_departure",
    "is_stockout_return",
]

for column_name in step6_23_numeric_columns:
    step6_23_problem_direction_hourly_df[column_name] = pd.to_numeric(
        step6_23_problem_direction_hourly_df[column_name],
        errors="coerce",
    )

step6_23_duplicate_key_count = int(
    step6_23_problem_direction_hourly_df.duplicated(
        subset=["activity_hour", "representative_station_id"]
    ).sum()
)

step6_23_null_profile_df = (
    step6_23_problem_direction_hourly_df[step6_21_required_columns]
    .isna()
    .sum()
    .reset_index()
    .rename(columns={"index": "column_name", 0: "null_count"})
)

step6_23_null_profile_df["row_count"] = int(step6_23_problem_direction_hourly_df.shape[0])
step6_23_null_profile_df["null_share"] = (
    step6_23_null_profile_df["null_count"]
    / step6_23_null_profile_df["row_count"]
)

step6_23_profile_df = pd.DataFrame(
    [
        {
            "check_area": "loaded_rows",
            "status": "ok",
            "value": str(step6_23_problem_direction_hourly_df.shape[0]),
        },
        {
            "check_area": "loaded_columns",
            "status": "ok",
            "value": str(step6_23_problem_direction_hourly_df.shape[1]),
        },
        {
            "check_area": "unique_stations",
            "status": "ok",
            "value": str(step6_23_problem_direction_hourly_df["representative_station_id"].nunique()),
        },
        {
            "check_area": "activity_hour_min",
            "status": "ok",
            "value": str(step6_23_problem_direction_hourly_df["activity_hour"].min()),
        },
        {
            "check_area": "activity_hour_max",
            "status": "ok",
            "value": str(step6_23_problem_direction_hourly_df["activity_hour"].max()),
        },
        {
            "check_area": "duplicate_hour_station_keys",
            "status": "ok" if step6_23_duplicate_key_count == 0 else "review",
            "value": str(step6_23_duplicate_key_count),
        },
    ]
)

step6_23_null_profile_path = step6_11_reports_dir / "b6_10_problem_direction_input_null_profile.parquet"
step6_23_profile_path = step6_11_reports_dir / "b6_10_problem_direction_input_profile.parquet"

step6_23_null_profile_df.to_parquet(step6_23_null_profile_path, index=False)
step6_23_profile_df.to_parquet(step6_23_profile_path, index=False)

display(step6_23_profile_df)
display(step6_23_null_profile_df)
display(step6_23_problem_direction_hourly_df.head(10))

                    check_area status                value
0                  loaded_rows     ok              5257704
1               loaded_columns     ok                   14
2              unique_stations     ok                  344
3            activity_hour_min     ok  2017-05-02 00:00:00
4            activity_hour_max     ok  2020-11-02 23:00:00
5  duplicate_hour_station_keys     ok                    0

                  column_name  null_count  row_count  null_share
0               activity_hour           0    5257704         0.0
1               activity_date           0    5257704         0.0
2                 hour_of_day           0    5257704         0.0
3   representative_station_id           0    5257704         0.0
4                station_name           0    5257704         0.0
5           departures_hourly           0    5257704         0.0
6              returns_hourly           0    5257704         0.0
7               net_flow_hour           0    5257704         0.0
8         cumulative_net_flow           0    5257704         0.0
9          estimated_capacity           0    5257704         0.0
10            occupancy_proxy           0    5257704         0.0
11        free_capacity_proxy           0    5257704         0.0
12      is_stockout_departure           0    5257704         0.0
13         is_stockout_return           0    5257704         0.0

,activity_hour,activity_date,hour_of_day,representative_station_id,station_name,departures_hourly,returns_hourly,net_flow_hour,cumulative_net_flow,estimated_capacity,occupancy_proxy,free_capacity_proxy,is_stockout_departure,is_stockout_return
0,2017-05-02 00:00:00,2017-05-02,0,601,Nokkala,0,0,0,0,8.0,0,8.0,1,0
1,2017-05-02 01:00:00,2017-05-02,1,601,Nokkala,0,0,0,0,8.0,0,8.0,1,0
2,2017-05-02 02:00:00,2017-05-02,2,601,Nokkala,0,0,0,0,8.0,0,8.0,1,0
3,2017-05-02 03:00:00,2017-05-02,3,601,Nokkala,0,0,0,0,8.0,0,8.0,1,0
4,2017-05-02 04:00:00,2017-05-02,4,601,Nokkala,0,0,0,0,8.0,0,8.0,1,0
5,2017-05-02 05:00:00,2017-05-02,5,601,Nokkala,0,0,0,0,8.0,0,8.0,1,0
6,2017-05-02 06:00:00,2017-05-02,6,601,Nokkala,0,0,0,0,8.0,0,8.0,1,0
7,2017-05-02 07:00:00,2017-05-02,7,601,Nokkala,0,0,0,0,8.0,0,8.0,1,0
8,2017-05-02 08:00:00,2017-05-02,8,601,Nokkala,1,1,0,0,8.0,0,8.0,1,0
9,2017-05-02 09:00:00,2017-05-02,9,601,Nokkala,0,0,0,0,8.0,0,8.0,1,0

In [11]:
# 6.2.4 Budowa godzinowego kierunku problemu

import numpy as np
import pandas as pd


step6_24_required_objects = [
    "step6_23_problem_direction_hourly_df",
    "step6_11_outputs_dir",
    "step6_11_reports_dir",
]

step6_24_missing_objects = [
    object_name
    for object_name in step6_24_required_objects
    if object_name not in globals()
]

assert not step6_24_missing_objects, f"Missing required objects: {step6_24_missing_objects}"

step6_24_problem_direction_hourly_df = step6_23_problem_direction_hourly_df.copy()

step6_24_problem_direction_hourly_df["departure_side_signal"] = (
    step6_24_problem_direction_hourly_df["is_stockout_departure"].fillna(0).astype("int8")
)

step6_24_problem_direction_hourly_df["return_side_signal"] = (
    step6_24_problem_direction_hourly_df["is_stockout_return"].fillna(0).astype("int8")
)

step6_24_problem_direction_hourly_df["problem_type"] = np.select(
    [
        (step6_24_problem_direction_hourly_df["departure_side_signal"] == 1)
        & (step6_24_problem_direction_hourly_df["return_side_signal"] == 0),
        (step6_24_problem_direction_hourly_df["departure_side_signal"] == 0)
        & (step6_24_problem_direction_hourly_df["return_side_signal"] == 1),
        (step6_24_problem_direction_hourly_df["departure_side_signal"] == 1)
        & (step6_24_problem_direction_hourly_df["return_side_signal"] == 1),
    ],
    [
        "bike_shortage_risk",
        "dock_shortage_risk",
        "mixed_risk",
    ],
    default="no_clear_signal",
)

step6_24_problem_direction_hourly_df["problem_type"] = (
    step6_24_problem_direction_hourly_df["problem_type"].astype("category")
)

step6_24_problem_direction_hourly_df["problem_signal_strength"] = (
    step6_24_problem_direction_hourly_df["departure_side_signal"]
    + step6_24_problem_direction_hourly_df["return_side_signal"]
).astype("int8")

step6_24_problem_direction_hourly_df["problem_direction_sort_score"] = np.select(
    [
        step6_24_problem_direction_hourly_df["problem_type"] == "bike_shortage_risk",
        step6_24_problem_direction_hourly_df["problem_type"] == "dock_shortage_risk",
        step6_24_problem_direction_hourly_df["problem_type"] == "mixed_risk",
    ],
    [
        3,
        3,
        2,
    ],
    default=1,
).astype("int8")

step6_24_output_columns = [
    "activity_hour",
    "activity_date",
    "hour_of_day",
    "representative_station_id",
    "station_name",
    "departures_hourly",
    "returns_hourly",
    "net_flow_hour",
    "cumulative_net_flow",
    "estimated_capacity",
    "occupancy_proxy",
    "free_capacity_proxy",
    "is_stockout_departure",
    "is_stockout_return",
    "departure_side_signal",
    "return_side_signal",
    "problem_signal_strength",
    "problem_direction_sort_score",
    "problem_type",
]

step6_24_problem_direction_hourly_df = (
    step6_24_problem_direction_hourly_df[step6_24_output_columns]
    .sort_values(["activity_hour", "representative_station_id"])
    .reset_index(drop=True)
)

step6_24_problem_type_summary_df = (
    step6_24_problem_direction_hourly_df["problem_type"]
    .value_counts(dropna=False)
    .rename_axis("problem_type")
    .reset_index(name="row_count")
)

step6_24_problem_type_summary_df["row_share"] = (
    step6_24_problem_type_summary_df["row_count"]
    / step6_24_problem_type_summary_df["row_count"].sum()
)

step6_24_signal_summary_df = pd.DataFrame(
    [
        {
            "check_area": "hourly_rows",
            "status": "ok",
            "value": str(step6_24_problem_direction_hourly_df.shape[0]),
        },
        {
            "check_area": "hourly_columns",
            "status": "ok",
            "value": str(step6_24_problem_direction_hourly_df.shape[1]),
        },
        {
            "check_area": "unique_stations",
            "status": "ok",
            "value": str(step6_24_problem_direction_hourly_df["representative_station_id"].nunique()),
        },
        {
            "check_area": "problem_type_count",
            "status": "ok",
            "value": str(step6_24_problem_direction_hourly_df["problem_type"].nunique()),
        },
        {
            "check_area": "departure_signal_rows",
            "status": "ok",
            "value": str(int(step6_24_problem_direction_hourly_df["departure_side_signal"].sum())),
        },
        {
            "check_area": "return_signal_rows",
            "status": "ok",
            "value": str(int(step6_24_problem_direction_hourly_df["return_side_signal"].sum())),
        },
    ]
)

step6_24_problem_direction_hourly_path = step6_11_outputs_dir / "b6_11_problem_direction_hourly.parquet"
step6_24_problem_type_summary_path = step6_11_reports_dir / "b6_11_problem_type_hourly_summary.parquet"
step6_24_signal_summary_path = step6_11_reports_dir / "b6_11_problem_direction_signal_summary.parquet"

step6_24_problem_direction_hourly_df.to_parquet(step6_24_problem_direction_hourly_path, index=False)
step6_24_problem_type_summary_df.to_parquet(step6_24_problem_type_summary_path, index=False)
step6_24_signal_summary_df.to_parquet(step6_24_signal_summary_path, index=False)

display(step6_24_signal_summary_df)
display(step6_24_problem_type_summary_df)
display(step6_24_problem_direction_hourly_df.head(10))

              check_area status    value
0            hourly_rows     ok  5257704
1         hourly_columns     ok       19
2        unique_stations     ok      344
3     problem_type_count     ok        3
4  departure_signal_rows     ok  2449142
5     return_signal_rows     ok    19739

         problem_type  row_count  row_share
0     no_clear_signal    2788823   0.530426
1  bike_shortage_risk    2449142   0.465820
2  dock_shortage_risk      19739   0.003754

,activity_hour,activity_date,hour_of_day,representative_station_id,station_name,departures_hourly,returns_hourly,net_flow_hour,cumulative_net_flow,estimated_capacity,occupancy_proxy,free_capacity_proxy,is_stockout_departure,is_stockout_return,departure_side_signal,return_side_signal,problem_signal_strength,problem_direction_sort_score,problem_type
0,2017-05-02,2017-05-02,0,1,Kaivopuisto,0,0,0,0,48.950001,0,48.950001,1,0,1,0,1,3,bike_shortage_risk
1,2017-05-02,2017-05-02,0,10,Kasarmitori,0,0,0,0,38.000000,0,38.000000,1,0,1,0,1,3,bike_shortage_risk
2,2017-05-02,2017-05-02,0,100,Teljäntie,0,0,0,0,11.950000,0,11.950000,1,0,1,0,1,3,bike_shortage_risk
3,2017-05-02,2017-05-02,0,101,Huopalahdentie,0,0,0,0,27.000000,0,27.000000,1,0,1,0,1,3,bike_shortage_risk
4,2017-05-02,2017-05-02,0,103,Vihdintie,0,0,0,0,16.000000,0,16.000000,1,0,1,0,1,3,bike_shortage_risk
5,2017-05-02,2017-05-02,0,104,Kriikunakuja,0,0,0,0,12.950000,0,12.950000,1,0,1,0,1,3,bike_shortage_risk
6,2017-05-02,2017-05-02,0,105,Tilkantori,0,0,0,0,15.000000,0,15.000000,1,0,1,0,1,3,bike_shortage_risk
7,2017-05-02,2017-05-02,0,106,Korppaanmäentie,0,0,0,0,16.000000,0,16.000000,1,0,1,0,1,3,bike_shortage_risk
8,2017-05-02,2017-05-02,0,107,Tenholantie,0,0,0,0,21.000000,0,21.000000,1,0,1,0,1,3,bike_shortage_risk
9,2017-05-02,2017-05-02,0,108,Radiokatu,0,0,0,0,16.000000,0,16.000000,1,0,1,0,1,3,bike_shortage_risk

In [12]:
# 6.2.5 Agregacja kierunku problemu do poziomu dzień-stacja

import numpy as np
import pandas as pd


step6_25_required_objects = [
    "step6_24_problem_direction_hourly_df",
    "step6_11_outputs_dir",
    "step6_11_reports_dir",
]

step6_25_missing_objects = [
    object_name
    for object_name in step6_25_required_objects
    if object_name not in globals()
]

assert not step6_25_missing_objects, f"Missing required objects: {step6_25_missing_objects}"

step6_25_problem_direction_daily_base_df = step6_24_problem_direction_hourly_df[
    [
        "activity_date",
        "representative_station_id",
        "station_name",
        "hour_of_day",
        "departures_hourly",
        "returns_hourly",
        "net_flow_hour",
        "cumulative_net_flow",
        "estimated_capacity",
        "occupancy_proxy",
        "free_capacity_proxy",
        "departure_side_signal",
        "return_side_signal",
        "problem_signal_strength",
        "problem_direction_sort_score",
        "problem_type",
    ]
].copy()

step6_25_daily_signal_summary_df = (
    step6_25_problem_direction_daily_base_df
    .groupby(["activity_date", "representative_station_id"], observed=True)
    .agg(
        station_name=("station_name", "first"),
        estimated_capacity=("estimated_capacity", "max"),
        departure_signal_hours=("departure_side_signal", "sum"),
        return_signal_hours=("return_side_signal", "sum"),
        max_problem_signal_strength=("problem_signal_strength", "max"),
        max_problem_direction_sort_score=("problem_direction_sort_score", "max"),
        total_departures=("departures_hourly", "sum"),
        total_returns=("returns_hourly", "sum"),
        daily_net_flow=("net_flow_hour", "sum"),
        min_occupancy_proxy=("occupancy_proxy", "min"),
        max_occupancy_proxy=("occupancy_proxy", "max"),
        min_free_capacity_proxy=("free_capacity_proxy", "min"),
        max_free_capacity_proxy=("free_capacity_proxy", "max"),
        observed_hour_count=("hour_of_day", "nunique"),
    )
    .reset_index()
)

step6_25_daily_signal_summary_df["departure_signal_hours"] = (
    step6_25_daily_signal_summary_df["departure_signal_hours"].astype("int16")
)

step6_25_daily_signal_summary_df["return_signal_hours"] = (
    step6_25_daily_signal_summary_df["return_signal_hours"].astype("int16")
)

step6_25_daily_signal_summary_df["observed_hour_count"] = (
    step6_25_daily_signal_summary_df["observed_hour_count"].astype("int16")
)

step6_25_daily_signal_summary_df["problem_type"] = np.select(
    [
        (step6_25_daily_signal_summary_df["departure_signal_hours"] > 0)
        & (step6_25_daily_signal_summary_df["return_signal_hours"] == 0),
        (step6_25_daily_signal_summary_df["departure_signal_hours"] == 0)
        & (step6_25_daily_signal_summary_df["return_signal_hours"] > 0),
        (step6_25_daily_signal_summary_df["departure_signal_hours"] > 0)
        & (step6_25_daily_signal_summary_df["return_signal_hours"] > 0),
    ],
    [
        "bike_shortage_risk",
        "dock_shortage_risk",
        "mixed_risk",
    ],
    default="no_clear_signal",
)

step6_25_daily_signal_summary_df["problem_type"] = (
    step6_25_daily_signal_summary_df["problem_type"].astype("category")
)

step6_25_daily_signal_summary_df["problem_direction_score"] = (
    step6_25_daily_signal_summary_df["departure_signal_hours"]
    + step6_25_daily_signal_summary_df["return_signal_hours"]
).astype("int16")

step6_25_daily_signal_summary_df["problem_direction_share_of_day"] = (
    step6_25_daily_signal_summary_df["problem_direction_score"]
    / step6_25_daily_signal_summary_df["observed_hour_count"].replace(0, np.nan)
).astype("float32")

step6_25_daily_signal_summary_df["dominant_signal_side"] = np.select(
    [
        step6_25_daily_signal_summary_df["departure_signal_hours"]
        > step6_25_daily_signal_summary_df["return_signal_hours"],
        step6_25_daily_signal_summary_df["return_signal_hours"]
        > step6_25_daily_signal_summary_df["departure_signal_hours"],
        (
            step6_25_daily_signal_summary_df["departure_signal_hours"]
            == step6_25_daily_signal_summary_df["return_signal_hours"]
        )
        & (step6_25_daily_signal_summary_df["problem_direction_score"] > 0),
    ],
    [
        "departure_side",
        "return_side",
        "balanced_sides",
    ],
    default="no_signal",
)

step6_25_daily_signal_summary_df["dominant_signal_side"] = (
    step6_25_daily_signal_summary_df["dominant_signal_side"].astype("category")
)

step6_25_problem_type_daily_summary_df = (
    step6_25_daily_signal_summary_df["problem_type"]
    .value_counts(dropna=False)
    .rename_axis("problem_type")
    .reset_index(name="row_count")
)

step6_25_problem_type_daily_summary_df["row_share"] = (
    step6_25_problem_type_daily_summary_df["row_count"]
    / step6_25_problem_type_daily_summary_df["row_count"].sum()
)

step6_25_duplicate_day_station_count = int(
    step6_25_daily_signal_summary_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_25_summary_df = pd.DataFrame(
    [
        {
            "check_area": "daily_rows",
            "status": "ok",
            "value": str(step6_25_daily_signal_summary_df.shape[0]),
        },
        {
            "check_area": "unique_stations",
            "status": "ok",
            "value": str(step6_25_daily_signal_summary_df["representative_station_id"].nunique()),
        },
        {
            "check_area": "date_min",
            "status": "ok",
            "value": str(step6_25_daily_signal_summary_df["activity_date"].min()),
        },
        {
            "check_area": "date_max",
            "status": "ok",
            "value": str(step6_25_daily_signal_summary_df["activity_date"].max()),
        },
        {
            "check_area": "duplicate_day_station_keys",
            "status": "ok" if step6_25_duplicate_day_station_count == 0 else "review",
            "value": str(step6_25_duplicate_day_station_count),
        },
        {
            "check_area": "problem_type_count",
            "status": "ok",
            "value": str(step6_25_daily_signal_summary_df["problem_type"].nunique()),
        },
    ]
)

step6_25_problem_direction_daily_path = step6_11_outputs_dir / "b6_12_problem_direction_day_station.parquet"
step6_25_problem_type_daily_summary_path = step6_11_reports_dir / "b6_12_problem_type_day_station_summary.parquet"
step6_25_summary_path = step6_11_reports_dir / "b6_12_problem_direction_day_station_profile.parquet"

step6_25_daily_signal_summary_df.to_parquet(step6_25_problem_direction_daily_path, index=False)
step6_25_problem_type_daily_summary_df.to_parquet(step6_25_problem_type_daily_summary_path, index=False)
step6_25_summary_df.to_parquet(step6_25_summary_path, index=False)

display(step6_25_summary_df)
display(step6_25_problem_type_daily_summary_df)
display(step6_25_daily_signal_summary_df.head(10))

                   check_area status                value
0                  daily_rows     ok               219071
1             unique_stations     ok                  344
2                    date_min     ok  2017-05-02 00:00:00
3                    date_max     ok  2020-11-02 00:00:00
4  duplicate_day_station_keys     ok                    0
5          problem_type_count     ok                    2

         problem_type  row_count  row_share
0  bike_shortage_risk     211990   0.967677
1          mixed_risk       7081   0.032323

,activity_date,representative_station_id,station_name,estimated_capacity,departure_signal_hours,return_signal_hours,max_problem_signal_strength,max_problem_direction_sort_score,total_departures,total_returns,daily_net_flow,min_occupancy_proxy,max_occupancy_proxy,min_free_capacity_proxy,max_free_capacity_proxy,observed_hour_count,problem_type,problem_direction_score,problem_direction_share_of_day,dominant_signal_side
0,2017-05-02,1,Kaivopuisto,48.950001,10,0,1,3,34,34,0,0,7,41.950001,48.950001,24,bike_shortage_risk,10,0.416667,departure_side
1,2017-05-02,10,Kasarmitori,38.000000,16,0,1,3,12,8,-4,0,2,36.000000,38.000000,24,bike_shortage_risk,16,0.666667,departure_side
2,2017-05-02,100,Teljäntie,11.950000,19,0,1,3,2,4,2,0,2,9.950000,11.950000,24,bike_shortage_risk,19,0.791667,departure_side
3,2017-05-02,101,Huopalahdentie,27.000000,17,0,1,3,6,10,4,0,4,23.000000,27.000000,24,bike_shortage_risk,17,0.708333,departure_side
4,2017-05-02,103,Vihdintie,16.000000,17,0,1,3,11,17,6,0,7,9.000000,16.000000,24,bike_shortage_risk,17,0.708333,departure_side
5,2017-05-02,104,Kriikunakuja,12.950000,19,0,1,3,6,6,0,0,2,10.950000,12.950000,24,bike_shortage_risk,19,0.791667,departure_side
6,2017-05-02,105,Tilkantori,15.000000,20,0,1,3,7,11,4,0,4,11.000000,15.000000,24,bike_shortage_risk,20,0.833333,departure_side
7,2017-05-02,106,Korppaanmäentie,16.000000,21,0,1,3,10,9,-1,0,1,15.000000,16.000000,24,bike_shortage_risk,21,0.875000,departure_side
8,2017-05-02,107,Tenholantie,21.000000,19,0,1,3,1,4,3,0,3,18.000000,21.000000,24,bike_shortage_risk,19,0.791667,departure_side
9,2017-05-02,108,Radiokatu,16.000000,20,0,1,3,10,4,-6,0,2,14.000000,16.000000,24,bike_shortage_risk,20,0.833333,departure_side

In [13]:
# 6.2.6 Kontrola spójności dziennego kierunku problemu

import json

import pandas as pd


step6_26_required_objects = [
    "step6_25_daily_signal_summary_df",
    "step6_11_reports_dir",
]

step6_26_missing_objects = [
    object_name
    for object_name in step6_26_required_objects
    if object_name not in globals()
]

assert not step6_26_missing_objects, f"Missing required objects: {step6_26_missing_objects}"

step6_26_direction_consistency_rules = [
    {
        "rule_name": "bike_shortage_requires_departure_signal",
        "problem_type": "bike_shortage_risk",
        "condition_passed": bool(
            (
                step6_25_daily_signal_summary_df.loc[
                    step6_25_daily_signal_summary_df["problem_type"] == "bike_shortage_risk",
                    "departure_signal_hours",
                ] > 0
            ).all()
        ),
    },
    {
        "rule_name": "bike_shortage_excludes_return_signal",
        "problem_type": "bike_shortage_risk",
        "condition_passed": bool(
            (
                step6_25_daily_signal_summary_df.loc[
                    step6_25_daily_signal_summary_df["problem_type"] == "bike_shortage_risk",
                    "return_signal_hours",
                ] == 0
            ).all()
        ),
    },
    {
        "rule_name": "mixed_risk_requires_departure_signal",
        "problem_type": "mixed_risk",
        "condition_passed": bool(
            (
                step6_25_daily_signal_summary_df.loc[
                    step6_25_daily_signal_summary_df["problem_type"] == "mixed_risk",
                    "departure_signal_hours",
                ] > 0
            ).all()
        ),
    },
    {
        "rule_name": "mixed_risk_requires_return_signal",
        "problem_type": "mixed_risk",
        "condition_passed": bool(
            (
                step6_25_daily_signal_summary_df.loc[
                    step6_25_daily_signal_summary_df["problem_type"] == "mixed_risk",
                    "return_signal_hours",
                ] > 0
            ).all()
        ),
    },
    {
        "rule_name": "daily_key_uniqueness",
        "problem_type": "all",
        "condition_passed": bool(
            step6_25_daily_signal_summary_df.duplicated(
                subset=["activity_date", "representative_station_id"]
            ).sum() == 0
        ),
    },
    {
        "rule_name": "observed_hour_count_positive",
        "problem_type": "all",
        "condition_passed": bool(
            (step6_25_daily_signal_summary_df["observed_hour_count"] > 0).all()
        ),
    },
]

step6_26_direction_consistency_df = pd.DataFrame(step6_26_direction_consistency_rules)

step6_26_direction_consistency_df["status"] = step6_26_direction_consistency_df[
    "condition_passed"
].map({True: "ok", False: "review"})

step6_26_problem_direction_statistics_df = (
    step6_25_daily_signal_summary_df
    .groupby("problem_type", observed=True)
    .agg(
        row_count=("problem_type", "size"),
        mean_departure_signal_hours=("departure_signal_hours", "mean"),
        median_departure_signal_hours=("departure_signal_hours", "median"),
        max_departure_signal_hours=("departure_signal_hours", "max"),
        mean_return_signal_hours=("return_signal_hours", "mean"),
        median_return_signal_hours=("return_signal_hours", "median"),
        max_return_signal_hours=("return_signal_hours", "max"),
        mean_problem_direction_score=("problem_direction_score", "mean"),
        median_problem_direction_score=("problem_direction_score", "median"),
        max_problem_direction_score=("problem_direction_score", "max"),
        mean_problem_direction_share_of_day=("problem_direction_share_of_day", "mean"),
        max_problem_direction_share_of_day=("problem_direction_share_of_day", "max"),
    )
    .reset_index()
)

step6_26_problem_direction_statistics_df["row_share"] = (
    step6_26_problem_direction_statistics_df["row_count"]
    / step6_26_problem_direction_statistics_df["row_count"].sum()
)

step6_26_consistency_review_count = int(
    (step6_26_direction_consistency_df["status"] == "review").sum()
)

step6_26_direction_contract = {
    "block_name": "block_6",
    "section_name": "6.2",
    "contract_scope": "daily_problem_direction_consistency",
    "grain": "day_station",
    "source_object": "step6_25_daily_signal_summary_df",
    "key_columns": ["activity_date", "representative_station_id"],
    "output_field": "problem_type",
    "allowed_values_observed": sorted(
        step6_25_daily_signal_summary_df["problem_type"].astype("string").unique().tolist()
    ),
    "consistency_review_count": step6_26_consistency_review_count,
}

step6_26_consistency_path = step6_11_reports_dir / "b6_13_problem_direction_consistency.parquet"
step6_26_statistics_path = step6_11_reports_dir / "b6_13_problem_direction_statistics.parquet"
step6_26_contract_path = step6_11_reports_dir / "b6_13_problem_direction_consistency_contract.json"

step6_26_direction_consistency_df.to_parquet(step6_26_consistency_path, index=False)
step6_26_problem_direction_statistics_df.to_parquet(step6_26_statistics_path, index=False)

with open(step6_26_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_26_direction_contract, file, ensure_ascii=False, indent=2)

step6_26_summary_df = pd.DataFrame(
    [
        {
            "check_area": "consistency_rules",
            "status": "ok",
            "value": str(step6_26_direction_consistency_df.shape[0]),
        },
        {
            "check_area": "consistency_review_count",
            "status": "ok" if step6_26_consistency_review_count == 0 else "review",
            "value": str(step6_26_consistency_review_count),
        },
        {
            "check_area": "problem_types_observed",
            "status": "ok",
            "value": str(step6_25_daily_signal_summary_df["problem_type"].nunique()),
        },
        {
            "check_area": "consistency_path",
            "status": "ok",
            "value": str(step6_26_consistency_path),
        },
        {
            "check_area": "statistics_path",
            "status": "ok",
            "value": str(step6_26_statistics_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_26_contract_path),
        },
    ]
)

step6_26_summary_df["check_area"] = step6_26_summary_df["check_area"].astype("string")
step6_26_summary_df["status"] = step6_26_summary_df["status"].astype("string")
step6_26_summary_df["value"] = step6_26_summary_df["value"].astype("string")

display(step6_26_summary_df)
display(step6_26_direction_consistency_df)
display(step6_26_problem_direction_statistics_df)

,check_area,status,value
0,consistency_rules,ok,6
1,consistency_review_count,ok,0
2,problem_types_observed,ok,2
3,consistency_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,statistics_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,rule_name,problem_type,condition_passed,status
0,bike_shortage_requires_departure_signal,bike_shortage_risk,True,ok
1,bike_shortage_excludes_return_signal,bike_shortage_risk,True,ok
2,mixed_risk_requires_departure_signal,mixed_risk,True,ok
3,mixed_risk_requires_return_signal,mixed_risk,True,ok
4,daily_key_uniqueness,all,True,ok
5,observed_hour_count_positive,all,True,ok

,problem_type,row_count,mean_departure_signal_hours,median_departure_signal_hours,max_departure_signal_hours,mean_return_signal_hours,median_return_signal_hours,max_return_signal_hours,mean_problem_direction_score,median_problem_direction_score,max_problem_direction_score,mean_problem_direction_share_of_day,max_problem_direction_share_of_day,row_share
0,bike_shortage_risk,211990,11.260286,11.0,24,0.000000,0.0,0,11.260286,11.0,24,0.469179,1.0,0.967677
1,mixed_risk,7081,8.766276,9.0,21,2.787601,2.0,17,11.553877,12.0,24,0.481412,1.0,0.032323

In [14]:
# 6.2.7 Zamknięcie kontraktu kierunku problemu

import json

import pandas as pd


step6_27_required_objects = [
    "step6_21_problem_direction_contract",
    "step6_25_daily_signal_summary_df",
    "step6_25_problem_type_daily_summary_df",
    "step6_26_direction_consistency_df",
    "step6_26_problem_direction_statistics_df",
    "step6_11_reports_dir",
    "step6_11_outputs_dir",
]

step6_27_missing_objects = [
    object_name
    for object_name in step6_27_required_objects
    if object_name not in globals()
]

assert not step6_27_missing_objects, f"Missing required objects: {step6_27_missing_objects}"

step6_27_daily_row_count = int(step6_25_daily_signal_summary_df.shape[0])
step6_27_unique_station_count = int(step6_25_daily_signal_summary_df["representative_station_id"].nunique())
step6_27_duplicate_key_count = int(
    step6_25_daily_signal_summary_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_27_consistency_review_count = int(
    (step6_26_direction_consistency_df["status"] == "review").sum()
)

step6_27_observed_problem_types = sorted(
    step6_25_daily_signal_summary_df["problem_type"]
    .astype("string")
    .unique()
    .tolist()
)

step6_27_required_output_columns = [
    "activity_date",
    "representative_station_id",
    "station_name",
    "estimated_capacity",
    "departure_signal_hours",
    "return_signal_hours",
    "total_departures",
    "total_returns",
    "daily_net_flow",
    "min_occupancy_proxy",
    "max_occupancy_proxy",
    "min_free_capacity_proxy",
    "max_free_capacity_proxy",
    "observed_hour_count",
    "problem_type",
    "problem_direction_score",
    "problem_direction_share_of_day",
    "dominant_signal_side",
]

step6_27_available_output_columns = step6_25_daily_signal_summary_df.columns.tolist()

step6_27_missing_output_columns = [
    column_name
    for column_name in step6_27_required_output_columns
    if column_name not in step6_27_available_output_columns
]

assert not step6_27_missing_output_columns, f"Missing output columns: {step6_27_missing_output_columns}"
assert step6_27_duplicate_key_count == 0, "Duplicated day-station keys detected."
assert step6_27_consistency_review_count == 0, "Problem direction consistency review detected."

step6_27_problem_direction_output_df = (
    step6_25_daily_signal_summary_df[step6_27_required_output_columns]
    .sort_values(["activity_date", "representative_station_id"])
    .reset_index(drop=True)
)

step6_27_problem_direction_output_path = step6_11_outputs_dir / "b6_13_problem_direction_output_day_station.parquet"
step6_27_problem_direction_output_df.to_parquet(step6_27_problem_direction_output_path, index=False)

step6_27_section_contract = {
    "block_name": "block_6",
    "section_name": "6.2",
    "section_scope": "problem_direction_layer",
    "source_grain": "hour_station",
    "output_grain": "day_station",
    "source_object": "step6_24_problem_direction_hourly_df",
    "output_object": "step6_27_problem_direction_output_df",
    "output_path": str(step6_27_problem_direction_output_path),
    "key_columns": [
        "activity_date",
        "representative_station_id",
    ],
    "output_field": "problem_type",
    "observed_problem_types": step6_27_observed_problem_types,
    "allowed_problem_types": [
        "bike_shortage_risk",
        "dock_shortage_risk",
        "mixed_risk",
        "no_clear_signal",
    ],
    "direction_logic": {
        "bike_shortage_risk": "departure_signal_hours > 0 and return_signal_hours == 0",
        "dock_shortage_risk": "departure_signal_hours == 0 and return_signal_hours > 0",
        "mixed_risk": "departure_signal_hours > 0 and return_signal_hours > 0",
        "no_clear_signal": "departure_signal_hours == 0 and return_signal_hours == 0",
    },
    "dispatcher_action_family_mapping": {
        "bike_shortage_risk": "deliver_bikes",
        "dock_shortage_risk": "remove_bikes",
        "mixed_risk": "check_station_state",
        "no_clear_signal": "check_station_state",
    },
    "daily_row_count": step6_27_daily_row_count,
    "unique_station_count": step6_27_unique_station_count,
    "duplicate_key_count": step6_27_duplicate_key_count,
    "consistency_review_count": step6_27_consistency_review_count,
}

step6_27_section_status_df = pd.DataFrame(
    [
        {
            "section_item": "section_6_2_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "section_item": "output_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "section_item": "daily_rows",
            "status": "ok",
            "value": str(step6_27_daily_row_count),
        },
        {
            "section_item": "unique_stations",
            "status": "ok",
            "value": str(step6_27_unique_station_count),
        },
        {
            "section_item": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_27_duplicate_key_count),
        },
        {
            "section_item": "consistency_review_count",
            "status": "ok",
            "value": str(step6_27_consistency_review_count),
        },
        {
            "section_item": "observed_problem_types",
            "status": "ok",
            "value": json.dumps(step6_27_observed_problem_types, ensure_ascii=False),
        },
    ]
)

step6_27_section_contract_path = step6_11_reports_dir / "b6_14_problem_direction_section_contract.json"
step6_27_section_status_path = step6_11_reports_dir / "b6_14_problem_direction_section_status.parquet"

with open(step6_27_section_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_27_section_contract, file, ensure_ascii=False, indent=2)

step6_27_section_status_df.to_parquet(step6_27_section_status_path, index=False)

step6_27_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_6_2_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "check_area": "problem_direction_output_rows",
            "status": "ok",
            "value": str(step6_27_problem_direction_output_df.shape[0]),
        },
        {
            "check_area": "problem_direction_output_columns",
            "status": "ok",
            "value": str(step6_27_problem_direction_output_df.shape[1]),
        },
        {
            "check_area": "output_path",
            "status": "ok",
            "value": str(step6_27_problem_direction_output_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_27_section_contract_path),
        },
        {
            "check_area": "status_path",
            "status": "ok",
            "value": str(step6_27_section_status_path),
        },
    ]
)

step6_27_summary_df["check_area"] = step6_27_summary_df["check_area"].astype("string")
step6_27_summary_df["status"] = step6_27_summary_df["status"].astype("string")
step6_27_summary_df["value"] = step6_27_summary_df["value"].astype("string")

display(step6_27_summary_df)
display(step6_27_section_status_df)
display(step6_27_problem_direction_output_df.head(10))

,check_area,status,value
0,section_6_2_status,ok,closed
1,problem_direction_output_rows,ok,219071
2,problem_direction_output_columns,ok,18
3,output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,status_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                 section_item status                                 value
0          section_6_2_status     ok                                closed
1                output_grain     ok                           day_station
2                  daily_rows     ok                                219071
3             unique_stations     ok                                   344
4  duplicate_day_station_keys     ok                                     0
5    consistency_review_count     ok                                     0
6      observed_problem_types     ok  ["bike_shortage_risk", "mixed_risk"]

,activity_date,representative_station_id,station_name,estimated_capacity,departure_signal_hours,return_signal_hours,total_departures,total_returns,daily_net_flow,min_occupancy_proxy,max_occupancy_proxy,min_free_capacity_proxy,max_free_capacity_proxy,observed_hour_count,problem_type,problem_direction_score,problem_direction_share_of_day,dominant_signal_side
0,2017-05-02,1,Kaivopuisto,48.950001,10,0,34,34,0,0,7,41.950001,48.950001,24,bike_shortage_risk,10,0.416667,departure_side
1,2017-05-02,10,Kasarmitori,38.000000,16,0,12,8,-4,0,2,36.000000,38.000000,24,bike_shortage_risk,16,0.666667,departure_side
2,2017-05-02,100,Teljäntie,11.950000,19,0,2,4,2,0,2,9.950000,11.950000,24,bike_shortage_risk,19,0.791667,departure_side
3,2017-05-02,101,Huopalahdentie,27.000000,17,0,6,10,4,0,4,23.000000,27.000000,24,bike_shortage_risk,17,0.708333,departure_side
4,2017-05-02,103,Vihdintie,16.000000,17,0,11,17,6,0,7,9.000000,16.000000,24,bike_shortage_risk,17,0.708333,departure_side
5,2017-05-02,104,Kriikunakuja,12.950000,19,0,6,6,0,0,2,10.950000,12.950000,24,bike_shortage_risk,19,0.791667,departure_side
6,2017-05-02,105,Tilkantori,15.000000,20,0,7,11,4,0,4,11.000000,15.000000,24,bike_shortage_risk,20,0.833333,departure_side
7,2017-05-02,106,Korppaanmäentie,16.000000,21,0,10,9,-1,0,1,15.000000,16.000000,24,bike_shortage_risk,21,0.875000,departure_side
8,2017-05-02,107,Tenholantie,21.000000,19,0,1,4,3,0,3,18.000000,21.000000,24,bike_shortage_risk,19,0.791667,departure_side
9,2017-05-02,108,Radiokatu,16.000000,20,0,10,4,-6,0,2,14.000000,16.000000,24,bike_shortage_risk,20,0.833333,departure_side

## Podsumowanie działu 6.2 Warstwa kierunku problemu: brak czy nadmiar rowerów

**Kontekst inżynieryjny:** W dziale `6.2` zbudowano warstwę kierunku problemu, której celem jest przekształcenie godzinowych sygnałów alertowych w dzienną klasyfikację typu problemu dla każdej stacji. Najpierw zdefiniowano kontrakt logiczny dla pola `problem_type`, obejmujący wartości `bike_shortage_risk`, `dock_shortage_risk`, `mixed_risk` oraz `no_clear_signal`. Następnie zweryfikowano, że główne źródło `station_alert_hour_df.parquet` zawiera komplet `14` wymaganych kolumn, w tym `activity_hour`, `activity_date`, `hour_of_day`, `representative_station_id`, `station_name`, `departures_hourly`, `returns_hourly`, `net_flow_hour`, `cumulative_net_flow`, `estimated_capacity`, `occupancy_proxy`, `free_capacity_proxy`, `is_stockout_departure` oraz `is_stockout_return`. Po wczytaniu pełnej warstwy godzinowej zbudowano sygnały pomocnicze `departure_side_signal` i `return_side_signal`, wyznaczono godzinowy `problem_type`, a następnie zagregowano wynik z poziomu godzina–stacja do poziomu dzień–stacja.

**Interpretacja wyniku:** Źródło wejściowe dla działu `6.2` obejmuje `5 257 704` rekordy godzinowe, `14` kolumn oraz `344` unikalne stacje w zakresie od `2017-05-02 00:00:00` do `2020-11-02 23:00:00`. Nie stwierdzono duplikatów klucza `activity_hour + representative_station_id` ani braków danych w wymaganych kolumnach. Godzinowa warstwa kierunku problemu została zbudowana dla `5 257 704` rekordów i `19` kolumn. Na poziomie godzinowym rozkład `problem_type` obejmuje `no_clear_signal` dla `2 788 823` rekordów, `bike_shortage_risk` dla `2 449 142` rekordów oraz `dock_shortage_risk` dla `19 739` rekordów. Po agregacji do poziomu dzień–stacja uzyskano `219 071` rekordów, `344` stacje, brak duplikatów klucza `activity_date + representative_station_id` oraz dwa obserwowane typy problemu: `bike_shortage_risk` i `mixed_risk`. Typ `bike_shortage_risk` występuje w `211 990` rekordach, co stanowi około `96.77%` warstwy dziennej, natomiast `mixed_risk` występuje w `7 081` rekordach, czyli około `3.23%`. Kontrola spójności potwierdziła `6` reguł kierunku problemu, przy `0` regułach wymagających przeglądu.

**Znaczenie biznesowe:** Dział `6.2` przekształca surowe sygnały godzinowe w dzienny język operacyjny, który może być dalej wykorzystany przez panel dyspozytora. Dzięki polom `departure_signal_hours`, `return_signal_hours`, `problem_direction_score`, `problem_direction_share_of_day` oraz `dominant_signal_side` dalsze etapy BLOKU 6 nie muszą pracować bezpośrednio na milionach rekordów godzinowych, lecz na zwartej warstwie dzień–stacja. Warstwa ta wskazuje, czy problem wynika głównie ze strony wypożyczeń, ze strony zwrotów, czy z kombinacji obu sygnałów. W praktyce przygotowuje to podstawę pod rekomendacje operacyjne, takie jak `deliver_bikes`, `remove_bikes` oraz `check_station_state`, a także pod późniejszą priorytetyzację stacji, szacowanie relokacji i budowę listy działań dla dyspozytora.

**Wniosek:** Dział `6.2` został domknięty poprawnie. Zbudowano finalną warstwę kierunku problemu na poziomie dzień–stacja, zapisaną jako `b6_13_problem_direction_output_day_station.parquet`, wraz z kontraktem `b6_14_problem_direction_section_contract.json` i statusem `b6_14_problem_direction_section_status.parquet`. Warstwa zawiera `219 071` rekordów, `18` kolumn, `344` stacje, brak duplikatów klucza dziennego oraz spójny `problem_type`. Oznacza to, że można przejść do kolejnego etapu, czyli `6.3 Warstwa rekomendacji: dowieź / zabierz / sprawdź`, mając gotowy kierunek problemu jako podstawę do przypisania działania operacyjnego.

## 6.3 Warstwa rekomendacji: dowieź / zabierz / sprawdź

In [15]:
# 6.3.1 Definicja kontraktu rekomendacji operacyjnej

import json

import pandas as pd


step6_31_required_objects = [
    "step6_27_problem_direction_output_df",
    "step6_11_reports_dir",
]

step6_31_missing_objects = [
    object_name
    for object_name in step6_31_required_objects
    if object_name not in globals()
]

assert not step6_31_missing_objects, f"Missing required objects: {step6_31_missing_objects}"

step6_31_recommendation_contract = {
    "block_name": "block_6",
    "section_name": "6.3",
    "section_scope": "operational_recommendation_layer",
    "source_object": "step6_27_problem_direction_output_df",
    "source_grain": "day_station",
    "output_grain": "day_station",
    "input_field": "problem_type",
    "output_field": "recommended_action",
    "allowed_values": [
        "deliver_bikes",
        "remove_bikes",
        "check_station_state",
    ],
    "recommendation_rules": {
        "bike_shortage_risk": "deliver_bikes",
        "dock_shortage_risk": "remove_bikes",
        "mixed_risk": "check_station_state",
        "no_clear_signal": "check_station_state",
    },
    "supporting_intensity_fields": [
        "departure_signal_hours",
        "return_signal_hours",
        "problem_direction_score",
        "problem_direction_share_of_day",
        "dominant_signal_side",
    ],
    "routing_scope": "station_level_recommendation",
    "builds_global_fleet_routing": False,
}

step6_31_recommendation_values_df = pd.DataFrame(
    [
        {
            "problem_type": "bike_shortage_risk",
            "recommended_action": "deliver_bikes",
            "action_priority": 1,
            "requires_departure_signal": True,
            "requires_return_signal": False,
        },
        {
            "problem_type": "dock_shortage_risk",
            "recommended_action": "remove_bikes",
            "action_priority": 2,
            "requires_departure_signal": False,
            "requires_return_signal": True,
        },
        {
            "problem_type": "mixed_risk",
            "recommended_action": "check_station_state",
            "action_priority": 3,
            "requires_departure_signal": True,
            "requires_return_signal": True,
        },
        {
            "problem_type": "no_clear_signal",
            "recommended_action": "check_station_state",
            "action_priority": 4,
            "requires_departure_signal": False,
            "requires_return_signal": False,
        },
    ]
)

step6_31_recommendation_values_df["problem_type"] = (
    step6_31_recommendation_values_df["problem_type"].astype("string")
)

step6_31_recommendation_values_df["recommended_action"] = (
    step6_31_recommendation_values_df["recommended_action"].astype("string")
)

step6_31_recommendation_contract_path = step6_11_reports_dir / "b6_15_operational_recommendation_contract.json"
step6_31_recommendation_values_path = step6_11_reports_dir / "b6_15_operational_recommendation_values.parquet"

with open(step6_31_recommendation_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_31_recommendation_contract, file, ensure_ascii=False, indent=2)

step6_31_recommendation_values_df.to_parquet(step6_31_recommendation_values_path, index=False)

step6_31_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_scope",
            "status": "ok",
            "value": "operational_recommendation_layer",
        },
        {
            "check_area": "source_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "check_area": "allowed_recommendations",
            "status": "ok",
            "value": str(step6_31_recommendation_values_df["recommended_action"].nunique()),
        },
        {
            "check_area": "problem_type_rules",
            "status": "ok",
            "value": str(step6_31_recommendation_values_df.shape[0]),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_31_recommendation_contract_path),
        },
        {
            "check_area": "recommendation_values_path",
            "status": "ok",
            "value": str(step6_31_recommendation_values_path),
        },
    ]
)

step6_31_summary_df["check_area"] = step6_31_summary_df["check_area"].astype("string")
step6_31_summary_df["status"] = step6_31_summary_df["status"].astype("string")
step6_31_summary_df["value"] = step6_31_summary_df["value"].astype("string")

display(step6_31_summary_df)
display(step6_31_recommendation_values_df)

,check_area,status,value
0,section_scope,ok,operational_recommendation_layer
1,source_grain,ok,day_station
2,allowed_recommendations,ok,3
3,problem_type_rules,ok,4
4,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,recommendation_values_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,problem_type,recommended_action,action_priority,requires_departure_signal,requires_return_signal
0,bike_shortage_risk,deliver_bikes,1,True,False
1,dock_shortage_risk,remove_bikes,2,False,True
2,mixed_risk,check_station_state,3,True,True
3,no_clear_signal,check_station_state,4,False,False

In [16]:
# 6.3.2 Budowa rekomendacji operacyjnej

import pandas as pd


step6_32_required_objects = [
    "step6_27_problem_direction_output_df",
    "step6_31_recommendation_values_df",
    "step6_11_reports_dir",
]

step6_32_missing_objects = [
    object_name
    for object_name in step6_32_required_objects
    if object_name not in globals()
]

assert not step6_32_missing_objects, f"Missing required objects: {step6_32_missing_objects}"

step6_32_recommendation_input_df = step6_27_problem_direction_output_df.copy()

step6_32_recommendation_mapping_df = step6_31_recommendation_values_df[
    [
        "problem_type",
        "recommended_action",
        "action_priority",
    ]
].copy()

step6_32_recommendation_mapping_df["problem_type"] = (
    step6_32_recommendation_mapping_df["problem_type"].astype("string")
)

step6_32_recommendation_input_df["problem_type"] = (
    step6_32_recommendation_input_df["problem_type"].astype("string")
)

step6_32_operational_recommendation_df = (
    step6_32_recommendation_input_df
    .merge(
        step6_32_recommendation_mapping_df,
        on="problem_type",
        how="left",
        validate="many_to_one",
    )
)

step6_32_missing_recommendation_count = int(
    step6_32_operational_recommendation_df["recommended_action"].isna().sum()
)

assert step6_32_missing_recommendation_count == 0, "Missing recommended_action values detected."

step6_32_operational_recommendation_df["recommended_action"] = (
    step6_32_operational_recommendation_df["recommended_action"].astype("category")
)

step6_32_operational_recommendation_df["action_priority"] = (
    step6_32_operational_recommendation_df["action_priority"].astype("int8")
)

step6_32_action_summary_df = (
    step6_32_operational_recommendation_df["recommended_action"]
    .value_counts(dropna=False)
    .rename_axis("recommended_action")
    .reset_index(name="row_count")
)

step6_32_action_summary_df["row_share"] = (
    step6_32_action_summary_df["row_count"]
    / step6_32_action_summary_df["row_count"].sum()
)

step6_32_problem_action_summary_df = (
    step6_32_operational_recommendation_df
    .groupby(["problem_type", "recommended_action"], observed=True)
    .size()
    .reset_index(name="row_count")
)

step6_32_problem_action_summary_df["row_share"] = (
    step6_32_problem_action_summary_df["row_count"]
    / step6_32_problem_action_summary_df["row_count"].sum()
)

step6_32_duplicate_key_count = int(
    step6_32_operational_recommendation_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_32_summary_df = pd.DataFrame(
    [
        {
            "check_area": "recommendation_rows",
            "status": "ok",
            "value": str(step6_32_operational_recommendation_df.shape[0]),
        },
        {
            "check_area": "recommendation_columns",
            "status": "ok",
            "value": str(step6_32_operational_recommendation_df.shape[1]),
        },
        {
            "check_area": "missing_recommendations",
            "status": "ok",
            "value": str(step6_32_missing_recommendation_count),
        },
        {
            "check_area": "duplicate_day_station_keys",
            "status": "ok" if step6_32_duplicate_key_count == 0 else "review",
            "value": str(step6_32_duplicate_key_count),
        },
        {
            "check_area": "observed_actions",
            "status": "ok",
            "value": str(step6_32_operational_recommendation_df["recommended_action"].nunique()),
        },
    ]
)

step6_32_action_summary_path = step6_11_reports_dir / "b6_16_recommended_action_summary.parquet"
step6_32_problem_action_summary_path = step6_11_reports_dir / "b6_16_problem_action_summary.parquet"
step6_32_summary_path = step6_11_reports_dir / "b6_16_operational_recommendation_profile.parquet"

step6_32_action_summary_df.to_parquet(step6_32_action_summary_path, index=False)
step6_32_problem_action_summary_df.to_parquet(step6_32_problem_action_summary_path, index=False)
step6_32_summary_df.to_parquet(step6_32_summary_path, index=False)

display(step6_32_summary_df)
display(step6_32_action_summary_df)
display(step6_32_problem_action_summary_df)
display(step6_32_operational_recommendation_df.head(10))

                   check_area status   value
0         recommendation_rows     ok  219071
1      recommendation_columns     ok      20
2     missing_recommendations     ok       0
3  duplicate_day_station_keys     ok       0
4            observed_actions     ok       2

    recommended_action  row_count  row_share
0        deliver_bikes     211990   0.967677
1  check_station_state       7081   0.032323

         problem_type   recommended_action  row_count  row_share
0  bike_shortage_risk        deliver_bikes     211990   0.967677
1          mixed_risk  check_station_state       7081   0.032323

,activity_date,representative_station_id,station_name,estimated_capacity,departure_signal_hours,return_signal_hours,total_departures,total_returns,daily_net_flow,min_occupancy_proxy,max_occupancy_proxy,min_free_capacity_proxy,max_free_capacity_proxy,observed_hour_count,problem_type,problem_direction_score,problem_direction_share_of_day,dominant_signal_side,recommended_action,action_priority
0,2017-05-02,1,Kaivopuisto,48.950001,10,0,34,34,0,0,7,41.950001,48.950001,24,bike_shortage_risk,10,0.416667,departure_side,deliver_bikes,1
1,2017-05-02,10,Kasarmitori,38.000000,16,0,12,8,-4,0,2,36.000000,38.000000,24,bike_shortage_risk,16,0.666667,departure_side,deliver_bikes,1
2,2017-05-02,100,Teljäntie,11.950000,19,0,2,4,2,0,2,9.950000,11.950000,24,bike_shortage_risk,19,0.791667,departure_side,deliver_bikes,1
3,2017-05-02,101,Huopalahdentie,27.000000,17,0,6,10,4,0,4,23.000000,27.000000,24,bike_shortage_risk,17,0.708333,departure_side,deliver_bikes,1
4,2017-05-02,103,Vihdintie,16.000000,17,0,11,17,6,0,7,9.000000,16.000000,24,bike_shortage_risk,17,0.708333,departure_side,deliver_bikes,1
5,2017-05-02,104,Kriikunakuja,12.950000,19,0,6,6,0,0,2,10.950000,12.950000,24,bike_shortage_risk,19,0.791667,departure_side,deliver_bikes,1
6,2017-05-02,105,Tilkantori,15.000000,20,0,7,11,4,0,4,11.000000,15.000000,24,bike_shortage_risk,20,0.833333,departure_side,deliver_bikes,1
7,2017-05-02,106,Korppaanmäentie,16.000000,21,0,10,9,-1,0,1,15.000000,16.000000,24,bike_shortage_risk,21,0.875000,departure_side,deliver_bikes,1
8,2017-05-02,107,Tenholantie,21.000000,19,0,1,4,3,0,3,18.000000,21.000000,24,bike_shortage_risk,19,0.791667,departure_side,deliver_bikes,1
9,2017-05-02,108,Radiokatu,16.000000,20,0,10,4,-6,0,2,14.000000,16.000000,24,bike_shortage_risk,20,0.833333,departure_side,deliver_bikes,1

In [17]:
# 6.3.3 Kontrola spójności rekomendacji operacyjnej

import json

import pandas as pd


step6_33_required_objects = [
    "step6_32_operational_recommendation_df",
    "step6_31_recommendation_values_df",
    "step6_11_reports_dir",
]

step6_33_missing_objects = [
    object_name
    for object_name in step6_33_required_objects
    if object_name not in globals()
]

assert not step6_33_missing_objects, f"Missing required objects: {step6_33_missing_objects}"

step6_33_expected_mapping = (
    step6_31_recommendation_values_df[
        [
            "problem_type",
            "recommended_action",
        ]
    ]
    .drop_duplicates()
    .copy()
)

step6_33_observed_mapping_df = (
    step6_32_operational_recommendation_df[
        [
            "problem_type",
            "recommended_action",
        ]
    ]
    .drop_duplicates()
    .copy()
)

step6_33_mapping_check_df = (
    step6_33_observed_mapping_df
    .merge(
        step6_33_expected_mapping,
        on=["problem_type", "recommended_action"],
        how="left",
        indicator=True,
    )
)

step6_33_unexpected_mapping_count = int(
    (step6_33_mapping_check_df["_merge"] != "both").sum()
)

step6_33_duplicate_key_count = int(
    step6_32_operational_recommendation_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_33_missing_action_count = int(
    step6_32_operational_recommendation_df["recommended_action"].isna().sum()
)

step6_33_consistency_rules = [
    {
        "rule_name": "no_missing_recommended_action",
        "condition_passed": step6_33_missing_action_count == 0,
        "value": str(step6_33_missing_action_count),
    },
    {
        "rule_name": "no_duplicate_day_station_keys",
        "condition_passed": step6_33_duplicate_key_count == 0,
        "value": str(step6_33_duplicate_key_count),
    },
    {
        "rule_name": "observed_mapping_matches_contract",
        "condition_passed": step6_33_unexpected_mapping_count == 0,
        "value": str(step6_33_unexpected_mapping_count),
    },
    {
        "rule_name": "deliver_bikes_requires_bike_shortage",
        "condition_passed": bool(
            (
                step6_32_operational_recommendation_df.loc[
                    step6_32_operational_recommendation_df["recommended_action"] == "deliver_bikes",
                    "problem_type",
                ].astype("string")
                == "bike_shortage_risk"
            ).all()
        ),
        "value": "deliver_bikes",
    },
    {
        "rule_name": "check_station_state_excludes_bike_shortage_only",
        "condition_passed": bool(
            (
                step6_32_operational_recommendation_df.loc[
                    step6_32_operational_recommendation_df["recommended_action"] == "check_station_state",
                    "problem_type",
                ].astype("string")
                != "bike_shortage_risk"
            ).all()
        ),
        "value": "check_station_state",
    },
]

step6_33_consistency_df = pd.DataFrame(step6_33_consistency_rules)

step6_33_consistency_df["status"] = step6_33_consistency_df["condition_passed"].map(
    {
        True: "ok",
        False: "review",
    }
)

step6_33_review_count = int(
    (step6_33_consistency_df["status"] == "review").sum()
)

step6_33_action_statistics_df = (
    step6_32_operational_recommendation_df
    .groupby("recommended_action", observed=True)
    .agg(
        row_count=("recommended_action", "size"),
        mean_departure_signal_hours=("departure_signal_hours", "mean"),
        median_departure_signal_hours=("departure_signal_hours", "median"),
        max_departure_signal_hours=("departure_signal_hours", "max"),
        mean_return_signal_hours=("return_signal_hours", "mean"),
        median_return_signal_hours=("return_signal_hours", "median"),
        max_return_signal_hours=("return_signal_hours", "max"),
        mean_problem_direction_score=("problem_direction_score", "mean"),
        median_problem_direction_score=("problem_direction_score", "median"),
        max_problem_direction_score=("problem_direction_score", "max"),
        mean_problem_direction_share_of_day=("problem_direction_share_of_day", "mean"),
        max_problem_direction_share_of_day=("problem_direction_share_of_day", "max"),
    )
    .reset_index()
)

step6_33_action_statistics_df["row_share"] = (
    step6_33_action_statistics_df["row_count"]
    / step6_33_action_statistics_df["row_count"].sum()
)

step6_33_consistency_contract = {
    "block_name": "block_6",
    "section_name": "6.3",
    "contract_scope": "operational_recommendation_consistency",
    "grain": "day_station",
    "key_columns": [
        "activity_date",
        "representative_station_id",
    ],
    "output_field": "recommended_action",
    "review_count": step6_33_review_count,
    "observed_actions": sorted(
        step6_32_operational_recommendation_df["recommended_action"]
        .astype("string")
        .unique()
        .tolist()
    ),
}

step6_33_consistency_path = step6_11_reports_dir / "b6_17_operational_recommendation_consistency.parquet"
step6_33_action_statistics_path = step6_11_reports_dir / "b6_17_operational_recommendation_statistics.parquet"
step6_33_consistency_contract_path = step6_11_reports_dir / "b6_17_operational_recommendation_consistency_contract.json"

step6_33_consistency_df.to_parquet(step6_33_consistency_path, index=False)
step6_33_action_statistics_df.to_parquet(step6_33_action_statistics_path, index=False)

with open(step6_33_consistency_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_33_consistency_contract, file, ensure_ascii=False, indent=2)

step6_33_summary_df = pd.DataFrame(
    [
        {
            "check_area": "consistency_rules",
            "status": "ok",
            "value": str(step6_33_consistency_df.shape[0]),
        },
        {
            "check_area": "consistency_review_count",
            "status": "ok" if step6_33_review_count == 0 else "review",
            "value": str(step6_33_review_count),
        },
        {
            "check_area": "observed_actions",
            "status": "ok",
            "value": str(step6_32_operational_recommendation_df["recommended_action"].nunique()),
        },
        {
            "check_area": "consistency_path",
            "status": "ok",
            "value": str(step6_33_consistency_path),
        },
        {
            "check_area": "statistics_path",
            "status": "ok",
            "value": str(step6_33_action_statistics_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_33_consistency_contract_path),
        },
    ]
)

step6_33_summary_df["check_area"] = step6_33_summary_df["check_area"].astype("string")
step6_33_summary_df["status"] = step6_33_summary_df["status"].astype("string")
step6_33_summary_df["value"] = step6_33_summary_df["value"].astype("string")

display(step6_33_summary_df)
display(step6_33_consistency_df)
display(step6_33_action_statistics_df)

,check_area,status,value
0,consistency_rules,ok,5
1,consistency_review_count,ok,0
2,observed_actions,ok,2
3,consistency_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,statistics_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,rule_name,condition_passed,value,status
0,no_missing_recommended_action,True,0,ok
1,no_duplicate_day_station_keys,True,0,ok
2,observed_mapping_matches_contract,True,0,ok
3,deliver_bikes_requires_bike_shortage,True,deliver_bikes,ok
4,check_station_state_excludes_bike_shortage_only,True,check_station_state,ok

,recommended_action,row_count,mean_departure_signal_hours,median_departure_signal_hours,max_departure_signal_hours,mean_return_signal_hours,median_return_signal_hours,max_return_signal_hours,mean_problem_direction_score,median_problem_direction_score,max_problem_direction_score,mean_problem_direction_share_of_day,max_problem_direction_share_of_day,row_share
0,check_station_state,7081,8.766276,9.0,21,2.787601,2.0,17,11.553877,12.0,24,0.481412,1.0,0.032323
1,deliver_bikes,211990,11.260286,11.0,24,0.000000,0.0,0,11.260286,11.0,24,0.469179,1.0,0.967677

In [18]:
# 6.3.4 Zamknięcie kontraktu rekomendacji operacyjnej

import json

import pandas as pd


step6_34_required_objects = [
    "step6_31_recommendation_contract",
    "step6_32_operational_recommendation_df",
    "step6_33_consistency_df",
    "step6_33_action_statistics_df",
    "step6_11_reports_dir",
    "step6_11_outputs_dir",
]

step6_34_missing_objects = [
    object_name
    for object_name in step6_34_required_objects
    if object_name not in globals()
]

assert not step6_34_missing_objects, f"Missing required objects: {step6_34_missing_objects}"

step6_34_output_columns = [
    "activity_date",
    "representative_station_id",
    "station_name",
    "estimated_capacity",
    "departure_signal_hours",
    "return_signal_hours",
    "total_departures",
    "total_returns",
    "daily_net_flow",
    "min_occupancy_proxy",
    "max_occupancy_proxy",
    "min_free_capacity_proxy",
    "max_free_capacity_proxy",
    "observed_hour_count",
    "problem_type",
    "problem_direction_score",
    "problem_direction_share_of_day",
    "dominant_signal_side",
    "recommended_action",
    "action_priority",
]

step6_34_available_columns = step6_32_operational_recommendation_df.columns.tolist()

step6_34_missing_output_columns = [
    column_name
    for column_name in step6_34_output_columns
    if column_name not in step6_34_available_columns
]

assert not step6_34_missing_output_columns, f"Missing output columns: {step6_34_missing_output_columns}"

step6_34_review_count = int(
    (step6_33_consistency_df["status"] == "review").sum()
)

step6_34_duplicate_key_count = int(
    step6_32_operational_recommendation_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_34_missing_action_count = int(
    step6_32_operational_recommendation_df["recommended_action"].isna().sum()
)

assert step6_34_review_count == 0, "Operational recommendation consistency review detected."
assert step6_34_duplicate_key_count == 0, "Duplicated day-station keys detected."
assert step6_34_missing_action_count == 0, "Missing recommended_action values detected."

step6_34_operational_recommendation_output_df = (
    step6_32_operational_recommendation_df[step6_34_output_columns]
    .sort_values(
        [
            "activity_date",
            "action_priority",
            "problem_direction_score",
            "representative_station_id",
        ],
        ascending=[True, True, False, True],
    )
    .reset_index(drop=True)
)

step6_34_observed_actions = sorted(
    step6_34_operational_recommendation_output_df["recommended_action"]
    .astype("string")
    .unique()
    .tolist()
)

step6_34_observed_problem_types = sorted(
    step6_34_operational_recommendation_output_df["problem_type"]
    .astype("string")
    .unique()
    .tolist()
)

step6_34_output_path = step6_11_outputs_dir / "b6_18_operational_recommendation_day_station.parquet"
step6_34_output_profile_path = step6_11_reports_dir / "b6_18_operational_recommendation_output_profile.parquet"
step6_34_section_contract_path = step6_11_reports_dir / "b6_18_operational_recommendation_section_contract.json"
step6_34_section_status_path = step6_11_reports_dir / "b6_18_operational_recommendation_section_status.parquet"

step6_34_operational_recommendation_output_df.to_parquet(step6_34_output_path, index=False)

step6_34_output_profile_df = pd.DataFrame(
    [
        {
            "profile_area": "output_rows",
            "status": "ok",
            "value": str(step6_34_operational_recommendation_output_df.shape[0]),
        },
        {
            "profile_area": "output_columns",
            "status": "ok",
            "value": str(step6_34_operational_recommendation_output_df.shape[1]),
        },
        {
            "profile_area": "unique_stations",
            "status": "ok",
            "value": str(step6_34_operational_recommendation_output_df["representative_station_id"].nunique()),
        },
        {
            "profile_area": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_34_duplicate_key_count),
        },
        {
            "profile_area": "missing_recommended_action",
            "status": "ok",
            "value": str(step6_34_missing_action_count),
        },
        {
            "profile_area": "observed_actions",
            "status": "ok",
            "value": json.dumps(step6_34_observed_actions, ensure_ascii=False),
        },
        {
            "profile_area": "observed_problem_types",
            "status": "ok",
            "value": json.dumps(step6_34_observed_problem_types, ensure_ascii=False),
        },
    ]
)

step6_34_output_profile_df.to_parquet(step6_34_output_profile_path, index=False)

step6_34_section_contract = {
    "block_name": "block_6",
    "section_name": "6.3",
    "section_scope": "operational_recommendation_layer",
    "source_grain": "day_station",
    "output_grain": "day_station",
    "source_object": "step6_32_operational_recommendation_df",
    "output_object": "step6_34_operational_recommendation_output_df",
    "output_path": str(step6_34_output_path),
    "key_columns": [
        "activity_date",
        "representative_station_id",
    ],
    "input_field": "problem_type",
    "output_field": "recommended_action",
    "allowed_recommended_actions": [
        "deliver_bikes",
        "remove_bikes",
        "check_station_state",
    ],
    "observed_recommended_actions": step6_34_observed_actions,
    "observed_problem_types": step6_34_observed_problem_types,
    "recommendation_rules": step6_31_recommendation_contract["recommendation_rules"],
    "routing_scope": "station_level_recommendation",
    "builds_global_fleet_routing": False,
    "output_row_count": int(step6_34_operational_recommendation_output_df.shape[0]),
    "output_column_count": int(step6_34_operational_recommendation_output_df.shape[1]),
    "unique_station_count": int(step6_34_operational_recommendation_output_df["representative_station_id"].nunique()),
    "duplicate_key_count": step6_34_duplicate_key_count,
    "consistency_review_count": step6_34_review_count,
}

with open(step6_34_section_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_34_section_contract, file, ensure_ascii=False, indent=2)

step6_34_section_status_df = pd.DataFrame(
    [
        {
            "section_item": "section_6_3_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "section_item": "output_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "section_item": "output_rows",
            "status": "ok",
            "value": str(step6_34_operational_recommendation_output_df.shape[0]),
        },
        {
            "section_item": "output_columns",
            "status": "ok",
            "value": str(step6_34_operational_recommendation_output_df.shape[1]),
        },
        {
            "section_item": "observed_actions",
            "status": "ok",
            "value": json.dumps(step6_34_observed_actions, ensure_ascii=False),
        },
        {
            "section_item": "consistency_review_count",
            "status": "ok",
            "value": str(step6_34_review_count),
        },
    ]
)

step6_34_section_status_df.to_parquet(step6_34_section_status_path, index=False)

step6_34_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_6_3_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "check_area": "operational_recommendation_rows",
            "status": "ok",
            "value": str(step6_34_operational_recommendation_output_df.shape[0]),
        },
        {
            "check_area": "operational_recommendation_columns",
            "status": "ok",
            "value": str(step6_34_operational_recommendation_output_df.shape[1]),
        },
        {
            "check_area": "output_path",
            "status": "ok",
            "value": str(step6_34_output_path),
        },
        {
            "check_area": "profile_path",
            "status": "ok",
            "value": str(step6_34_output_profile_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_34_section_contract_path),
        },
        {
            "check_area": "status_path",
            "status": "ok",
            "value": str(step6_34_section_status_path),
        },
    ]
)

step6_34_summary_df["check_area"] = step6_34_summary_df["check_area"].astype("string")
step6_34_summary_df["status"] = step6_34_summary_df["status"].astype("string")
step6_34_summary_df["value"] = step6_34_summary_df["value"].astype("string")

display(step6_34_summary_df)
display(step6_34_section_status_df)
display(step6_34_output_profile_df)
display(step6_34_operational_recommendation_output_df.head(10))

,check_area,status,value
0,section_6_3_status,ok,closed
1,operational_recommendation_rows,ok,219071
2,operational_recommendation_columns,ok,20
3,output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,profile_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,status_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

               section_item status                                     value
0        section_6_3_status     ok                                    closed
1              output_grain     ok                               day_station
2               output_rows     ok                                    219071
3            output_columns     ok                                        20
4          observed_actions     ok  ["check_station_state", "deliver_bikes"]
5  consistency_review_count     ok                                         0

                 profile_area status                                     value
0                 output_rows     ok                                    219071
1              output_columns     ok                                        20
2             unique_stations     ok                                       344
3  duplicate_day_station_keys     ok                                         0
4  missing_recommended_action     ok                                         0
5            observed_actions     ok  ["check_station_state", "deliver_bikes"]
6      observed_problem_types     ok      ["bike_shortage_risk", "mixed_risk"]

,activity_date,representative_station_id,station_name,estimated_capacity,departure_signal_hours,return_signal_hours,total_departures,total_returns,daily_net_flow,min_occupancy_proxy,max_occupancy_proxy,min_free_capacity_proxy,max_free_capacity_proxy,observed_hour_count,problem_type,problem_direction_score,problem_direction_share_of_day,dominant_signal_side,recommended_action,action_priority
0,2017-05-02,112,Rautatieläisenkatu,19.950001,24,0,27,14,-13,0,0,19.950001,19.950001,24,bike_shortage_risk,24,1.000000,departure_side,deliver_bikes,1
1,2017-05-02,609,Sepetlahdentie,7.000000,24,0,5,5,0,0,0,7.000000,7.000000,24,bike_shortage_risk,24,1.000000,departure_side,deliver_bikes,1
2,2017-05-02,79,Uimastadion,23.000000,24,0,14,9,-5,0,0,23.000000,23.000000,24,bike_shortage_risk,24,1.000000,departure_side,deliver_bikes,1
3,2017-05-02,83,Meilahden sairaala,45.950001,24,0,3,3,0,0,0,45.950001,45.950001,24,bike_shortage_risk,24,1.000000,departure_side,deliver_bikes,1
4,2017-05-02,131,Elimäenkatu,34.950001,23,0,5,5,0,0,1,33.950001,34.950001,24,bike_shortage_risk,23,0.958333,departure_side,deliver_bikes,1
5,2017-05-02,14,Senaatintori,39.950001,23,0,28,12,-16,0,2,37.950001,39.950001,24,bike_shortage_risk,23,0.958333,departure_side,deliver_bikes,1
6,2017-05-02,17,Varsapuistikko,40.000000,23,0,34,18,-16,0,1,39.000000,40.000000,24,bike_shortage_risk,23,0.958333,departure_side,deliver_bikes,1
7,2017-05-02,120,Mäkelänkatu,48.000000,22,0,8,7,-1,0,2,46.000000,48.000000,24,bike_shortage_risk,22,0.916667,departure_side,deliver_bikes,1
8,2017-05-02,23,Kiasma,38.000000,22,0,33,20,-13,0,1,37.000000,38.000000,24,bike_shortage_risk,22,0.916667,departure_side,deliver_bikes,1
9,2017-05-02,25,Narinkka,31.000000,22,0,55,36,-19,0,2,29.000000,31.000000,24,bike_shortage_risk,22,0.916667,departure_side,deliver_bikes,1

## Podsumowanie działu 6.3 Warstwa rekomendacji: dowieź / zabierz / sprawdź

**Kontekst inżynieryjny:** W dziale `6.3` zbudowano warstwę rekomendacji operacyjnej na podstawie wyniku działu `6.2`. Źródłem wejściowym była dzienna warstwa kierunku problemu `step6_27_problem_direction_output_df`, działająca na poziomie `day_station`. Najpierw zdefiniowano kontrakt mapowania pola `problem_type` na pole `recommended_action`, obejmujący wartości `deliver_bikes`, `remove_bikes` oraz `check_station_state`. Następnie zastosowano reguły rekomendacyjne do danych dziennych, przypisując rekomendację operacyjną do każdej pary `activity_date + representative_station_id`. W kolejnym kroku zweryfikowano spójność mapowania, brak pustych rekomendacji, brak duplikatów klucza dziennego oraz zgodność obserwowanych rekomendacji z kontraktem. Na końcu zapisano finalną warstwę rekomendacji operacyjnej jako artefakt wyjściowy działu `6.3`.

**Interpretacja wyniku:** Warstwa rekomendacji operacyjnej została zbudowana dla `219 071` rekordów i `344` unikalnych stacji na poziomie dzień–stacja. Finalny output zawiera `20` kolumn, w tym `problem_type`, `recommended_action`, `action_priority`, `departure_signal_hours`, `return_signal_hours`, `problem_direction_score`, `problem_direction_share_of_day` oraz `dominant_signal_side`. Nie występują brakujące wartości w kolumnie `recommended_action`, a liczba duplikatów klucza `activity_date + representative_station_id` wynosi `0`. W danych zaobserwowano `2` rekomendacje: `deliver_bikes` oraz `check_station_state`. Rekomendacja `deliver_bikes` występuje dla `211 990` rekordów, co odpowiada około `96.77%` warstwy, natomiast `check_station_state` występuje dla `7 081` rekordów, czyli około `3.23%`. Kontrola spójności objęła `5` reguł i zakończyła się wynikiem `0` reguł wymagających przeglądu. Zaobserwowane mapowanie jest zgodne z kontraktem: `bike_shortage_risk` prowadzi do `deliver_bikes`, a `mixed_risk` prowadzi do `check_station_state`.

**Znaczenie biznesowe:** Dział `6.3` przekształca wynik analitycznej warstwy kierunku problemu w prostą rekomendację operacyjną możliwą do wykorzystania w panelu dyspozytora. Zamiast prezentować wyłącznie typ problemu, warstwa ta dostarcza bezpośrednią informację o działaniu: `deliver_bikes`, `remove_bikes` lub `check_station_state`. Dzięki temu dalsze części BLOKU 6 mogą budować listę działań, priorytetyzację stacji, szacowaną relokację, mapę oraz widok kierowcy na podstawie gotowego pola rekomendacyjnego. Obecność pól intensywności problemu, takich jak `problem_direction_score` i `problem_direction_share_of_day`, pozwala w kolejnych etapach różnicować siłę rekomendacji, zamiast traktować wszystkie przypadki tego samego typu jednakowo.

**Wniosek:** Dział `6.3` został domknięty poprawnie. Zbudowano finalną warstwę rekomendacji operacyjnej na poziomie dzień–stacja, zapisaną jako `b6_18_operational_recommendation_day_station.parquet`, wraz z profilem, kontraktem i statusem działu. Warstwa zawiera `219 071` rekordów, `20` kolumn, brak duplikatów klucza dziennego, brak pustych rekomendacji oraz spójne mapowanie `problem_type → recommended_action`. Oznacza to, że można przejść do kolejnego etapu, czyli `6.4 Godzina największego ryzyka`, wykorzystując gotową rekomendację operacyjną jako podstawę dalszego panelu dyspozytora.

## 6.4 Godzina największego ryzyka

In [19]:
# 6.4.1 Definicja kontraktu godziny największego ryzyka

import json

import pandas as pd


step6_41_required_objects = [
    "step6_24_problem_direction_hourly_df",
    "step6_34_operational_recommendation_output_df",
    "step6_11_reports_dir",
]

step6_41_missing_objects = [
    object_name
    for object_name in step6_41_required_objects
    if object_name not in globals()
]

assert not step6_41_missing_objects, f"Missing required objects: {step6_41_missing_objects}"

step6_41_risk_hour_contract = {
    "block_name": "block_6",
    "section_name": "6.4",
    "section_scope": "highest_risk_hour_layer",
    "hourly_source_object": "step6_24_problem_direction_hourly_df",
    "daily_source_object": "step6_34_operational_recommendation_output_df",
    "hourly_grain": "hour_station",
    "output_grain": "day_station",
    "output_fields": [
        "highest_risk_hour",
        "highest_risk_hour_label",
        "highest_risk_hour_score",
        "highest_risk_hour_problem_type",
    ],
    "risk_score_components": [
        "problem_signal_strength",
        "problem_direction_sort_score",
        "departure_side_signal",
        "return_side_signal",
        "net_flow_hour",
        "cumulative_net_flow",
        "occupancy_proxy",
        "free_capacity_proxy",
    ],
    "main_screen_policy": {
        "show_single_hour_or_window": True,
        "show_all_hours_on_main_screen": False,
    },
    "selection_policy": {
        "primary_sort": "problem_signal_strength",
        "secondary_sort": "problem_direction_sort_score",
        "tertiary_sort": "absolute_net_flow_hour",
        "quaternary_sort": "absolute_cumulative_net_flow",
        "tie_breaker": "earliest_hour",
    },
}

step6_41_required_hourly_columns = [
    "activity_hour",
    "activity_date",
    "hour_of_day",
    "representative_station_id",
    "station_name",
    "net_flow_hour",
    "cumulative_net_flow",
    "occupancy_proxy",
    "free_capacity_proxy",
    "departure_side_signal",
    "return_side_signal",
    "problem_signal_strength",
    "problem_direction_sort_score",
    "problem_type",
]

step6_41_required_daily_columns = [
    "activity_date",
    "representative_station_id",
    "recommended_action",
    "problem_type",
    "problem_direction_score",
    "problem_direction_share_of_day",
]

step6_41_contract_values_df = pd.DataFrame(
    [
        {
            "field_name": "highest_risk_hour",
            "field_role": "numeric_hour",
            "source_grain": "hour_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "highest_risk_hour_label",
            "field_role": "display_label",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "highest_risk_hour_score",
            "field_role": "risk_intensity",
            "source_grain": "hour_station",
            "display_scope": "technical_support",
        },
        {
            "field_name": "highest_risk_hour_problem_type",
            "field_role": "risk_context",
            "source_grain": "hour_station",
            "display_scope": "technical_support",
        },
    ]
)

step6_41_contract_values_df["field_name"] = step6_41_contract_values_df["field_name"].astype("string")
step6_41_contract_values_df["field_role"] = step6_41_contract_values_df["field_role"].astype("string")
step6_41_contract_values_df["source_grain"] = step6_41_contract_values_df["source_grain"].astype("string")
step6_41_contract_values_df["display_scope"] = step6_41_contract_values_df["display_scope"].astype("string")

step6_41_hourly_missing_columns = [
    column_name
    for column_name in step6_41_required_hourly_columns
    if column_name not in step6_24_problem_direction_hourly_df.columns
]

step6_41_daily_missing_columns = [
    column_name
    for column_name in step6_41_required_daily_columns
    if column_name not in step6_34_operational_recommendation_output_df.columns
]

assert not step6_41_hourly_missing_columns, f"Missing hourly columns: {step6_41_hourly_missing_columns}"
assert not step6_41_daily_missing_columns, f"Missing daily columns: {step6_41_daily_missing_columns}"

step6_41_contract_path = step6_11_reports_dir / "b6_19_highest_risk_hour_contract.json"
step6_41_contract_values_path = step6_11_reports_dir / "b6_19_highest_risk_hour_contract_values.parquet"

with open(step6_41_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_41_risk_hour_contract, file, ensure_ascii=False, indent=2)

step6_41_contract_values_df.to_parquet(step6_41_contract_values_path, index=False)

step6_41_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_scope",
            "status": "ok",
            "value": "highest_risk_hour_layer",
        },
        {
            "check_area": "hourly_required_columns",
            "status": "ok",
            "value": str(len(step6_41_required_hourly_columns)),
        },
        {
            "check_area": "daily_required_columns",
            "status": "ok",
            "value": str(len(step6_41_required_daily_columns)),
        },
        {
            "check_area": "output_fields",
            "status": "ok",
            "value": str(step6_41_contract_values_df.shape[0]),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_41_contract_path),
        },
        {
            "check_area": "contract_values_path",
            "status": "ok",
            "value": str(step6_41_contract_values_path),
        },
    ]
)

step6_41_summary_df["check_area"] = step6_41_summary_df["check_area"].astype("string")
step6_41_summary_df["status"] = step6_41_summary_df["status"].astype("string")
step6_41_summary_df["value"] = step6_41_summary_df["value"].astype("string")

display(step6_41_summary_df)
display(step6_41_contract_values_df)

,check_area,status,value
0,section_scope,ok,highest_risk_hour_layer
1,hourly_required_columns,ok,14
2,daily_required_columns,ok,6
3,output_fields,ok,4
4,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,contract_values_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,field_name,field_role,source_grain,display_scope
0,highest_risk_hour,numeric_hour,hour_station,main_screen
1,highest_risk_hour_label,display_label,day_station,main_screen
2,highest_risk_hour_score,risk_intensity,hour_station,technical_support
3,highest_risk_hour_problem_type,risk_context,hour_station,technical_support

In [20]:
# 6.4.2 Budowa rankingu godzin ryzyka

import numpy as np
import pandas as pd


step6_42_required_objects = [
    "step6_24_problem_direction_hourly_df",
    "step6_11_reports_dir",
]

step6_42_missing_objects = [
    object_name
    for object_name in step6_42_required_objects
    if object_name not in globals()
]

assert not step6_42_missing_objects, f"Missing required objects: {step6_42_missing_objects}"

step6_42_hourly_risk_input_columns = [
    "activity_hour",
    "activity_date",
    "hour_of_day",
    "representative_station_id",
    "station_name",
    "net_flow_hour",
    "cumulative_net_flow",
    "occupancy_proxy",
    "free_capacity_proxy",
    "departure_side_signal",
    "return_side_signal",
    "problem_signal_strength",
    "problem_direction_sort_score",
    "problem_type",
]

step6_42_hourly_risk_df = step6_24_problem_direction_hourly_df[
    step6_42_hourly_risk_input_columns
].copy()

step6_42_hourly_risk_df["absolute_net_flow_hour"] = (
    step6_42_hourly_risk_df["net_flow_hour"].abs()
)

step6_42_hourly_risk_df["absolute_cumulative_net_flow"] = (
    step6_42_hourly_risk_df["cumulative_net_flow"].abs()
)

step6_42_hourly_risk_df["capacity_pressure_score"] = np.select(
    [
        step6_42_hourly_risk_df["problem_type"].astype("string") == "bike_shortage_risk",
        step6_42_hourly_risk_df["problem_type"].astype("string") == "dock_shortage_risk",
        step6_42_hourly_risk_df["problem_type"].astype("string") == "mixed_risk",
    ],
    [
        step6_42_hourly_risk_df["occupancy_proxy"].abs(),
        step6_42_hourly_risk_df["free_capacity_proxy"].abs(),
        (
            step6_42_hourly_risk_df["occupancy_proxy"].abs()
            + step6_42_hourly_risk_df["free_capacity_proxy"].abs()
        ),
    ],
    default=0,
)

step6_42_hourly_risk_df["highest_risk_hour_score"] = (
    step6_42_hourly_risk_df["problem_signal_strength"].astype("float32") * 1000
    + step6_42_hourly_risk_df["problem_direction_sort_score"].astype("float32") * 100
    + step6_42_hourly_risk_df["absolute_net_flow_hour"].astype("float32") * 10
    + step6_42_hourly_risk_df["absolute_cumulative_net_flow"].astype("float32")
    + step6_42_hourly_risk_df["capacity_pressure_score"].astype("float32") * 0.01
).astype("float32")

step6_42_hourly_risk_df["risk_hour_rank"] = (
    step6_42_hourly_risk_df
    .sort_values(
        [
            "activity_date",
            "representative_station_id",
            "highest_risk_hour_score",
            "problem_signal_strength",
            "problem_direction_sort_score",
            "absolute_net_flow_hour",
            "absolute_cumulative_net_flow",
            "hour_of_day",
        ],
        ascending=[True, True, False, False, False, False, False, True],
    )
    .groupby(["activity_date", "representative_station_id"], observed=True)
    .cumcount()
    .add(1)
    .astype("int16")
)

step6_42_top_hour_candidates_df = (
    step6_42_hourly_risk_df.loc[
        step6_42_hourly_risk_df["risk_hour_rank"] <= 3,
        [
            "activity_date",
            "representative_station_id",
            "station_name",
            "hour_of_day",
            "problem_type",
            "problem_signal_strength",
            "problem_direction_sort_score",
            "absolute_net_flow_hour",
            "absolute_cumulative_net_flow",
            "capacity_pressure_score",
            "highest_risk_hour_score",
            "risk_hour_rank",
        ],
    ]
    .sort_values(["activity_date", "representative_station_id", "risk_hour_rank"])
    .reset_index(drop=True)
)

step6_42_duplicate_rank_count = int(
    step6_42_top_hour_candidates_df.duplicated(
        subset=["activity_date", "representative_station_id", "risk_hour_rank"]
    ).sum()
)

step6_42_rank_summary_df = pd.DataFrame(
    [
        {
            "check_area": "hourly_rows",
            "status": "ok",
            "value": str(step6_42_hourly_risk_df.shape[0]),
        },
        {
            "check_area": "top_hour_candidate_rows",
            "status": "ok",
            "value": str(step6_42_top_hour_candidates_df.shape[0]),
        },
        {
            "check_area": "unique_day_station_keys",
            "status": "ok",
            "value": str(
                step6_42_hourly_risk_df[
                    ["activity_date", "representative_station_id"]
                ].drop_duplicates().shape[0]
            ),
        },
        {
            "check_area": "duplicate_rank_keys",
            "status": "ok" if step6_42_duplicate_rank_count == 0 else "review",
            "value": str(step6_42_duplicate_rank_count),
        },
        {
            "check_area": "max_risk_hour_rank",
            "status": "ok",
            "value": str(int(step6_42_top_hour_candidates_df["risk_hour_rank"].max())),
        },
    ]
)

step6_42_top_hour_candidates_path = step6_11_reports_dir / "b6_20_top_hour_risk_candidates.parquet"
step6_42_rank_summary_path = step6_11_reports_dir / "b6_20_hourly_risk_rank_summary.parquet"

step6_42_top_hour_candidates_df.to_parquet(step6_42_top_hour_candidates_path, index=False)
step6_42_rank_summary_df.to_parquet(step6_42_rank_summary_path, index=False)

display(step6_42_rank_summary_df)
display(step6_42_top_hour_candidates_df.head(20))

                check_area status    value
0              hourly_rows     ok  5257704
1  top_hour_candidate_rows     ok   657213
2  unique_day_station_keys     ok   219071
3      duplicate_rank_keys     ok        0
4       max_risk_hour_rank     ok        3

,activity_date,representative_station_id,station_name,hour_of_day,problem_type,problem_signal_strength,problem_direction_sort_score,absolute_net_flow_hour,absolute_cumulative_net_flow,capacity_pressure_score,highest_risk_hour_score,risk_hour_rank
0,2017-05-02,1,Kaivopuisto,9,bike_shortage_risk,1,3,3,3,0.0,1333.0,1
1,2017-05-02,1,Kaivopuisto,0,bike_shortage_risk,1,3,0,0,0.0,1300.0,2
2,2017-05-02,1,Kaivopuisto,1,bike_shortage_risk,1,3,0,0,0.0,1300.0,3
3,2017-05-02,10,Kasarmitori,12,bike_shortage_risk,1,3,2,3,0.0,1323.0,1
4,2017-05-02,10,Kasarmitori,15,bike_shortage_risk,1,3,1,5,0.0,1315.0,2
5,2017-05-02,10,Kasarmitori,14,bike_shortage_risk,1,3,1,4,0.0,1314.0,3
6,2017-05-02,100,Teljäntie,16,bike_shortage_risk,1,3,1,0,0.0,1310.0,1
7,2017-05-02,100,Teljäntie,0,bike_shortage_risk,1,3,0,0,0.0,1300.0,2
8,2017-05-02,100,Teljäntie,1,bike_shortage_risk,1,3,0,0,0.0,1300.0,3
9,2017-05-02,101,Huopalahdentie,16,bike_shortage_risk,1,3,1,0,0.0,1310.0,1
10,2017-05-02,101,Huopalahdentie,19,bike_shortage_risk,1,3,1,0,0.0,1310.0,2
11,2017-05-02,101,Huopalahdentie,0,bike_shortage_risk,1,3,0,0,0.0,1300.0,3
12,2017-05-02,103,Vihdintie,0,bike_shortage_risk,1,3,0,0,0.0,1300.0,1
13,2017-05-02,103,Vihdintie,1,bike_shortage_risk,1,3,0,0,0.0,1300.0,2
14,2017-05-02,103,Vihdintie,2,bike_shortage_risk,1,3,0,0,0.0,1300.0,3
15,2017-05-02,104,Kriikunakuja,20,bike_shortage_risk,1,3,2,0,0.0,1320.0,1
16,2017-05-02,104,Kriikunakuja,0,bike_shortage_risk,1,3,0,0,0.0,1300.0,2
17,2017-05-02,104,Kriikunakuja,1,bike_shortage_risk,1,3,0,0,0.0,1300.0,3
18,2017-05-02,105,Tilkantori,18,bike_shortage_risk,1,3,1,0,0.0,1310.0,1
19,2017-05-02,105,Tilkantori,0,bike_shortage_risk,1,3,0,0,0.0,1300.0,2

In [21]:
# 6.4.3 Wybór godziny największego ryzyka

import pandas as pd


step6_43_required_objects = [
    "step6_42_top_hour_candidates_df",
    "step6_34_operational_recommendation_output_df",
    "step6_11_reports_dir",
]

step6_43_missing_objects = [
    object_name
    for object_name in step6_43_required_objects
    if object_name not in globals()
]

assert not step6_43_missing_objects, f"Missing required objects: {step6_43_missing_objects}"

step6_43_highest_risk_hour_df = step6_42_top_hour_candidates_df.loc[
    step6_42_top_hour_candidates_df["risk_hour_rank"] == 1
].copy()

step6_43_highest_risk_hour_df = step6_43_highest_risk_hour_df.rename(
    columns={
        "hour_of_day": "highest_risk_hour",
        "problem_type": "highest_risk_hour_problem_type",
    }
)

step6_43_highest_risk_hour_df["highest_risk_hour"] = (
    step6_43_highest_risk_hour_df["highest_risk_hour"].astype("int16")
)

step6_43_highest_risk_hour_df["highest_risk_hour_label"] = (
    step6_43_highest_risk_hour_df["highest_risk_hour"]
    .astype("int16")
    .astype("string")
    .str.zfill(2)
    + ":00"
)

step6_43_highest_risk_hour_df = step6_43_highest_risk_hour_df[
    [
        "activity_date",
        "representative_station_id",
        "highest_risk_hour",
        "highest_risk_hour_label",
        "highest_risk_hour_score",
        "highest_risk_hour_problem_type",
        "problem_signal_strength",
        "problem_direction_sort_score",
        "absolute_net_flow_hour",
        "absolute_cumulative_net_flow",
        "capacity_pressure_score",
    ]
].copy()

step6_43_highest_risk_hour_df = step6_43_highest_risk_hour_df.rename(
    columns={
        "problem_signal_strength": "highest_risk_hour_signal_strength",
        "problem_direction_sort_score": "highest_risk_hour_direction_sort_score",
        "absolute_net_flow_hour": "highest_risk_hour_absolute_net_flow",
        "absolute_cumulative_net_flow": "highest_risk_hour_absolute_cumulative_net_flow",
        "capacity_pressure_score": "highest_risk_hour_capacity_pressure_score",
    }
)

step6_43_enriched_recommendation_df = (
    step6_34_operational_recommendation_output_df
    .merge(
        step6_43_highest_risk_hour_df,
        on=["activity_date", "representative_station_id"],
        how="left",
        validate="one_to_one",
    )
)

step6_43_missing_highest_risk_hour_count = int(
    step6_43_enriched_recommendation_df["highest_risk_hour"].isna().sum()
)

step6_43_duplicate_key_count = int(
    step6_43_enriched_recommendation_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

assert step6_43_missing_highest_risk_hour_count == 0, "Missing highest_risk_hour values detected."
assert step6_43_duplicate_key_count == 0, "Duplicated day-station keys detected."

step6_43_hour_summary_df = (
    step6_43_enriched_recommendation_df["highest_risk_hour_label"]
    .value_counts(dropna=False)
    .rename_axis("highest_risk_hour_label")
    .reset_index(name="row_count")
    .sort_values(["row_count", "highest_risk_hour_label"], ascending=[False, True])
    .reset_index(drop=True)
)

step6_43_hour_summary_df["row_share"] = (
    step6_43_hour_summary_df["row_count"]
    / step6_43_hour_summary_df["row_count"].sum()
)

step6_43_action_hour_summary_df = (
    step6_43_enriched_recommendation_df
    .groupby(["recommended_action", "highest_risk_hour_label"], observed=True)
    .size()
    .reset_index(name="row_count")
    .sort_values(["recommended_action", "row_count"], ascending=[True, False])
    .reset_index(drop=True)
)

step6_43_action_hour_summary_df["row_share_within_action"] = (
    step6_43_action_hour_summary_df["row_count"]
    / step6_43_action_hour_summary_df.groupby("recommended_action", observed=True)["row_count"].transform("sum")
)

step6_43_hour_summary_path = step6_11_reports_dir / "b6_21_highest_risk_hour_summary.parquet"
step6_43_action_hour_summary_path = step6_11_reports_dir / "b6_21_action_highest_risk_hour_summary.parquet"
step6_43_highest_risk_hour_path = step6_11_reports_dir / "b6_21_highest_risk_hour_day_station.parquet"

step6_43_highest_risk_hour_df.to_parquet(step6_43_highest_risk_hour_path, index=False)
step6_43_hour_summary_df.to_parquet(step6_43_hour_summary_path, index=False)
step6_43_action_hour_summary_df.to_parquet(step6_43_action_hour_summary_path, index=False)

step6_43_summary_df = pd.DataFrame(
    [
        {
            "check_area": "highest_risk_hour_rows",
            "status": "ok",
            "value": str(step6_43_highest_risk_hour_df.shape[0]),
        },
        {
            "check_area": "enriched_recommendation_rows",
            "status": "ok",
            "value": str(step6_43_enriched_recommendation_df.shape[0]),
        },
        {
            "check_area": "missing_highest_risk_hour",
            "status": "ok",
            "value": str(step6_43_missing_highest_risk_hour_count),
        },
        {
            "check_area": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_43_duplicate_key_count),
        },
        {
            "check_area": "unique_highest_risk_hours",
            "status": "ok",
            "value": str(step6_43_enriched_recommendation_df["highest_risk_hour"].nunique()),
        },
        {
            "check_area": "highest_risk_hour_path",
            "status": "ok",
            "value": str(step6_43_highest_risk_hour_path),
        },
        {
            "check_area": "hour_summary_path",
            "status": "ok",
            "value": str(step6_43_hour_summary_path),
        },
        {
            "check_area": "action_hour_summary_path",
            "status": "ok",
            "value": str(step6_43_action_hour_summary_path),
        },
    ]
)

step6_43_summary_df["check_area"] = step6_43_summary_df["check_area"].astype("string")
step6_43_summary_df["status"] = step6_43_summary_df["status"].astype("string")
step6_43_summary_df["value"] = step6_43_summary_df["value"].astype("string")

display(step6_43_summary_df)
display(step6_43_hour_summary_df.head(24))
display(step6_43_action_hour_summary_df.head(30))
display(step6_43_enriched_recommendation_df.head(10))

,check_area,status,value
0,highest_risk_hour_rows,ok,219071
1,enriched_recommendation_rows,ok,219071
2,missing_highest_risk_hour,ok,0
3,duplicate_day_station_keys,ok,0
4,unique_highest_risk_hours,ok,24
5,highest_risk_hour_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,hour_summary_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,action_hour_summary_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

   highest_risk_hour_label  row_count  row_share
0                    00:00      30089   0.137348
1                    08:00      22812   0.104131
2                    07:00      17815   0.081321
3                    16:00      13467   0.061473
4                    15:00      12049      0.055
5                    17:00      11550   0.052723
6                    12:00      10426   0.047592
7                    09:00      10360   0.047291
8                    11:00      10091   0.046063
9                    13:00      10039   0.045825
10                   14:00      10021   0.045743
11                   18:00       9515   0.043433
12                   19:00       8038   0.036691
13                   10:00       7914   0.036125
14                   20:00       7132   0.032556
15                   21:00       5503    0.02512
16                   06:00       4692   0.021418
17                   01:00       3885   0.017734
18                   22:00       3601   0.016438
19                   02:00       2958   0.013502
20                   23:00       2626   0.011987
21                   03:00       1891   0.008632
22                   05:00       1353   0.006176
23                   04:00       1244   0.005679

,recommended_action,highest_risk_hour_label,row_count,row_share_within_action
0,check_station_state,08:00,730,0.103093
1,check_station_state,19:00,551,0.077814
2,check_station_state,18:00,532,0.075131
3,check_station_state,21:00,513,0.072447
4,check_station_state,07:00,474,0.066940
5,check_station_state,22:00,469,0.066234
6,check_station_state,20:00,451,0.063692
7,check_station_state,17:00,424,0.059879
8,check_station_state,16:00,365,0.051546
9,check_station_state,09:00,340,0.048016
10,check_station_state,12:00,337,0.047592
11,check_station_state,13:00,330,0.046604
12,check_station_state,23:00,324,0.045756
13,check_station_state,14:00,316,0.044626
14,check_station_state,15:00,299,0.042226
15,check_station_state,11:00,254,0.035871
16,check_station_state,10:00,207,0.029233
17,check_station_state,00:00,66,0.009321
18,check_station_state,06:00,39,0.005508
19,check_station_state,01:00,37,0.005225
20,check_station_state,03:00,12,0.001695
21,check_station_state,02:00,5,0.000706
22,check_station_state,04:00,5,0.000706
23,check_station_state,05:00,1,0.000141
24,deliver_bikes,00:00,30023,0.141625
25,deliver_bikes,08:00,22082,0.104165
26,deliver_bikes,07:00,17341,0.081801
27,deliver_bikes,16:00,13102,0.061805
28,deliver_bikes,15:00,11750,0.055427
29,deliver_bikes,17:00,11126,0.052484

,activity_date,representative_station_id,station_name,estimated_capacity,departure_signal_hours,return_signal_hours,total_departures,total_returns,daily_net_flow,min_occupancy_proxy,...,action_priority,highest_risk_hour,highest_risk_hour_label,highest_risk_hour_score,highest_risk_hour_problem_type,highest_risk_hour_signal_strength,highest_risk_hour_direction_sort_score,highest_risk_hour_absolute_net_flow,highest_risk_hour_absolute_cumulative_net_flow,highest_risk_hour_capacity_pressure_score
0,2017-05-02,112,Rautatieläisenkatu,19.950001,24,0,27,14,-13,0,...,1,17,17:00,1352.0,bike_shortage_risk,1,3,4,12,0.0
1,2017-05-02,609,Sepetlahdentie,7.000000,24,0,5,5,0,0,...,1,0,00:00,1300.0,bike_shortage_risk,1,3,0,0,0.0
2,2017-05-02,79,Uimastadion,23.000000,24,0,14,9,-5,0,...,1,17,17:00,1325.0,bike_shortage_risk,1,3,2,5,0.0
3,2017-05-02,83,Meilahden sairaala,45.950001,24,0,3,3,0,0,...,1,0,00:00,1300.0,bike_shortage_risk,1,3,0,0,0.0
4,2017-05-02,131,Elimäenkatu,34.950001,23,0,5,5,0,0,...,1,17,17:00,1310.0,bike_shortage_risk,1,3,1,0,0.0
5,2017-05-02,14,Senaatintori,39.950001,23,0,28,12,-16,0,...,1,17,17:00,1362.0,bike_shortage_risk,1,3,5,12,0.0
6,2017-05-02,17,Varsapuistikko,40.000000,23,0,34,18,-16,0,...,1,17,17:00,1425.0,bike_shortage_risk,1,3,11,15,0.0
7,2017-05-02,120,Mäkelänkatu,48.000000,22,0,8,7,-1,0,...,1,19,19:00,1320.0,bike_shortage_risk,1,3,2,0,0.0
8,2017-05-02,23,Kiasma,38.000000,22,0,33,20,-13,0,...,1,20,20:00,1352.0,bike_shortage_risk,1,3,4,12,0.0
9,2017-05-02,25,Narinkka,31.000000,22,0,55,36,-19,0,...,1,18,18:00,1401.0,bike_shortage_risk,1,3,9,11,0.0

In [22]:
# 6.4.4 Zamknięcie kontraktu godziny największego ryzyka

import json

import pandas as pd


step6_44_required_objects = [
    "step6_41_risk_hour_contract",
    "step6_43_enriched_recommendation_df",
    "step6_43_hour_summary_df",
    "step6_43_action_hour_summary_df",
    "step6_11_reports_dir",
    "step6_11_outputs_dir",
]

step6_44_missing_objects = [
    object_name
    for object_name in step6_44_required_objects
    if object_name not in globals()
]

assert not step6_44_missing_objects, f"Missing required objects: {step6_44_missing_objects}"

step6_44_output_columns = [
    "activity_date",
    "representative_station_id",
    "station_name",
    "estimated_capacity",
    "departure_signal_hours",
    "return_signal_hours",
    "total_departures",
    "total_returns",
    "daily_net_flow",
    "min_occupancy_proxy",
    "max_occupancy_proxy",
    "min_free_capacity_proxy",
    "max_free_capacity_proxy",
    "observed_hour_count",
    "problem_type",
    "problem_direction_score",
    "problem_direction_share_of_day",
    "dominant_signal_side",
    "recommended_action",
    "action_priority",
    "highest_risk_hour",
    "highest_risk_hour_label",
    "highest_risk_hour_score",
    "highest_risk_hour_problem_type",
    "highest_risk_hour_signal_strength",
    "highest_risk_hour_direction_sort_score",
    "highest_risk_hour_absolute_net_flow",
    "highest_risk_hour_absolute_cumulative_net_flow",
    "highest_risk_hour_capacity_pressure_score",
]

step6_44_available_columns = step6_43_enriched_recommendation_df.columns.tolist()

step6_44_missing_output_columns = [
    column_name
    for column_name in step6_44_output_columns
    if column_name not in step6_44_available_columns
]

assert not step6_44_missing_output_columns, f"Missing output columns: {step6_44_missing_output_columns}"

step6_44_duplicate_key_count = int(
    step6_43_enriched_recommendation_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_44_missing_hour_count = int(
    step6_43_enriched_recommendation_df["highest_risk_hour"].isna().sum()
)

step6_44_missing_hour_label_count = int(
    step6_43_enriched_recommendation_df["highest_risk_hour_label"].isna().sum()
)

assert step6_44_duplicate_key_count == 0, "Duplicated day-station keys detected."
assert step6_44_missing_hour_count == 0, "Missing highest_risk_hour values detected."
assert step6_44_missing_hour_label_count == 0, "Missing highest_risk_hour_label values detected."

step6_44_highest_risk_hour_output_df = (
    step6_43_enriched_recommendation_df[step6_44_output_columns]
    .sort_values(
        [
            "activity_date",
            "action_priority",
            "highest_risk_hour_score",
            "problem_direction_score",
            "representative_station_id",
        ],
        ascending=[True, True, False, False, True],
    )
    .reset_index(drop=True)
)

step6_44_observed_hours = sorted(
    step6_44_highest_risk_hour_output_df["highest_risk_hour"]
    .dropna()
    .astype("int16")
    .unique()
    .tolist()
)

step6_44_observed_hour_labels = sorted(
    step6_44_highest_risk_hour_output_df["highest_risk_hour_label"]
    .astype("string")
    .unique()
    .tolist()
)

step6_44_output_path = step6_11_outputs_dir / "b6_22_operational_recommendation_with_risk_hour.parquet"
step6_44_output_profile_path = step6_11_reports_dir / "b6_22_highest_risk_hour_output_profile.parquet"
step6_44_section_contract_path = step6_11_reports_dir / "b6_22_highest_risk_hour_section_contract.json"
step6_44_section_status_path = step6_11_reports_dir / "b6_22_highest_risk_hour_section_status.parquet"

step6_44_highest_risk_hour_output_df.to_parquet(step6_44_output_path, index=False)

step6_44_output_profile_df = pd.DataFrame(
    [
        {
            "profile_area": "output_rows",
            "status": "ok",
            "value": str(step6_44_highest_risk_hour_output_df.shape[0]),
        },
        {
            "profile_area": "output_columns",
            "status": "ok",
            "value": str(step6_44_highest_risk_hour_output_df.shape[1]),
        },
        {
            "profile_area": "unique_stations",
            "status": "ok",
            "value": str(step6_44_highest_risk_hour_output_df["representative_station_id"].nunique()),
        },
        {
            "profile_area": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_44_duplicate_key_count),
        },
        {
            "profile_area": "missing_highest_risk_hour",
            "status": "ok",
            "value": str(step6_44_missing_hour_count),
        },
        {
            "profile_area": "missing_highest_risk_hour_label",
            "status": "ok",
            "value": str(step6_44_missing_hour_label_count),
        },
        {
            "profile_area": "observed_highest_risk_hours",
            "status": "ok",
            "value": json.dumps(step6_44_observed_hours, ensure_ascii=False),
        },
        {
            "profile_area": "observed_highest_risk_hour_labels",
            "status": "ok",
            "value": json.dumps(step6_44_observed_hour_labels, ensure_ascii=False),
        },
    ]
)

step6_44_output_profile_df.to_parquet(step6_44_output_profile_path, index=False)

step6_44_section_contract = {
    "block_name": "block_6",
    "section_name": "6.4",
    "section_scope": "highest_risk_hour_layer",
    "source_grain": "hour_station",
    "output_grain": "day_station",
    "source_object": "step6_43_enriched_recommendation_df",
    "output_object": "step6_44_highest_risk_hour_output_df",
    "output_path": str(step6_44_output_path),
    "key_columns": [
        "activity_date",
        "representative_station_id",
    ],
    "main_output_fields": [
        "highest_risk_hour",
        "highest_risk_hour_label",
    ],
    "technical_support_fields": [
        "highest_risk_hour_score",
        "highest_risk_hour_problem_type",
        "highest_risk_hour_signal_strength",
        "highest_risk_hour_direction_sort_score",
        "highest_risk_hour_absolute_net_flow",
        "highest_risk_hour_absolute_cumulative_net_flow",
        "highest_risk_hour_capacity_pressure_score",
    ],
    "selection_policy": step6_41_risk_hour_contract["selection_policy"],
    "main_screen_policy": step6_41_risk_hour_contract["main_screen_policy"],
    "observed_highest_risk_hours": step6_44_observed_hours,
    "observed_highest_risk_hour_labels": step6_44_observed_hour_labels,
    "output_row_count": int(step6_44_highest_risk_hour_output_df.shape[0]),
    "output_column_count": int(step6_44_highest_risk_hour_output_df.shape[1]),
    "unique_station_count": int(step6_44_highest_risk_hour_output_df["representative_station_id"].nunique()),
    "duplicate_key_count": step6_44_duplicate_key_count,
    "missing_highest_risk_hour_count": step6_44_missing_hour_count,
}

with open(step6_44_section_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_44_section_contract, file, ensure_ascii=False, indent=2)

step6_44_section_status_df = pd.DataFrame(
    [
        {
            "section_item": "section_6_4_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "section_item": "output_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "section_item": "output_rows",
            "status": "ok",
            "value": str(step6_44_highest_risk_hour_output_df.shape[0]),
        },
        {
            "section_item": "output_columns",
            "status": "ok",
            "value": str(step6_44_highest_risk_hour_output_df.shape[1]),
        },
        {
            "section_item": "unique_highest_risk_hours",
            "status": "ok",
            "value": str(len(step6_44_observed_hours)),
        },
        {
            "section_item": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_44_duplicate_key_count),
        },
        {
            "section_item": "missing_highest_risk_hour",
            "status": "ok",
            "value": str(step6_44_missing_hour_count),
        },
    ]
)

step6_44_section_status_df.to_parquet(step6_44_section_status_path, index=False)

step6_44_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_6_4_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "check_area": "risk_hour_output_rows",
            "status": "ok",
            "value": str(step6_44_highest_risk_hour_output_df.shape[0]),
        },
        {
            "check_area": "risk_hour_output_columns",
            "status": "ok",
            "value": str(step6_44_highest_risk_hour_output_df.shape[1]),
        },
        {
            "check_area": "output_path",
            "status": "ok",
            "value": str(step6_44_output_path),
        },
        {
            "check_area": "profile_path",
            "status": "ok",
            "value": str(step6_44_output_profile_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_44_section_contract_path),
        },
        {
            "check_area": "status_path",
            "status": "ok",
            "value": str(step6_44_section_status_path),
        },
    ]
)

step6_44_summary_df["check_area"] = step6_44_summary_df["check_area"].astype("string")
step6_44_summary_df["status"] = step6_44_summary_df["status"].astype("string")
step6_44_summary_df["value"] = step6_44_summary_df["value"].astype("string")

display(step6_44_summary_df)
display(step6_44_section_status_df)
display(step6_44_output_profile_df)
display(step6_44_highest_risk_hour_output_df.head(10))

,check_area,status,value
0,section_6_4_status,ok,closed
1,risk_hour_output_rows,ok,219071
2,risk_hour_output_columns,ok,29
3,output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,profile_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,status_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                 section_item status        value
0          section_6_4_status     ok       closed
1                output_grain     ok  day_station
2                 output_rows     ok       219071
3              output_columns     ok           29
4   unique_highest_risk_hours     ok           24
5  duplicate_day_station_keys     ok            0
6   missing_highest_risk_hour     ok            0

,profile_area,status,value
0,output_rows,ok,219071
1,output_columns,ok,29
2,unique_stations,ok,344
3,duplicate_day_station_keys,ok,0
4,missing_highest_risk_hour,ok,0
5,missing_highest_risk_hour_label,ok,0
6,observed_highest_risk_hours,ok,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,..."
7,observed_highest_risk_hour_labels,ok,"[""00:00"", ""01:00"", ""02:00"", ""03:00"", ""04:00"", ..."

,activity_date,representative_station_id,station_name,estimated_capacity,departure_signal_hours,return_signal_hours,total_departures,total_returns,daily_net_flow,min_occupancy_proxy,...,action_priority,highest_risk_hour,highest_risk_hour_label,highest_risk_hour_score,highest_risk_hour_problem_type,highest_risk_hour_signal_strength,highest_risk_hour_direction_sort_score,highest_risk_hour_absolute_net_flow,highest_risk_hour_absolute_cumulative_net_flow,highest_risk_hour_capacity_pressure_score
0,2017-05-02,30,Itämerentori,117.949997,15,0,91,57,-34,0,...,1,17,17:00,1453.0,bike_shortage_risk,1,3,12,33,0.0
1,2017-05-02,17,Varsapuistikko,40.000000,23,0,34,18,-16,0,...,1,17,17:00,1425.0,bike_shortage_risk,1,3,11,15,0.0
2,2017-05-02,6,Hietalahdentori,27.000000,14,0,49,40,-9,0,...,1,16,16:00,1422.0,bike_shortage_risk,1,3,11,12,0.0
3,2017-05-02,25,Narinkka,31.000000,22,0,55,36,-19,0,...,1,18,18:00,1401.0,bike_shortage_risk,1,3,9,11,0.0
4,2017-05-02,9,Erottajan aukio,68.949997,19,0,38,22,-16,0,...,1,16,16:00,1386.0,bike_shortage_risk,1,3,7,16,0.0
5,2017-05-02,26,Kamppi (M),46.799999,20,0,71,55,-16,0,...,1,16,16:00,1371.0,bike_shortage_risk,1,3,6,11,0.0
6,2017-05-02,24,Mannerheimintie,30.950001,15,0,32,32,0,0,...,1,17,17:00,1370.0,bike_shortage_risk,1,3,7,0,0.0
7,2017-05-02,40,Hakaniemi (M),31.850000,20,0,53,34,-19,0,...,1,17,17:00,1369.0,bike_shortage_risk,1,3,5,19,0.0
8,2017-05-02,8,Vanha kirkkopuisto,29.950001,20,0,25,17,-8,0,...,1,18,18:00,1365.0,bike_shortage_risk,1,3,6,5,0.0
9,2017-05-02,28,Lastenlehto,25.799999,18,0,26,23,-3,0,...,1,16,16:00,1365.0,bike_shortage_risk,1,3,6,5,0.0

## Podsumowanie działu 6.4 Godzina największego ryzyka

**Kontekst inżynieryjny:** W dziale `6.4` zbudowano warstwę godziny największego ryzyka na podstawie godzinowej warstwy alertowej oraz dziennej warstwy rekomendacji operacyjnej. Źródłem godzinowym była tabela `step6_24_problem_direction_hourly_df`, zawierająca sygnały problemu na poziomie godzina–stacja, natomiast źródłem dziennym była tabela `step6_34_operational_recommendation_output_df`, zawierająca rekomendację operacyjną na poziomie dzień–stacja. Najpierw zdefiniowano kontrakt dla pól `highest_risk_hour`, `highest_risk_hour_label`, `highest_risk_hour_score` oraz `highest_risk_hour_problem_type`. Następnie zbudowano ranking godzin ryzyka dla każdej pary `activity_date + representative_station_id`, wykorzystując m.in. `problem_signal_strength`, `problem_direction_sort_score`, `net_flow_hour`, `cumulative_net_flow`, `occupancy_proxy` oraz `free_capacity_proxy`. Z rankingu wybrano godzinę z najwyższym wynikiem i dołączono ją do dziennej warstwy rekomendacji operacyjnej. Na końcu zapisano finalny output działu `6.4` wraz z profilem, kontraktem i statusem.

**Interpretacja wyniku:** Warstwa godziny największego ryzyka została zbudowana dla `219 071` rekordów dzień–stacja i obejmuje `344` unikalne stacje. Ranking godzin został policzony na pełnej warstwie `5 257 704` rekordów godzinowych, a dla każdego rekordu dzień–stacja zapisano maksymalnie `3` kandydatów godzinowych, łącznie `657 213` rekordów kandydackich. Finalny output zawiera `29` kolumn i nie posiada braków w polach `highest_risk_hour` ani `highest_risk_hour_label`. Nie występują również duplikaty klucza `activity_date + representative_station_id`. W danych zaobserwowano wszystkie `24` godziny doby jako możliwe godziny największego ryzyka. Najczęściej wskazywanymi godzinami były `00:00`, `08:00`, `07:00`, `16:00`, `15:00` oraz `17:00`. Dla rekomendacji `deliver_bikes` dominowały szczególnie godziny `00:00`, `08:00`, `07:00`, `16:00`, `15:00` i `17:00`, natomiast dla `check_station_state` najwyżej pojawiały się m.in. `08:00`, `19:00`, `18:00`, `21:00` oraz `07:00`.

**Znaczenie biznesowe:** Dział `6.4` rozszerza warstwę operacyjną o informację czasową, dzięki czemu rekomendacja nie ogranicza się tylko do wskazania, co należy zrobić, ale określa również, kiedy problem jest największy. Pole `highest_risk_hour_label` może być bezpośrednio pokazane w panelu dyspozytora jako jedna czytelna godzina, np. `08:00` albo `17:00`, bez prezentowania pełnej tabeli godzinowej na głównym ekranie. Jednocześnie pola techniczne, takie jak `highest_risk_hour_score`, `highest_risk_hour_signal_strength`, `highest_risk_hour_absolute_net_flow` oraz `highest_risk_hour_absolute_cumulative_net_flow`, zachowują możliwość późniejszego uzasadnienia wyboru godziny. Dzięki temu BLOK 6 zaczyna łączyć trzy kluczowe elementy decyzji operacyjnej: typ problemu, rekomendowane działanie oraz moment największego ryzyka.

**Wniosek:** Dział `6.4` został domknięty poprawnie. Zbudowano finalną warstwę rekomendacji operacyjnej z godziną największego ryzyka, zapisaną jako `b6_22_operational_recommendation_with_risk_hour.parquet`, wraz z profilem, kontraktem i statusem działu. Warstwa zawiera `219 071` rekordów, `29` kolumn, kompletne pole `highest_risk_hour_label`, brak duplikatów klucza dziennego oraz wszystkie `24` możliwe godziny ryzyka. Oznacza to, że można przejść do kolejnego etapu, czyli `6.5 Szacowana relokacja rowerów`, wykorzystując gotowe pola `recommended_action` oraz `highest_risk_hour_label` jako podstawę dalszej warstwy operacyjnej.

## 6.5 Szacowana relokacja rowerów

In [23]:
# 6.5.1 Definicja kontraktu szacowanej relokacji

import json

import pandas as pd


step6_51_required_objects = [
    "step6_44_highest_risk_hour_output_df",
    "step6_11_reports_dir",
]

step6_51_missing_objects = [
    object_name
    for object_name in step6_51_required_objects
    if object_name not in globals()
]

assert not step6_51_missing_objects, f"Missing required objects: {step6_51_missing_objects}"

step6_51_relocation_contract = {
    "block_name": "block_6",
    "section_name": "6.5",
    "section_scope": "estimated_relocation_layer",
    "source_object": "step6_44_highest_risk_hour_output_df",
    "source_grain": "day_station",
    "output_grain": "day_station",
    "input_fields": [
        "recommended_action",
        "problem_type",
        "estimated_capacity",
        "departure_signal_hours",
        "return_signal_hours",
        "problem_direction_score",
        "problem_direction_share_of_day",
        "highest_risk_hour_score",
        "highest_risk_hour_absolute_net_flow",
        "highest_risk_hour_absolute_cumulative_net_flow",
        "min_occupancy_proxy",
        "max_occupancy_proxy",
        "min_free_capacity_proxy",
        "max_free_capacity_proxy",
    ],
    "output_fields": [
        "estimated_relocation_units",
        "estimated_relocation_min",
        "estimated_relocation_max",
        "estimated_relocation_label",
        "relocation_direction",
        "relocation_sanity_limit",
    ],
    "allowed_relocation_directions": [
        "deliver",
        "remove",
        "check",
    ],
    "action_mapping": {
        "deliver_bikes": "deliver",
        "remove_bikes": "remove",
        "check_station_state": "check",
    },
    "quantity_policy": {
        "uses_estimated_relocation": True,
        "uses_exact_live_inventory": False,
        "minimum_relocation_units": 0,
        "maximum_share_of_estimated_capacity": 0.50,
        "range_width_units": 1,
    },
    "sanity_policy": {
        "estimated_relocation_units_lte_sanity_limit": True,
        "estimated_relocation_min_gte_zero": True,
        "estimated_relocation_max_gte_estimated_relocation_min": True,
    },
}

step6_51_required_columns = [
    "activity_date",
    "representative_station_id",
    "station_name",
    "estimated_capacity",
    "recommended_action",
    "problem_type",
    "departure_signal_hours",
    "return_signal_hours",
    "problem_direction_score",
    "problem_direction_share_of_day",
    "highest_risk_hour_score",
    "highest_risk_hour_absolute_net_flow",
    "highest_risk_hour_absolute_cumulative_net_flow",
    "min_occupancy_proxy",
    "max_occupancy_proxy",
    "min_free_capacity_proxy",
    "max_free_capacity_proxy",
]

step6_51_missing_columns = [
    column_name
    for column_name in step6_51_required_columns
    if column_name not in step6_44_highest_risk_hour_output_df.columns
]

assert not step6_51_missing_columns, f"Missing required columns: {step6_51_missing_columns}"

step6_51_relocation_fields_df = pd.DataFrame(
    [
        {
            "field_name": "estimated_relocation_units",
            "field_role": "central_estimate",
            "source_grain": "day_station",
            "display_scope": "technical_support",
        },
        {
            "field_name": "estimated_relocation_min",
            "field_role": "lower_bound",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "estimated_relocation_max",
            "field_role": "upper_bound",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "estimated_relocation_label",
            "field_role": "display_label",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "relocation_direction",
            "field_role": "action_direction",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "relocation_sanity_limit",
            "field_role": "quantity_guardrail",
            "source_grain": "day_station",
            "display_scope": "technical_support",
        },
    ]
)

for column_name in ["field_name", "field_role", "source_grain", "display_scope"]:
    step6_51_relocation_fields_df[column_name] = (
        step6_51_relocation_fields_df[column_name].astype("string")
    )

step6_51_contract_path = step6_11_reports_dir / "b6_23_estimated_relocation_contract.json"
step6_51_fields_path = step6_11_reports_dir / "b6_23_estimated_relocation_fields.parquet"

with open(step6_51_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_51_relocation_contract, file, ensure_ascii=False, indent=2)

step6_51_relocation_fields_df.to_parquet(step6_51_fields_path, index=False)

step6_51_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_scope",
            "status": "ok",
            "value": "estimated_relocation_layer",
        },
        {
            "check_area": "source_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "check_area": "required_columns",
            "status": "ok",
            "value": str(len(step6_51_required_columns)),
        },
        {
            "check_area": "output_fields",
            "status": "ok",
            "value": str(step6_51_relocation_fields_df.shape[0]),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_51_contract_path),
        },
        {
            "check_area": "fields_path",
            "status": "ok",
            "value": str(step6_51_fields_path),
        },
    ]
)

step6_51_summary_df["check_area"] = step6_51_summary_df["check_area"].astype("string")
step6_51_summary_df["status"] = step6_51_summary_df["status"].astype("string")
step6_51_summary_df["value"] = step6_51_summary_df["value"].astype("string")

display(step6_51_summary_df)
display(step6_51_relocation_fields_df)

         check_area status                                              value
0     section_scope     ok                         estimated_relocation_layer
1      source_grain     ok                                        day_station
2  required_columns     ok                                                 17
3     output_fields     ok                                                  6
4     contract_path     ok  /root/projects/6_samodzielny_projekt_koncowy_w...
5       fields_path     ok  /root/projects/6_samodzielny_projekt_koncowy_w...

,field_name,field_role,source_grain,display_scope
0,estimated_relocation_units,central_estimate,day_station,technical_support
1,estimated_relocation_min,lower_bound,day_station,main_screen
2,estimated_relocation_max,upper_bound,day_station,main_screen
3,estimated_relocation_label,display_label,day_station,main_screen
4,relocation_direction,action_direction,day_station,main_screen
5,relocation_sanity_limit,quantity_guardrail,day_station,technical_support

In [24]:
# 6.5.2 Budowa szacowanej relokacji

import numpy as np
import pandas as pd


step6_52_required_objects = [
    "step6_44_highest_risk_hour_output_df",
    "step6_11_reports_dir",
]

step6_52_missing_objects = [
    object_name
    for object_name in step6_52_required_objects
    if object_name not in globals()
]

assert not step6_52_missing_objects, f"Missing required objects: {step6_52_missing_objects}"

step6_52_estimated_relocation_df = step6_44_highest_risk_hour_output_df.copy()

step6_52_estimated_relocation_df["relocation_direction"] = np.select(
    [
        step6_52_estimated_relocation_df["recommended_action"].astype("string") == "deliver_bikes",
        step6_52_estimated_relocation_df["recommended_action"].astype("string") == "remove_bikes",
        step6_52_estimated_relocation_df["recommended_action"].astype("string") == "check_station_state",
    ],
    [
        "deliver",
        "remove",
        "check",
    ],
    default="check",
)

step6_52_estimated_relocation_df["relocation_direction"] = (
    step6_52_estimated_relocation_df["relocation_direction"].astype("category")
)

step6_52_estimated_relocation_df["relocation_sanity_limit"] = (
    np.ceil(step6_52_estimated_relocation_df["estimated_capacity"].fillna(0) * 0.50)
    .clip(lower=0)
    .astype("int16")
)

step6_52_raw_units = np.select(
    [
        step6_52_estimated_relocation_df["relocation_direction"].astype("string") == "deliver",
        step6_52_estimated_relocation_df["relocation_direction"].astype("string") == "remove",
    ],
    [
        np.ceil(
            step6_52_estimated_relocation_df["estimated_capacity"].fillna(0)
            * step6_52_estimated_relocation_df["problem_direction_share_of_day"].fillna(0)
            * 0.25
        ),
        np.ceil(
            step6_52_estimated_relocation_df["estimated_capacity"].fillna(0)
            * step6_52_estimated_relocation_df["problem_direction_share_of_day"].fillna(0)
            * 0.25
        ),
    ],
    default=0,
)

step6_52_estimated_relocation_df["estimated_relocation_units"] = (
    pd.Series(step6_52_raw_units, index=step6_52_estimated_relocation_df.index)
    .fillna(0)
    .clip(lower=0)
    .astype("int16")
)

step6_52_estimated_relocation_df["estimated_relocation_units"] = np.minimum(
    step6_52_estimated_relocation_df["estimated_relocation_units"],
    step6_52_estimated_relocation_df["relocation_sanity_limit"],
).astype("int16")

step6_52_estimated_relocation_df.loc[
    step6_52_estimated_relocation_df["relocation_direction"].astype("string") == "check",
    "estimated_relocation_units",
] = 0

step6_52_estimated_relocation_df["estimated_relocation_min"] = (
    step6_52_estimated_relocation_df["estimated_relocation_units"] - 1
).clip(lower=0).astype("int16")

step6_52_estimated_relocation_df["estimated_relocation_max"] = (
    step6_52_estimated_relocation_df["estimated_relocation_units"] + 1
).clip(
    lower=0,
    upper=step6_52_estimated_relocation_df["relocation_sanity_limit"],
).astype("int16")

step6_52_estimated_relocation_df.loc[
    step6_52_estimated_relocation_df["relocation_direction"].astype("string") == "check",
    ["estimated_relocation_min", "estimated_relocation_max"],
] = 0

step6_52_estimated_relocation_df["estimated_relocation_label"] = np.select(
    [
        step6_52_estimated_relocation_df["relocation_direction"].astype("string") == "deliver",
        step6_52_estimated_relocation_df["relocation_direction"].astype("string") == "remove",
    ],
    [
        (
            "deliver "
            + step6_52_estimated_relocation_df["estimated_relocation_min"].astype("string")
            + "-"
            + step6_52_estimated_relocation_df["estimated_relocation_max"].astype("string")
        ),
        (
            "remove "
            + step6_52_estimated_relocation_df["estimated_relocation_min"].astype("string")
            + "-"
            + step6_52_estimated_relocation_df["estimated_relocation_max"].astype("string")
        ),
    ],
    default="check",
)

step6_52_estimated_relocation_df["estimated_relocation_label"] = (
    step6_52_estimated_relocation_df["estimated_relocation_label"].astype("string")
)

step6_52_summary_by_direction_df = (
    step6_52_estimated_relocation_df
    .groupby("relocation_direction", observed=True)
    .agg(
        row_count=("relocation_direction", "size"),
        mean_estimated_relocation_units=("estimated_relocation_units", "mean"),
        median_estimated_relocation_units=("estimated_relocation_units", "median"),
        max_estimated_relocation_units=("estimated_relocation_units", "max"),
        mean_sanity_limit=("relocation_sanity_limit", "mean"),
        max_sanity_limit=("relocation_sanity_limit", "max"),
    )
    .reset_index()
)

step6_52_summary_by_direction_df["row_share"] = (
    step6_52_summary_by_direction_df["row_count"]
    / step6_52_summary_by_direction_df["row_count"].sum()
)

step6_52_sanity_check_df = pd.DataFrame(
    [
        {
            "check_area": "relocation_rows",
            "status": "ok",
            "value": str(step6_52_estimated_relocation_df.shape[0]),
        },
        {
            "check_area": "missing_relocation_units",
            "status": "ok",
            "value": str(int(step6_52_estimated_relocation_df["estimated_relocation_units"].isna().sum())),
        },
        {
            "check_area": "units_above_sanity_limit",
            "status": "ok",
            "value": str(
                int(
                    (
                        step6_52_estimated_relocation_df["estimated_relocation_units"]
                        > step6_52_estimated_relocation_df["relocation_sanity_limit"]
                    ).sum()
                )
            ),
        },
        {
            "check_area": "negative_relocation_min",
            "status": "ok",
            "value": str(int((step6_52_estimated_relocation_df["estimated_relocation_min"] < 0).sum())),
        },
        {
            "check_area": "max_below_min",
            "status": "ok",
            "value": str(
                int(
                    (
                        step6_52_estimated_relocation_df["estimated_relocation_max"]
                        < step6_52_estimated_relocation_df["estimated_relocation_min"]
                    ).sum()
                )
            ),
        },
        {
            "check_area": "observed_relocation_directions",
            "status": "ok",
            "value": str(step6_52_estimated_relocation_df["relocation_direction"].nunique()),
        },
    ]
)

step6_52_summary_by_direction_path = step6_11_reports_dir / "b6_24_estimated_relocation_direction_summary.parquet"
step6_52_sanity_check_path = step6_11_reports_dir / "b6_24_estimated_relocation_sanity_check.parquet"

step6_52_summary_by_direction_df.to_parquet(step6_52_summary_by_direction_path, index=False)
step6_52_sanity_check_df.to_parquet(step6_52_sanity_check_path, index=False)

display(step6_52_sanity_check_df)
display(step6_52_summary_by_direction_df)
display(
    step6_52_estimated_relocation_df[
        [
            "activity_date",
            "representative_station_id",
            "station_name",
            "recommended_action",
            "relocation_direction",
            "estimated_capacity",
            "problem_direction_share_of_day",
            "relocation_sanity_limit",
            "estimated_relocation_units",
            "estimated_relocation_min",
            "estimated_relocation_max",
            "estimated_relocation_label",
        ]
    ].head(10)
)

                       check_area status   value
0                 relocation_rows     ok  219071
1        missing_relocation_units     ok       0
2        units_above_sanity_limit     ok       0
3         negative_relocation_min     ok       0
4                   max_below_min     ok       0
5  observed_relocation_directions     ok       2

,relocation_direction,row_count,mean_estimated_relocation_units,median_estimated_relocation_units,max_estimated_relocation_units,mean_sanity_limit,max_sanity_limit,row_share
0,check,7081,0.000000,0.0,0,11.977122,70,0.032323
1,deliver,211990,2.951243,3.0,30,11.811548,70,0.967677

,activity_date,representative_station_id,station_name,recommended_action,relocation_direction,estimated_capacity,problem_direction_share_of_day,relocation_sanity_limit,estimated_relocation_units,estimated_relocation_min,estimated_relocation_max,estimated_relocation_label
0,2017-05-02,30,Itämerentori,deliver_bikes,deliver,117.949997,0.625000,59,19,18,20,deliver 18-20
1,2017-05-02,17,Varsapuistikko,deliver_bikes,deliver,40.000000,0.958333,20,10,9,11,deliver 9-11
2,2017-05-02,6,Hietalahdentori,deliver_bikes,deliver,27.000000,0.583333,14,4,3,5,deliver 3-5
3,2017-05-02,25,Narinkka,deliver_bikes,deliver,31.000000,0.916667,16,8,7,9,deliver 7-9
4,2017-05-02,9,Erottajan aukio,deliver_bikes,deliver,68.949997,0.791667,35,14,13,15,deliver 13-15
5,2017-05-02,26,Kamppi (M),deliver_bikes,deliver,46.799999,0.833333,24,10,9,11,deliver 9-11
6,2017-05-02,24,Mannerheimintie,deliver_bikes,deliver,30.950001,0.625000,16,5,4,6,deliver 4-6
7,2017-05-02,40,Hakaniemi (M),deliver_bikes,deliver,31.850000,0.833333,16,7,6,8,deliver 6-8
8,2017-05-02,8,Vanha kirkkopuisto,deliver_bikes,deliver,29.950001,0.833333,15,7,6,8,deliver 6-8
9,2017-05-02,28,Lastenlehto,deliver_bikes,deliver,25.799999,0.750000,13,5,4,6,deliver 4-6

In [25]:
# 6.5.3 Kontrola spójności szacowanej relokacji

import json

import pandas as pd


step6_53_required_objects = [
    "step6_52_estimated_relocation_df",
    "step6_11_reports_dir",
]

step6_53_missing_objects = [
    object_name
    for object_name in step6_53_required_objects
    if object_name not in globals()
]

assert not step6_53_missing_objects, f"Missing required objects: {step6_53_missing_objects}"

step6_53_duplicate_key_count = int(
    step6_52_estimated_relocation_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_53_missing_label_count = int(
    step6_52_estimated_relocation_df["estimated_relocation_label"].isna().sum()
)

step6_53_units_above_limit_count = int(
    (
        step6_52_estimated_relocation_df["estimated_relocation_units"]
        > step6_52_estimated_relocation_df["relocation_sanity_limit"]
    ).sum()
)

step6_53_min_negative_count = int(
    (step6_52_estimated_relocation_df["estimated_relocation_min"] < 0).sum()
)

step6_53_max_below_min_count = int(
    (
        step6_52_estimated_relocation_df["estimated_relocation_max"]
        < step6_52_estimated_relocation_df["estimated_relocation_min"]
    ).sum()
)

step6_53_check_has_units_count = int(
    (
        (
            step6_52_estimated_relocation_df["relocation_direction"].astype("string") == "check"
        )
        & (step6_52_estimated_relocation_df["estimated_relocation_units"] != 0)
    ).sum()
)

step6_53_deliver_zero_units_count = int(
    (
        (
            step6_52_estimated_relocation_df["relocation_direction"].astype("string") == "deliver"
        )
        & (step6_52_estimated_relocation_df["estimated_relocation_units"] <= 0)
    ).sum()
)

step6_53_remove_zero_units_count = int(
    (
        (
            step6_52_estimated_relocation_df["relocation_direction"].astype("string") == "remove"
        )
        & (step6_52_estimated_relocation_df["estimated_relocation_units"] <= 0)
    ).sum()
)

step6_53_consistency_rules = [
    {
        "rule_name": "no_duplicate_day_station_keys",
        "condition_passed": step6_53_duplicate_key_count == 0,
        "value": str(step6_53_duplicate_key_count),
    },
    {
        "rule_name": "no_missing_estimated_relocation_label",
        "condition_passed": step6_53_missing_label_count == 0,
        "value": str(step6_53_missing_label_count),
    },
    {
        "rule_name": "estimated_units_within_sanity_limit",
        "condition_passed": step6_53_units_above_limit_count == 0,
        "value": str(step6_53_units_above_limit_count),
    },
    {
        "rule_name": "estimated_min_is_non_negative",
        "condition_passed": step6_53_min_negative_count == 0,
        "value": str(step6_53_min_negative_count),
    },
    {
        "rule_name": "estimated_max_is_not_below_min",
        "condition_passed": step6_53_max_below_min_count == 0,
        "value": str(step6_53_max_below_min_count),
    },
    {
        "rule_name": "check_direction_has_zero_units",
        "condition_passed": step6_53_check_has_units_count == 0,
        "value": str(step6_53_check_has_units_count),
    },
    {
        "rule_name": "deliver_direction_has_positive_units",
        "condition_passed": step6_53_deliver_zero_units_count == 0,
        "value": str(step6_53_deliver_zero_units_count),
    },
    {
        "rule_name": "remove_direction_has_positive_units",
        "condition_passed": step6_53_remove_zero_units_count == 0,
        "value": str(step6_53_remove_zero_units_count),
    },
]

step6_53_consistency_df = pd.DataFrame(step6_53_consistency_rules)

step6_53_consistency_df["status"] = step6_53_consistency_df["condition_passed"].map(
    {
        True: "ok",
        False: "review",
    }
)

step6_53_review_count = int(
    (step6_53_consistency_df["status"] == "review").sum()
)

step6_53_relocation_statistics_df = (
    step6_52_estimated_relocation_df
    .groupby(["recommended_action", "relocation_direction"], observed=True)
    .agg(
        row_count=("relocation_direction", "size"),
        mean_estimated_relocation_units=("estimated_relocation_units", "mean"),
        median_estimated_relocation_units=("estimated_relocation_units", "median"),
        min_estimated_relocation_units=("estimated_relocation_units", "min"),
        max_estimated_relocation_units=("estimated_relocation_units", "max"),
        mean_estimated_relocation_min=("estimated_relocation_min", "mean"),
        mean_estimated_relocation_max=("estimated_relocation_max", "mean"),
        mean_relocation_sanity_limit=("relocation_sanity_limit", "mean"),
        max_relocation_sanity_limit=("relocation_sanity_limit", "max"),
    )
    .reset_index()
)

step6_53_relocation_statistics_df["row_share"] = (
    step6_53_relocation_statistics_df["row_count"]
    / step6_53_relocation_statistics_df["row_count"].sum()
)

step6_53_contract = {
    "block_name": "block_6",
    "section_name": "6.5",
    "contract_scope": "estimated_relocation_consistency",
    "grain": "day_station",
    "key_columns": [
        "activity_date",
        "representative_station_id",
    ],
    "review_count": step6_53_review_count,
    "observed_relocation_directions": sorted(
        step6_52_estimated_relocation_df["relocation_direction"]
        .astype("string")
        .unique()
        .tolist()
    ),
    "observed_recommended_actions": sorted(
        step6_52_estimated_relocation_df["recommended_action"]
        .astype("string")
        .unique()
        .tolist()
    ),
}

step6_53_consistency_path = step6_11_reports_dir / "b6_25_estimated_relocation_consistency.parquet"
step6_53_statistics_path = step6_11_reports_dir / "b6_25_estimated_relocation_statistics.parquet"
step6_53_contract_path = step6_11_reports_dir / "b6_25_estimated_relocation_consistency_contract.json"

step6_53_consistency_df.to_parquet(step6_53_consistency_path, index=False)
step6_53_relocation_statistics_df.to_parquet(step6_53_statistics_path, index=False)

with open(step6_53_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_53_contract, file, ensure_ascii=False, indent=2)

step6_53_summary_df = pd.DataFrame(
    [
        {
            "check_area": "consistency_rules",
            "status": "ok",
            "value": str(step6_53_consistency_df.shape[0]),
        },
        {
            "check_area": "consistency_review_count",
            "status": "ok" if step6_53_review_count == 0 else "review",
            "value": str(step6_53_review_count),
        },
        {
            "check_area": "observed_relocation_directions",
            "status": "ok",
            "value": str(step6_52_estimated_relocation_df["relocation_direction"].nunique()),
        },
        {
            "check_area": "consistency_path",
            "status": "ok",
            "value": str(step6_53_consistency_path),
        },
        {
            "check_area": "statistics_path",
            "status": "ok",
            "value": str(step6_53_statistics_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_53_contract_path),
        },
    ]
)

step6_53_summary_df["check_area"] = step6_53_summary_df["check_area"].astype("string")
step6_53_summary_df["status"] = step6_53_summary_df["status"].astype("string")
step6_53_summary_df["value"] = step6_53_summary_df["value"].astype("string")

display(step6_53_summary_df)
display(step6_53_consistency_df)
display(step6_53_relocation_statistics_df)

,check_area,status,value
0,consistency_rules,ok,8
1,consistency_review_count,ok,0
2,observed_relocation_directions,ok,2
3,consistency_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,statistics_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                               rule_name  condition_passed value status
0          no_duplicate_day_station_keys              True     0     ok
1  no_missing_estimated_relocation_label              True     0     ok
2    estimated_units_within_sanity_limit              True     0     ok
3          estimated_min_is_non_negative              True     0     ok
4         estimated_max_is_not_below_min              True     0     ok
5         check_direction_has_zero_units              True     0     ok
6   deliver_direction_has_positive_units              True     0     ok
7    remove_direction_has_positive_units              True     0     ok

,recommended_action,relocation_direction,row_count,mean_estimated_relocation_units,median_estimated_relocation_units,min_estimated_relocation_units,max_estimated_relocation_units,mean_estimated_relocation_min,mean_estimated_relocation_max,mean_relocation_sanity_limit,max_relocation_sanity_limit,row_share
0,check_station_state,check,7081,0.000000,0.0,0,0,0.000000,0.000000,11.977122,70,0.032323
1,deliver_bikes,deliver,211990,2.951243,3.0,1,30,1.951243,3.951243,11.811548,70,0.967677

In [26]:
# 6.5.4 Zamknięcie kontraktu szacowanej relokacji

import json

import pandas as pd


step6_54_required_objects = [
    "step6_51_relocation_contract",
    "step6_52_estimated_relocation_df",
    "step6_53_consistency_df",
    "step6_53_relocation_statistics_df",
    "step6_11_reports_dir",
    "step6_11_outputs_dir",
]

step6_54_missing_objects = [
    object_name
    for object_name in step6_54_required_objects
    if object_name not in globals()
]

assert not step6_54_missing_objects, f"Missing required objects: {step6_54_missing_objects}"

step6_54_output_columns = [
    "activity_date",
    "representative_station_id",
    "station_name",
    "estimated_capacity",
    "departure_signal_hours",
    "return_signal_hours",
    "total_departures",
    "total_returns",
    "daily_net_flow",
    "min_occupancy_proxy",
    "max_occupancy_proxy",
    "min_free_capacity_proxy",
    "max_free_capacity_proxy",
    "observed_hour_count",
    "problem_type",
    "problem_direction_score",
    "problem_direction_share_of_day",
    "dominant_signal_side",
    "recommended_action",
    "action_priority",
    "highest_risk_hour",
    "highest_risk_hour_label",
    "highest_risk_hour_score",
    "highest_risk_hour_problem_type",
    "highest_risk_hour_signal_strength",
    "highest_risk_hour_direction_sort_score",
    "highest_risk_hour_absolute_net_flow",
    "highest_risk_hour_absolute_cumulative_net_flow",
    "highest_risk_hour_capacity_pressure_score",
    "relocation_direction",
    "relocation_sanity_limit",
    "estimated_relocation_units",
    "estimated_relocation_min",
    "estimated_relocation_max",
    "estimated_relocation_label",
]

step6_54_available_columns = step6_52_estimated_relocation_df.columns.tolist()

step6_54_missing_output_columns = [
    column_name
    for column_name in step6_54_output_columns
    if column_name not in step6_54_available_columns
]

assert not step6_54_missing_output_columns, f"Missing output columns: {step6_54_missing_output_columns}"

step6_54_review_count = int(
    (step6_53_consistency_df["status"] == "review").sum()
)

step6_54_duplicate_key_count = int(
    step6_52_estimated_relocation_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_54_missing_label_count = int(
    step6_52_estimated_relocation_df["estimated_relocation_label"].isna().sum()
)

step6_54_units_above_limit_count = int(
    (
        step6_52_estimated_relocation_df["estimated_relocation_units"]
        > step6_52_estimated_relocation_df["relocation_sanity_limit"]
    ).sum()
)

assert step6_54_review_count == 0, "Estimated relocation consistency review detected."
assert step6_54_duplicate_key_count == 0, "Duplicated day-station keys detected."
assert step6_54_missing_label_count == 0, "Missing estimated_relocation_label values detected."
assert step6_54_units_above_limit_count == 0, "Estimated relocation units above sanity limit detected."

step6_54_estimated_relocation_output_df = (
    step6_52_estimated_relocation_df[step6_54_output_columns]
    .sort_values(
        [
            "activity_date",
            "action_priority",
            "estimated_relocation_units",
            "highest_risk_hour_score",
            "problem_direction_score",
            "representative_station_id",
        ],
        ascending=[True, True, False, False, False, True],
    )
    .reset_index(drop=True)
)

step6_54_observed_relocation_directions = sorted(
    step6_54_estimated_relocation_output_df["relocation_direction"]
    .astype("string")
    .unique()
    .tolist()
)

step6_54_observed_recommended_actions = sorted(
    step6_54_estimated_relocation_output_df["recommended_action"]
    .astype("string")
    .unique()
    .tolist()
)

step6_54_output_path = step6_11_outputs_dir / "b6_26_operational_recommendation_with_estimated_relocation.parquet"
step6_54_output_profile_path = step6_11_reports_dir / "b6_26_estimated_relocation_output_profile.parquet"
step6_54_section_contract_path = step6_11_reports_dir / "b6_26_estimated_relocation_section_contract.json"
step6_54_section_status_path = step6_11_reports_dir / "b6_26_estimated_relocation_section_status.parquet"

step6_54_estimated_relocation_output_df.to_parquet(step6_54_output_path, index=False)

step6_54_output_profile_df = pd.DataFrame(
    [
        {
            "profile_area": "output_rows",
            "status": "ok",
            "value": str(step6_54_estimated_relocation_output_df.shape[0]),
        },
        {
            "profile_area": "output_columns",
            "status": "ok",
            "value": str(step6_54_estimated_relocation_output_df.shape[1]),
        },
        {
            "profile_area": "unique_stations",
            "status": "ok",
            "value": str(step6_54_estimated_relocation_output_df["representative_station_id"].nunique()),
        },
        {
            "profile_area": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_54_duplicate_key_count),
        },
        {
            "profile_area": "missing_estimated_relocation_label",
            "status": "ok",
            "value": str(step6_54_missing_label_count),
        },
        {
            "profile_area": "units_above_sanity_limit",
            "status": "ok",
            "value": str(step6_54_units_above_limit_count),
        },
        {
            "profile_area": "observed_relocation_directions",
            "status": "ok",
            "value": json.dumps(step6_54_observed_relocation_directions, ensure_ascii=False),
        },
        {
            "profile_area": "observed_recommended_actions",
            "status": "ok",
            "value": json.dumps(step6_54_observed_recommended_actions, ensure_ascii=False),
        },
    ]
)

step6_54_output_profile_df.to_parquet(step6_54_output_profile_path, index=False)

step6_54_section_contract = {
    "block_name": "block_6",
    "section_name": "6.5",
    "section_scope": "estimated_relocation_layer",
    "source_grain": "day_station",
    "output_grain": "day_station",
    "source_object": "step6_52_estimated_relocation_df",
    "output_object": "step6_54_estimated_relocation_output_df",
    "output_path": str(step6_54_output_path),
    "key_columns": [
        "activity_date",
        "representative_station_id",
    ],
    "main_output_fields": [
        "relocation_direction",
        "estimated_relocation_min",
        "estimated_relocation_max",
        "estimated_relocation_label",
    ],
    "technical_support_fields": [
        "estimated_relocation_units",
        "relocation_sanity_limit",
    ],
    "quantity_policy": step6_51_relocation_contract["quantity_policy"],
    "sanity_policy": step6_51_relocation_contract["sanity_policy"],
    "observed_relocation_directions": step6_54_observed_relocation_directions,
    "observed_recommended_actions": step6_54_observed_recommended_actions,
    "output_row_count": int(step6_54_estimated_relocation_output_df.shape[0]),
    "output_column_count": int(step6_54_estimated_relocation_output_df.shape[1]),
    "unique_station_count": int(step6_54_estimated_relocation_output_df["representative_station_id"].nunique()),
    "duplicate_key_count": step6_54_duplicate_key_count,
    "consistency_review_count": step6_54_review_count,
}

with open(step6_54_section_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_54_section_contract, file, ensure_ascii=False, indent=2)

step6_54_section_status_df = pd.DataFrame(
    [
        {
            "section_item": "section_6_5_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "section_item": "output_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "section_item": "output_rows",
            "status": "ok",
            "value": str(step6_54_estimated_relocation_output_df.shape[0]),
        },
        {
            "section_item": "output_columns",
            "status": "ok",
            "value": str(step6_54_estimated_relocation_output_df.shape[1]),
        },
        {
            "section_item": "observed_relocation_directions",
            "status": "ok",
            "value": json.dumps(step6_54_observed_relocation_directions, ensure_ascii=False),
        },
        {
            "section_item": "consistency_review_count",
            "status": "ok",
            "value": str(step6_54_review_count),
        },
    ]
)

step6_54_section_status_df.to_parquet(step6_54_section_status_path, index=False)

step6_54_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_6_5_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "check_area": "estimated_relocation_rows",
            "status": "ok",
            "value": str(step6_54_estimated_relocation_output_df.shape[0]),
        },
        {
            "check_area": "estimated_relocation_columns",
            "status": "ok",
            "value": str(step6_54_estimated_relocation_output_df.shape[1]),
        },
        {
            "check_area": "output_path",
            "status": "ok",
            "value": str(step6_54_output_path),
        },
        {
            "check_area": "profile_path",
            "status": "ok",
            "value": str(step6_54_output_profile_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_54_section_contract_path),
        },
        {
            "check_area": "status_path",
            "status": "ok",
            "value": str(step6_54_section_status_path),
        },
    ]
)

step6_54_summary_df["check_area"] = step6_54_summary_df["check_area"].astype("string")
step6_54_summary_df["status"] = step6_54_summary_df["status"].astype("string")
step6_54_summary_df["value"] = step6_54_summary_df["value"].astype("string")

display(step6_54_summary_df)
display(step6_54_section_status_df)
display(step6_54_output_profile_df)
display(step6_54_estimated_relocation_output_df.head(10))

,check_area,status,value
0,section_6_5_status,ok,closed
1,estimated_relocation_rows,ok,219071
2,estimated_relocation_columns,ok,35
3,output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,profile_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,status_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                     section_item status                 value
0              section_6_5_status     ok                closed
1                    output_grain     ok           day_station
2                     output_rows     ok                219071
3                  output_columns     ok                    35
4  observed_relocation_directions     ok  ["check", "deliver"]
5        consistency_review_count     ok                     0

,profile_area,status,value
0,output_rows,ok,219071
1,output_columns,ok,35
2,unique_stations,ok,344
3,duplicate_day_station_keys,ok,0
4,missing_estimated_relocation_label,ok,0
5,units_above_sanity_limit,ok,0
6,observed_relocation_directions,ok,"[""check"", ""deliver""]"
7,observed_recommended_actions,ok,"[""check_station_state"", ""deliver_bikes""]"

,activity_date,representative_station_id,station_name,estimated_capacity,departure_signal_hours,return_signal_hours,total_departures,total_returns,daily_net_flow,min_occupancy_proxy,...,highest_risk_hour_direction_sort_score,highest_risk_hour_absolute_net_flow,highest_risk_hour_absolute_cumulative_net_flow,highest_risk_hour_capacity_pressure_score,relocation_direction,relocation_sanity_limit,estimated_relocation_units,estimated_relocation_min,estimated_relocation_max,estimated_relocation_label
0,2017-05-02,11,Unioninkatu,88.000000,21,0,29,19,-10,0,...,3,4,10,0.0,deliver,44,20,19,21,deliver 19-21
1,2017-05-02,30,Itämerentori,117.949997,15,0,91,57,-34,0,...,3,12,33,0.0,deliver,59,19,18,20,deliver 18-20
2,2017-05-02,9,Erottajan aukio,68.949997,19,0,38,22,-16,0,...,3,7,16,0.0,deliver,35,14,13,15,deliver 13-15
3,2017-05-02,21,Töölönlahdenkatu,54.000000,21,0,57,51,-6,0,...,3,3,6,0.0,deliver,27,12,11,13,deliver 11-13
4,2017-05-02,120,Mäkelänkatu,48.000000,22,0,8,7,-1,0,...,3,2,0,0.0,deliver,24,12,11,13,deliver 11-13
5,2017-05-02,83,Meilahden sairaala,45.950001,24,0,3,3,0,0,...,3,0,0,0.0,deliver,23,12,11,13,deliver 11-13
6,2017-05-02,17,Varsapuistikko,40.000000,23,0,34,18,-16,0,...,3,11,15,0.0,deliver,20,10,9,11,deliver 9-11
7,2017-05-02,26,Kamppi (M),46.799999,20,0,71,55,-16,0,...,3,6,11,0.0,deliver,24,10,9,11,deliver 9-11
8,2017-05-02,14,Senaatintori,39.950001,23,0,28,12,-16,0,...,3,5,12,0.0,deliver,20,10,9,11,deliver 9-11
9,2017-05-02,41,Ympyrätalo,54.000000,15,0,47,49,2,0,...,3,5,12,0.0,deliver,27,9,8,10,deliver 8-10

## Podsumowanie działu 6.5 Szacowana relokacja rowerów

**Kontekst inżynieryjny:** W dziale `6.5` zbudowano warstwę szacowanej relokacji rowerów na podstawie dotychczasowej warstwy operacyjnej BLOKU 6. Źródłem wejściowym była tabela `step6_44_highest_risk_hour_output_df`, działająca na poziomie `day_station`, zawierająca już typ problemu, rekomendację operacyjną oraz godzinę największego ryzyka. Najpierw zdefiniowano kontrakt szacowanej relokacji, obejmujący pola `estimated_relocation_units`, `estimated_relocation_min`, `estimated_relocation_max`, `estimated_relocation_label`, `relocation_direction` oraz `relocation_sanity_limit`. Następnie zbudowano roboczą warstwę ilościową, w której kierunek relokacji wynika z `recommended_action`, a szacowana liczba rowerów zależy od pojemności stacji oraz intensywności problemu mierzonej przez `problem_direction_share_of_day`. Na końcu przeprowadzono kontrolę spójności zakresów, limitów bezpieczeństwa i kompletności etykiet relokacji, a finalny output zapisano jako artefakt działu `6.5`.

**Interpretacja wyniku:** Warstwa szacowanej relokacji została zbudowana dla `219 071` rekordów dzień–stacja i obejmuje `344` unikalne stacje. Finalny output zawiera `35` kolumn, w tym `relocation_direction`, `relocation_sanity_limit`, `estimated_relocation_units`, `estimated_relocation_min`, `estimated_relocation_max` oraz `estimated_relocation_label`. W danych zaobserwowano dwa kierunki relokacji: `deliver` oraz `check`. Kierunek `deliver` występuje dla `211 990` rekordów, natomiast `check` dla `7 081` rekordów. Dla kierunku `deliver` średnia szacowana relokacja wynosi około `2.95` roweru, mediana wynosi `3`, a maksymalna wartość wynosi `30`. Dla kierunku `check` liczba relokowanych rowerów wynosi `0`, zgodnie z logiką kontroli stanu. Kontrola spójności objęła `8` reguł i zakończyła się wynikiem `0` reguł wymagających przeglądu. Nie występują duplikaty klucza `activity_date + representative_station_id`, nie występują brakujące etykiety relokacji, a żadna szacowana liczba rowerów nie przekracza limitu bezpieczeństwa względem pojemności stacji.

**Znaczenie biznesowe:** Dział `6.5` dodaje do panelu dyspozytora element ilościowy, czyli informację, ile rowerów należy szacunkowo przesunąć. Warstwa ta nie udaje dokładnego stanu magazynowego stacji, lecz tworzy operacyjny zakres relokacji oparty na intensywności problemu i pojemności stacji. Dzięki temu rekomendacja nie kończy się na informacji `deliver_bikes`, ale zostaje rozwinięta do formy możliwej do użycia w pracy operacyjnej, np. `deliver 4-6`, `deliver 9-11` albo `check`. Jednocześnie zastosowany `relocation_sanity_limit` ogranicza rekomendacje ilościowe do zakresu spójnego z pojemnością stacji, co zabezpiecza warstwę operacyjną przed nierealnymi wartościami. To przygotowuje dane pod kolejne etapy BLOKU 6, w szczególności priorytetyzację stacji, plan dnia, pary kompensacyjne oraz widok kierowcy.

**Wniosek:** Dział `6.5` został domknięty poprawnie. Zbudowano finalną warstwę szacowanej relokacji na poziomie dzień–stacja, zapisaną jako `b6_26_operational_recommendation_with_estimated_relocation.parquet`, wraz z profilem, kontraktem i statusem działu. Warstwa zawiera komplet `219 071` rekordów, `35` kolumn, brak duplikatów klucza dziennego, brak pustych etykiet relokacji oraz `0` przypadków przekroczenia limitu bezpieczeństwa. Oznacza to, że można przejść do kolejnego etapu, czyli `6.6 Priorytetyzacja stacji i plan dnia`, wykorzystując gotowe pola `recommended_action`, `highest_risk_hour_label` oraz `estimated_relocation_label` jako podstawę listy działań dla dyspozytora.

## 6.6 Priorytetyzacja stacji i plan dnia

In [27]:
# 6.6.1 Definicja kontraktu priorytetyzacji stacji

import json

import pandas as pd


step6_61_required_objects = [
    "step6_54_estimated_relocation_output_df",
    "step6_11_reports_dir",
]

step6_61_missing_objects = [
    object_name
    for object_name in step6_61_required_objects
    if object_name not in globals()
]

assert not step6_61_missing_objects, f"Missing required objects: {step6_61_missing_objects}"

step6_61_priority_contract = {
    "block_name": "block_6",
    "section_name": "6.6",
    "section_scope": "station_priority_and_daily_plan_layer",
    "source_object": "step6_54_estimated_relocation_output_df",
    "source_grain": "day_station",
    "output_grain": "day_station",
    "main_output_fields": [
        "station_name",
        "priority_level",
        "problem_type",
        "recommended_action",
        "highest_risk_hour_label",
        "estimated_relocation_label",
        "recommendation_confidence",
        "decision_reason",
        "expected_business_impact",
    ],
    "priority_levels": [
        "very_high",
        "high",
        "medium",
        "low",
    ],
    "confidence_levels": [
        "high",
        "medium",
        "low",
    ],
    "expected_business_impact_policy": {
        "uses_money_roi": False,
        "uses_operational_impact_proxy": True,
        "main_formula": "problem_direction_share_of_day * station_business_scale",
        "station_business_scale_candidates": [
            "total_departures",
            "total_returns",
            "estimated_capacity",
            "highest_risk_hour_absolute_net_flow",
            "highest_risk_hour_absolute_cumulative_net_flow",
        ],
    },
    "sorting_policy": {
        "primary_sort": "expected_business_impact",
        "secondary_sort": "priority_score",
        "tertiary_sort": "estimated_relocation_units",
        "quaternary_sort": "highest_risk_hour_score",
    },
    "main_screen_policy": {
        "show_operational_language": True,
        "show_raw_model_fields": False,
        "show_money_roi_claim": False,
    },
}

step6_61_required_columns = [
    "activity_date",
    "representative_station_id",
    "station_name",
    "estimated_capacity",
    "total_departures",
    "total_returns",
    "daily_net_flow",
    "problem_type",
    "problem_direction_score",
    "problem_direction_share_of_day",
    "dominant_signal_side",
    "recommended_action",
    "action_priority",
    "highest_risk_hour_label",
    "highest_risk_hour_score",
    "highest_risk_hour_absolute_net_flow",
    "highest_risk_hour_absolute_cumulative_net_flow",
    "relocation_direction",
    "estimated_relocation_units",
    "estimated_relocation_min",
    "estimated_relocation_max",
    "estimated_relocation_label",
]

step6_61_missing_columns = [
    column_name
    for column_name in step6_61_required_columns
    if column_name not in step6_54_estimated_relocation_output_df.columns
]

assert not step6_61_missing_columns, f"Missing required columns: {step6_61_missing_columns}"

step6_61_output_fields_df = pd.DataFrame(
    [
        {
            "field_name": "priority_level",
            "field_role": "dispatcher_priority",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "priority_score",
            "field_role": "technical_priority_score",
            "source_grain": "day_station",
            "display_scope": "technical_support",
        },
        {
            "field_name": "expected_business_impact",
            "field_role": "operational_impact_proxy",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "station_business_scale",
            "field_role": "station_activity_scale",
            "source_grain": "day_station",
            "display_scope": "technical_support",
        },
        {
            "field_name": "recommendation_confidence",
            "field_role": "decision_confidence",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "decision_reason",
            "field_role": "short_decision_explanation",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "daily_plan_rank",
            "field_role": "dispatcher_daily_order",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
    ]
)

for column_name in ["field_name", "field_role", "source_grain", "display_scope"]:
    step6_61_output_fields_df[column_name] = step6_61_output_fields_df[column_name].astype("string")

step6_61_contract_path = step6_11_reports_dir / "b6_27_station_priority_contract.json"
step6_61_output_fields_path = step6_11_reports_dir / "b6_27_station_priority_output_fields.parquet"

with open(step6_61_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_61_priority_contract, file, ensure_ascii=False, indent=2)

step6_61_output_fields_df.to_parquet(step6_61_output_fields_path, index=False)

step6_61_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_scope",
            "status": "ok",
            "value": "station_priority_and_daily_plan_layer",
        },
        {
            "check_area": "source_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "check_area": "required_columns",
            "status": "ok",
            "value": str(len(step6_61_required_columns)),
        },
        {
            "check_area": "main_output_fields",
            "status": "ok",
            "value": str(len(step6_61_priority_contract["main_output_fields"])),
        },
        {
            "check_area": "priority_levels",
            "status": "ok",
            "value": str(len(step6_61_priority_contract["priority_levels"])),
        },
        {
            "check_area": "output_fields",
            "status": "ok",
            "value": str(step6_61_output_fields_df.shape[0]),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_61_contract_path),
        },
        {
            "check_area": "output_fields_path",
            "status": "ok",
            "value": str(step6_61_output_fields_path),
        },
    ]
)

step6_61_summary_df["check_area"] = step6_61_summary_df["check_area"].astype("string")
step6_61_summary_df["status"] = step6_61_summary_df["status"].astype("string")
step6_61_summary_df["value"] = step6_61_summary_df["value"].astype("string")

display(step6_61_summary_df)
display(step6_61_output_fields_df)

,check_area,status,value
0,section_scope,ok,station_priority_and_daily_plan_layer
1,source_grain,ok,day_station
2,required_columns,ok,22
3,main_output_fields,ok,9
4,priority_levels,ok,4
5,output_fields,ok,7
6,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,output_fields_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,field_name,field_role,source_grain,display_scope
0,priority_level,dispatcher_priority,day_station,main_screen
1,priority_score,technical_priority_score,day_station,technical_support
2,expected_business_impact,operational_impact_proxy,day_station,main_screen
3,station_business_scale,station_activity_scale,day_station,technical_support
4,recommendation_confidence,decision_confidence,day_station,main_screen
5,decision_reason,short_decision_explanation,day_station,main_screen
6,daily_plan_rank,dispatcher_daily_order,day_station,main_screen

In [28]:
# 6.6.2 Budowa wskaźników priorytetyzacji stacji

import numpy as np
import pandas as pd


step6_62_required_objects = [
    "step6_54_estimated_relocation_output_df",
    "step6_11_reports_dir",
]

step6_62_missing_objects = [
    object_name
    for object_name in step6_62_required_objects
    if object_name not in globals()
]

assert not step6_62_missing_objects, f"Missing required objects: {step6_62_missing_objects}"

step6_62_priority_df = step6_54_estimated_relocation_output_df.copy()

step6_62_priority_df["station_business_scale"] = (
    step6_62_priority_df["total_departures"].fillna(0).astype("float32")
    + step6_62_priority_df["total_returns"].fillna(0).astype("float32")
    + step6_62_priority_df["estimated_capacity"].fillna(0).astype("float32") * 0.25
    + step6_62_priority_df["highest_risk_hour_absolute_net_flow"].fillna(0).astype("float32")
    + step6_62_priority_df["highest_risk_hour_absolute_cumulative_net_flow"].fillna(0).astype("float32") * 0.50
).astype("float32")

step6_62_priority_df["expected_business_impact"] = (
    step6_62_priority_df["problem_direction_share_of_day"].fillna(0).astype("float32")
    * step6_62_priority_df["station_business_scale"].fillna(0).astype("float32")
).astype("float32")

step6_62_priority_df["priority_score"] = (
    step6_62_priority_df["expected_business_impact"].fillna(0).astype("float32") * 10
    + step6_62_priority_df["estimated_relocation_units"].fillna(0).astype("float32") * 5
    + step6_62_priority_df["highest_risk_hour_score"].fillna(0).astype("float32") * 0.01
    + step6_62_priority_df["problem_direction_score"].fillna(0).astype("float32")
).astype("float32")

step6_62_priority_quantiles = step6_62_priority_df["priority_score"].quantile(
    [0.50, 0.75, 0.90]
)

step6_62_medium_threshold = float(step6_62_priority_quantiles.loc[0.50])
step6_62_high_threshold = float(step6_62_priority_quantiles.loc[0.75])
step6_62_very_high_threshold = float(step6_62_priority_quantiles.loc[0.90])

step6_62_priority_df["priority_level"] = np.select(
    [
        step6_62_priority_df["priority_score"] >= step6_62_very_high_threshold,
        step6_62_priority_df["priority_score"] >= step6_62_high_threshold,
        step6_62_priority_df["priority_score"] >= step6_62_medium_threshold,
    ],
    [
        "very_high",
        "high",
        "medium",
    ],
    default="low",
)

step6_62_priority_df["priority_level"] = step6_62_priority_df["priority_level"].astype("category")

step6_62_priority_summary_df = (
    step6_62_priority_df
    .groupby("priority_level", observed=True)
    .agg(
        row_count=("priority_level", "size"),
        mean_expected_business_impact=("expected_business_impact", "mean"),
        median_expected_business_impact=("expected_business_impact", "median"),
        max_expected_business_impact=("expected_business_impact", "max"),
        mean_priority_score=("priority_score", "mean"),
        median_priority_score=("priority_score", "median"),
        max_priority_score=("priority_score", "max"),
        mean_estimated_relocation_units=("estimated_relocation_units", "mean"),
    )
    .reset_index()
)

step6_62_priority_summary_df["row_share"] = (
    step6_62_priority_summary_df["row_count"]
    / step6_62_priority_summary_df["row_count"].sum()
)

step6_62_action_priority_summary_df = (
    step6_62_priority_df
    .groupby(["recommended_action", "priority_level"], observed=True)
    .agg(
        row_count=("priority_level", "size"),
        mean_expected_business_impact=("expected_business_impact", "mean"),
        mean_priority_score=("priority_score", "mean"),
        mean_estimated_relocation_units=("estimated_relocation_units", "mean"),
    )
    .reset_index()
)

step6_62_action_priority_summary_df["row_share_within_action"] = (
    step6_62_action_priority_summary_df["row_count"]
    / step6_62_action_priority_summary_df.groupby("recommended_action", observed=True)["row_count"].transform("sum")
)

step6_62_priority_thresholds_df = pd.DataFrame(
    [
        {
            "threshold_name": "medium_threshold",
            "threshold_value": step6_62_medium_threshold,
        },
        {
            "threshold_name": "high_threshold",
            "threshold_value": step6_62_high_threshold,
        },
        {
            "threshold_name": "very_high_threshold",
            "threshold_value": step6_62_very_high_threshold,
        },
    ]
)

step6_62_priority_profile_df = pd.DataFrame(
    [
        {
            "check_area": "priority_rows",
            "status": "ok",
            "value": str(step6_62_priority_df.shape[0]),
        },
        {
            "check_area": "priority_columns",
            "status": "ok",
            "value": str(step6_62_priority_df.shape[1]),
        },
        {
            "check_area": "missing_expected_business_impact",
            "status": "ok",
            "value": str(int(step6_62_priority_df["expected_business_impact"].isna().sum())),
        },
        {
            "check_area": "missing_priority_score",
            "status": "ok",
            "value": str(int(step6_62_priority_df["priority_score"].isna().sum())),
        },
        {
            "check_area": "priority_levels",
            "status": "ok",
            "value": str(step6_62_priority_df["priority_level"].nunique()),
        },
    ]
)

step6_62_priority_summary_path = step6_11_reports_dir / "b6_28_priority_level_summary.parquet"
step6_62_action_priority_summary_path = step6_11_reports_dir / "b6_28_action_priority_summary.parquet"
step6_62_priority_thresholds_path = step6_11_reports_dir / "b6_28_priority_thresholds.parquet"
step6_62_priority_profile_path = step6_11_reports_dir / "b6_28_priority_profile.parquet"

step6_62_priority_summary_df.to_parquet(step6_62_priority_summary_path, index=False)
step6_62_action_priority_summary_df.to_parquet(step6_62_action_priority_summary_path, index=False)
step6_62_priority_thresholds_df.to_parquet(step6_62_priority_thresholds_path, index=False)
step6_62_priority_profile_df.to_parquet(step6_62_priority_profile_path, index=False)

display(step6_62_priority_profile_df)
display(step6_62_priority_thresholds_df)
display(step6_62_priority_summary_df)
display(step6_62_action_priority_summary_df)
display(
    step6_62_priority_df[
        [
            "activity_date",
            "representative_station_id",
            "station_name",
            "recommended_action",
            "highest_risk_hour_label",
            "estimated_relocation_label",
            "station_business_scale",
            "expected_business_impact",
            "priority_score",
            "priority_level",
        ]
    ].head(10)
)

                         check_area status   value
0                     priority_rows     ok  219071
1                  priority_columns     ok      39
2  missing_expected_business_impact     ok       0
3            missing_priority_score     ok       0
4                   priority_levels     ok       4

        threshold_name  threshold_value
0     medium_threshold       338.266907
1       high_threshold       640.053925
2  very_high_threshold      1072.923340

,priority_level,row_count,mean_expected_business_impact,median_expected_business_impact,max_expected_business_impact,mean_priority_score,median_priority_score,max_priority_score,mean_estimated_relocation_units,row_share
0,high,32860,77.868835,76.239586,105.072914,822.061646,805.408752,1072.920044,3.784601,0.149997
1,low,109535,15.602734,15.297916,31.935938,191.375015,188.970001,338.262512,2.125750,0.499998
2,medium,54768,42.808716,41.854164,61.833336,467.777802,457.895233,640.050354,3.030291,0.250001
3,very_high,21908,155.303162,135.568756,1241.005127,1601.790039,1403.546631,12458.292969,4.677059,0.100004

,recommended_action,priority_level,row_count,mean_expected_business_impact,mean_priority_score,mean_estimated_relocation_units,row_share_within_action
0,check_station_state,high,1334,80.887840,834.132935,0.000000,0.188391
1,check_station_state,low,2156,20.144548,225.906326,0.000000,0.304477
2,check_station_state,medium,1842,44.413116,470.178802,0.000000,0.260133
3,check_station_state,very_high,1749,187.166733,1897.907471,0.000000,0.246999
4,deliver_bikes,high,31526,77.741096,821.550842,3.944744,0.148715
5,deliver_bikes,low,107379,15.511541,190.681686,2.168431,0.506529
6,deliver_bikes,medium,52926,42.752876,467.694214,3.135756,0.249663
7,deliver_bikes,very_high,20159,152.538681,1576.098755,5.082841,0.095094

,activity_date,representative_station_id,station_name,recommended_action,highest_risk_hour_label,estimated_relocation_label,station_business_scale,expected_business_impact,priority_score,priority_level
0,2017-05-02,11,Unioninkatu,deliver_bikes,16:00,deliver 19-21,79.000000,69.125000,825.750000,high
1,2017-05-02,30,Itämerentori,deliver_bikes,17:00,deliver 18-20,205.987503,128.742188,1411.951904,very_high
2,2017-05-02,9,Erottajan aukio,deliver_bikes,16:00,deliver 13-15,92.237503,73.021355,833.073547,high
3,2017-05-02,21,Töölönlahdenkatu,deliver_bikes,19:00,deliver 11-13,127.500000,111.562500,1209.984985,very_high
4,2017-05-02,120,Mäkelänkatu,deliver_bikes,19:00,deliver 11-13,29.000000,26.583334,361.033356,medium
5,2017-05-02,83,Meilahden sairaala,deliver_bikes,00:00,deliver 11-13,17.487499,17.487499,271.875000,low
6,2017-05-02,17,Varsapuistikko,deliver_bikes,17:00,deliver 9-11,80.500000,77.145828,858.708252,high
7,2017-05-02,26,Kamppi (M),deliver_bikes,16:00,deliver 9-11,149.199997,124.333328,1327.043213,very_high
8,2017-05-02,14,Senaatintori,deliver_bikes,17:00,deliver 9-11,60.987499,58.446354,671.083557,high
9,2017-05-02,41,Ympyrätalo,deliver_bikes,13:00,deliver 8-10,120.500000,75.312500,826.744995,high

In [29]:
# 6.6.3 Budowa planu dnia dyspozytora

import numpy as np
import pandas as pd


step6_63_required_objects = [
    "step6_62_priority_df",
    "step6_11_reports_dir",
]

step6_63_missing_objects = [
    object_name
    for object_name in step6_63_required_objects
    if object_name not in globals()
]

assert not step6_63_missing_objects, f"Missing required objects: {step6_63_missing_objects}"

step6_63_daily_plan_df = step6_62_priority_df.copy()

step6_63_daily_plan_df["recommendation_confidence"] = np.select(
    [
        (
            (step6_63_daily_plan_df["recommended_action"].astype("string") == "deliver_bikes")
            & (step6_63_daily_plan_df["dominant_signal_side"].astype("string") == "departure_side")
            & (step6_63_daily_plan_df["problem_direction_share_of_day"] >= 0.50)
        ),
        (
            (step6_63_daily_plan_df["recommended_action"].astype("string") == "check_station_state")
            & (step6_63_daily_plan_df["problem_direction_share_of_day"] >= 0.35)
        ),
        (
            step6_63_daily_plan_df["problem_direction_share_of_day"] >= 0.25
        ),
    ],
    [
        "high",
        "medium",
        "medium",
    ],
    default="low",
)

step6_63_daily_plan_df["recommendation_confidence"] = (
    step6_63_daily_plan_df["recommendation_confidence"].astype("category")
)

step6_63_daily_plan_df["decision_reason"] = np.select(
    [
        (
            (step6_63_daily_plan_df["priority_level"].astype("string") == "very_high")
            & (step6_63_daily_plan_df["recommended_action"].astype("string") == "deliver_bikes")
        ),
        (
            (step6_63_daily_plan_df["priority_level"].astype("string").isin(["high", "medium"]))
            & (step6_63_daily_plan_df["recommended_action"].astype("string") == "deliver_bikes")
        ),
        (
            step6_63_daily_plan_df["recommended_action"].astype("string") == "check_station_state"
        ),
    ],
    [
        "high_impact_bike_shortage_risk",
        "bike_shortage_risk_with_operational_impact",
        "mixed_signal_requires_station_check",
    ],
    default="low_priority_operational_signal",
)

step6_63_daily_plan_df["decision_reason"] = (
    step6_63_daily_plan_df["decision_reason"].astype("string")
)

step6_63_daily_plan_df = (
    step6_63_daily_plan_df
    .sort_values(
        [
            "activity_date",
            "expected_business_impact",
            "priority_score",
            "estimated_relocation_units",
            "highest_risk_hour_score",
            "representative_station_id",
        ],
        ascending=[True, False, False, False, False, True],
    )
    .reset_index(drop=True)
)

step6_63_daily_plan_df["daily_plan_rank"] = (
    step6_63_daily_plan_df
    .groupby("activity_date", observed=True)
    .cumcount()
    .add(1)
    .astype("int32")
)

step6_63_top_daily_plan_df = (
    step6_63_daily_plan_df.loc[
        step6_63_daily_plan_df["daily_plan_rank"] <= 50,
        [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "priority_level",
            "problem_type",
            "recommended_action",
            "highest_risk_hour_label",
            "estimated_relocation_label",
            "recommendation_confidence",
            "decision_reason",
            "expected_business_impact",
            "priority_score",
            "station_business_scale",
            "estimated_relocation_units",
        ],
    ]
    .copy()
)

step6_63_duplicate_rank_count = int(
    step6_63_daily_plan_df.duplicated(
        subset=["activity_date", "daily_plan_rank"]
    ).sum()
)

step6_63_duplicate_key_count = int(
    step6_63_daily_plan_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_63_missing_rank_count = int(
    step6_63_daily_plan_df["daily_plan_rank"].isna().sum()
)

step6_63_missing_confidence_count = int(
    step6_63_daily_plan_df["recommendation_confidence"].isna().sum()
)

step6_63_missing_reason_count = int(
    step6_63_daily_plan_df["decision_reason"].isna().sum()
)

step6_63_plan_profile_df = pd.DataFrame(
    [
        {
            "check_area": "daily_plan_rows",
            "status": "ok",
            "value": str(step6_63_daily_plan_df.shape[0]),
        },
        {
            "check_area": "daily_plan_columns",
            "status": "ok",
            "value": str(step6_63_daily_plan_df.shape[1]),
        },
        {
            "check_area": "duplicate_day_station_keys",
            "status": "ok" if step6_63_duplicate_key_count == 0 else "review",
            "value": str(step6_63_duplicate_key_count),
        },
        {
            "check_area": "duplicate_daily_rank_keys",
            "status": "ok" if step6_63_duplicate_rank_count == 0 else "review",
            "value": str(step6_63_duplicate_rank_count),
        },
        {
            "check_area": "missing_daily_plan_rank",
            "status": "ok" if step6_63_missing_rank_count == 0 else "review",
            "value": str(step6_63_missing_rank_count),
        },
        {
            "check_area": "missing_recommendation_confidence",
            "status": "ok" if step6_63_missing_confidence_count == 0 else "review",
            "value": str(step6_63_missing_confidence_count),
        },
        {
            "check_area": "missing_decision_reason",
            "status": "ok" if step6_63_missing_reason_count == 0 else "review",
            "value": str(step6_63_missing_reason_count),
        },
    ]
)

step6_63_confidence_summary_df = (
    step6_63_daily_plan_df
    .groupby(["priority_level", "recommendation_confidence"], observed=True)
    .agg(
        row_count=("recommendation_confidence", "size"),
        mean_expected_business_impact=("expected_business_impact", "mean"),
        mean_priority_score=("priority_score", "mean"),
        mean_estimated_relocation_units=("estimated_relocation_units", "mean"),
    )
    .reset_index()
)

step6_63_confidence_summary_df["row_share"] = (
    step6_63_confidence_summary_df["row_count"]
    / step6_63_confidence_summary_df["row_count"].sum()
)

step6_63_reason_summary_df = (
    step6_63_daily_plan_df["decision_reason"]
    .value_counts(dropna=False)
    .rename_axis("decision_reason")
    .reset_index(name="row_count")
)

step6_63_reason_summary_df["row_share"] = (
    step6_63_reason_summary_df["row_count"]
    / step6_63_reason_summary_df["row_count"].sum()
)

step6_63_plan_profile_path = step6_11_reports_dir / "b6_29_daily_plan_profile.parquet"
step6_63_top_daily_plan_path = step6_11_reports_dir / "b6_29_top_daily_plan_preview.parquet"
step6_63_confidence_summary_path = step6_11_reports_dir / "b6_29_confidence_summary.parquet"
step6_63_reason_summary_path = step6_11_reports_dir / "b6_29_decision_reason_summary.parquet"

step6_63_plan_profile_df.to_parquet(step6_63_plan_profile_path, index=False)
step6_63_top_daily_plan_df.to_parquet(step6_63_top_daily_plan_path, index=False)
step6_63_confidence_summary_df.to_parquet(step6_63_confidence_summary_path, index=False)
step6_63_reason_summary_df.to_parquet(step6_63_reason_summary_path, index=False)

display(step6_63_plan_profile_df)
display(step6_63_confidence_summary_df)
display(step6_63_reason_summary_df)
display(step6_63_top_daily_plan_df.head(20))

                          check_area status   value
0                    daily_plan_rows     ok  219071
1                 daily_plan_columns     ok      42
2         duplicate_day_station_keys     ok       0
3          duplicate_daily_rank_keys     ok       0
4            missing_daily_plan_rank     ok       0
5  missing_recommendation_confidence     ok       0
6            missing_decision_reason     ok       0

,priority_level,recommendation_confidence,row_count,mean_expected_business_impact,mean_priority_score,mean_estimated_relocation_units,row_share
0,high,high,13129,77.329910,823.536133,4.504151,0.059930
1,high,low,1893,77.915764,812.249512,3.001585,0.008641
2,high,medium,17838,78.260521,822.017639,3.338098,0.081426
3,low,high,53275,15.896479,201.102432,2.567959,0.243186
4,low,low,16827,11.998341,142.961777,1.281750,0.076811
5,low,medium,39433,16.743956,198.892090,1.888469,0.180001
6,medium,high,23971,41.642193,462.023895,3.495223,0.109421
7,medium,low,4567,43.316605,462.530060,2.303481,0.020847
8,medium,medium,26230,43.786343,473.949829,2.731948,0.119733
9,very_high,high,9496,155.878036,1615.483521,5.713353,0.043347
10,very_high,low,645,142.038605,1456.384277,3.536434,0.002944
11,very_high,medium,11767,155.566345,1598.709595,3.903289,0.053713

                              decision_reason  row_count  row_share
0             low_priority_operational_signal     107379   0.490156
1  bike_shortage_risk_with_operational_impact      84452   0.385501
2              high_impact_bike_shortage_risk      20159    0.09202
3         mixed_signal_requires_station_check       7081   0.032323

,activity_date,daily_plan_rank,representative_station_id,station_name,priority_level,problem_type,recommended_action,highest_risk_hour_label,estimated_relocation_label,recommendation_confidence,decision_reason,expected_business_impact,priority_score,station_business_scale,estimated_relocation_units
0,2017-05-02,1,30,Itämerentori,very_high,bike_shortage_risk,deliver_bikes,17:00,deliver 18-20,high,high_impact_bike_shortage_risk,128.742188,1411.951904,205.987503,19
1,2017-05-02,2,26,Kamppi (M),very_high,bike_shortage_risk,deliver_bikes,16:00,deliver 9-11,high,high_impact_bike_shortage_risk,124.333328,1327.043213,149.199997,10
2,2017-05-02,3,21,Töölönlahdenkatu,very_high,bike_shortage_risk,deliver_bikes,19:00,deliver 11-13,high,high_impact_bike_shortage_risk,111.562500,1209.984985,127.500000,12
3,2017-05-02,4,25,Narinkka,very_high,bike_shortage_risk,deliver_bikes,18:00,deliver 7-9,high,high_impact_bike_shortage_risk,103.812500,1114.135010,113.250000,8
4,2017-05-02,5,40,Hakaniemi (M),high,bike_shortage_risk,deliver_bikes,17:00,deliver 6-8,high,bike_shortage_risk_with_operational_impact,91.218750,980.877502,109.462502,7
5,2017-05-02,6,17,Varsapuistikko,high,bike_shortage_risk,deliver_bikes,17:00,deliver 9-11,high,bike_shortage_risk_with_operational_impact,77.145828,858.708252,80.500000,10
6,2017-05-02,7,41,Ympyrätalo,high,bike_shortage_risk,deliver_bikes,13:00,deliver 8-10,high,bike_shortage_risk_with_operational_impact,75.312500,826.744995,120.500000,9
7,2017-05-02,8,9,Erottajan aukio,high,bike_shortage_risk,deliver_bikes,16:00,deliver 13-15,high,bike_shortage_risk_with_operational_impact,73.021355,833.073547,92.237503,14
8,2017-05-02,9,44,Sörnäinen (M),high,bike_shortage_risk,deliver_bikes,19:00,deliver 7-9,high,bike_shortage_risk_with_operational_impact,72.021873,792.518738,90.974998,8
9,2017-05-02,10,22,Rautatientori / länsi,high,bike_shortage_risk,deliver_bikes,15:00,deliver 8-10,high,bike_shortage_risk_with_operational_impact,71.437500,792.755005,85.724998,9
10,2017-05-02,11,5,Sepänkatu,high,bike_shortage_risk,deliver_bikes,11:00,deliver 6-8,high,bike_shortage_risk_with_operational_impact,71.158340,776.073364,106.737503,7
11,2017-05-02,12,11,Unioninkatu,high,bike_shortage_risk,deliver_bikes,16:00,deliver 19-21,high,bike_shortage_risk_with_operational_impact,69.125000,825.750000,79.000000,20
12,2017-05-02,13,23,Kiasma,high,bike_shortage_risk,deliver_bikes,20:00,deliver 8-10,high,bike_shortage_risk_with_operational_impact,66.458336,745.103394,72.500000,9
13,2017-05-02,14,29,Baana,high,bike_shortage_risk,deliver_bikes,12:00,deliver 6-8,high,bike_shortage_risk_with_operational_impact,66.178131,728.221313,88.237503,7
14,2017-05-02,15,6,Hietalahdentori,high,bike_shortage_risk,deliver_bikes,16:00,deliver 3-5,high,bike_shortage_risk_with_operational_impact,65.770828,705.928223,112.750000,4
15,2017-05-02,16,19,Rautatientori / itä,high,bike_shortage_risk,deliver_bikes,21:00,deliver 6-8,high,bike_shortage_risk_with_operational_impact,62.387497,686.275024,106.949997,7
16,2017-05-02,17,14,Senaatintori,high,bike_shortage_risk,deliver_bikes,17:00,deliver 9-11,high,bike_shortage_risk_with_operational_impact,58.446354,671.083557,60.987499,10
17,2017-05-02,18,150,Töölönlahden puisto,high,bike_shortage_risk,deliver_bikes,21:00,deliver 5-7,high,bike_shortage_risk_with_operational_impact,57.928127,640.661255,77.237503,6
18,2017-05-02,19,20,Kaisaniemenpuisto,medium,bike_shortage_risk,deliver_bikes,20:00,deliver 5-7,high,bike_shortage_risk_with_operational_impact,57.409901,630.499023,105.987503,6
19,2017-05-02,20,112,Rautatieläisenkatu,medium,bike_shortage_risk,deliver_bikes,17:00,deliver 4-6,high,bike_shortage_risk_with_operational_impact,55.987499,622.395020,55.987499,5

In [30]:
# 6.6.4 Kontrola spójności planu dnia dyspozytora

import json

import pandas as pd


step6_64_required_objects = [
    "step6_63_daily_plan_df",
    "step6_11_reports_dir",
]

step6_64_missing_objects = [
    object_name
    for object_name in step6_64_required_objects
    if object_name not in globals()
]

assert not step6_64_missing_objects, f"Missing required objects: {step6_64_missing_objects}"

step6_64_duplicate_key_count = int(
    step6_63_daily_plan_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_64_duplicate_rank_count = int(
    step6_63_daily_plan_df.duplicated(
        subset=["activity_date", "daily_plan_rank"]
    ).sum()
)

step6_64_missing_priority_count = int(
    step6_63_daily_plan_df["priority_level"].isna().sum()
)

step6_64_missing_impact_count = int(
    step6_63_daily_plan_df["expected_business_impact"].isna().sum()
)

step6_64_missing_confidence_count = int(
    step6_63_daily_plan_df["recommendation_confidence"].isna().sum()
)

step6_64_missing_reason_count = int(
    step6_63_daily_plan_df["decision_reason"].isna().sum()
)

step6_64_negative_impact_count = int(
    (step6_63_daily_plan_df["expected_business_impact"] < 0).sum()
)

step6_64_rank_min_check = (
    step6_63_daily_plan_df
    .groupby("activity_date", observed=True)["daily_plan_rank"]
    .min()
    .eq(1)
    .all()
)

step6_64_rank_count_check = (
    step6_63_daily_plan_df
    .groupby("activity_date", observed=True)
    .agg(
        row_count=("daily_plan_rank", "size"),
        max_rank=("daily_plan_rank", "max"),
    )
    .assign(rank_matches_rows=lambda df: df["row_count"] == df["max_rank"])
)

step6_64_rank_gap_count = int(
    (~step6_64_rank_count_check["rank_matches_rows"]).sum()
)

step6_64_top_rank_order_check_df = (
    step6_63_daily_plan_df.loc[
        step6_63_daily_plan_df["daily_plan_rank"] <= 20,
        [
            "activity_date",
            "daily_plan_rank",
            "expected_business_impact",
            "priority_score",
            "estimated_relocation_units",
            "highest_risk_hour_score",
        ],
    ]
    .sort_values(["activity_date", "daily_plan_rank"])
    .copy()
)

step6_64_top_rank_order_check_df["previous_expected_business_impact"] = (
    step6_64_top_rank_order_check_df
    .groupby("activity_date", observed=True)["expected_business_impact"]
    .shift(1)
)

step6_64_top_rank_order_check_df["impact_order_check"] = (
    step6_64_top_rank_order_check_df["previous_expected_business_impact"].isna()
    | (
        step6_64_top_rank_order_check_df["previous_expected_business_impact"]
        >= step6_64_top_rank_order_check_df["expected_business_impact"]
    )
)

step6_64_top_rank_order_review_count = int(
    (~step6_64_top_rank_order_check_df["impact_order_check"]).sum()
)

step6_64_consistency_rules = [
    {
        "rule_name": "no_duplicate_day_station_keys",
        "condition_passed": step6_64_duplicate_key_count == 0,
        "value": str(step6_64_duplicate_key_count),
    },
    {
        "rule_name": "no_duplicate_daily_rank_keys",
        "condition_passed": step6_64_duplicate_rank_count == 0,
        "value": str(step6_64_duplicate_rank_count),
    },
    {
        "rule_name": "no_missing_priority_level",
        "condition_passed": step6_64_missing_priority_count == 0,
        "value": str(step6_64_missing_priority_count),
    },
    {
        "rule_name": "no_missing_expected_business_impact",
        "condition_passed": step6_64_missing_impact_count == 0,
        "value": str(step6_64_missing_impact_count),
    },
    {
        "rule_name": "no_missing_recommendation_confidence",
        "condition_passed": step6_64_missing_confidence_count == 0,
        "value": str(step6_64_missing_confidence_count),
    },
    {
        "rule_name": "no_missing_decision_reason",
        "condition_passed": step6_64_missing_reason_count == 0,
        "value": str(step6_64_missing_reason_count),
    },
    {
        "rule_name": "expected_business_impact_is_non_negative",
        "condition_passed": step6_64_negative_impact_count == 0,
        "value": str(step6_64_negative_impact_count),
    },
    {
        "rule_name": "daily_rank_starts_at_one",
        "condition_passed": bool(step6_64_rank_min_check),
        "value": str(bool(step6_64_rank_min_check)),
    },
    {
        "rule_name": "daily_rank_has_no_gaps",
        "condition_passed": step6_64_rank_gap_count == 0,
        "value": str(step6_64_rank_gap_count),
    },
    {
        "rule_name": "top_rank_sorted_by_expected_business_impact",
        "condition_passed": step6_64_top_rank_order_review_count == 0,
        "value": str(step6_64_top_rank_order_review_count),
    },
]

step6_64_consistency_df = pd.DataFrame(step6_64_consistency_rules)

step6_64_consistency_df["status"] = step6_64_consistency_df["condition_passed"].map(
    {
        True: "ok",
        False: "review",
    }
)

step6_64_review_count = int(
    (step6_64_consistency_df["status"] == "review").sum()
)

step6_64_daily_top_summary_df = (
    step6_63_daily_plan_df.loc[step6_63_daily_plan_df["daily_plan_rank"] <= 20]
    .groupby("activity_date", observed=True)
    .agg(
        top_rows=("daily_plan_rank", "size"),
        top_mean_expected_business_impact=("expected_business_impact", "mean"),
        top_max_expected_business_impact=("expected_business_impact", "max"),
        top_mean_priority_score=("priority_score", "mean"),
        top_total_estimated_relocation_units=("estimated_relocation_units", "sum"),
    )
    .reset_index()
)

step6_64_priority_rank_summary_df = (
    step6_63_daily_plan_df
    .groupby("priority_level", observed=True)
    .agg(
        row_count=("priority_level", "size"),
        mean_daily_plan_rank=("daily_plan_rank", "mean"),
        median_daily_plan_rank=("daily_plan_rank", "median"),
        min_daily_plan_rank=("daily_plan_rank", "min"),
        max_daily_plan_rank=("daily_plan_rank", "max"),
        mean_expected_business_impact=("expected_business_impact", "mean"),
        mean_priority_score=("priority_score", "mean"),
    )
    .reset_index()
)

step6_64_contract = {
    "block_name": "block_6",
    "section_name": "6.6",
    "contract_scope": "daily_plan_consistency",
    "grain": "day_station",
    "key_columns": [
        "activity_date",
        "representative_station_id",
    ],
    "rank_column": "daily_plan_rank",
    "primary_sort_column": "expected_business_impact",
    "review_count": step6_64_review_count,
    "observed_priority_levels": sorted(
        step6_63_daily_plan_df["priority_level"]
        .astype("string")
        .unique()
        .tolist()
    ),
    "observed_confidence_levels": sorted(
        step6_63_daily_plan_df["recommendation_confidence"]
        .astype("string")
        .unique()
        .tolist()
    ),
}

step6_64_consistency_path = step6_11_reports_dir / "b6_30_daily_plan_consistency.parquet"
step6_64_daily_top_summary_path = step6_11_reports_dir / "b6_30_daily_top_plan_summary.parquet"
step6_64_priority_rank_summary_path = step6_11_reports_dir / "b6_30_priority_rank_summary.parquet"
step6_64_contract_path = step6_11_reports_dir / "b6_30_daily_plan_consistency_contract.json"

step6_64_consistency_df.to_parquet(step6_64_consistency_path, index=False)
step6_64_daily_top_summary_df.to_parquet(step6_64_daily_top_summary_path, index=False)
step6_64_priority_rank_summary_df.to_parquet(step6_64_priority_rank_summary_path, index=False)

with open(step6_64_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_64_contract, file, ensure_ascii=False, indent=2)

step6_64_summary_df = pd.DataFrame(
    [
        {
            "check_area": "consistency_rules",
            "status": "ok",
            "value": str(step6_64_consistency_df.shape[0]),
        },
        {
            "check_area": "consistency_review_count",
            "status": "ok" if step6_64_review_count == 0 else "review",
            "value": str(step6_64_review_count),
        },
        {
            "check_area": "daily_plan_dates",
            "status": "ok",
            "value": str(step6_63_daily_plan_df["activity_date"].nunique()),
        },
        {
            "check_area": "priority_levels",
            "status": "ok",
            "value": str(step6_63_daily_plan_df["priority_level"].nunique()),
        },
        {
            "check_area": "consistency_path",
            "status": "ok",
            "value": str(step6_64_consistency_path),
        },
        {
            "check_area": "daily_top_summary_path",
            "status": "ok",
            "value": str(step6_64_daily_top_summary_path),
        },
        {
            "check_area": "priority_rank_summary_path",
            "status": "ok",
            "value": str(step6_64_priority_rank_summary_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_64_contract_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_64_summary_df[column_name] = step6_64_summary_df[column_name].astype("string")

display(step6_64_summary_df)
display(step6_64_consistency_df)
display(step6_64_priority_rank_summary_df)
display(step6_64_daily_top_summary_df.head(10))

,check_area,status,value
0,consistency_rules,ok,10
1,consistency_review_count,ok,0
2,daily_plan_dates,ok,839
3,priority_levels,ok,4
4,consistency_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,daily_top_summary_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,priority_rank_summary_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                                     rule_name  condition_passed value status
0                no_duplicate_day_station_keys              True     0     ok
1                 no_duplicate_daily_rank_keys              True     0     ok
2                    no_missing_priority_level              True     0     ok
3          no_missing_expected_business_impact              True     0     ok
4         no_missing_recommendation_confidence              True     0     ok
5                   no_missing_decision_reason              True     0     ok
6     expected_business_impact_is_non_negative              True     0     ok
7                     daily_rank_starts_at_one              True  True     ok
8                       daily_rank_has_no_gaps              True     0     ok
9  top_rank_sorted_by_expected_business_impact              True     0     ok

,priority_level,row_count,mean_daily_plan_rank,median_daily_plan_rank,min_daily_plan_rank,max_daily_plan_rank,mean_expected_business_impact,mean_priority_score
0,high,32860,57.451917,56.0,1,156,77.868835,822.061646
1,low,109535,214.741115,217.0,1,344,15.602734,191.375015
2,medium,54768,108.469489,107.0,1,252,42.808716,467.777802
3,very_high,21908,22.622193,18.0,1,96,155.303162,1601.790039

,activity_date,top_rows,top_mean_expected_business_impact,top_max_expected_business_impact,top_mean_priority_score,top_total_estimated_relocation_units
0,2017-05-02,20,77.972916,128.742188,858.989136,187
1,2017-05-03,20,97.103439,241.493744,1027.540894,117
2,2017-05-04,20,96.158546,140.250000,1014.455933,107
3,2017-05-05,20,105.022812,262.494781,1101.501221,102
4,2017-05-06,20,96.360367,175.312500,1010.446655,86
5,2017-05-07,20,73.572578,112.618752,785.703735,100
6,2017-05-08,20,93.481537,119.893227,986.790833,108
7,2017-05-09,20,87.022530,176.521881,923.175781,108
8,2017-05-10,20,84.748230,152.350006,897.103821,95
9,2017-05-11,20,96.497917,223.562500,1015.421692,100

In [31]:
# 6.6.5 Zamknięcie kontraktu priorytetyzacji stacji

import json

import pandas as pd


step6_65_required_objects = [
    "step6_61_priority_contract",
    "step6_63_daily_plan_df",
    "step6_64_consistency_df",
    "step6_64_daily_top_summary_df",
    "step6_64_priority_rank_summary_df",
    "step6_11_reports_dir",
    "step6_11_outputs_dir",
]

step6_65_missing_objects = [
    object_name
    for object_name in step6_65_required_objects
    if object_name not in globals()
]

assert not step6_65_missing_objects, f"Missing required objects: {step6_65_missing_objects}"

step6_65_output_columns = [
    "activity_date",
    "daily_plan_rank",
    "representative_station_id",
    "station_name",
    "priority_level",
    "problem_type",
    "recommended_action",
    "highest_risk_hour_label",
    "estimated_relocation_label",
    "recommendation_confidence",
    "decision_reason",
    "expected_business_impact",
    "priority_score",
    "station_business_scale",
    "estimated_capacity",
    "departure_signal_hours",
    "return_signal_hours",
    "problem_direction_score",
    "problem_direction_share_of_day",
    "dominant_signal_side",
    "highest_risk_hour",
    "highest_risk_hour_score",
    "estimated_relocation_units",
    "estimated_relocation_min",
    "estimated_relocation_max",
    "relocation_direction",
    "relocation_sanity_limit",
    "total_departures",
    "total_returns",
    "daily_net_flow",
]

step6_65_available_columns = step6_63_daily_plan_df.columns.tolist()

step6_65_missing_output_columns = [
    column_name
    for column_name in step6_65_output_columns
    if column_name not in step6_65_available_columns
]

assert not step6_65_missing_output_columns, f"Missing output columns: {step6_65_missing_output_columns}"

step6_65_review_count = int(
    (step6_64_consistency_df["status"] == "review").sum()
)

step6_65_duplicate_key_count = int(
    step6_63_daily_plan_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_65_duplicate_rank_count = int(
    step6_63_daily_plan_df.duplicated(
        subset=["activity_date", "daily_plan_rank"]
    ).sum()
)

step6_65_missing_priority_count = int(
    step6_63_daily_plan_df["priority_level"].isna().sum()
)

step6_65_missing_impact_count = int(
    step6_63_daily_plan_df["expected_business_impact"].isna().sum()
)

step6_65_missing_confidence_count = int(
    step6_63_daily_plan_df["recommendation_confidence"].isna().sum()
)

step6_65_missing_reason_count = int(
    step6_63_daily_plan_df["decision_reason"].isna().sum()
)

assert step6_65_review_count == 0, "Daily plan consistency review detected."
assert step6_65_duplicate_key_count == 0, "Duplicated day-station keys detected."
assert step6_65_duplicate_rank_count == 0, "Duplicated daily rank keys detected."
assert step6_65_missing_priority_count == 0, "Missing priority_level values detected."
assert step6_65_missing_impact_count == 0, "Missing expected_business_impact values detected."
assert step6_65_missing_confidence_count == 0, "Missing recommendation_confidence values detected."
assert step6_65_missing_reason_count == 0, "Missing decision_reason values detected."

step6_65_daily_plan_output_df = (
    step6_63_daily_plan_df[step6_65_output_columns]
    .sort_values(
        [
            "activity_date",
            "daily_plan_rank",
        ],
        ascending=[True, True],
    )
    .reset_index(drop=True)
)

step6_65_observed_priority_levels = sorted(
    step6_65_daily_plan_output_df["priority_level"]
    .astype("string")
    .unique()
    .tolist()
)

step6_65_observed_confidence_levels = sorted(
    step6_65_daily_plan_output_df["recommendation_confidence"]
    .astype("string")
    .unique()
    .tolist()
)

step6_65_observed_recommended_actions = sorted(
    step6_65_daily_plan_output_df["recommended_action"]
    .astype("string")
    .unique()
    .tolist()
)

step6_65_output_path = step6_11_outputs_dir / "b6_31_dispatcher_daily_plan.parquet"
step6_65_output_profile_path = step6_11_reports_dir / "b6_31_dispatcher_daily_plan_output_profile.parquet"
step6_65_section_contract_path = step6_11_reports_dir / "b6_31_dispatcher_daily_plan_section_contract.json"
step6_65_section_status_path = step6_11_reports_dir / "b6_31_dispatcher_daily_plan_section_status.parquet"

step6_65_daily_plan_output_df.to_parquet(step6_65_output_path, index=False)

step6_65_output_profile_df = pd.DataFrame(
    [
        {
            "profile_area": "output_rows",
            "status": "ok",
            "value": str(step6_65_daily_plan_output_df.shape[0]),
        },
        {
            "profile_area": "output_columns",
            "status": "ok",
            "value": str(step6_65_daily_plan_output_df.shape[1]),
        },
        {
            "profile_area": "unique_dates",
            "status": "ok",
            "value": str(step6_65_daily_plan_output_df["activity_date"].nunique()),
        },
        {
            "profile_area": "unique_stations",
            "status": "ok",
            "value": str(step6_65_daily_plan_output_df["representative_station_id"].nunique()),
        },
        {
            "profile_area": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_65_duplicate_key_count),
        },
        {
            "profile_area": "duplicate_daily_rank_keys",
            "status": "ok",
            "value": str(step6_65_duplicate_rank_count),
        },
        {
            "profile_area": "observed_priority_levels",
            "status": "ok",
            "value": json.dumps(step6_65_observed_priority_levels, ensure_ascii=False),
        },
        {
            "profile_area": "observed_confidence_levels",
            "status": "ok",
            "value": json.dumps(step6_65_observed_confidence_levels, ensure_ascii=False),
        },
        {
            "profile_area": "observed_recommended_actions",
            "status": "ok",
            "value": json.dumps(step6_65_observed_recommended_actions, ensure_ascii=False),
        },
    ]
)

step6_65_output_profile_df.to_parquet(step6_65_output_profile_path, index=False)

step6_65_section_contract = {
    "block_name": "block_6",
    "section_name": "6.6",
    "section_scope": "station_priority_and_daily_plan_layer",
    "source_grain": "day_station",
    "output_grain": "day_station",
    "source_object": "step6_63_daily_plan_df",
    "output_object": "step6_65_daily_plan_output_df",
    "output_path": str(step6_65_output_path),
    "key_columns": [
        "activity_date",
        "representative_station_id",
    ],
    "rank_column": "daily_plan_rank",
    "main_output_fields": step6_61_priority_contract["main_output_fields"],
    "expected_business_impact_policy": step6_61_priority_contract["expected_business_impact_policy"],
    "sorting_policy": step6_61_priority_contract["sorting_policy"],
    "main_screen_policy": step6_61_priority_contract["main_screen_policy"],
    "observed_priority_levels": step6_65_observed_priority_levels,
    "observed_confidence_levels": step6_65_observed_confidence_levels,
    "observed_recommended_actions": step6_65_observed_recommended_actions,
    "output_row_count": int(step6_65_daily_plan_output_df.shape[0]),
    "output_column_count": int(step6_65_daily_plan_output_df.shape[1]),
    "unique_date_count": int(step6_65_daily_plan_output_df["activity_date"].nunique()),
    "unique_station_count": int(step6_65_daily_plan_output_df["representative_station_id"].nunique()),
    "duplicate_key_count": step6_65_duplicate_key_count,
    "duplicate_rank_count": step6_65_duplicate_rank_count,
    "consistency_review_count": step6_65_review_count,
}

with open(step6_65_section_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_65_section_contract, file, ensure_ascii=False, indent=2)

step6_65_section_status_df = pd.DataFrame(
    [
        {
            "section_item": "section_6_6_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "section_item": "output_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "section_item": "output_rows",
            "status": "ok",
            "value": str(step6_65_daily_plan_output_df.shape[0]),
        },
        {
            "section_item": "output_columns",
            "status": "ok",
            "value": str(step6_65_daily_plan_output_df.shape[1]),
        },
        {
            "section_item": "unique_dates",
            "status": "ok",
            "value": str(step6_65_daily_plan_output_df["activity_date"].nunique()),
        },
        {
            "section_item": "observed_priority_levels",
            "status": "ok",
            "value": json.dumps(step6_65_observed_priority_levels, ensure_ascii=False),
        },
        {
            "section_item": "consistency_review_count",
            "status": "ok",
            "value": str(step6_65_review_count),
        },
    ]
)

step6_65_section_status_df.to_parquet(step6_65_section_status_path, index=False)

step6_65_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_6_6_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "check_area": "daily_plan_rows",
            "status": "ok",
            "value": str(step6_65_daily_plan_output_df.shape[0]),
        },
        {
            "check_area": "daily_plan_columns",
            "status": "ok",
            "value": str(step6_65_daily_plan_output_df.shape[1]),
        },
        {
            "check_area": "output_path",
            "status": "ok",
            "value": str(step6_65_output_path),
        },
        {
            "check_area": "profile_path",
            "status": "ok",
            "value": str(step6_65_output_profile_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_65_section_contract_path),
        },
        {
            "check_area": "status_path",
            "status": "ok",
            "value": str(step6_65_section_status_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_65_summary_df[column_name] = step6_65_summary_df[column_name].astype("string")

display(step6_65_summary_df)
display(step6_65_section_status_df)
display(step6_65_output_profile_df)
display(step6_65_daily_plan_output_df.head(20))

,check_area,status,value
0,section_6_6_status,ok,closed
1,daily_plan_rows,ok,219071
2,daily_plan_columns,ok,30
3,output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,profile_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,status_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

               section_item status                                   value
0        section_6_6_status     ok                                  closed
1              output_grain     ok                             day_station
2               output_rows     ok                                  219071
3            output_columns     ok                                      30
4              unique_dates     ok                                     839
5  observed_priority_levels     ok  ["high", "low", "medium", "very_high"]
6  consistency_review_count     ok                                       0

,profile_area,status,value
0,output_rows,ok,219071
1,output_columns,ok,30
2,unique_dates,ok,839
3,unique_stations,ok,344
4,duplicate_day_station_keys,ok,0
5,duplicate_daily_rank_keys,ok,0
6,observed_priority_levels,ok,"[""high"", ""low"", ""medium"", ""very_high""]"
7,observed_confidence_levels,ok,"[""high"", ""low"", ""medium""]"
8,observed_recommended_actions,ok,"[""check_station_state"", ""deliver_bikes""]"

,activity_date,daily_plan_rank,representative_station_id,station_name,priority_level,problem_type,recommended_action,highest_risk_hour_label,estimated_relocation_label,recommendation_confidence,...,highest_risk_hour,highest_risk_hour_score,estimated_relocation_units,estimated_relocation_min,estimated_relocation_max,relocation_direction,relocation_sanity_limit,total_departures,total_returns,daily_net_flow
0,2017-05-02,1,30,Itämerentori,very_high,bike_shortage_risk,deliver_bikes,17:00,deliver 18-20,high,...,17,1453.0,19,18,20,deliver,59,91,57,-34
1,2017-05-02,2,26,Kamppi (M),very_high,bike_shortage_risk,deliver_bikes,16:00,deliver 9-11,high,...,16,1371.0,10,9,11,deliver,24,71,55,-16
2,2017-05-02,3,21,Töölönlahdenkatu,very_high,bike_shortage_risk,deliver_bikes,19:00,deliver 11-13,high,...,19,1336.0,12,11,13,deliver,27,57,51,-6
3,2017-05-02,4,25,Narinkka,very_high,bike_shortage_risk,deliver_bikes,18:00,deliver 7-9,high,...,18,1401.0,8,7,9,deliver,16,55,36,-19
4,2017-05-02,5,40,Hakaniemi (M),high,bike_shortage_risk,deliver_bikes,17:00,deliver 6-8,high,...,17,1369.0,7,6,8,deliver,16,53,34,-19
5,2017-05-02,6,17,Varsapuistikko,high,bike_shortage_risk,deliver_bikes,17:00,deliver 9-11,high,...,17,1425.0,10,9,11,deliver,20,34,18,-16
6,2017-05-02,7,41,Ympyrätalo,high,bike_shortage_risk,deliver_bikes,13:00,deliver 8-10,high,...,13,1362.0,9,8,10,deliver,27,47,49,2
7,2017-05-02,8,9,Erottajan aukio,high,bike_shortage_risk,deliver_bikes,16:00,deliver 13-15,high,...,16,1386.0,14,13,15,deliver,35,38,22,-16
8,2017-05-02,9,44,Sörnäinen (M),high,bike_shortage_risk,deliver_bikes,19:00,deliver 7-9,high,...,19,1330.0,8,7,9,deliver,18,39,40,1
9,2017-05-02,10,22,Rautatientori / länsi,high,bike_shortage_risk,deliver_bikes,15:00,deliver 8-10,high,...,15,1338.0,9,8,10,deliver,20,39,30,-9
10,2017-05-02,11,5,Sepänkatu,high,bike_shortage_risk,deliver_bikes,11:00,deliver 6-8,high,...,11,1349.0,7,6,8,deliver,19,51,38,-13
11,2017-05-02,12,11,Unioninkatu,high,bike_shortage_risk,deliver_bikes,16:00,deliver 19-21,high,...,16,1350.0,20,19,21,deliver,44,29,19,-10
12,2017-05-02,13,23,Kiasma,high,bike_shortage_risk,deliver_bikes,20:00,deliver 8-10,high,...,20,1352.0,9,8,10,deliver,19,33,20,-13
13,2017-05-02,14,29,Baana,high,bike_shortage_risk,deliver_bikes,12:00,deliver 6-8,high,...,12,1344.0,7,6,8,deliver,19,39,34,-5
14,2017-05-02,15,6,Hietalahdentori,high,bike_shortage_risk,deliver_bikes,16:00,deliver 3-5,high,...,16,1422.0,4,3,5,deliver,14,49,40,-9
15,2017-05-02,16,19,Rautatientori / itä,high,bike_shortage_risk,deliver_bikes,21:00,deliver 6-8,high,...,21,1340.0,7,6,8,deliver,22,45,47,2
16,2017-05-02,17,14,Senaatintori,high,bike_shortage_risk,deliver_bikes,17:00,deliver 9-11,high,...,17,1362.0,10,9,11,deliver,20,28,12,-16
17,2017-05-02,18,150,Töölönlahden puisto,high,bike_shortage_risk,deliver_bikes,21:00,deliver 5-7,high,...,21,1338.0,6,5,7,deliver,15,36,27,-9
18,2017-05-02,19,20,Kaisaniemenpuisto,medium,bike_shortage_risk,deliver_bikes,20:00,deliver 5-7,high,...,20,1340.0,6,5,7,deliver,22,46,45,-1
19,2017-05-02,20,112,Rautatieläisenkatu,medium,bike_shortage_risk,deliver_bikes,17:00,deliver 4-6,high,...,17,1352.0,5,4,6,deliver,10,27,14,-13

## Podsumowanie działu 6.6 Priorytetyzacja stacji i plan dnia

**Kontekst inżynieryjny:** W dziale `6.6` zbudowano warstwę priorytetyzacji stacji oraz dzienny plan działań dyspozytora na podstawie finalnej warstwy szacowanej relokacji z działu `6.5`. Źródłem wejściowym była tabela `step6_54_estimated_relocation_output_df`, działająca na poziomie `day_station`, zawierająca już typ problemu, rekomendację operacyjną, godzinę największego ryzyka oraz szacowany zakres relokacji. Najpierw zdefiniowano kontrakt priorytetyzacji, obejmujący pola `priority_level`, `priority_score`, `expected_business_impact`, `station_business_scale`, `recommendation_confidence`, `decision_reason` oraz `daily_plan_rank`. Następnie zbudowano wskaźnik `station_business_scale`, wskaźnik `expected_business_impact` oraz techniczny `priority_score`. Ranking został oparty przede wszystkim na `expected_business_impact`, czyli na oczekiwanym wpływie operacyjnym problemu, a nie wyłącznie na samej obecności lub sile alertu. W kolejnym kroku przypisano poziomy priorytetu, poziomy pewności rekomendacji, krótkie uzasadnienia decyzji oraz pozycję stacji w dziennym planie działań. Na końcu przeprowadzono kontrolę spójności rankingu i zapisano finalny artefakt planu dnia.

**Interpretacja wyniku:** Finalny plan dnia został zbudowany dla `219 071` rekordów dzień–stacja, obejmuje `839` dni oraz `344` unikalne stacje. Output zawiera `30` kolumn i zachowuje poziom `day_station`. Nie występują duplikaty klucza `activity_date + representative_station_id`, nie występują duplikaty pozycji `daily_plan_rank` w obrębie dnia, a wszystkie rekordy mają komplet pól `priority_level`, `expected_business_impact`, `recommendation_confidence` oraz `decision_reason`. W danych występują cztery poziomy priorytetu: `very_high`, `high`, `medium` i `low`, trzy poziomy pewności rekomendacji: `high`, `medium` i `low`, oraz dwie obserwowane rekomendacje operacyjne: `deliver_bikes` i `check_station_state`. Kontrola spójności objęła `10` reguł i zakończyła się wynikiem `0` reguł wymagających przeglądu. Ranking dzienny zaczyna się od pozycji `1`, nie ma luk oraz jest uporządkowany według `expected_business_impact`. W podglądzie planu dla dnia `2017-05-02` najwyżej znalazły się m.in. stacje `Itämerentori`, `Kamppi (M)`, `Töölönlahdenkatu`, `Narinkka` oraz `Hakaniemi (M)`, z rekomendacją `deliver_bikes`, godziną największego ryzyka oraz szacowanym zakresem relokacji.

**Znaczenie biznesowe:** Dział `6.6` przekształca wcześniejsze sygnały operacyjne w praktyczny plan dnia. Dyspozytor nie otrzymuje już jedynie informacji o typie problemu lub rekomendacji, lecz kompletną listę stacji uporządkowaną według oczekiwanego wpływu operacyjnego. Najważniejszą logiką biznesową jest wykorzystanie `expected_business_impact`, dzięki czemu pierwszeństwo otrzymują stacje, gdzie potencjalna strata operacyjna może być największa. Oznacza to, że ranking nie kieruje pojazdu wyłącznie tam, gdzie sygnał jest najmocniejszy, ale tam, gdzie problem może mieć największe znaczenie dla działania systemu. Jednocześnie pola `recommendation_confidence` oraz `decision_reason` pozwalają odróżnić przypadki o wysokim wpływie i wysokiej pewności od przypadków, które wymagają ostrożniejszej interpretacji. W rezultacie warstwa `6.6` tworzy podstawę dla ekranów aplikacji: listy priorytetów, planu dnia, filtrów operacyjnych oraz dalszego widoku kierowcy.

**Wniosek:** Dział `6.6` został domknięty poprawnie. Zbudowano finalny dzienny plan dyspozytora, zapisany jako `b6_31_dispatcher_daily_plan.parquet`, wraz z profilem, kontraktem i statusem działu. Warstwa zawiera komplet `219 071` rekordów, `30` kolumn, `839` dni, `344` stacje, brak duplikatów klucza dziennego oraz `0` reguł wymagających przeglądu. Oznacza to, że można przejść do kolejnego etapu BLOKU 6, wykorzystując gotowe pola `daily_plan_rank`, `priority_level`, `recommended_action`, `highest_risk_hour_label`, `estimated_relocation_label`, `recommendation_confidence`, `decision_reason` oraz `expected_business_impact` jako podstawę właściwego panelu dyspozytora.

## 6.7 Mikrostrefy i lokalne balansowanie

In [32]:
# 6.7.1 Definicja kontraktu mikrostref i lokalnego balansowania

import json

import pandas as pd


step6_71_required_objects = [
    "step6_65_daily_plan_output_df",
    "step6_11_reports_dir",
]

step6_71_missing_objects = [
    object_name
    for object_name in step6_71_required_objects
    if object_name not in globals()
]

assert not step6_71_missing_objects, f"Missing required objects: {step6_71_missing_objects}"

step6_71_microzone_contract = {
    "block_name": "block_6",
    "section_name": "6.7",
    "section_scope": "microzone_local_balancing_layer",
    "source_object": "step6_65_daily_plan_output_df",
    "source_grain": "day_station",
    "output_grain": [
        "day_microzone",
        "day_microzone_pair",
    ],
    "main_use_cases": [
        "microzone_filter",
        "microzone_summary",
        "local_donor_receiver_pairs",
    ],
    "microzone_summary_fields": [
        "activity_date",
        "microzone_id",
        "stations_to_deliver",
        "stations_to_remove",
        "stations_to_check",
        "estimated_deliver_units",
        "estimated_remove_units",
        "microzone_balance",
        "microzone_expected_business_impact",
    ],
    "local_pair_fields": [
        "activity_date",
        "microzone_id",
        "donor_station_id",
        "donor_station_name",
        "receiver_station_id",
        "receiver_station_name",
        "paired_relocation_units",
        "pairing_reason",
        "pair_expected_business_impact",
    ],
    "pairing_policy": {
        "scope": "within_same_microzone",
        "method": "local_heuristic",
        "uses_global_fleet_optimization": False,
        "pairing_name": "local_donor_receiver_relocation_heuristic",
        "unit_policy": "min(donor_available_units, receiver_needed_units)",
    },
    "main_screen_policy": {
        "show_microzone_filter": True,
        "show_microzone_summary": True,
        "show_local_pairs": True,
        "show_global_optimization_claim": False,
    },
    "required_join_fields": [
        "activity_date",
        "representative_station_id",
    ],
    "required_microzone_field": "microzone_id",
}

step6_71_required_columns = [
    "activity_date",
    "daily_plan_rank",
    "representative_station_id",
    "station_name",
    "priority_level",
    "problem_type",
    "recommended_action",
    "highest_risk_hour_label",
    "estimated_relocation_units",
    "estimated_relocation_min",
    "estimated_relocation_max",
    "estimated_relocation_label",
    "relocation_direction",
    "expected_business_impact",
    "priority_score",
    "recommendation_confidence",
    "decision_reason",
]

step6_71_missing_columns = [
    column_name
    for column_name in step6_71_required_columns
    if column_name not in step6_65_daily_plan_output_df.columns
]

assert not step6_71_missing_columns, f"Missing required columns: {step6_71_missing_columns}"

step6_71_output_fields_df = pd.DataFrame(
    [
        {
            "field_name": "microzone_id",
            "field_role": "microzone_filter_key",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "stations_to_deliver",
            "field_role": "microzone_deliver_count",
            "source_grain": "day_microzone",
            "display_scope": "main_screen",
        },
        {
            "field_name": "stations_to_remove",
            "field_role": "microzone_remove_count",
            "source_grain": "day_microzone",
            "display_scope": "main_screen",
        },
        {
            "field_name": "microzone_balance",
            "field_role": "microzone_local_balance",
            "source_grain": "day_microzone",
            "display_scope": "main_screen",
        },
        {
            "field_name": "donor_station_id",
            "field_role": "local_pair_donor",
            "source_grain": "day_microzone_pair",
            "display_scope": "main_screen",
        },
        {
            "field_name": "receiver_station_id",
            "field_role": "local_pair_receiver",
            "source_grain": "day_microzone_pair",
            "display_scope": "main_screen",
        },
        {
            "field_name": "paired_relocation_units",
            "field_role": "local_pair_units",
            "source_grain": "day_microzone_pair",
            "display_scope": "main_screen",
        },
        {
            "field_name": "pairing_reason",
            "field_role": "local_pair_explanation",
            "source_grain": "day_microzone_pair",
            "display_scope": "main_screen",
        },
    ]
)

for column_name in ["field_name", "field_role", "source_grain", "display_scope"]:
    step6_71_output_fields_df[column_name] = step6_71_output_fields_df[column_name].astype("string")

step6_71_contract_path = step6_11_reports_dir / "b6_32_microzone_balancing_contract.json"
step6_71_output_fields_path = step6_11_reports_dir / "b6_32_microzone_balancing_output_fields.parquet"

with open(step6_71_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_71_microzone_contract, file, ensure_ascii=False, indent=2)

step6_71_output_fields_df.to_parquet(step6_71_output_fields_path, index=False)

step6_71_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_scope",
            "status": "ok",
            "value": "microzone_local_balancing_layer",
        },
        {
            "check_area": "source_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "check_area": "required_columns",
            "status": "ok",
            "value": str(len(step6_71_required_columns)),
        },
        {
            "check_area": "microzone_summary_fields",
            "status": "ok",
            "value": str(len(step6_71_microzone_contract["microzone_summary_fields"])),
        },
        {
            "check_area": "local_pair_fields",
            "status": "ok",
            "value": str(len(step6_71_microzone_contract["local_pair_fields"])),
        },
        {
            "check_area": "output_fields",
            "status": "ok",
            "value": str(step6_71_output_fields_df.shape[0]),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_71_contract_path),
        },
        {
            "check_area": "output_fields_path",
            "status": "ok",
            "value": str(step6_71_output_fields_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_71_summary_df[column_name] = step6_71_summary_df[column_name].astype("string")

display(step6_71_summary_df)
display(step6_71_output_fields_df)

,check_area,status,value
0,section_scope,ok,microzone_local_balancing_layer
1,source_grain,ok,day_station
2,required_columns,ok,17
3,microzone_summary_fields,ok,9
4,local_pair_fields,ok,9
5,output_fields,ok,8
6,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,output_fields_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,field_name,field_role,source_grain,display_scope
0,microzone_id,microzone_filter_key,day_station,main_screen
1,stations_to_deliver,microzone_deliver_count,day_microzone,main_screen
2,stations_to_remove,microzone_remove_count,day_microzone,main_screen
3,microzone_balance,microzone_local_balance,day_microzone,main_screen
4,donor_station_id,local_pair_donor,day_microzone_pair,main_screen
5,receiver_station_id,local_pair_receiver,day_microzone_pair,main_screen
6,paired_relocation_units,local_pair_units,day_microzone_pair,main_screen
7,pairing_reason,local_pair_explanation,day_microzone_pair,main_screen

In [33]:
# 6.7.2 Dołączenie identyfikatora mikrostrefy do planu dnia

import json
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq


step6_72_required_objects = [
    "step6_65_daily_plan_output_df",
    "step6_11_search_roots",
    "step6_11_reports_dir",
]

step6_72_missing_objects = [
    object_name
    for object_name in step6_72_required_objects
    if object_name not in globals()
]

assert not step6_72_missing_objects, f"Missing required objects: {step6_72_missing_objects}"

step6_72_plan_station_ids = set(
    step6_65_daily_plan_output_df["representative_station_id"]
    .astype("string")
    .dropna()
    .unique()
    .tolist()
)

step6_72_candidate_records = []
step6_72_mapping_candidates = []
step6_72_seen_paths = set()

for root_path in step6_11_search_roots:
    for file_path in sorted(root_path.rglob("*.parquet")):
        resolved_file_path = file_path.resolve()

        if str(resolved_file_path) in step6_72_seen_paths:
            continue

        step6_72_seen_paths.add(str(resolved_file_path))

        try:
            parquet_file = pq.ParquetFile(resolved_file_path)
            schema_names = parquet_file.schema.names
            schema_names_lower = [column_name.lower() for column_name in schema_names]

            has_microzone_id = "microzone_id" in schema_names_lower
            has_representative_station_id = "representative_station_id" in schema_names_lower
            has_station_id = "station_id" in schema_names_lower
            has_station_key = has_representative_station_id or has_station_id

            if not (has_microzone_id and has_station_key):
                continue

            station_key_column = (
                "representative_station_id"
                if has_representative_station_id
                else "station_id"
            )

            candidate_mapping_df = pd.read_parquet(
                resolved_file_path,
                columns=[
                    station_key_column,
                    "microzone_id",
                ],
            )

            candidate_mapping_df = (
                candidate_mapping_df
                .rename(columns={station_key_column: "representative_station_id"})
                .assign(
                    representative_station_id=lambda df: df["representative_station_id"].astype("string"),
                    microzone_id=lambda df: df["microzone_id"].astype("string"),
                )
                .dropna(subset=["representative_station_id", "microzone_id"])
                .drop_duplicates(subset=["representative_station_id"])
                .reset_index(drop=True)
            )

            candidate_station_ids = set(
                candidate_mapping_df["representative_station_id"]
                .dropna()
                .unique()
                .tolist()
            )

            matched_station_count = len(step6_72_plan_station_ids.intersection(candidate_station_ids))
            missing_station_count = len(step6_72_plan_station_ids.difference(candidate_station_ids))
            coverage_share = matched_station_count / len(step6_72_plan_station_ids)

            step6_72_candidate_records.append(
                {
                    "file_name": resolved_file_path.name,
                    "row_count": int(parquet_file.metadata.num_rows),
                    "column_count": int(len(schema_names)),
                    "station_key_column": station_key_column,
                    "mapping_rows": int(candidate_mapping_df.shape[0]),
                    "matched_station_count": int(matched_station_count),
                    "missing_station_count": int(missing_station_count),
                    "coverage_share": float(coverage_share),
                    "has_microzone_id": bool(has_microzone_id),
                    "has_representative_station_id": bool(has_representative_station_id),
                    "has_station_id": bool(has_station_id),
                    "resolved_path": str(resolved_file_path),
                }
            )

            step6_72_mapping_candidates.append(
                {
                    "resolved_path": str(resolved_file_path),
                    "mapping_df": candidate_mapping_df,
                }
            )

        except Exception as exc:
            continue

step6_72_candidate_df = pd.DataFrame(step6_72_candidate_records)

assert not step6_72_candidate_df.empty, "No microzone mapping candidates found."

step6_72_candidate_df = (
    step6_72_candidate_df
    .sort_values(
        [
            "coverage_share",
            "matched_station_count",
            "missing_station_count",
            "mapping_rows",
            "file_name",
        ],
        ascending=[False, False, True, True, True],
    )
    .reset_index(drop=True)
)

step6_72_candidate_df["candidate_rank"] = range(1, len(step6_72_candidate_df) + 1)

step6_72_selected_candidate = step6_72_candidate_df.iloc[0].to_dict()
step6_72_selected_path = Path(step6_72_selected_candidate["resolved_path"])

step6_72_microzone_mapping_df = [
    candidate["mapping_df"]
    for candidate in step6_72_mapping_candidates
    if candidate["resolved_path"] == str(step6_72_selected_path)
][0]

step6_72_daily_plan_with_microzone_df = (
    step6_65_daily_plan_output_df
    .assign(
        representative_station_id=lambda df: df["representative_station_id"].astype("string")
    )
    .merge(
        step6_72_microzone_mapping_df,
        on="representative_station_id",
        how="left",
        validate="many_to_one",
    )
)

step6_72_missing_microzone_count = int(
    step6_72_daily_plan_with_microzone_df["microzone_id"].isna().sum()
)

step6_72_duplicate_key_count = int(
    step6_72_daily_plan_with_microzone_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_72_microzone_coverage_share = float(
    1 - (
        step6_72_missing_microzone_count
        / step6_72_daily_plan_with_microzone_df.shape[0]
    )
)

assert step6_72_duplicate_key_count == 0, "Duplicated day-station keys detected after microzone join."
assert step6_72_missing_microzone_count == 0, "Missing microzone_id values detected after microzone join."

step6_72_candidate_path = step6_11_reports_dir / "b6_33_microzone_mapping_candidates.parquet"
step6_72_mapping_path = step6_11_reports_dir / "b6_33_microzone_station_mapping.parquet"
step6_72_join_profile_path = step6_11_reports_dir / "b6_33_daily_plan_microzone_join_profile.parquet"
step6_72_join_contract_path = step6_11_reports_dir / "b6_33_daily_plan_microzone_join_contract.json"

step6_72_candidate_df.to_parquet(step6_72_candidate_path, index=False)
step6_72_microzone_mapping_df.to_parquet(step6_72_mapping_path, index=False)

step6_72_join_profile_df = pd.DataFrame(
    [
        {
            "check_area": "mapping_candidates",
            "status": "ok",
            "value": str(step6_72_candidate_df.shape[0]),
        },
        {
            "check_area": "selected_mapping_file",
            "status": "ok",
            "value": step6_72_selected_candidate["file_name"],
        },
        {
            "check_area": "mapping_rows",
            "status": "ok",
            "value": str(step6_72_microzone_mapping_df.shape[0]),
        },
        {
            "check_area": "daily_plan_rows",
            "status": "ok",
            "value": str(step6_72_daily_plan_with_microzone_df.shape[0]),
        },
        {
            "check_area": "unique_microzones",
            "status": "ok",
            "value": str(step6_72_daily_plan_with_microzone_df["microzone_id"].nunique()),
        },
        {
            "check_area": "missing_microzone_id",
            "status": "ok",
            "value": str(step6_72_missing_microzone_count),
        },
        {
            "check_area": "microzone_coverage_share",
            "status": "ok",
            "value": str(round(step6_72_microzone_coverage_share, 6)),
        },
        {
            "check_area": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_72_duplicate_key_count),
        },
    ]
)

step6_72_join_profile_df.to_parquet(step6_72_join_profile_path, index=False)

step6_72_join_contract = {
    "block_name": "block_6",
    "section_name": "6.7",
    "contract_scope": "daily_plan_microzone_join",
    "source_object": "step6_65_daily_plan_output_df",
    "mapping_object": "step6_72_microzone_mapping_df",
    "output_object": "step6_72_daily_plan_with_microzone_df",
    "source_grain": "day_station",
    "output_grain": "day_station",
    "join_key": "representative_station_id",
    "joined_field": "microzone_id",
    "selected_mapping_file": step6_72_selected_candidate["file_name"],
    "selected_mapping_path": str(step6_72_selected_path),
    "row_count": int(step6_72_daily_plan_with_microzone_df.shape[0]),
    "unique_microzone_count": int(step6_72_daily_plan_with_microzone_df["microzone_id"].nunique()),
    "missing_microzone_id_count": step6_72_missing_microzone_count,
    "duplicate_key_count": step6_72_duplicate_key_count,
}

with open(step6_72_join_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_72_join_contract, file, ensure_ascii=False, indent=2)

display(step6_72_join_profile_df)

display(
    step6_72_candidate_df[
        [
            "candidate_rank",
            "file_name",
            "row_count",
            "column_count",
            "station_key_column",
            "mapping_rows",
            "matched_station_count",
            "missing_station_count",
            "coverage_share",
            "resolved_path",
        ]
    ].head(10)
)

display(step6_72_microzone_mapping_df.head(10))

display(
    step6_72_daily_plan_with_microzone_df[
        [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "microzone_id",
            "priority_level",
            "recommended_action",
            "estimated_relocation_label",
            "expected_business_impact",
        ]
    ].head(20)
)

                   check_area status                                  value
0          mapping_candidates     ok                                     30
1       selected_mapping_file     ok  3_classification_base_dataset.parquet
2                mapping_rows     ok                                    344
3             daily_plan_rows     ok                                 219071
4           unique_microzones     ok                                    304
5        missing_microzone_id     ok                                      0
6    microzone_coverage_share     ok                                    1.0
7  duplicate_day_station_keys     ok                                      0

,candidate_rank,file_name,row_count,column_count,station_key_column,mapping_rows,matched_station_count,missing_station_count,coverage_share,resolved_path
0,1,3_classification_base_dataset.parquet,218222,31,representative_station_id,344,344,0,1.0,/root/projects/6_samodzielny_projekt_koncowy_w...
1,2,3_classification_feature_dataset.parquet,218222,131,representative_station_id,344,344,0,1.0,/root/projects/6_samodzielny_projekt_koncowy_w...
2,3,3_classification_feature_dataset.parquet,218222,131,representative_station_id,344,344,0,1.0,/mnt/c/Users/User/Desktop/6_samodzielny_projek...
3,4,b6_33_microzone_station_mapping.parquet,344,2,representative_station_id,344,344,0,1.0,/root/projects/6_samodzielny_projekt_koncowy_w...
4,5,b6_37_dispatcher_daily_plan_with_microzones.pa...,219071,22,representative_station_id,344,344,0,1.0,/root/projects/6_samodzielny_projekt_koncowy_w...
5,6,b6_41_dispatcher_daily_plan_with_confidence.pa...,219071,24,representative_station_id,344,344,0,1.0,/root/projects/6_samodzielny_projekt_koncowy_w...
6,7,b6_44_map_base_with_coordinates.parquet,219071,26,representative_station_id,344,344,0,1.0,/root/projects/6_samodzielny_projekt_koncowy_w...
7,8,b6_45_map_station_layer.parquet,219071,31,representative_station_id,344,344,0,1.0,/root/projects/6_samodzielny_projekt_koncowy_w...
8,9,b6_57_driver_task_card_layer.parquet,219071,16,representative_station_id,344,344,0,1.0,/root/projects/6_samodzielny_projekt_koncowy_w...
9,10,station_alert_prediction_df.parquet,5257704,79,representative_station_id,344,344,0,1.0,/root/projects/6_samodzielny_projekt_koncowy_w...

  representative_station_id microzone_id
0                         1      MZ_0012
1                        10      MZ_0049
2                       100      MZ_0227
3                       101      MZ_0191
4                       103      MZ_0220
5                       104      MZ_0210
6                       105      MZ_0197
7                       106      MZ_0200
8                       107      MZ_0195
9                       108      MZ_0208

,activity_date,daily_plan_rank,representative_station_id,station_name,microzone_id,priority_level,recommended_action,estimated_relocation_label,expected_business_impact
0,2017-05-02,1,30,Itämerentori,MZ_0045,very_high,deliver_bikes,deliver 18-20,128.742188
1,2017-05-02,2,26,Kamppi (M),MZ_0064,very_high,deliver_bikes,deliver 9-11,124.333328
2,2017-05-02,3,21,Töölönlahdenkatu,MZ_0067,very_high,deliver_bikes,deliver 11-13,111.562500
3,2017-05-02,4,25,Narinkka,MZ_0067,very_high,deliver_bikes,deliver 7-9,103.812500
4,2017-05-02,5,40,Hakaniemi (M),MZ_0099,high,deliver_bikes,deliver 6-8,91.218750
5,2017-05-02,6,17,Varsapuistikko,MZ_0079,high,deliver_bikes,deliver 9-11,77.145828
6,2017-05-02,7,41,Ympyrätalo,MZ_0113,high,deliver_bikes,deliver 8-10,75.312500
7,2017-05-02,8,9,Erottajan aukio,MZ_0054,high,deliver_bikes,deliver 13-15,73.021355
8,2017-05-02,9,44,Sörnäinen (M),MZ_0140,high,deliver_bikes,deliver 7-9,72.021873
9,2017-05-02,10,22,Rautatientori / länsi,MZ_0067,high,deliver_bikes,deliver 8-10,71.437500
10,2017-05-02,11,5,Sepänkatu,MZ_0021,high,deliver_bikes,deliver 6-8,71.158340
11,2017-05-02,12,11,Unioninkatu,MZ_0054,high,deliver_bikes,deliver 19-21,69.125000
12,2017-05-02,13,23,Kiasma,MZ_0067,high,deliver_bikes,deliver 8-10,66.458336
13,2017-05-02,14,29,Baana,MZ_0037,high,deliver_bikes,deliver 6-8,66.178131
14,2017-05-02,15,6,Hietalahdentori,MZ_0038,high,deliver_bikes,deliver 3-5,65.770828
15,2017-05-02,16,19,Rautatientori / itä,MZ_0067,high,deliver_bikes,deliver 6-8,62.387497
16,2017-05-02,17,14,Senaatintori,MZ_0054,high,deliver_bikes,deliver 9-11,58.446354
17,2017-05-02,18,150,Töölönlahden puisto,MZ_0083,high,deliver_bikes,deliver 5-7,57.928127
18,2017-05-02,19,20,Kaisaniemenpuisto,MZ_0067,medium,deliver_bikes,deliver 5-7,57.409901
19,2017-05-02,20,112,Rautatieläisenkatu,MZ_0193,medium,deliver_bikes,deliver 4-6,55.987499

In [34]:
# 6.7.3 Budowa podsumowania mikrostref

import pandas as pd


step6_73_required_objects = [
    "step6_72_daily_plan_with_microzone_df",
    "step6_11_reports_dir",
]

step6_73_missing_objects = [
    object_name
    for object_name in step6_73_required_objects
    if object_name not in globals()
]

assert not step6_73_missing_objects, f"Missing required objects: {step6_73_missing_objects}"

step6_73_microzone_source_df = step6_72_daily_plan_with_microzone_df.copy()

step6_73_microzone_source_df["deliver_units"] = (
    step6_73_microzone_source_df["estimated_relocation_units"]
    .where(step6_73_microzone_source_df["relocation_direction"].astype("string") == "deliver", 0)
    .fillna(0)
    .astype("int16")
)

step6_73_microzone_source_df["remove_units"] = (
    step6_73_microzone_source_df["estimated_relocation_units"]
    .where(step6_73_microzone_source_df["relocation_direction"].astype("string") == "remove", 0)
    .fillna(0)
    .astype("int16")
)

step6_73_microzone_summary_df = (
    step6_73_microzone_source_df
    .groupby(["activity_date", "microzone_id"], observed=True)
    .agg(
        station_count=("representative_station_id", "nunique"),
        stations_to_deliver=("relocation_direction", lambda series: int((series.astype("string") == "deliver").sum())),
        stations_to_remove=("relocation_direction", lambda series: int((series.astype("string") == "remove").sum())),
        stations_to_check=("relocation_direction", lambda series: int((series.astype("string") == "check").sum())),
        estimated_deliver_units=("deliver_units", "sum"),
        estimated_remove_units=("remove_units", "sum"),
        microzone_expected_business_impact=("expected_business_impact", "sum"),
        max_expected_business_impact=("expected_business_impact", "max"),
        mean_expected_business_impact=("expected_business_impact", "mean"),
        top_priority_score=("priority_score", "max"),
        top_daily_plan_rank=("daily_plan_rank", "min"),
    )
    .reset_index()
)

step6_73_microzone_summary_df["microzone_balance"] = (
    step6_73_microzone_summary_df["estimated_remove_units"]
    - step6_73_microzone_summary_df["estimated_deliver_units"]
).astype("int32")

step6_73_microzone_summary_df["microzone_balance_direction"] = pd.Series(
    "balanced_or_check",
    index=step6_73_microzone_summary_df.index,
    dtype="string",
)

step6_73_microzone_summary_df.loc[
    step6_73_microzone_summary_df["microzone_balance"] < 0,
    "microzone_balance_direction",
] = "net_delivery_need"

step6_73_microzone_summary_df.loc[
    step6_73_microzone_summary_df["microzone_balance"] > 0,
    "microzone_balance_direction",
] = "net_removal_need"

step6_73_microzone_summary_df = (
    step6_73_microzone_summary_df
    .sort_values(
        [
            "activity_date",
            "microzone_expected_business_impact",
            "estimated_deliver_units",
            "top_priority_score",
            "microzone_id",
        ],
        ascending=[True, False, False, False, True],
    )
    .reset_index(drop=True)
)

step6_73_duplicate_microzone_key_count = int(
    step6_73_microzone_summary_df.duplicated(
        subset=["activity_date", "microzone_id"]
    ).sum()
)

step6_73_missing_microzone_count = int(
    step6_73_microzone_summary_df["microzone_id"].isna().sum()
)

step6_73_profile_df = pd.DataFrame(
    [
        {
            "check_area": "microzone_summary_rows",
            "status": "ok",
            "value": str(step6_73_microzone_summary_df.shape[0]),
        },
        {
            "check_area": "unique_dates",
            "status": "ok",
            "value": str(step6_73_microzone_summary_df["activity_date"].nunique()),
        },
        {
            "check_area": "unique_microzones",
            "status": "ok",
            "value": str(step6_73_microzone_summary_df["microzone_id"].nunique()),
        },
        {
            "check_area": "duplicate_day_microzone_keys",
            "status": "ok" if step6_73_duplicate_microzone_key_count == 0 else "review",
            "value": str(step6_73_duplicate_microzone_key_count),
        },
        {
            "check_area": "missing_microzone_id",
            "status": "ok" if step6_73_missing_microzone_count == 0 else "review",
            "value": str(step6_73_missing_microzone_count),
        },
        {
            "check_area": "microzones_with_delivery_need",
            "status": "ok",
            "value": str(int((step6_73_microzone_summary_df["estimated_deliver_units"] > 0).sum())),
        },
        {
            "check_area": "microzones_with_removal_need",
            "status": "ok",
            "value": str(int((step6_73_microzone_summary_df["estimated_remove_units"] > 0).sum())),
        },
    ]
)

step6_73_balance_summary_df = (
    step6_73_microzone_summary_df
    .groupby("microzone_balance_direction", observed=True)
    .agg(
        row_count=("microzone_balance_direction", "size"),
        mean_microzone_expected_business_impact=("microzone_expected_business_impact", "mean"),
        median_microzone_expected_business_impact=("microzone_expected_business_impact", "median"),
        max_microzone_expected_business_impact=("microzone_expected_business_impact", "max"),
        mean_estimated_deliver_units=("estimated_deliver_units", "mean"),
        mean_estimated_remove_units=("estimated_remove_units", "mean"),
        mean_microzone_balance=("microzone_balance", "mean"),
    )
    .reset_index()
)

step6_73_balance_summary_df["row_share"] = (
    step6_73_balance_summary_df["row_count"]
    / step6_73_balance_summary_df["row_count"].sum()
)

step6_73_microzone_summary_path = step6_11_reports_dir / "b6_34_microzone_summary.parquet"
step6_73_profile_path = step6_11_reports_dir / "b6_34_microzone_summary_profile.parquet"
step6_73_balance_summary_path = step6_11_reports_dir / "b6_34_microzone_balance_summary.parquet"

step6_73_microzone_summary_df.to_parquet(step6_73_microzone_summary_path, index=False)
step6_73_profile_df.to_parquet(step6_73_profile_path, index=False)
step6_73_balance_summary_df.to_parquet(step6_73_balance_summary_path, index=False)

display(step6_73_profile_df)
display(step6_73_balance_summary_df)
display(step6_73_microzone_summary_df.head(20))

                      check_area status   value
0         microzone_summary_rows     ok  191777
1                   unique_dates     ok     839
2              unique_microzones     ok     304
3   duplicate_day_microzone_keys     ok       0
4           missing_microzone_id     ok       0
5  microzones_with_delivery_need     ok  185978
6   microzones_with_removal_need     ok       0

,microzone_balance_direction,row_count,mean_microzone_expected_business_impact,median_microzone_expected_business_impact,max_microzone_expected_business_impact,mean_estimated_deliver_units,mean_estimated_remove_units,mean_microzone_balance,row_share
0,balanced_or_check,5799,72.875328,44.118752,1241.005127,0.000000,0.0,0.000000,0.030238
1,net_delivery_need,185978,51.576752,28.830729,1948.627197,3.364022,0.0,-3.364022,0.969762

,activity_date,microzone_id,station_count,stations_to_deliver,stations_to_remove,stations_to_check,estimated_deliver_units,estimated_remove_units,microzone_expected_business_impact,max_expected_business_impact,mean_expected_business_impact,top_priority_score,top_daily_plan_rank,microzone_balance,microzone_balance_direction
0,2017-05-02,MZ_0067,8,8,0,0,60,0,565.820862,111.562500,70.727608,1209.984985,3,-60,net_delivery_need
1,2017-05-02,MZ_0054,3,3,0,0,44,0,200.592712,73.021355,66.864235,833.073547,8,-44,net_delivery_need
2,2017-05-02,MZ_0064,2,2,0,0,15,0,177.458328,124.333328,88.729164,1327.043213,2,-15,net_delivery_need
3,2017-05-02,MZ_0045,1,1,0,0,19,0,128.742188,128.742188,128.742188,1411.951904,1,-19,net_delivery_need
4,2017-05-02,MZ_0037,2,2,0,0,13,0,111.639069,66.178131,55.819534,728.221313,14,-13,net_delivery_need
5,2017-05-02,MZ_0099,1,1,0,0,7,0,91.218750,91.218750,91.218750,980.877502,5,-7,net_delivery_need
6,2017-05-02,MZ_0116,2,2,0,0,12,0,84.795319,54.178127,42.397659,607.991272,21,-12,net_delivery_need
7,2017-05-02,MZ_0141,2,2,0,0,11,0,77.625000,40.312500,38.812500,459.635010,36,-11,net_delivery_need
8,2017-05-02,MZ_0079,1,1,0,0,10,0,77.145828,77.145828,77.145828,858.708252,6,-10,net_delivery_need
9,2017-05-02,MZ_0113,1,1,0,0,9,0,75.312500,75.312500,75.312500,826.744995,7,-9,net_delivery_need
10,2017-05-02,MZ_0140,1,1,0,0,8,0,72.021873,72.021873,72.021873,792.518738,9,-8,net_delivery_need
11,2017-05-02,MZ_0021,1,1,0,0,7,0,71.158340,71.158340,71.158340,776.073364,11,-7,net_delivery_need
12,2017-05-02,MZ_0044,2,2,0,0,10,0,71.156250,48.322914,35.578125,551.879150,26,-10,net_delivery_need
13,2017-05-02,MZ_0083,2,2,0,0,9,0,67.490631,57.928127,33.745316,640.661255,18,-9,net_delivery_need
14,2017-05-02,MZ_0038,1,1,0,0,4,0,65.770828,65.770828,65.770828,705.928223,15,-4,net_delivery_need
15,2017-05-02,MZ_0052,2,2,0,0,9,0,63.993752,47.962502,31.996876,536.275024,27,-9,net_delivery_need
16,2017-05-02,MZ_0122,2,2,0,0,10,0,62.437500,39.375000,31.218750,441.850006,37,-10,net_delivery_need
17,2017-05-02,MZ_0193,1,1,0,0,5,0,55.987499,55.987499,55.987499,622.395020,20,-5,net_delivery_need
18,2017-05-02,MZ_0068,1,1,0,0,9,0,52.447918,52.447918,52.447918,601.879211,23,-9,net_delivery_need
19,2017-05-02,MZ_0153,2,2,0,0,9,0,50.096870,32.043228,25.048435,375.432281,52,-9,net_delivery_need

In [35]:
# 6.7.4 Budowa lokalnych par kompensacyjnych w mikrostrefach

import pandas as pd


step6_74_required_objects = [
    "step6_72_daily_plan_with_microzone_df",
    "step6_73_microzone_summary_df",
    "step6_11_reports_dir",
]

step6_74_missing_objects = [
    object_name
    for object_name in step6_74_required_objects
    if object_name not in globals()
]

assert not step6_74_missing_objects, f"Missing required objects: {step6_74_missing_objects}"

step6_74_donor_df = (
    step6_72_daily_plan_with_microzone_df.loc[
        step6_72_daily_plan_with_microzone_df["relocation_direction"].astype("string") == "remove",
        [
            "activity_date",
            "microzone_id",
            "representative_station_id",
            "station_name",
            "estimated_relocation_units",
            "expected_business_impact",
            "priority_score",
            "daily_plan_rank",
        ],
    ]
    .rename(
        columns={
            "representative_station_id": "donor_station_id",
            "station_name": "donor_station_name",
            "estimated_relocation_units": "donor_available_units",
            "expected_business_impact": "donor_expected_business_impact",
            "priority_score": "donor_priority_score",
            "daily_plan_rank": "donor_daily_plan_rank",
        }
    )
    .copy()
)

step6_74_receiver_df = (
    step6_72_daily_plan_with_microzone_df.loc[
        step6_72_daily_plan_with_microzone_df["relocation_direction"].astype("string") == "deliver",
        [
            "activity_date",
            "microzone_id",
            "representative_station_id",
            "station_name",
            "estimated_relocation_units",
            "expected_business_impact",
            "priority_score",
            "daily_plan_rank",
        ],
    ]
    .rename(
        columns={
            "representative_station_id": "receiver_station_id",
            "station_name": "receiver_station_name",
            "estimated_relocation_units": "receiver_needed_units",
            "expected_business_impact": "receiver_expected_business_impact",
            "priority_score": "receiver_priority_score",
            "daily_plan_rank": "receiver_daily_plan_rank",
        }
    )
    .copy()
)

step6_74_donor_df = (
    step6_74_donor_df
    .sort_values(
        [
            "activity_date",
            "microzone_id",
            "donor_available_units",
            "donor_expected_business_impact",
            "donor_priority_score",
            "donor_station_id",
        ],
        ascending=[True, True, False, False, False, True],
    )
    .reset_index(drop=True)
)

step6_74_receiver_df = (
    step6_74_receiver_df
    .sort_values(
        [
            "activity_date",
            "microzone_id",
            "receiver_needed_units",
            "receiver_expected_business_impact",
            "receiver_priority_score",
            "receiver_station_id",
        ],
        ascending=[True, True, False, False, False, True],
    )
    .reset_index(drop=True)
)

step6_74_donor_df["local_pair_order"] = (
    step6_74_donor_df
    .groupby(["activity_date", "microzone_id"], observed=True)
    .cumcount()
    .add(1)
    .astype("int32")
)

step6_74_receiver_df["local_pair_order"] = (
    step6_74_receiver_df
    .groupby(["activity_date", "microzone_id"], observed=True)
    .cumcount()
    .add(1)
    .astype("int32")
)

step6_74_local_pair_df = (
    step6_74_donor_df
    .merge(
        step6_74_receiver_df,
        on=["activity_date", "microzone_id", "local_pair_order"],
        how="inner",
        validate="one_to_one",
    )
)

if step6_74_local_pair_df.empty:
    step6_74_local_pair_df = pd.DataFrame(
        columns=[
            "activity_date",
            "microzone_id",
            "local_pair_order",
            "donor_station_id",
            "donor_station_name",
            "receiver_station_id",
            "receiver_station_name",
            "donor_available_units",
            "receiver_needed_units",
            "paired_relocation_units",
            "pair_expected_business_impact",
            "pairing_reason",
        ]
    )
else:
    step6_74_local_pair_df["paired_relocation_units"] = (
        step6_74_local_pair_df[
            [
                "donor_available_units",
                "receiver_needed_units",
            ]
        ]
        .min(axis=1)
        .astype("int16")
    )

    step6_74_local_pair_df["pair_expected_business_impact"] = (
        step6_74_local_pair_df["donor_expected_business_impact"].fillna(0).astype("float32")
        + step6_74_local_pair_df["receiver_expected_business_impact"].fillna(0).astype("float32")
    ).astype("float32")

    step6_74_local_pair_df["pairing_reason"] = "same_microzone_local_donor_receiver_heuristic"

    step6_74_local_pair_df = (
        step6_74_local_pair_df.loc[
            step6_74_local_pair_df["paired_relocation_units"] > 0,
            [
                "activity_date",
                "microzone_id",
                "local_pair_order",
                "donor_station_id",
                "donor_station_name",
                "receiver_station_id",
                "receiver_station_name",
                "donor_available_units",
                "receiver_needed_units",
                "paired_relocation_units",
                "pair_expected_business_impact",
                "pairing_reason",
            ],
        ]
        .sort_values(
            [
                "activity_date",
                "microzone_id",
                "pair_expected_business_impact",
                "paired_relocation_units",
                "local_pair_order",
            ],
            ascending=[True, True, False, False, True],
        )
        .reset_index(drop=True)
    )

step6_74_pair_profile_df = pd.DataFrame(
    [
        {
            "check_area": "donor_rows",
            "status": "ok",
            "value": str(step6_74_donor_df.shape[0]),
        },
        {
            "check_area": "receiver_rows",
            "status": "ok",
            "value": str(step6_74_receiver_df.shape[0]),
        },
        {
            "check_area": "local_pair_rows",
            "status": "ok",
            "value": str(step6_74_local_pair_df.shape[0]),
        },
        {
            "check_area": "unique_pair_dates",
            "status": "ok",
            "value": str(step6_74_local_pair_df["activity_date"].nunique() if not step6_74_local_pair_df.empty else 0),
        },
        {
            "check_area": "unique_pair_microzones",
            "status": "ok",
            "value": str(step6_74_local_pair_df["microzone_id"].nunique() if not step6_74_local_pair_df.empty else 0),
        },
        {
            "check_area": "total_paired_relocation_units",
            "status": "ok",
            "value": str(int(step6_74_local_pair_df["paired_relocation_units"].sum()) if not step6_74_local_pair_df.empty else 0),
        },
    ]
)

step6_74_pair_summary_df = pd.DataFrame(
    [
        {
            "summary_area": "local_pairing_scope",
            "status": "ok",
            "value": "within_same_microzone",
        },
        {
            "summary_area": "local_pairing_method",
            "status": "ok",
            "value": "local_donor_receiver_heuristic",
        },
        {
            "summary_area": "uses_global_fleet_optimization",
            "status": "ok",
            "value": "false",
        },
        {
            "summary_area": "available_donor_rows",
            "status": "ok",
            "value": str(step6_74_donor_df.shape[0]),
        },
        {
            "summary_area": "available_receiver_rows",
            "status": "ok",
            "value": str(step6_74_receiver_df.shape[0]),
        },
        {
            "summary_area": "created_local_pairs",
            "status": "ok",
            "value": str(step6_74_local_pair_df.shape[0]),
        },
    ]
)

step6_74_donor_path = step6_11_reports_dir / "b6_35_microzone_local_donor_candidates.parquet"
step6_74_receiver_path = step6_11_reports_dir / "b6_35_microzone_local_receiver_candidates.parquet"
step6_74_pair_path = step6_11_reports_dir / "b6_35_microzone_local_pairs.parquet"
step6_74_profile_path = step6_11_reports_dir / "b6_35_microzone_local_pair_profile.parquet"
step6_74_summary_path = step6_11_reports_dir / "b6_35_microzone_local_pair_summary.parquet"

step6_74_donor_df.to_parquet(step6_74_donor_path, index=False)
step6_74_receiver_df.to_parquet(step6_74_receiver_path, index=False)
step6_74_local_pair_df.to_parquet(step6_74_pair_path, index=False)
step6_74_pair_profile_df.to_parquet(step6_74_profile_path, index=False)
step6_74_pair_summary_df.to_parquet(step6_74_summary_path, index=False)

display(step6_74_pair_profile_df)
display(step6_74_pair_summary_df)
display(step6_74_local_pair_df.head(20))

                      check_area status   value
0                     donor_rows     ok       0
1                  receiver_rows     ok  211990
2                local_pair_rows     ok       0
3              unique_pair_dates     ok       0
4         unique_pair_microzones     ok       0
5  total_paired_relocation_units     ok       0

                     summary_area status                           value
0             local_pairing_scope     ok           within_same_microzone
1            local_pairing_method     ok  local_donor_receiver_heuristic
2  uses_global_fleet_optimization     ok                           false
3            available_donor_rows     ok                               0
4         available_receiver_rows     ok                          211990
5             created_local_pairs     ok                               0

Empty DataFrame
Columns: [activity_date, microzone_id, local_pair_order, donor_station_id, donor_station_name, receiver_station_id, receiver_station_name, donor_available_units, receiver_needed_units, paired_relocation_units, pair_expected_business_impact, pairing_reason]
Index: []

In [36]:
# 6.7.5 Kontrola spójności mikrostref i lokalnego balansowania

import json

import pandas as pd


step6_75_required_objects = [
    "step6_72_daily_plan_with_microzone_df",
    "step6_73_microzone_summary_df",
    "step6_74_local_pair_df",
    "step6_74_donor_df",
    "step6_74_receiver_df",
    "step6_11_reports_dir",
]

step6_75_missing_objects = [
    object_name
    for object_name in step6_75_required_objects
    if object_name not in globals()
]

assert not step6_75_missing_objects, f"Missing required objects: {step6_75_missing_objects}"

step6_75_duplicate_day_station_count = int(
    step6_72_daily_plan_with_microzone_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_75_missing_microzone_count = int(
    step6_72_daily_plan_with_microzone_df["microzone_id"].isna().sum()
)

step6_75_duplicate_day_microzone_count = int(
    step6_73_microzone_summary_df.duplicated(
        subset=["activity_date", "microzone_id"]
    ).sum()
)

step6_75_negative_deliver_units_count = int(
    (step6_73_microzone_summary_df["estimated_deliver_units"] < 0).sum()
)

step6_75_negative_remove_units_count = int(
    (step6_73_microzone_summary_df["estimated_remove_units"] < 0).sum()
)

step6_75_pair_units_negative_count = (
    int((step6_74_local_pair_df["paired_relocation_units"] < 0).sum())
    if not step6_74_local_pair_df.empty
    else 0
)

step6_75_pair_scope_count = (
    int(
        step6_74_local_pair_df[
            ["activity_date", "microzone_id", "donor_station_id", "receiver_station_id"]
        ]
        .isna()
        .any(axis=1)
        .sum()
    )
    if not step6_74_local_pair_df.empty
    else 0
)

step6_75_pair_same_station_count = (
    int(
        (
            step6_74_local_pair_df["donor_station_id"].astype("string")
            == step6_74_local_pair_df["receiver_station_id"].astype("string")
        ).sum()
    )
    if not step6_74_local_pair_df.empty
    else 0
)

step6_75_pair_without_donors_condition = (
    step6_74_local_pair_df.shape[0] == 0
    if step6_74_donor_df.shape[0] == 0
    else True
)

step6_75_pair_without_receivers_condition = (
    step6_74_local_pair_df.shape[0] == 0
    if step6_74_receiver_df.shape[0] == 0
    else True
)

step6_75_consistency_rules = [
    {
        "rule_name": "no_duplicate_day_station_keys",
        "condition_passed": step6_75_duplicate_day_station_count == 0,
        "value": str(step6_75_duplicate_day_station_count),
    },
    {
        "rule_name": "no_missing_microzone_id",
        "condition_passed": step6_75_missing_microzone_count == 0,
        "value": str(step6_75_missing_microzone_count),
    },
    {
        "rule_name": "no_duplicate_day_microzone_keys",
        "condition_passed": step6_75_duplicate_day_microzone_count == 0,
        "value": str(step6_75_duplicate_day_microzone_count),
    },
    {
        "rule_name": "estimated_deliver_units_non_negative",
        "condition_passed": step6_75_negative_deliver_units_count == 0,
        "value": str(step6_75_negative_deliver_units_count),
    },
    {
        "rule_name": "estimated_remove_units_non_negative",
        "condition_passed": step6_75_negative_remove_units_count == 0,
        "value": str(step6_75_negative_remove_units_count),
    },
    {
        "rule_name": "paired_relocation_units_non_negative",
        "condition_passed": step6_75_pair_units_negative_count == 0,
        "value": str(step6_75_pair_units_negative_count),
    },
    {
        "rule_name": "local_pairs_have_required_scope_keys",
        "condition_passed": step6_75_pair_scope_count == 0,
        "value": str(step6_75_pair_scope_count),
    },
    {
        "rule_name": "local_pair_donor_receiver_are_distinct",
        "condition_passed": step6_75_pair_same_station_count == 0,
        "value": str(step6_75_pair_same_station_count),
    },
    {
        "rule_name": "no_pairs_without_available_donors",
        "condition_passed": bool(step6_75_pair_without_donors_condition),
        "value": str(bool(step6_75_pair_without_donors_condition)),
    },
    {
        "rule_name": "no_pairs_without_available_receivers",
        "condition_passed": bool(step6_75_pair_without_receivers_condition),
        "value": str(bool(step6_75_pair_without_receivers_condition)),
    },
]

step6_75_consistency_df = pd.DataFrame(step6_75_consistency_rules)

step6_75_consistency_df["status"] = step6_75_consistency_df["condition_passed"].map(
    {
        True: "ok",
        False: "review",
    }
)

step6_75_review_count = int(
    (step6_75_consistency_df["status"] == "review").sum()
)

step6_75_microzone_operational_summary_df = pd.DataFrame(
    [
        {
            "summary_area": "daily_plan_rows",
            "status": "ok",
            "value": str(step6_72_daily_plan_with_microzone_df.shape[0]),
        },
        {
            "summary_area": "microzone_summary_rows",
            "status": "ok",
            "value": str(step6_73_microzone_summary_df.shape[0]),
        },
        {
            "summary_area": "unique_dates",
            "status": "ok",
            "value": str(step6_73_microzone_summary_df["activity_date"].nunique()),
        },
        {
            "summary_area": "unique_microzones",
            "status": "ok",
            "value": str(step6_73_microzone_summary_df["microzone_id"].nunique()),
        },
        {
            "summary_area": "donor_rows",
            "status": "ok",
            "value": str(step6_74_donor_df.shape[0]),
        },
        {
            "summary_area": "receiver_rows",
            "status": "ok",
            "value": str(step6_74_receiver_df.shape[0]),
        },
        {
            "summary_area": "local_pair_rows",
            "status": "ok",
            "value": str(step6_74_local_pair_df.shape[0]),
        },
        {
            "summary_area": "uses_global_fleet_optimization",
            "status": "ok",
            "value": "false",
        },
    ]
)

step6_75_contract = {
    "block_name": "block_6",
    "section_name": "6.7",
    "contract_scope": "microzone_local_balancing_consistency",
    "source_grain": "day_station",
    "summary_grain": "day_microzone",
    "pair_grain": "day_microzone_pair",
    "microzone_filter_field": "microzone_id",
    "pairing_method": "local_donor_receiver_heuristic",
    "uses_global_fleet_optimization": False,
    "daily_plan_rows": int(step6_72_daily_plan_with_microzone_df.shape[0]),
    "microzone_summary_rows": int(step6_73_microzone_summary_df.shape[0]),
    "donor_rows": int(step6_74_donor_df.shape[0]),
    "receiver_rows": int(step6_74_receiver_df.shape[0]),
    "local_pair_rows": int(step6_74_local_pair_df.shape[0]),
    "consistency_review_count": step6_75_review_count,
}

step6_75_consistency_path = step6_11_reports_dir / "b6_36_microzone_balancing_consistency.parquet"
step6_75_summary_path = step6_11_reports_dir / "b6_36_microzone_operational_summary.parquet"
step6_75_contract_path = step6_11_reports_dir / "b6_36_microzone_balancing_consistency_contract.json"

step6_75_consistency_df.to_parquet(step6_75_consistency_path, index=False)
step6_75_microzone_operational_summary_df.to_parquet(step6_75_summary_path, index=False)

with open(step6_75_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_75_contract, file, ensure_ascii=False, indent=2)

step6_75_summary_df = pd.DataFrame(
    [
        {
            "check_area": "consistency_rules",
            "status": "ok",
            "value": str(step6_75_consistency_df.shape[0]),
        },
        {
            "check_area": "consistency_review_count",
            "status": "ok" if step6_75_review_count == 0 else "review",
            "value": str(step6_75_review_count),
        },
        {
            "check_area": "microzone_summary_rows",
            "status": "ok",
            "value": str(step6_73_microzone_summary_df.shape[0]),
        },
        {
            "check_area": "local_pair_rows",
            "status": "ok",
            "value": str(step6_74_local_pair_df.shape[0]),
        },
        {
            "check_area": "donor_rows",
            "status": "ok",
            "value": str(step6_74_donor_df.shape[0]),
        },
        {
            "check_area": "receiver_rows",
            "status": "ok",
            "value": str(step6_74_receiver_df.shape[0]),
        },
        {
            "check_area": "consistency_path",
            "status": "ok",
            "value": str(step6_75_consistency_path),
        },
        {
            "check_area": "summary_path",
            "status": "ok",
            "value": str(step6_75_summary_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_75_contract_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_75_summary_df[column_name] = step6_75_summary_df[column_name].astype("string")

display(step6_75_summary_df)
display(step6_75_consistency_df)
display(step6_75_microzone_operational_summary_df)

,check_area,status,value
0,consistency_rules,ok,10
1,consistency_review_count,ok,0
2,microzone_summary_rows,ok,191777
3,local_pair_rows,ok,0
4,donor_rows,ok,0
5,receiver_rows,ok,211990
6,consistency_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,summary_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
8,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                                rule_name  condition_passed value status
0           no_duplicate_day_station_keys              True     0     ok
1                 no_missing_microzone_id              True     0     ok
2         no_duplicate_day_microzone_keys              True     0     ok
3    estimated_deliver_units_non_negative              True     0     ok
4     estimated_remove_units_non_negative              True     0     ok
5    paired_relocation_units_non_negative              True     0     ok
6    local_pairs_have_required_scope_keys              True     0     ok
7  local_pair_donor_receiver_are_distinct              True     0     ok
8       no_pairs_without_available_donors              True  True     ok
9    no_pairs_without_available_receivers              True  True     ok

                     summary_area status   value
0                 daily_plan_rows     ok  219071
1          microzone_summary_rows     ok  191777
2                    unique_dates     ok     839
3               unique_microzones     ok     304
4                      donor_rows     ok       0
5                   receiver_rows     ok  211990
6                 local_pair_rows     ok       0
7  uses_global_fleet_optimization     ok   false

In [37]:
# 6.7.6 Zamknięcie warstwy mikrostref i lokalnego balansowania

import json

import pandas as pd


step6_76_required_objects = [
    "step6_72_daily_plan_with_microzone_df",
    "step6_73_microzone_summary_df",
    "step6_74_local_pair_df",
    "step6_74_donor_df",
    "step6_74_receiver_df",
    "step6_75_consistency_df",
    "step6_75_microzone_operational_summary_df",
    "step6_11_reports_dir",
    "step6_11_outputs_dir",
]

step6_76_missing_objects = [
    object_name
    for object_name in step6_76_required_objects
    if object_name not in globals()
]

assert not step6_76_missing_objects, f"Missing required objects: {step6_76_missing_objects}"

step6_76_review_count = int(
    (step6_75_consistency_df["status"].astype("string") == "review").sum()
)

step6_76_duplicate_day_station_count = int(
    step6_72_daily_plan_with_microzone_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_76_duplicate_day_microzone_count = int(
    step6_73_microzone_summary_df.duplicated(
        subset=["activity_date", "microzone_id"]
    ).sum()
)

step6_76_missing_microzone_count = int(
    step6_72_daily_plan_with_microzone_df["microzone_id"].isna().sum()
)

assert step6_76_review_count == 0, "Microzone consistency review detected."
assert step6_76_duplicate_day_station_count == 0, "Duplicated day-station keys detected."
assert step6_76_duplicate_day_microzone_count == 0, "Duplicated day-microzone keys detected."
assert step6_76_missing_microzone_count == 0, "Missing microzone_id values detected."

step6_76_daily_plan_microzone_output_columns = [
    "activity_date",
    "daily_plan_rank",
    "representative_station_id",
    "station_name",
    "microzone_id",
    "priority_level",
    "problem_type",
    "recommended_action",
    "highest_risk_hour_label",
    "estimated_relocation_label",
    "recommendation_confidence",
    "decision_reason",
    "expected_business_impact",
    "priority_score",
    "station_business_scale",
    "estimated_relocation_units",
    "estimated_relocation_min",
    "estimated_relocation_max",
    "relocation_direction",
    "total_departures",
    "total_returns",
    "daily_net_flow",
]

step6_76_microzone_summary_output_columns = [
    "activity_date",
    "microzone_id",
    "station_count",
    "stations_to_deliver",
    "stations_to_remove",
    "stations_to_check",
    "estimated_deliver_units",
    "estimated_remove_units",
    "microzone_balance",
    "microzone_balance_direction",
    "microzone_expected_business_impact",
    "max_expected_business_impact",
    "mean_expected_business_impact",
    "top_priority_score",
    "top_daily_plan_rank",
]

step6_76_missing_daily_plan_columns = [
    column_name
    for column_name in step6_76_daily_plan_microzone_output_columns
    if column_name not in step6_72_daily_plan_with_microzone_df.columns
]

step6_76_missing_microzone_summary_columns = [
    column_name
    for column_name in step6_76_microzone_summary_output_columns
    if column_name not in step6_73_microzone_summary_df.columns
]

assert not step6_76_missing_daily_plan_columns, f"Missing daily plan columns: {step6_76_missing_daily_plan_columns}"
assert not step6_76_missing_microzone_summary_columns, f"Missing microzone summary columns: {step6_76_missing_microzone_summary_columns}"

step6_76_daily_plan_with_microzone_output_df = (
    step6_72_daily_plan_with_microzone_df[step6_76_daily_plan_microzone_output_columns]
    .sort_values(["activity_date", "daily_plan_rank"])
    .reset_index(drop=True)
)

step6_76_microzone_summary_output_df = (
    step6_73_microzone_summary_df[step6_76_microzone_summary_output_columns]
    .sort_values(
        [
            "activity_date",
            "microzone_expected_business_impact",
            "estimated_deliver_units",
            "top_priority_score",
            "microzone_id",
        ],
        ascending=[True, False, False, False, True],
    )
    .reset_index(drop=True)
)

step6_76_local_pair_output_df = step6_74_local_pair_df.copy()

step6_76_daily_plan_microzone_output_path = step6_11_outputs_dir / "b6_37_dispatcher_daily_plan_with_microzones.parquet"
step6_76_microzone_summary_output_path = step6_11_outputs_dir / "b6_37_microzone_summary.parquet"
step6_76_local_pair_output_path = step6_11_outputs_dir / "b6_37_microzone_local_pairs.parquet"
step6_76_output_profile_path = step6_11_reports_dir / "b6_37_microzone_layer_output_profile.parquet"
step6_76_section_contract_path = step6_11_reports_dir / "b6_37_microzone_layer_section_contract.json"
step6_76_section_status_path = step6_11_reports_dir / "b6_37_microzone_layer_section_status.parquet"

step6_76_daily_plan_with_microzone_output_df.to_parquet(
    step6_76_daily_plan_microzone_output_path,
    index=False,
)

step6_76_microzone_summary_output_df.to_parquet(
    step6_76_microzone_summary_output_path,
    index=False,
)

step6_76_local_pair_output_df.to_parquet(
    step6_76_local_pair_output_path,
    index=False,
)

step6_76_output_profile_df = pd.DataFrame(
    [
        {
            "profile_area": "daily_plan_microzone_rows",
            "status": "ok",
            "value": str(step6_76_daily_plan_with_microzone_output_df.shape[0]),
        },
        {
            "profile_area": "daily_plan_microzone_columns",
            "status": "ok",
            "value": str(step6_76_daily_plan_with_microzone_output_df.shape[1]),
        },
        {
            "profile_area": "microzone_summary_rows",
            "status": "ok",
            "value": str(step6_76_microzone_summary_output_df.shape[0]),
        },
        {
            "profile_area": "microzone_summary_columns",
            "status": "ok",
            "value": str(step6_76_microzone_summary_output_df.shape[1]),
        },
        {
            "profile_area": "local_pair_rows",
            "status": "ok",
            "value": str(step6_76_local_pair_output_df.shape[0]),
        },
        {
            "profile_area": "unique_dates",
            "status": "ok",
            "value": str(step6_76_daily_plan_with_microzone_output_df["activity_date"].nunique()),
        },
        {
            "profile_area": "unique_microzones",
            "status": "ok",
            "value": str(step6_76_daily_plan_with_microzone_output_df["microzone_id"].nunique()),
        },
        {
            "profile_area": "donor_rows",
            "status": "ok",
            "value": str(step6_74_donor_df.shape[0]),
        },
        {
            "profile_area": "receiver_rows",
            "status": "ok",
            "value": str(step6_74_receiver_df.shape[0]),
        },
        {
            "profile_area": "consistency_review_count",
            "status": "ok",
            "value": str(step6_76_review_count),
        },
        {
            "profile_area": "uses_global_fleet_optimization",
            "status": "ok",
            "value": "false",
        },
    ]
)

step6_76_output_profile_df.to_parquet(step6_76_output_profile_path, index=False)

step6_76_section_contract = {
    "block_name": "block_6",
    "section_name": "6.7",
    "section_scope": "microzone_local_balancing_layer",
    "source_grain": "day_station",
    "daily_plan_microzone_output_grain": "day_station",
    "microzone_summary_output_grain": "day_microzone",
    "local_pair_output_grain": "day_microzone_pair",
    "daily_plan_microzone_output_path": str(step6_76_daily_plan_microzone_output_path),
    "microzone_summary_output_path": str(step6_76_microzone_summary_output_path),
    "local_pair_output_path": str(step6_76_local_pair_output_path),
    "microzone_filter_field": "microzone_id",
    "pairing_method": "local_donor_receiver_heuristic",
    "uses_global_fleet_optimization": False,
    "daily_plan_microzone_rows": int(step6_76_daily_plan_with_microzone_output_df.shape[0]),
    "microzone_summary_rows": int(step6_76_microzone_summary_output_df.shape[0]),
    "local_pair_rows": int(step6_76_local_pair_output_df.shape[0]),
    "unique_date_count": int(step6_76_daily_plan_with_microzone_output_df["activity_date"].nunique()),
    "unique_microzone_count": int(step6_76_daily_plan_with_microzone_output_df["microzone_id"].nunique()),
    "donor_rows": int(step6_74_donor_df.shape[0]),
    "receiver_rows": int(step6_74_receiver_df.shape[0]),
    "consistency_review_count": step6_76_review_count,
}

with open(step6_76_section_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_76_section_contract, file, ensure_ascii=False, indent=2)

step6_76_section_status_df = pd.DataFrame(
    [
        {
            "section_item": "section_6_7_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "section_item": "daily_plan_microzone_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "section_item": "microzone_summary_grain",
            "status": "ok",
            "value": "day_microzone",
        },
        {
            "section_item": "local_pair_grain",
            "status": "ok",
            "value": "day_microzone_pair",
        },
        {
            "section_item": "daily_plan_microzone_rows",
            "status": "ok",
            "value": str(step6_76_daily_plan_with_microzone_output_df.shape[0]),
        },
        {
            "section_item": "microzone_summary_rows",
            "status": "ok",
            "value": str(step6_76_microzone_summary_output_df.shape[0]),
        },
        {
            "section_item": "local_pair_rows",
            "status": "ok",
            "value": str(step6_76_local_pair_output_df.shape[0]),
        },
        {
            "section_item": "consistency_review_count",
            "status": "ok",
            "value": str(step6_76_review_count),
        },
    ]
)

step6_76_section_status_df.to_parquet(step6_76_section_status_path, index=False)

step6_76_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_6_7_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "check_area": "daily_plan_microzone_rows",
            "status": "ok",
            "value": str(step6_76_daily_plan_with_microzone_output_df.shape[0]),
        },
        {
            "check_area": "microzone_summary_rows",
            "status": "ok",
            "value": str(step6_76_microzone_summary_output_df.shape[0]),
        },
        {
            "check_area": "local_pair_rows",
            "status": "ok",
            "value": str(step6_76_local_pair_output_df.shape[0]),
        },
        {
            "check_area": "daily_plan_microzone_output_path",
            "status": "ok",
            "value": str(step6_76_daily_plan_microzone_output_path),
        },
        {
            "check_area": "microzone_summary_output_path",
            "status": "ok",
            "value": str(step6_76_microzone_summary_output_path),
        },
        {
            "check_area": "local_pair_output_path",
            "status": "ok",
            "value": str(step6_76_local_pair_output_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_76_section_contract_path),
        },
        {
            "check_area": "status_path",
            "status": "ok",
            "value": str(step6_76_section_status_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_76_summary_df[column_name] = step6_76_summary_df[column_name].astype("string")

display(step6_76_summary_df)
display(step6_76_section_status_df)
display(step6_76_output_profile_df)
display(step6_76_microzone_summary_output_df.head(20))

,check_area,status,value
0,section_6_7_status,ok,closed
1,daily_plan_microzone_rows,ok,219071
2,microzone_summary_rows,ok,191777
3,local_pair_rows,ok,0
4,daily_plan_microzone_output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,microzone_summary_output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,local_pair_output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
8,status_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                 section_item status               value
0          section_6_7_status     ok              closed
1  daily_plan_microzone_grain     ok         day_station
2     microzone_summary_grain     ok       day_microzone
3            local_pair_grain     ok  day_microzone_pair
4   daily_plan_microzone_rows     ok              219071
5      microzone_summary_rows     ok              191777
6             local_pair_rows     ok                   0
7    consistency_review_count     ok                   0

                      profile_area status   value
0        daily_plan_microzone_rows     ok  219071
1     daily_plan_microzone_columns     ok      22
2           microzone_summary_rows     ok  191777
3        microzone_summary_columns     ok      15
4                  local_pair_rows     ok       0
5                     unique_dates     ok     839
6                unique_microzones     ok     304
7                       donor_rows     ok       0
8                    receiver_rows     ok  211990
9         consistency_review_count     ok       0
10  uses_global_fleet_optimization     ok   false

,activity_date,microzone_id,station_count,stations_to_deliver,stations_to_remove,stations_to_check,estimated_deliver_units,estimated_remove_units,microzone_balance,microzone_balance_direction,microzone_expected_business_impact,max_expected_business_impact,mean_expected_business_impact,top_priority_score,top_daily_plan_rank
0,2017-05-02,MZ_0067,8,8,0,0,60,0,-60,net_delivery_need,565.820862,111.562500,70.727608,1209.984985,3
1,2017-05-02,MZ_0054,3,3,0,0,44,0,-44,net_delivery_need,200.592712,73.021355,66.864235,833.073547,8
2,2017-05-02,MZ_0064,2,2,0,0,15,0,-15,net_delivery_need,177.458328,124.333328,88.729164,1327.043213,2
3,2017-05-02,MZ_0045,1,1,0,0,19,0,-19,net_delivery_need,128.742188,128.742188,128.742188,1411.951904,1
4,2017-05-02,MZ_0037,2,2,0,0,13,0,-13,net_delivery_need,111.639069,66.178131,55.819534,728.221313,14
5,2017-05-02,MZ_0099,1,1,0,0,7,0,-7,net_delivery_need,91.218750,91.218750,91.218750,980.877502,5
6,2017-05-02,MZ_0116,2,2,0,0,12,0,-12,net_delivery_need,84.795319,54.178127,42.397659,607.991272,21
7,2017-05-02,MZ_0141,2,2,0,0,11,0,-11,net_delivery_need,77.625000,40.312500,38.812500,459.635010,36
8,2017-05-02,MZ_0079,1,1,0,0,10,0,-10,net_delivery_need,77.145828,77.145828,77.145828,858.708252,6
9,2017-05-02,MZ_0113,1,1,0,0,9,0,-9,net_delivery_need,75.312500,75.312500,75.312500,826.744995,7
10,2017-05-02,MZ_0140,1,1,0,0,8,0,-8,net_delivery_need,72.021873,72.021873,72.021873,792.518738,9
11,2017-05-02,MZ_0021,1,1,0,0,7,0,-7,net_delivery_need,71.158340,71.158340,71.158340,776.073364,11
12,2017-05-02,MZ_0044,2,2,0,0,10,0,-10,net_delivery_need,71.156250,48.322914,35.578125,551.879150,26
13,2017-05-02,MZ_0083,2,2,0,0,9,0,-9,net_delivery_need,67.490631,57.928127,33.745316,640.661255,18
14,2017-05-02,MZ_0038,1,1,0,0,4,0,-4,net_delivery_need,65.770828,65.770828,65.770828,705.928223,15
15,2017-05-02,MZ_0052,2,2,0,0,9,0,-9,net_delivery_need,63.993752,47.962502,31.996876,536.275024,27
16,2017-05-02,MZ_0122,2,2,0,0,10,0,-10,net_delivery_need,62.437500,39.375000,31.218750,441.850006,37
17,2017-05-02,MZ_0193,1,1,0,0,5,0,-5,net_delivery_need,55.987499,55.987499,55.987499,622.395020,20
18,2017-05-02,MZ_0068,1,1,0,0,9,0,-9,net_delivery_need,52.447918,52.447918,52.447918,601.879211,23
19,2017-05-02,MZ_0153,2,2,0,0,9,0,-9,net_delivery_need,50.096870,32.043228,25.048435,375.432281,52

## Podsumowanie działu 6.7 Mikrostrefy i lokalne balansowanie

**Kontekst inżynieryjny:** W dziale `6.7` zbudowano warstwę mikrostref oraz lokalnego balansowania jako rozszerzenie finalnego planu dnia dyspozytora z działu `6.6`. Najpierw zdefiniowano kontrakt warstwy mikrostrefowej, obejmujący filtr `microzone_id`, podsumowanie mikrostref oraz lokalne pary kompensacyjne typu dawca–biorca. Następnie do planu dnia dołączono identyfikator mikrostrefy na podstawie mapowania `representative_station_id -> microzone_id`. Spośród dostępnych kandydatów wybrano źródło z pełnym pokryciem stacji, co pozwoliło przypisać mikrostrefę do każdego rekordu planu dnia. W kolejnym kroku zbudowano podsumowanie mikrostref na poziomie `day_microzone`, obejmujące liczbę stacji wymagających dowozu, liczbę stacji wymagających zabrania rowerów, liczbę stacji do sprawdzenia, szacowane jednostki dowozu i zabrania, bilans mikrostrefy oraz łączny `microzone_expected_business_impact`. Następnie przygotowano warstwę lokalnych par kompensacyjnych jako heurystykę `local_donor_receiver_heuristic`, działającą wyłącznie w obrębie tej samej mikrostrefy. Na końcu wykonano kontrolę spójności oraz zapisano finalne artefakty działu.

**Interpretacja wyniku:** Finalna warstwa planu dnia z mikrostrefami obejmuje `219 071` rekordów na poziomie `day_station`, `839` dni oraz `304` unikalne mikrostrefy. Pokrycie `microzone_id` wynosi `100%`, nie występują braki identyfikatora mikrostrefy ani duplikaty klucza `activity_date + representative_station_id`. Warstwa podsumowania mikrostref zawiera `191 777` rekordów na poziomie `day_microzone` i nie zawiera duplikatów klucza `activity_date + microzone_id`. W aktualnym wyniku dominują mikrostrefy z kierunkiem `net_delivery_need`, czyli z przewagą potrzeby dowozu rowerów. Dla przykładu w dniu `2017-05-02` mikrostrefa `MZ_0067` obejmuje `8` stacji, wszystkie z potrzebą dowozu, łączną szacowaną potrzebę `60` rowerów oraz `microzone_expected_business_impact` równy około `565.82`. Warstwa lokalnych par kompensacyjnych została przygotowana, ale nie utworzyła par, ponieważ w aktualnym planie dnia występują stacje-biorcy (`receiver_rows = 211 990`), natomiast nie występują stacje-dawcy (`donor_rows = 0`). Liczba lokalnych par wynosi więc `0`, a kontrola spójności zakończyła się wynikiem `0` reguł wymagających przeglądu.

**Znaczenie biznesowe:** Dział `6.7` rozszerza panel dyspozytora z poziomu pojedynczych stacji do poziomu lokalnych obszarów operacyjnych. Mikrostrefa może być używana jako filtr geograficzny, ale również jako narzędzie planowania pracy: pokazuje, gdzie kumuluje się potrzeba dowozu, ile stacji w danej strefie wymaga działania, jaki jest bilans strefy oraz jaki jest łączny potencjalny wpływ operacyjny. Dzięki temu dyspozytor może analizować nie tylko pojedyncze stacje, ale całe lokalne skupiska problemów. Warstwa par kompensacyjnych została zaprojektowana jako lokalna heurystyka dawca–biorca, a nie jako globalna optymalizacja floty. W aktualnym przebiegu danych brak par kompensacyjnych jest wynikiem struktury rekomendacji: system wskazuje potrzeby dowozu i kontroli, ale nie wskazuje stacji, z których można zabrać rowery. Taki zapis zachowuje uczciwą interpretację wyniku i nie przypisuje aplikacji funkcji, których dane w tym przebiegu nie wspierają.

**Wniosek:** Dział `6.7` został domknięty poprawnie. Zapisano finalne artefakty `b6_37_dispatcher_daily_plan_with_microzones.parquet`, `b6_37_microzone_summary.parquet` oraz `b6_37_microzone_local_pairs.parquet`, wraz z profilem, kontraktem i statusem działu. Warstwa mikrostref jest gotowa do użycia w panelu dyspozytora jako filtr, podsumowanie lokalnych potrzeb oraz podstawa lokalnego balansowania. W aktualnym wyniku lokalne pary dawca–biorca nie występują, ponieważ nie ma stacji z kierunkiem `remove`, ale mechanizm ich obsługi został przygotowany i pozostaje zgodny z kontraktem jako lokalna heurystyka mikrostrefowa, bez deklarowania globalnej optymalizacji floty.

## 6.8 Pewność rekomendacji

In [38]:
# 6.8.1 Definicja kontraktu pewności rekomendacji

import json

import pandas as pd


step6_81_required_objects = [
    "step6_76_daily_plan_with_microzone_output_df",
    "step6_11_reports_dir",
]

step6_81_missing_objects = [
    object_name
    for object_name in step6_81_required_objects
    if object_name not in globals()
]

assert not step6_81_missing_objects, f"Missing required objects: {step6_81_missing_objects}"

step6_81_confidence_contract = {
    "block_name": "block_6",
    "section_name": "6.8",
    "section_scope": "recommendation_confidence_layer",
    "source_object": "step6_76_daily_plan_with_microzone_output_df",
    "source_grain": "day_station",
    "output_grain": "day_station",
    "confidence_field": "recommendation_confidence_final",
    "allowed_confidence_values": [
        "high",
        "medium",
        "low",
    ],
    "main_screen_fields": [
        "recommendation_confidence_final",
        "low_confidence_action",
        "confidence_reason",
    ],
    "confidence_policy": {
        "high": "aligned_operational_signals",
        "medium": "mixed_or_partial_operational_signals",
        "low": "weak_or_control_required_signal",
    },
    "low_confidence_policy": {
        "recommended_display_action": "check_station_state",
        "show_station_check_message": True,
    },
    "system_knowledge_policy": {
        "claims_full_certainty": False,
        "uses_probabilistic_operational_confidence": True,
    },
}

step6_81_required_columns = [
    "activity_date",
    "daily_plan_rank",
    "representative_station_id",
    "station_name",
    "microzone_id",
    "priority_level",
    "problem_type",
    "recommended_action",
    "highest_risk_hour_label",
    "estimated_relocation_label",
    "recommendation_confidence",
    "decision_reason",
    "expected_business_impact",
    "priority_score",
    "station_business_scale",
    "estimated_relocation_units",
    "relocation_direction",
    "total_departures",
    "total_returns",
    "daily_net_flow",
]

step6_81_missing_columns = [
    column_name
    for column_name in step6_81_required_columns
    if column_name not in step6_76_daily_plan_with_microzone_output_df.columns
]

assert not step6_81_missing_columns, f"Missing required columns: {step6_81_missing_columns}"

step6_81_output_fields_df = pd.DataFrame(
    [
        {
            "field_name": "recommendation_confidence_final",
            "field_role": "main_confidence_label",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "low_confidence_action",
            "field_role": "station_check_instruction",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "confidence_reason",
            "field_role": "short_confidence_explanation",
            "source_grain": "day_station",
            "display_scope": "main_screen",
        },
        {
            "field_name": "confidence_score",
            "field_role": "technical_confidence_score",
            "source_grain": "day_station",
            "display_scope": "technical_support",
        },
    ]
)

for column_name in ["field_name", "field_role", "source_grain", "display_scope"]:
    step6_81_output_fields_df[column_name] = step6_81_output_fields_df[column_name].astype("string")

step6_81_allowed_values_df = pd.DataFrame(
    [
        {
            "recommendation_confidence_final": "high",
            "display_label": "high",
            "sort_order": 1,
            "interpretation": "aligned_operational_signals",
        },
        {
            "recommendation_confidence_final": "medium",
            "display_label": "medium",
            "sort_order": 2,
            "interpretation": "mixed_or_partial_operational_signals",
        },
        {
            "recommendation_confidence_final": "low",
            "display_label": "low",
            "sort_order": 3,
            "interpretation": "weak_or_control_required_signal",
        },
    ]
)

for column_name in ["recommendation_confidence_final", "display_label", "interpretation"]:
    step6_81_allowed_values_df[column_name] = step6_81_allowed_values_df[column_name].astype("string")

step6_81_contract_path = step6_11_reports_dir / "b6_38_recommendation_confidence_contract.json"
step6_81_output_fields_path = step6_11_reports_dir / "b6_38_recommendation_confidence_output_fields.parquet"
step6_81_allowed_values_path = step6_11_reports_dir / "b6_38_recommendation_confidence_allowed_values.parquet"

with open(step6_81_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_81_confidence_contract, file, ensure_ascii=False, indent=2)

step6_81_output_fields_df.to_parquet(step6_81_output_fields_path, index=False)
step6_81_allowed_values_df.to_parquet(step6_81_allowed_values_path, index=False)

step6_81_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_scope",
            "status": "ok",
            "value": "recommendation_confidence_layer",
        },
        {
            "check_area": "source_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "check_area": "required_columns",
            "status": "ok",
            "value": str(len(step6_81_required_columns)),
        },
        {
            "check_area": "allowed_confidence_values",
            "status": "ok",
            "value": str(step6_81_allowed_values_df.shape[0]),
        },
        {
            "check_area": "output_fields",
            "status": "ok",
            "value": str(step6_81_output_fields_df.shape[0]),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_81_contract_path),
        },
        {
            "check_area": "output_fields_path",
            "status": "ok",
            "value": str(step6_81_output_fields_path),
        },
        {
            "check_area": "allowed_values_path",
            "status": "ok",
            "value": str(step6_81_allowed_values_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_81_summary_df[column_name] = step6_81_summary_df[column_name].astype("string")

display(step6_81_summary_df)
display(step6_81_output_fields_df)
display(step6_81_allowed_values_df)

,check_area,status,value
0,section_scope,ok,recommendation_confidence_layer
1,source_grain,ok,day_station
2,required_columns,ok,20
3,allowed_confidence_values,ok,3
4,output_fields,ok,4
5,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,output_fields_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,allowed_values_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,field_name,field_role,source_grain,display_scope
0,recommendation_confidence_final,main_confidence_label,day_station,main_screen
1,low_confidence_action,station_check_instruction,day_station,main_screen
2,confidence_reason,short_confidence_explanation,day_station,main_screen
3,confidence_score,technical_confidence_score,day_station,technical_support

,recommendation_confidence_final,display_label,sort_order,interpretation
0,high,high,1,aligned_operational_signals
1,medium,medium,2,mixed_or_partial_operational_signals
2,low,low,3,weak_or_control_required_signal

In [39]:
# 6.8.2 Budowa wskaźnika pewności rekomendacji

import numpy as np
import pandas as pd


step6_82_required_objects = [
    "step6_76_daily_plan_with_microzone_output_df",
    "step6_11_reports_dir",
]

step6_82_missing_objects = [
    object_name
    for object_name in step6_82_required_objects
    if object_name not in globals()
]

assert not step6_82_missing_objects, f"Missing required objects: {step6_82_missing_objects}"

step6_82_confidence_df = step6_76_daily_plan_with_microzone_output_df.copy()

step6_82_confidence_df["recommendation_confidence"] = (
    step6_82_confidence_df["recommendation_confidence"]
    .astype("string")
)

step6_82_confidence_df["problem_type"] = (
    step6_82_confidence_df["problem_type"]
    .astype("string")
)

step6_82_confidence_df["recommended_action"] = (
    step6_82_confidence_df["recommended_action"]
    .astype("string")
)

step6_82_confidence_df["relocation_direction"] = (
    step6_82_confidence_df["relocation_direction"]
    .astype("string")
)

step6_82_confidence_df["confidence_score"] = 0.0

step6_82_confidence_df["confidence_score"] = (
    step6_82_confidence_df["confidence_score"]
    + np.where(step6_82_confidence_df["recommendation_confidence"] == "high", 40.0, 0.0)
    + np.where(step6_82_confidence_df["recommendation_confidence"] == "medium", 25.0, 0.0)
    + np.where(step6_82_confidence_df["recommendation_confidence"] == "low", 10.0, 0.0)
    + np.where(step6_82_confidence_df["problem_type"] == "bike_shortage_risk", 20.0, 0.0)
    + np.where(step6_82_confidence_df["problem_type"] == "mixed_risk", 10.0, 0.0)
    + np.where(step6_82_confidence_df["recommended_action"] == "deliver_bikes", 15.0, 0.0)
    + np.where(step6_82_confidence_df["recommended_action"] == "check_station_state", 5.0, 0.0)
    + np.where(step6_82_confidence_df["relocation_direction"] == "deliver", 15.0, 0.0)
    + np.where(step6_82_confidence_df["relocation_direction"] == "check", 5.0, 0.0)
    + np.where(step6_82_confidence_df["estimated_relocation_units"].fillna(0) > 0, 10.0, 0.0)
)

step6_82_confidence_df["confidence_score"] = (
    step6_82_confidence_df["confidence_score"]
    .clip(lower=0.0, upper=100.0)
    .astype("float32")
)

step6_82_confidence_df["recommendation_confidence_final"] = pd.Series(
    "low",
    index=step6_82_confidence_df.index,
    dtype="string",
)

step6_82_confidence_df.loc[
    step6_82_confidence_df["confidence_score"] >= 70.0,
    "recommendation_confidence_final",
] = "high"

step6_82_confidence_df.loc[
    (step6_82_confidence_df["confidence_score"] >= 45.0)
    & (step6_82_confidence_df["confidence_score"] < 70.0),
    "recommendation_confidence_final",
] = "medium"

step6_82_confidence_df["low_confidence_action"] = pd.Series(
    "",
    index=step6_82_confidence_df.index,
    dtype="string",
)

step6_82_confidence_df.loc[
    step6_82_confidence_df["recommendation_confidence_final"] == "low",
    "low_confidence_action",
] = "check_station_state"

step6_82_confidence_df["confidence_reason"] = pd.Series(
    "weak_or_control_required_signal",
    index=step6_82_confidence_df.index,
    dtype="string",
)

step6_82_confidence_df.loc[
    step6_82_confidence_df["recommendation_confidence_final"] == "high",
    "confidence_reason",
] = "aligned_operational_signals"

step6_82_confidence_df.loc[
    step6_82_confidence_df["recommendation_confidence_final"] == "medium",
    "confidence_reason",
] = "mixed_or_partial_operational_signals"

step6_82_missing_confidence_count = int(
    step6_82_confidence_df["recommendation_confidence_final"].isna().sum()
)

step6_82_invalid_confidence_count = int(
    (
        ~step6_82_confidence_df["recommendation_confidence_final"]
        .isin(["high", "medium", "low"])
    ).sum()
)

step6_82_duplicate_day_station_count = int(
    step6_82_confidence_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_82_profile_df = pd.DataFrame(
    [
        {
            "check_area": "confidence_rows",
            "status": "ok",
            "value": str(step6_82_confidence_df.shape[0]),
        },
        {
            "check_area": "confidence_columns",
            "status": "ok",
            "value": str(step6_82_confidence_df.shape[1]),
        },
        {
            "check_area": "missing_confidence_final",
            "status": "ok" if step6_82_missing_confidence_count == 0 else "review",
            "value": str(step6_82_missing_confidence_count),
        },
        {
            "check_area": "invalid_confidence_final",
            "status": "ok" if step6_82_invalid_confidence_count == 0 else "review",
            "value": str(step6_82_invalid_confidence_count),
        },
        {
            "check_area": "duplicate_day_station_keys",
            "status": "ok" if step6_82_duplicate_day_station_count == 0 else "review",
            "value": str(step6_82_duplicate_day_station_count),
        },
        {
            "check_area": "observed_confidence_values",
            "status": "ok",
            "value": str(step6_82_confidence_df["recommendation_confidence_final"].nunique()),
        },
    ]
)

step6_82_confidence_summary_df = (
    step6_82_confidence_df
    .groupby("recommendation_confidence_final", observed=True)
    .agg(
        row_count=("recommendation_confidence_final", "size"),
        mean_confidence_score=("confidence_score", "mean"),
        median_confidence_score=("confidence_score", "median"),
        min_confidence_score=("confidence_score", "min"),
        max_confidence_score=("confidence_score", "max"),
        mean_expected_business_impact=("expected_business_impact", "mean"),
        mean_estimated_relocation_units=("estimated_relocation_units", "mean"),
    )
    .reset_index()
)

step6_82_confidence_summary_df["row_share"] = (
    step6_82_confidence_summary_df["row_count"]
    / step6_82_confidence_summary_df["row_count"].sum()
)

step6_82_confidence_profile_path = step6_11_reports_dir / "b6_39_recommendation_confidence_profile.parquet"
step6_82_confidence_summary_path = step6_11_reports_dir / "b6_39_recommendation_confidence_summary.parquet"

step6_82_profile_df.to_parquet(step6_82_confidence_profile_path, index=False)
step6_82_confidence_summary_df.to_parquet(step6_82_confidence_summary_path, index=False)

display(step6_82_profile_df)
display(step6_82_confidence_summary_df)
display(
    step6_82_confidence_df[
        [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "priority_level",
            "problem_type",
            "recommended_action",
            "recommendation_confidence",
            "recommendation_confidence_final",
            "confidence_score",
            "confidence_reason",
            "low_confidence_action",
            "expected_business_impact",
            "estimated_relocation_label",
        ]
    ].head(20)
)

                   check_area status   value
0             confidence_rows     ok  219071
1          confidence_columns     ok      26
2    missing_confidence_final     ok       0
3    invalid_confidence_final     ok       0
4  duplicate_day_station_keys     ok       0
5  observed_confidence_values     ok       3

,recommendation_confidence_final,row_count,mean_confidence_score,median_confidence_score,min_confidence_score,max_confidence_score,mean_expected_business_impact,mean_estimated_relocation_units,row_share
0,high,211990,90.410728,85.0,70.0,100.0,44.597599,2.951243,0.967677
1,low,529,30.000000,30.0,30.0,30.0,39.746021,0.000000,0.002415
2,medium,6552,45.000000,45.0,45.0,45.0,82.337303,0.000000,0.029908

,activity_date,daily_plan_rank,representative_station_id,station_name,priority_level,problem_type,recommended_action,recommendation_confidence,recommendation_confidence_final,confidence_score,confidence_reason,low_confidence_action,expected_business_impact,estimated_relocation_label
0,2017-05-02,1,30,Itämerentori,very_high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,128.742188,deliver 18-20
1,2017-05-02,2,26,Kamppi (M),very_high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,124.333328,deliver 9-11
2,2017-05-02,3,21,Töölönlahdenkatu,very_high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,111.562500,deliver 11-13
3,2017-05-02,4,25,Narinkka,very_high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,103.812500,deliver 7-9
4,2017-05-02,5,40,Hakaniemi (M),high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,91.218750,deliver 6-8
5,2017-05-02,6,17,Varsapuistikko,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,77.145828,deliver 9-11
6,2017-05-02,7,41,Ympyrätalo,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,75.312500,deliver 8-10
7,2017-05-02,8,9,Erottajan aukio,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,73.021355,deliver 13-15
8,2017-05-02,9,44,Sörnäinen (M),high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,72.021873,deliver 7-9
9,2017-05-02,10,22,Rautatientori / länsi,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,71.437500,deliver 8-10
10,2017-05-02,11,5,Sepänkatu,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,71.158340,deliver 6-8
11,2017-05-02,12,11,Unioninkatu,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,69.125000,deliver 19-21
12,2017-05-02,13,23,Kiasma,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,66.458336,deliver 8-10
13,2017-05-02,14,29,Baana,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,66.178131,deliver 6-8
14,2017-05-02,15,6,Hietalahdentori,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,65.770828,deliver 3-5
15,2017-05-02,16,19,Rautatientori / itä,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,62.387497,deliver 6-8
16,2017-05-02,17,14,Senaatintori,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,58.446354,deliver 9-11
17,2017-05-02,18,150,Töölönlahden puisto,high,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,57.928127,deliver 5-7
18,2017-05-02,19,20,Kaisaniemenpuisto,medium,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,57.409901,deliver 5-7
19,2017-05-02,20,112,Rautatieläisenkatu,medium,bike_shortage_risk,deliver_bikes,high,high,100.0,aligned_operational_signals,,55.987499,deliver 4-6

In [40]:
# 6.8.3 Kontrola spójności pewności rekomendacji

import json

import pandas as pd


step6_83_required_objects = [
    "step6_82_confidence_df",
    "step6_11_reports_dir",
]

step6_83_missing_objects = [
    object_name
    for object_name in step6_83_required_objects
    if object_name not in globals()
]

assert not step6_83_missing_objects, f"Missing required objects: {step6_83_missing_objects}"

step6_83_allowed_confidence_values = ["high", "medium", "low"]

step6_83_duplicate_day_station_count = int(
    step6_82_confidence_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_83_missing_confidence_count = int(
    step6_82_confidence_df["recommendation_confidence_final"].isna().sum()
)

step6_83_invalid_confidence_count = int(
    (
        ~step6_82_confidence_df["recommendation_confidence_final"]
        .isin(step6_83_allowed_confidence_values)
    ).sum()
)

step6_83_missing_confidence_score_count = int(
    step6_82_confidence_df["confidence_score"].isna().sum()
)

step6_83_score_below_range_count = int(
    (step6_82_confidence_df["confidence_score"] < 0).sum()
)

step6_83_score_above_range_count = int(
    (step6_82_confidence_df["confidence_score"] > 100).sum()
)

step6_83_low_without_action_count = int(
    (
        (step6_82_confidence_df["recommendation_confidence_final"].astype("string") == "low")
        & (step6_82_confidence_df["low_confidence_action"].astype("string") != "check_station_state")
    ).sum()
)

step6_83_non_low_with_action_count = int(
    (
        (step6_82_confidence_df["recommendation_confidence_final"].astype("string") != "low")
        & (step6_82_confidence_df["low_confidence_action"].astype("string") != "")
    ).sum()
)

step6_83_high_reason_mismatch_count = int(
    (
        (step6_82_confidence_df["recommendation_confidence_final"].astype("string") == "high")
        & (step6_82_confidence_df["confidence_reason"].astype("string") != "aligned_operational_signals")
    ).sum()
)

step6_83_medium_reason_mismatch_count = int(
    (
        (step6_82_confidence_df["recommendation_confidence_final"].astype("string") == "medium")
        & (step6_82_confidence_df["confidence_reason"].astype("string") != "mixed_or_partial_operational_signals")
    ).sum()
)

step6_83_low_reason_mismatch_count = int(
    (
        (step6_82_confidence_df["recommendation_confidence_final"].astype("string") == "low")
        & (step6_82_confidence_df["confidence_reason"].astype("string") != "weak_or_control_required_signal")
    ).sum()
)

step6_83_consistency_rules = [
    {
        "rule_name": "no_duplicate_day_station_keys",
        "condition_passed": step6_83_duplicate_day_station_count == 0,
        "value": str(step6_83_duplicate_day_station_count),
    },
    {
        "rule_name": "no_missing_confidence_final",
        "condition_passed": step6_83_missing_confidence_count == 0,
        "value": str(step6_83_missing_confidence_count),
    },
    {
        "rule_name": "no_invalid_confidence_final",
        "condition_passed": step6_83_invalid_confidence_count == 0,
        "value": str(step6_83_invalid_confidence_count),
    },
    {
        "rule_name": "no_missing_confidence_score",
        "condition_passed": step6_83_missing_confidence_score_count == 0,
        "value": str(step6_83_missing_confidence_score_count),
    },
    {
        "rule_name": "confidence_score_not_below_zero",
        "condition_passed": step6_83_score_below_range_count == 0,
        "value": str(step6_83_score_below_range_count),
    },
    {
        "rule_name": "confidence_score_not_above_one_hundred",
        "condition_passed": step6_83_score_above_range_count == 0,
        "value": str(step6_83_score_above_range_count),
    },
    {
        "rule_name": "low_confidence_has_station_check_action",
        "condition_passed": step6_83_low_without_action_count == 0,
        "value": str(step6_83_low_without_action_count),
    },
    {
        "rule_name": "non_low_confidence_has_no_low_action",
        "condition_passed": step6_83_non_low_with_action_count == 0,
        "value": str(step6_83_non_low_with_action_count),
    },
    {
        "rule_name": "high_confidence_reason_matches_contract",
        "condition_passed": step6_83_high_reason_mismatch_count == 0,
        "value": str(step6_83_high_reason_mismatch_count),
    },
    {
        "rule_name": "medium_confidence_reason_matches_contract",
        "condition_passed": step6_83_medium_reason_mismatch_count == 0,
        "value": str(step6_83_medium_reason_mismatch_count),
    },
    {
        "rule_name": "low_confidence_reason_matches_contract",
        "condition_passed": step6_83_low_reason_mismatch_count == 0,
        "value": str(step6_83_low_reason_mismatch_count),
    },
]

step6_83_consistency_df = pd.DataFrame(step6_83_consistency_rules)

step6_83_consistency_df["status"] = step6_83_consistency_df["condition_passed"].map(
    {
        True: "ok",
        False: "review",
    }
)

step6_83_review_count = int(
    (step6_83_consistency_df["status"] == "review").sum()
)

step6_83_confidence_action_summary_df = (
    step6_82_confidence_df
    .groupby(
        [
            "recommendation_confidence_final",
            "recommended_action",
            "low_confidence_action",
        ],
        observed=True,
    )
    .agg(
        row_count=("recommendation_confidence_final", "size"),
        mean_confidence_score=("confidence_score", "mean"),
        mean_expected_business_impact=("expected_business_impact", "mean"),
        mean_estimated_relocation_units=("estimated_relocation_units", "mean"),
    )
    .reset_index()
)

step6_83_confidence_action_summary_df["row_share"] = (
    step6_83_confidence_action_summary_df["row_count"]
    / step6_83_confidence_action_summary_df["row_count"].sum()
)

step6_83_contract = {
    "block_name": "block_6",
    "section_name": "6.8",
    "contract_scope": "recommendation_confidence_consistency",
    "source_object": "step6_82_confidence_df",
    "source_grain": "day_station",
    "allowed_confidence_values": step6_83_allowed_confidence_values,
    "low_confidence_action": "check_station_state",
    "confidence_score_min": 0,
    "confidence_score_max": 100,
    "row_count": int(step6_82_confidence_df.shape[0]),
    "consistency_review_count": step6_83_review_count,
}

step6_83_consistency_path = step6_11_reports_dir / "b6_40_recommendation_confidence_consistency.parquet"
step6_83_action_summary_path = step6_11_reports_dir / "b6_40_recommendation_confidence_action_summary.parquet"
step6_83_contract_path = step6_11_reports_dir / "b6_40_recommendation_confidence_consistency_contract.json"

step6_83_consistency_df.to_parquet(step6_83_consistency_path, index=False)
step6_83_confidence_action_summary_df.to_parquet(step6_83_action_summary_path, index=False)

with open(step6_83_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_83_contract, file, ensure_ascii=False, indent=2)

step6_83_summary_df = pd.DataFrame(
    [
        {
            "check_area": "consistency_rules",
            "status": "ok",
            "value": str(step6_83_consistency_df.shape[0]),
        },
        {
            "check_area": "consistency_review_count",
            "status": "ok" if step6_83_review_count == 0 else "review",
            "value": str(step6_83_review_count),
        },
        {
            "check_area": "confidence_rows",
            "status": "ok",
            "value": str(step6_82_confidence_df.shape[0]),
        },
        {
            "check_area": "observed_confidence_values",
            "status": "ok",
            "value": str(step6_82_confidence_df["recommendation_confidence_final"].nunique()),
        },
        {
            "check_area": "low_confidence_rows",
            "status": "ok",
            "value": str(int((step6_82_confidence_df["recommendation_confidence_final"] == "low").sum())),
        },
        {
            "check_area": "consistency_path",
            "status": "ok",
            "value": str(step6_83_consistency_path),
        },
        {
            "check_area": "action_summary_path",
            "status": "ok",
            "value": str(step6_83_action_summary_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_83_contract_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_83_summary_df[column_name] = step6_83_summary_df[column_name].astype("string")

display(step6_83_summary_df)
display(step6_83_consistency_df)
display(step6_83_confidence_action_summary_df)

,check_area,status,value
0,consistency_rules,ok,11
1,consistency_review_count,ok,0
2,confidence_rows,ok,219071
3,observed_confidence_values,ok,3
4,low_confidence_rows,ok,529
5,consistency_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,action_summary_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                                    rule_name  condition_passed value status
0               no_duplicate_day_station_keys              True     0     ok
1                 no_missing_confidence_final              True     0     ok
2                 no_invalid_confidence_final              True     0     ok
3                 no_missing_confidence_score              True     0     ok
4             confidence_score_not_below_zero              True     0     ok
5      confidence_score_not_above_one_hundred              True     0     ok
6     low_confidence_has_station_check_action              True     0     ok
7        non_low_confidence_has_no_low_action              True     0     ok
8     high_confidence_reason_matches_contract              True     0     ok
9   medium_confidence_reason_matches_contract              True     0     ok
10     low_confidence_reason_matches_contract              True     0     ok

,recommendation_confidence_final,recommended_action,low_confidence_action,row_count,mean_confidence_score,mean_expected_business_impact,mean_estimated_relocation_units,row_share
0,high,deliver_bikes,,211990,90.410728,44.597599,2.951243,0.967677
1,low,check_station_state,check_station_state,529,30.000000,39.746021,0.000000,0.002415
2,medium,check_station_state,,6552,45.000000,82.337303,0.000000,0.029908

In [41]:
# 6.8.4 Zamknięcie warstwy pewności rekomendacji

import json

import pandas as pd


step6_84_required_objects = [
    "step6_82_confidence_df",
    "step6_83_consistency_df",
    "step6_83_confidence_action_summary_df",
    "step6_11_reports_dir",
    "step6_11_outputs_dir",
]

step6_84_missing_objects = [
    object_name
    for object_name in step6_84_required_objects
    if object_name not in globals()
]

assert not step6_84_missing_objects, f"Missing required objects: {step6_84_missing_objects}"

step6_84_review_count = int(
    (step6_83_consistency_df["status"].astype("string") == "review").sum()
)

step6_84_duplicate_day_station_count = int(
    step6_82_confidence_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_84_missing_confidence_count = int(
    step6_82_confidence_df["recommendation_confidence_final"].isna().sum()
)

step6_84_invalid_confidence_count = int(
    (
        ~step6_82_confidence_df["recommendation_confidence_final"]
        .isin(["high", "medium", "low"])
    ).sum()
)

assert step6_84_review_count == 0, "Recommendation confidence consistency review detected."
assert step6_84_duplicate_day_station_count == 0, "Duplicated day-station keys detected."
assert step6_84_missing_confidence_count == 0, "Missing recommendation_confidence_final values detected."
assert step6_84_invalid_confidence_count == 0, "Invalid recommendation_confidence_final values detected."

step6_84_output_columns = [
    "activity_date",
    "daily_plan_rank",
    "representative_station_id",
    "station_name",
    "microzone_id",
    "priority_level",
    "problem_type",
    "recommended_action",
    "recommendation_confidence_final",
    "confidence_score",
    "confidence_reason",
    "low_confidence_action",
    "highest_risk_hour_label",
    "estimated_relocation_label",
    "expected_business_impact",
    "priority_score",
    "station_business_scale",
    "estimated_relocation_units",
    "estimated_relocation_min",
    "estimated_relocation_max",
    "relocation_direction",
    "total_departures",
    "total_returns",
    "daily_net_flow",
]

step6_84_missing_output_columns = [
    column_name
    for column_name in step6_84_output_columns
    if column_name not in step6_82_confidence_df.columns
]

assert not step6_84_missing_output_columns, f"Missing output columns: {step6_84_missing_output_columns}"

step6_84_confidence_output_df = (
    step6_82_confidence_df[step6_84_output_columns]
    .sort_values(["activity_date", "daily_plan_rank"])
    .reset_index(drop=True)
)

step6_84_output_path = step6_11_outputs_dir / "b6_41_dispatcher_daily_plan_with_confidence.parquet"
step6_84_profile_path = step6_11_reports_dir / "b6_41_recommendation_confidence_output_profile.parquet"
step6_84_action_summary_path = step6_11_reports_dir / "b6_41_recommendation_confidence_action_summary.parquet"
step6_84_contract_path = step6_11_reports_dir / "b6_41_recommendation_confidence_section_contract.json"
step6_84_status_path = step6_11_reports_dir / "b6_41_recommendation_confidence_section_status.parquet"

step6_84_confidence_output_df.to_parquet(step6_84_output_path, index=False)
step6_83_confidence_action_summary_df.to_parquet(step6_84_action_summary_path, index=False)

step6_84_profile_df = pd.DataFrame(
    [
        {
            "profile_area": "confidence_output_rows",
            "status": "ok",
            "value": str(step6_84_confidence_output_df.shape[0]),
        },
        {
            "profile_area": "confidence_output_columns",
            "status": "ok",
            "value": str(step6_84_confidence_output_df.shape[1]),
        },
        {
            "profile_area": "unique_dates",
            "status": "ok",
            "value": str(step6_84_confidence_output_df["activity_date"].nunique()),
        },
        {
            "profile_area": "unique_stations",
            "status": "ok",
            "value": str(step6_84_confidence_output_df["representative_station_id"].nunique()),
        },
        {
            "profile_area": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_84_duplicate_day_station_count),
        },
        {
            "profile_area": "missing_confidence_final",
            "status": "ok",
            "value": str(step6_84_missing_confidence_count),
        },
        {
            "profile_area": "invalid_confidence_final",
            "status": "ok",
            "value": str(step6_84_invalid_confidence_count),
        },
        {
            "profile_area": "observed_confidence_values",
            "status": "ok",
            "value": str(step6_84_confidence_output_df["recommendation_confidence_final"].nunique()),
        },
        {
            "profile_area": "low_confidence_rows",
            "status": "ok",
            "value": str(int((step6_84_confidence_output_df["recommendation_confidence_final"] == "low").sum())),
        },
        {
            "profile_area": "consistency_review_count",
            "status": "ok",
            "value": str(step6_84_review_count),
        },
    ]
)

step6_84_profile_df.to_parquet(step6_84_profile_path, index=False)

step6_84_contract = {
    "block_name": "block_6",
    "section_name": "6.8",
    "section_scope": "recommendation_confidence_layer",
    "source_object": "step6_82_confidence_df",
    "output_object": "step6_84_confidence_output_df",
    "output_grain": "day_station",
    "output_path": str(step6_84_output_path),
    "allowed_confidence_values": ["high", "medium", "low"],
    "confidence_score_min": 0,
    "confidence_score_max": 100,
    "low_confidence_action": "check_station_state",
    "row_count": int(step6_84_confidence_output_df.shape[0]),
    "column_count": int(step6_84_confidence_output_df.shape[1]),
    "unique_date_count": int(step6_84_confidence_output_df["activity_date"].nunique()),
    "unique_station_count": int(step6_84_confidence_output_df["representative_station_id"].nunique()),
    "consistency_review_count": step6_84_review_count,
    "claims_full_certainty": False,
}

with open(step6_84_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_84_contract, file, ensure_ascii=False, indent=2)

step6_84_status_df = pd.DataFrame(
    [
        {
            "section_item": "section_6_8_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "section_item": "output_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "section_item": "output_rows",
            "status": "ok",
            "value": str(step6_84_confidence_output_df.shape[0]),
        },
        {
            "section_item": "output_columns",
            "status": "ok",
            "value": str(step6_84_confidence_output_df.shape[1]),
        },
        {
            "section_item": "observed_confidence_values",
            "status": "ok",
            "value": str(sorted(step6_84_confidence_output_df["recommendation_confidence_final"].astype("string").unique().tolist())),
        },
        {
            "section_item": "low_confidence_rows",
            "status": "ok",
            "value": str(int((step6_84_confidence_output_df["recommendation_confidence_final"] == "low").sum())),
        },
        {
            "section_item": "consistency_review_count",
            "status": "ok",
            "value": str(step6_84_review_count),
        },
    ]
)

step6_84_status_df.to_parquet(step6_84_status_path, index=False)

step6_84_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_6_8_status",
            "status": "ok",
            "value": "closed",
        },
        {
            "check_area": "confidence_output_rows",
            "status": "ok",
            "value": str(step6_84_confidence_output_df.shape[0]),
        },
        {
            "check_area": "confidence_output_columns",
            "status": "ok",
            "value": str(step6_84_confidence_output_df.shape[1]),
        },
        {
            "check_area": "observed_confidence_values",
            "status": "ok",
            "value": str(step6_84_confidence_output_df["recommendation_confidence_final"].nunique()),
        },
        {
            "check_area": "low_confidence_rows",
            "status": "ok",
            "value": str(int((step6_84_confidence_output_df["recommendation_confidence_final"] == "low").sum())),
        },
        {
            "check_area": "output_path",
            "status": "ok",
            "value": str(step6_84_output_path),
        },
        {
            "check_area": "profile_path",
            "status": "ok",
            "value": str(step6_84_profile_path),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_84_contract_path),
        },
        {
            "check_area": "status_path",
            "status": "ok",
            "value": str(step6_84_status_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_84_summary_df[column_name] = step6_84_summary_df[column_name].astype("string")

display(step6_84_summary_df)
display(step6_84_status_df)
display(step6_84_profile_df)
display(step6_84_confidence_output_df.head(20))

,check_area,status,value
0,section_6_8_status,ok,closed
1,confidence_output_rows,ok,219071
2,confidence_output_columns,ok,24
3,observed_confidence_values,ok,3
4,low_confidence_rows,ok,529
5,output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,profile_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
8,status_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

                 section_item status                      value
0          section_6_8_status     ok                     closed
1                output_grain     ok                day_station
2                 output_rows     ok                     219071
3              output_columns     ok                         24
4  observed_confidence_values     ok  ['high', 'low', 'medium']
5         low_confidence_rows     ok                        529
6    consistency_review_count     ok                          0

                 profile_area status   value
0      confidence_output_rows     ok  219071
1   confidence_output_columns     ok      24
2                unique_dates     ok     839
3             unique_stations     ok     344
4  duplicate_day_station_keys     ok       0
5    missing_confidence_final     ok       0
6    invalid_confidence_final     ok       0
7  observed_confidence_values     ok       3
8         low_confidence_rows     ok     529
9    consistency_review_count     ok       0

,activity_date,daily_plan_rank,representative_station_id,station_name,microzone_id,priority_level,problem_type,recommended_action,recommendation_confidence_final,confidence_score,...,expected_business_impact,priority_score,station_business_scale,estimated_relocation_units,estimated_relocation_min,estimated_relocation_max,relocation_direction,total_departures,total_returns,daily_net_flow
0,2017-05-02,1,30,Itämerentori,MZ_0045,very_high,bike_shortage_risk,deliver_bikes,high,100.0,...,128.742188,1411.951904,205.987503,19,18,20,deliver,91,57,-34
1,2017-05-02,2,26,Kamppi (M),MZ_0064,very_high,bike_shortage_risk,deliver_bikes,high,100.0,...,124.333328,1327.043213,149.199997,10,9,11,deliver,71,55,-16
2,2017-05-02,3,21,Töölönlahdenkatu,MZ_0067,very_high,bike_shortage_risk,deliver_bikes,high,100.0,...,111.562500,1209.984985,127.500000,12,11,13,deliver,57,51,-6
3,2017-05-02,4,25,Narinkka,MZ_0067,very_high,bike_shortage_risk,deliver_bikes,high,100.0,...,103.812500,1114.135010,113.250000,8,7,9,deliver,55,36,-19
4,2017-05-02,5,40,Hakaniemi (M),MZ_0099,high,bike_shortage_risk,deliver_bikes,high,100.0,...,91.218750,980.877502,109.462502,7,6,8,deliver,53,34,-19
5,2017-05-02,6,17,Varsapuistikko,MZ_0079,high,bike_shortage_risk,deliver_bikes,high,100.0,...,77.145828,858.708252,80.500000,10,9,11,deliver,34,18,-16
6,2017-05-02,7,41,Ympyrätalo,MZ_0113,high,bike_shortage_risk,deliver_bikes,high,100.0,...,75.312500,826.744995,120.500000,9,8,10,deliver,47,49,2
7,2017-05-02,8,9,Erottajan aukio,MZ_0054,high,bike_shortage_risk,deliver_bikes,high,100.0,...,73.021355,833.073547,92.237503,14,13,15,deliver,38,22,-16
8,2017-05-02,9,44,Sörnäinen (M),MZ_0140,high,bike_shortage_risk,deliver_bikes,high,100.0,...,72.021873,792.518738,90.974998,8,7,9,deliver,39,40,1
9,2017-05-02,10,22,Rautatientori / länsi,MZ_0067,high,bike_shortage_risk,deliver_bikes,high,100.0,...,71.437500,792.755005,85.724998,9,8,10,deliver,39,30,-9
10,2017-05-02,11,5,Sepänkatu,MZ_0021,high,bike_shortage_risk,deliver_bikes,high,100.0,...,71.158340,776.073364,106.737503,7,6,8,deliver,51,38,-13
11,2017-05-02,12,11,Unioninkatu,MZ_0054,high,bike_shortage_risk,deliver_bikes,high,100.0,...,69.125000,825.750000,79.000000,20,19,21,deliver,29,19,-10
12,2017-05-02,13,23,Kiasma,MZ_0067,high,bike_shortage_risk,deliver_bikes,high,100.0,...,66.458336,745.103394,72.500000,9,8,10,deliver,33,20,-13
13,2017-05-02,14,29,Baana,MZ_0037,high,bike_shortage_risk,deliver_bikes,high,100.0,...,66.178131,728.221313,88.237503,7,6,8,deliver,39,34,-5
14,2017-05-02,15,6,Hietalahdentori,MZ_0038,high,bike_shortage_risk,deliver_bikes,high,100.0,...,65.770828,705.928223,112.750000,4,3,5,deliver,49,40,-9
15,2017-05-02,16,19,Rautatientori / itä,MZ_0067,high,bike_shortage_risk,deliver_bikes,high,100.0,...,62.387497,686.275024,106.949997,7,6,8,deliver,45,47,2
16,2017-05-02,17,14,Senaatintori,MZ_0054,high,bike_shortage_risk,deliver_bikes,high,100.0,...,58.446354,671.083557,60.987499,10,9,11,deliver,28,12,-16
17,2017-05-02,18,150,Töölönlahden puisto,MZ_0083,high,bike_shortage_risk,deliver_bikes,high,100.0,...,57.928127,640.661255,77.237503,6,5,7,deliver,36,27,-9
18,2017-05-02,19,20,Kaisaniemenpuisto,MZ_0067,medium,bike_shortage_risk,deliver_bikes,high,100.0,...,57.409901,630.499023,105.987503,6,5,7,deliver,46,45,-1
19,2017-05-02,20,112,Rautatieläisenkatu,MZ_0193,medium,bike_shortage_risk,deliver_bikes,high,100.0,...,55.987499,622.395020,55.987499,5,4,6,deliver,27,14,-13

## Podsumowanie działu 6.8 Pewność rekomendacji

**Kontekst inżynieryjny:** W dziale `6.8` zbudowano warstwę pewności rekomendacji jako rozszerzenie finalnego planu dnia dyspozytora. Najpierw zdefiniowano kontrakt warstwy `recommendation_confidence_layer`, obejmujący trzy dopuszczalne poziomy pewności: `high`, `medium` oraz `low`. Następnie na podstawie wcześniejszych sygnałów operacyjnych, typu problemu, rekomendowanej akcji, kierunku relokacji oraz szacowanej liczby jednostek relokacji wyliczono techniczny `confidence_score` w zakresie od `0` do `100`. Na jego podstawie utworzono finalną etykietę `recommendation_confidence_final`, pole `confidence_reason` oraz pomocnicze pole `low_confidence_action`, które przy niskiej pewności wskazuje konieczność sprawdzenia stanu stacji. W kolejnym kroku przeprowadzono kontrolę spójności, obejmującą poprawność wartości pewności, brak duplikatów klucza dzień–stacja, brak wartości spoza kontraktu, zakres punktacji oraz zgodność powodów pewności z finalną etykietą. Na końcu zapisano finalny output działu do pliku `b6_41_dispatcher_daily_plan_with_confidence.parquet`.

**Interpretacja wyniku:** Finalna warstwa pewności rekomendacji obejmuje `219 071` rekordów na poziomie `day_station`, `839` dni oraz `344` unikalne stacje. Nie występują duplikaty klucza `activity_date + representative_station_id`, braki w polu `recommendation_confidence_final` ani wartości spoza dopuszczalnego zbioru `high`, `medium`, `low`. Kontrola spójności zakończyła się wynikiem `0` reguł wymagających przeglądu. W danych występują wszystkie trzy poziomy pewności: `high`, `medium` oraz `low`. Największą grupę stanowią rekomendacje wysokiej pewności: `211 990` rekordów, czyli około `96.77%` wszystkich obserwacji. Rekomendacje średniej pewności obejmują `6 552` rekordy, czyli około `2.99%`, natomiast rekomendacje niskiej pewności obejmują `529` rekordów, czyli około `0.24%`. Dla rekomendacji niskiej pewności przypisywana jest akcja kontrolna `check_station_state`, co pozwala oddzielić sytuacje wymagające ostrożności od standardowych rekomendacji operacyjnych.

**Znaczenie biznesowe:** Dział `6.8` dodaje do panelu dyspozytora warstwę interpretowalności decyzji. Dyspozytor otrzymuje nie tylko informację, co należy zrobić ze stacją, ale również ocenę, jak silny i spójny jest sygnał stojący za rekomendacją. Rekomendacje wysokiej pewności wskazują przypadki, w których sygnały operacyjne są zgodne i mogą wspierać szybką decyzję. Rekomendacje średniej pewności oznaczają przypadki mieszane lub częściowe, które wymagają większej ostrożności. Rekomendacje niskiej pewności są jawnie kierowane do sprawdzenia stanu stacji, zamiast udawać jednoznaczną decyzję operacyjną. Takie podejście zwiększa wiarygodność aplikacji, ponieważ system nie deklaruje pełnej pewności tam, gdzie dane tego nie uzasadniają.

**Wniosek:** Dział `6.8` został domknięty poprawnie. Zbudowano, zweryfikowano i zapisano finalną warstwę `b6_41_dispatcher_daily_plan_with_confidence.parquet`, zawierającą plan dnia dyspozytora rozszerzony o `recommendation_confidence_final`, `confidence_score`, `confidence_reason` oraz `low_confidence_action`. Warstwa jest spójna technicznie, nie zawiera braków ani błędnych wartości pewności i może zostać użyta w kolejnych etapach panelu dyspozytora. Najważniejszym efektem działu jest to, że rekomendacje operacyjne nie są prezentowane jako bezwzględne decyzje, lecz jako decyzje z przypisaną pewnością i jasnym wskazaniem sytuacji wymagających kontroli.

## 6.9 Mapa działań i mapa relokacji

In [42]:
# 6.9.1 Definicja kontraktu mapy działań i mapy relokacji

import json

import pandas as pd


step6_91_required_objects = [
    "step6_84_confidence_output_df",
    "step6_76_local_pair_output_df",
    "step6_11_reports_dir",
]

step6_91_missing_objects = [
    object_name
    for object_name in step6_91_required_objects
    if object_name not in globals()
]

assert not step6_91_missing_objects, f"Missing required objects: {step6_91_missing_objects}"

step6_91_required_plan_columns = [
    "activity_date",
    "daily_plan_rank",
    "representative_station_id",
    "station_name",
    "microzone_id",
    "priority_level",
    "problem_type",
    "recommended_action",
    "recommendation_confidence_final",
    "confidence_score",
    "confidence_reason",
    "highest_risk_hour_label",
    "estimated_relocation_label",
    "expected_business_impact",
    "priority_score",
    "estimated_relocation_units",
    "relocation_direction",
]

step6_91_missing_plan_columns = [
    column_name
    for column_name in step6_91_required_plan_columns
    if column_name not in step6_84_confidence_output_df.columns
]

assert not step6_91_missing_plan_columns, f"Missing required plan columns: {step6_91_missing_plan_columns}"

step6_91_map_contract = {
    "block_name": "block_6",
    "section_name": "6.9",
    "section_scope": "action_map_and_relocation_map_layer",
    "source_object": "step6_84_confidence_output_df",
    "pair_source_object": "step6_76_local_pair_output_df",
    "source_grain": "day_station",
    "pair_grain": "day_microzone_pair",
    "map_engine": "folium",
    "uses_google_maps_api": False,
    "uses_external_map_api_keys": False,
    "main_map_elements": [
        "station_points",
        "priority_color",
        "problem_type_description",
        "station_popup",
        "local_pair_lines",
    ],
    "station_popup_fields": [
        "station_name",
        "priority_level",
        "problem_type",
        "recommended_action",
        "highest_risk_hour_label",
        "estimated_relocation_label",
        "expected_business_impact",
        "recommendation_confidence_final",
    ],
    "line_layer_policy": {
        "line_type": "folium.PolyLine",
        "line_scope": "local_donor_receiver_pairs",
        "draw_lines_only_when_pairs_exist": True,
        "uses_global_fleet_optimization": False,
    },
    "coordinate_policy": {
        "required_for_map_rendering": True,
        "accepted_coordinate_fields": [
            ["station_latitude", "station_longitude"],
            ["latitude", "longitude"],
            ["lat", "lon"],
            ["y", "x"],
        ],
    },
}

step6_91_output_fields_df = pd.DataFrame(
    [
        {
            "field_name": "map_priority_color",
            "field_role": "station_marker_priority_color",
            "source_grain": "day_station",
            "display_scope": "map_layer",
        },
        {
            "field_name": "map_problem_label",
            "field_role": "problem_type_display_description",
            "source_grain": "day_station",
            "display_scope": "map_popup",
        },
        {
            "field_name": "map_popup_text",
            "field_role": "station_popup_content",
            "source_grain": "day_station",
            "display_scope": "map_popup",
        },
        {
            "field_name": "map_marker_size",
            "field_role": "station_marker_intensity",
            "source_grain": "day_station",
            "display_scope": "map_layer",
        },
        {
            "field_name": "relocation_line_available",
            "field_role": "local_pair_line_flag",
            "source_grain": "day_microzone_pair",
            "display_scope": "map_layer",
        },
        {
            "field_name": "relocation_line_units",
            "field_role": "local_pair_line_weight",
            "source_grain": "day_microzone_pair",
            "display_scope": "map_layer",
        },
    ]
)

for column_name in ["field_name", "field_role", "source_grain", "display_scope"]:
    step6_91_output_fields_df[column_name] = step6_91_output_fields_df[column_name].astype("string")

step6_91_priority_color_df = pd.DataFrame(
    [
        {
            "priority_level": "very_high",
            "map_priority_color": "red",
            "sort_order": 1,
        },
        {
            "priority_level": "high",
            "map_priority_color": "orange",
            "sort_order": 2,
        },
        {
            "priority_level": "medium",
            "map_priority_color": "blue",
            "sort_order": 3,
        },
        {
            "priority_level": "low",
            "map_priority_color": "gray",
            "sort_order": 4,
        },
    ]
)

for column_name in ["priority_level", "map_priority_color"]:
    step6_91_priority_color_df[column_name] = step6_91_priority_color_df[column_name].astype("string")

step6_91_problem_label_df = pd.DataFrame(
    [
        {
            "problem_type": "bike_shortage_risk",
            "map_problem_label": "bike_shortage",
            "map_action_family": "deliver",
        },
        {
            "problem_type": "dock_shortage_risk",
            "map_problem_label": "dock_shortage",
            "map_action_family": "remove",
        },
        {
            "problem_type": "mixed_risk",
            "map_problem_label": "mixed_signal",
            "map_action_family": "check",
        },
        {
            "problem_type": "no_clear_signal",
            "map_problem_label": "no_clear_signal",
            "map_action_family": "check",
        },
    ]
)

for column_name in ["problem_type", "map_problem_label", "map_action_family"]:
    step6_91_problem_label_df[column_name] = step6_91_problem_label_df[column_name].astype("string")

step6_91_contract_path = step6_11_reports_dir / "b6_42_action_map_contract.json"
step6_91_output_fields_path = step6_11_reports_dir / "b6_42_action_map_output_fields.parquet"
step6_91_priority_color_path = step6_11_reports_dir / "b6_42_action_map_priority_colors.parquet"
step6_91_problem_label_path = step6_11_reports_dir / "b6_42_action_map_problem_labels.parquet"

with open(step6_91_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_91_map_contract, file, ensure_ascii=False, indent=2)

step6_91_output_fields_df.to_parquet(step6_91_output_fields_path, index=False)
step6_91_priority_color_df.to_parquet(step6_91_priority_color_path, index=False)
step6_91_problem_label_df.to_parquet(step6_91_problem_label_path, index=False)

step6_91_summary_df = pd.DataFrame(
    [
        {
            "check_area": "section_scope",
            "status": "ok",
            "value": "action_map_and_relocation_map_layer",
        },
        {
            "check_area": "source_grain",
            "status": "ok",
            "value": "day_station",
        },
        {
            "check_area": "map_engine",
            "status": "ok",
            "value": "folium",
        },
        {
            "check_area": "uses_google_maps_api",
            "status": "ok",
            "value": "false",
        },
        {
            "check_area": "required_plan_columns",
            "status": "ok",
            "value": str(len(step6_91_required_plan_columns)),
        },
        {
            "check_area": "output_fields",
            "status": "ok",
            "value": str(step6_91_output_fields_df.shape[0]),
        },
        {
            "check_area": "priority_color_values",
            "status": "ok",
            "value": str(step6_91_priority_color_df.shape[0]),
        },
        {
            "check_area": "problem_label_values",
            "status": "ok",
            "value": str(step6_91_problem_label_df.shape[0]),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_91_contract_path),
        },
        {
            "check_area": "output_fields_path",
            "status": "ok",
            "value": str(step6_91_output_fields_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_91_summary_df[column_name] = step6_91_summary_df[column_name].astype("string")

display(step6_91_summary_df)
display(step6_91_output_fields_df)
display(step6_91_priority_color_df)
display(step6_91_problem_label_df)

,check_area,status,value
0,section_scope,ok,action_map_and_relocation_map_layer
1,source_grain,ok,day_station
2,map_engine,ok,folium
3,uses_google_maps_api,ok,false
4,required_plan_columns,ok,17
5,output_fields,ok,6
6,priority_color_values,ok,4
7,problem_label_values,ok,4
8,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
9,output_fields_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,field_name,field_role,source_grain,display_scope
0,map_priority_color,station_marker_priority_color,day_station,map_layer
1,map_problem_label,problem_type_display_description,day_station,map_popup
2,map_popup_text,station_popup_content,day_station,map_popup
3,map_marker_size,station_marker_intensity,day_station,map_layer
4,relocation_line_available,local_pair_line_flag,day_microzone_pair,map_layer
5,relocation_line_units,local_pair_line_weight,day_microzone_pair,map_layer

  priority_level map_priority_color  sort_order
0      very_high                red           1
1           high             orange           2
2         medium               blue           3
3            low               gray           4

         problem_type map_problem_label map_action_family
0  bike_shortage_risk     bike_shortage           deliver
1  dock_shortage_risk     dock_shortage            remove
2          mixed_risk      mixed_signal             check
3     no_clear_signal   no_clear_signal             check

In [43]:
# 6.9.2 Weryfikacja źródeł współrzędnych stacji

from pathlib import Path

import pandas as pd


step6_92_required_objects = [
    "step6_84_confidence_output_df",
    "step6_11_reports_dir",
]

step6_92_missing_objects = [
    object_name
    for object_name in step6_92_required_objects
    if object_name not in globals()
]

assert not step6_92_missing_objects, f"Missing required objects: {step6_92_missing_objects}"

step6_92_reports_dir = Path(step6_11_reports_dir)
step6_92_search_root = step6_92_reports_dir.parents[1]

step6_92_expected_file_names = [
    "station_location_master.parquet",
    "stations_master.parquet",
    "station_business_analysis.parquet",
    "station_persona_profile.parquet",
    "3_classification_base_dataset.parquet",
    "3_classification_feature_dataset.parquet",
]

step6_92_candidate_paths = []

for expected_file_name in step6_92_expected_file_names:
    step6_92_candidate_paths.extend(
        list(step6_92_search_root.glob(f"**/{expected_file_name}"))
    )

step6_92_candidate_paths = sorted(set(step6_92_candidate_paths))

step6_92_source_candidates_df = pd.DataFrame(
    [
        {
            "candidate_order": candidate_order,
            "file_name": candidate_path.name,
            "resolved_path": str(candidate_path),
        }
        for candidate_order, candidate_path in enumerate(step6_92_candidate_paths, start=1)
    ]
)

assert not step6_92_source_candidates_df.empty, "No expected station coordinate source files found."

step6_92_summary_df = pd.DataFrame(
    [
        {
            "check_area": "search_root",
            "status": "ok",
            "value": str(step6_92_search_root),
        },
        {
            "check_area": "expected_file_names",
            "status": "ok",
            "value": str(len(step6_92_expected_file_names)),
        },
        {
            "check_area": "candidate_files_found",
            "status": "ok",
            "value": str(step6_92_source_candidates_df.shape[0]),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_92_summary_df[column_name] = step6_92_summary_df[column_name].astype("string")

display(step6_92_summary_df)
display(step6_92_source_candidates_df)

,check_area,status,value
0,search_root,ok,/root/projects/6_samodzielny_projekt_koncowy_wsl
1,expected_file_names,ok,6
2,candidate_files_found,ok,14

,candidate_order,file_name,resolved_path
0,1,station_business_analysis.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
1,2,station_location_master.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
2,3,station_persona_profile.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
3,4,stations_master.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
4,5,station_business_analysis.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
5,6,station_location_master.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
6,7,station_persona_profile.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
7,8,stations_master.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
8,9,3_classification_base_dataset.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
9,10,3_classification_feature_dataset.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
10,11,station_business_analysis.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
11,12,station_location_master.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
12,13,station_persona_profile.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...
13,14,stations_master.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...

In [44]:
# 6.9.3 Weryfikacja schematów źródeł współrzędnych stacji

import pandas as pd


step6_93_required_objects = [
    "step6_92_source_candidates_df",
]

step6_93_missing_objects = [
    object_name
    for object_name in step6_93_required_objects
    if object_name not in globals()
]

assert not step6_93_missing_objects, f"Missing required objects: {step6_93_missing_objects}"

step6_93_coordinate_pairs = [
    ("station_latitude", "station_longitude"),
    ("latitude", "longitude"),
    ("lat", "lon"),
    ("y", "x"),
]

step6_93_station_key_candidates = [
    "representative_station_id",
    "station_id",
    "departure_station_id",
    "return_station_id",
]

step6_93_schema_rows = []

for _, candidate_row in step6_92_source_candidates_df.iterrows():
    candidate_path = candidate_row["resolved_path"]

    schema_df = pd.read_parquet(candidate_path).head(0)
    schema_columns = set(schema_df.columns)

    station_key_columns = [
        column_name
        for column_name in step6_93_station_key_candidates
        if column_name in schema_columns
    ]

    coordinate_columns = [
        f"{lat_col}+{lon_col}"
        for lat_col, lon_col in step6_93_coordinate_pairs
        if lat_col in schema_columns and lon_col in schema_columns
    ]

    step6_93_schema_rows.append(
        {
            "candidate_order": int(candidate_row["candidate_order"]),
            "file_name": candidate_row["file_name"],
            "station_key_columns": ", ".join(station_key_columns),
            "coordinate_column_pairs": ", ".join(coordinate_columns),
            "has_station_key": bool(station_key_columns),
            "has_coordinate_pair": bool(coordinate_columns),
            "resolved_path": candidate_path,
        }
    )

step6_93_schema_review_df = pd.DataFrame(step6_93_schema_rows)

step6_93_schema_review_df["is_coordinate_source_candidate"] = (
    step6_93_schema_review_df["has_station_key"]
    & step6_93_schema_review_df["has_coordinate_pair"]
)

step6_93_coordinate_source_count = int(
    step6_93_schema_review_df["is_coordinate_source_candidate"].sum()
)

assert step6_93_coordinate_source_count > 0, "No usable station coordinate source schemas found."

step6_93_summary_df = pd.DataFrame(
    [
        {
            "check_area": "schema_files_checked",
            "status": "ok",
            "value": str(step6_93_schema_review_df.shape[0]),
        },
        {
            "check_area": "coordinate_source_candidates",
            "status": "ok",
            "value": str(step6_93_coordinate_source_count),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_93_summary_df[column_name] = step6_93_summary_df[column_name].astype("string")

display(step6_93_summary_df)
display(step6_93_schema_review_df)

                     check_area status value
0          schema_files_checked     ok    14
1  coordinate_source_candidates     ok     9

,candidate_order,file_name,station_key_columns,coordinate_column_pairs,has_station_key,has_coordinate_pair,resolved_path,is_coordinate_source_candidate
0,1,station_business_analysis.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True
1,2,station_location_master.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True
2,3,station_persona_profile.parquet,,,False,False,/root/projects/6_samodzielny_projekt_koncowy_w...,False
3,4,stations_master.parquet,station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True
4,5,station_business_analysis.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True
5,6,station_location_master.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True
6,7,station_persona_profile.parquet,,,False,False,/root/projects/6_samodzielny_projekt_koncowy_w...,False
7,8,stations_master.parquet,station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True
8,9,3_classification_base_dataset.parquet,"representative_station_id, station_id",,True,False,/root/projects/6_samodzielny_projekt_koncowy_w...,False
9,10,3_classification_feature_dataset.parquet,"representative_station_id, station_id",,True,False,/root/projects/6_samodzielny_projekt_koncowy_w...,False
10,11,station_business_analysis.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True
11,12,station_location_master.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True
12,13,station_persona_profile.parquet,,,False,False,/root/projects/6_samodzielny_projekt_koncowy_w...,False
13,14,stations_master.parquet,station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True

In [45]:
# 6.9.4 Wybór źródła współrzędnych stacji

from pathlib import Path

import pandas as pd


step6_94_required_objects = [
    "step6_93_schema_review_df",
    "step6_84_confidence_output_df",
    "step6_11_reports_dir",
]

step6_94_missing_objects = [
    object_name
    for object_name in step6_94_required_objects
    if object_name not in globals()
]

assert not step6_94_missing_objects, f"Missing required objects: {step6_94_missing_objects}"

step6_94_usable_sources_df = (
    step6_93_schema_review_df[
        step6_93_schema_review_df["is_coordinate_source_candidate"] == True
    ]
    .copy()
    .reset_index(drop=True)
)

step6_94_usable_sources_df["source_priority"] = 99

step6_94_usable_sources_df.loc[
    step6_94_usable_sources_df["file_name"].eq("station_location_master.parquet")
    & step6_94_usable_sources_df["station_key_columns"].str.contains("representative_station_id", regex=False),
    "source_priority",
] = 1

step6_94_usable_sources_df.loc[
    step6_94_usable_sources_df["file_name"].eq("station_business_analysis.parquet")
    & step6_94_usable_sources_df["station_key_columns"].str.contains("representative_station_id", regex=False),
    "source_priority",
] = 2

step6_94_usable_sources_df.loc[
    step6_94_usable_sources_df["file_name"].eq("stations_master.parquet")
    & step6_94_usable_sources_df["station_key_columns"].str.contains("station_id", regex=False),
    "source_priority",
] = 3

step6_94_usable_sources_df = (
    step6_94_usable_sources_df
    .sort_values(["source_priority", "candidate_order"])
    .reset_index(drop=True)
)

step6_94_selected_source = step6_94_usable_sources_df.iloc[0].to_dict()

step6_94_selected_path = Path(step6_94_selected_source["resolved_path"])
step6_94_selected_file_name = step6_94_selected_source["file_name"]

if "representative_station_id" in step6_94_selected_source["station_key_columns"]:
    step6_94_station_key_column = "representative_station_id"
else:
    step6_94_station_key_column = "station_id"

step6_94_latitude_column = "latitude"
step6_94_longitude_column = "longitude"

step6_94_station_coordinates_df = pd.read_parquet(
    step6_94_selected_path,
    columns=[
        step6_94_station_key_column,
        step6_94_latitude_column,
        step6_94_longitude_column,
    ],
)

step6_94_station_coordinates_df = (
    step6_94_station_coordinates_df
    .dropna(
        subset=[
            step6_94_station_key_column,
            step6_94_latitude_column,
            step6_94_longitude_column,
        ]
    )
    .rename(
        columns={
            step6_94_station_key_column: "representative_station_id",
            step6_94_latitude_column: "station_latitude",
            step6_94_longitude_column: "station_longitude",
        }
    )
)

step6_94_station_coordinates_df["representative_station_id"] = (
    step6_94_station_coordinates_df["representative_station_id"]
    .astype("string")
)

step6_94_station_coordinates_df["station_latitude"] = pd.to_numeric(
    step6_94_station_coordinates_df["station_latitude"],
    errors="coerce",
)

step6_94_station_coordinates_df["station_longitude"] = pd.to_numeric(
    step6_94_station_coordinates_df["station_longitude"],
    errors="coerce",
)

step6_94_station_coordinates_df = (
    step6_94_station_coordinates_df
    .dropna(subset=["station_latitude", "station_longitude"])
    .sort_values(["representative_station_id"])
    .drop_duplicates(subset=["representative_station_id"], keep="first")
    .reset_index(drop=True)
)

step6_94_plan_station_count = int(
    step6_84_confidence_output_df["representative_station_id"]
    .astype("string")
    .nunique()
)

step6_94_coordinate_station_count = int(
    step6_94_station_coordinates_df["representative_station_id"].nunique()
)

step6_94_matched_station_count = int(
    len(
        set(
            step6_84_confidence_output_df["representative_station_id"]
            .astype("string")
            .unique()
        ).intersection(
            set(step6_94_station_coordinates_df["representative_station_id"].unique())
        )
    )
)

step6_94_missing_station_count = int(
    step6_94_plan_station_count - step6_94_matched_station_count
)

step6_94_coverage_share = float(
    step6_94_matched_station_count / step6_94_plan_station_count
)

assert step6_94_missing_station_count == 0, "Missing station coordinates for plan station universe."

step6_94_coordinates_path = step6_11_reports_dir / "b6_43_selected_station_coordinates.parquet"
step6_94_source_review_path = step6_11_reports_dir / "b6_43_coordinate_source_review.parquet"

step6_94_station_coordinates_df.to_parquet(step6_94_coordinates_path, index=False)
step6_94_usable_sources_df.to_parquet(step6_94_source_review_path, index=False)

step6_94_summary_df = pd.DataFrame(
    [
        {
            "check_area": "selected_coordinate_file",
            "status": "ok",
            "value": step6_94_selected_file_name,
        },
        {
            "check_area": "selected_station_key_column",
            "status": "ok",
            "value": step6_94_station_key_column,
        },
        {
            "check_area": "coordinate_mapping_rows",
            "status": "ok",
            "value": str(step6_94_station_coordinates_df.shape[0]),
        },
        {
            "check_area": "plan_station_count",
            "status": "ok",
            "value": str(step6_94_plan_station_count),
        },
        {
            "check_area": "matched_station_count",
            "status": "ok",
            "value": str(step6_94_matched_station_count),
        },
        {
            "check_area": "missing_station_count",
            "status": "ok",
            "value": str(step6_94_missing_station_count),
        },
        {
            "check_area": "coordinate_coverage_share",
            "status": "ok",
            "value": str(round(step6_94_coverage_share, 6)),
        },
        {
            "check_area": "coordinates_path",
            "status": "ok",
            "value": str(step6_94_coordinates_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_94_summary_df[column_name] = step6_94_summary_df[column_name].astype("string")

display(step6_94_summary_df)
display(step6_94_usable_sources_df.head(10))
display(step6_94_station_coordinates_df.head(20))

,check_area,status,value
0,selected_coordinate_file,ok,station_location_master.parquet
1,selected_station_key_column,ok,representative_station_id
2,coordinate_mapping_rows,ok,344
3,plan_station_count,ok,344
4,matched_station_count,ok,344
5,missing_station_count,ok,0
6,coordinate_coverage_share,ok,1.0
7,coordinates_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,candidate_order,file_name,station_key_columns,coordinate_column_pairs,has_station_key,has_coordinate_pair,resolved_path,is_coordinate_source_candidate,source_priority
0,2,station_location_master.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,1
1,6,station_location_master.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,1
2,12,station_location_master.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,1
3,1,station_business_analysis.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,2
4,5,station_business_analysis.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,2
5,11,station_business_analysis.parquet,representative_station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,2
6,4,stations_master.parquet,station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3
7,8,stations_master.parquet,station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3
8,14,stations_master.parquet,station_id,latitude+longitude,True,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3

   representative_station_id  station_latitude  station_longitude
0                          1         60.155445          24.950293
1                         10         60.165016          24.949472
2                        100         60.209694          24.868740
3                        101         60.199665          24.883621
4                        103         60.208923          24.889521
5                        104         60.205677          24.891682
6                        105         60.202839          24.893476
7                        106         60.203472          24.898930
8                        107         60.202438          24.905460
9                        108         60.204990          24.918419
10                       109         60.202538          24.922459
11                        11         60.167458          24.951023
12                       110         60.199150          24.924873
13                       111         60.197571          24.926781
14                       112         60.201439          24.933271
15                       113         60.186977          24.943357
16                       114         60.196430          24.936256
17                       115         60.194210          24.941578
18                       116         60.191139          24.940159
19                       117         60.189671          24.948103

In [46]:
# 6.9.5 Dołączenie współrzędnych do planu mapy

import pandas as pd


step6_95_required_objects = [
    "step6_84_confidence_output_df",
    "step6_94_station_coordinates_df",
    "step6_11_reports_dir",
]

step6_95_missing_objects = [
    object_name
    for object_name in step6_95_required_objects
    if object_name not in globals()
]

assert not step6_95_missing_objects, f"Missing required objects: {step6_95_missing_objects}"

step6_95_map_base_df = step6_84_confidence_output_df.copy()

step6_95_map_base_df["representative_station_id"] = (
    step6_95_map_base_df["representative_station_id"]
    .astype("string")
)

step6_95_station_coordinates_df = step6_94_station_coordinates_df.copy()

step6_95_station_coordinates_df["representative_station_id"] = (
    step6_95_station_coordinates_df["representative_station_id"]
    .astype("string")
)

step6_95_map_base_df = step6_95_map_base_df.merge(
    step6_95_station_coordinates_df,
    on="representative_station_id",
    how="left",
    validate="many_to_one",
)

step6_95_missing_coordinates_count = int(
    step6_95_map_base_df[["station_latitude", "station_longitude"]]
    .isna()
    .any(axis=1)
    .sum()
)

step6_95_duplicate_day_station_count = int(
    step6_95_map_base_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_95_unique_station_count = int(
    step6_95_map_base_df["representative_station_id"].nunique()
)

step6_95_unique_date_count = int(
    step6_95_map_base_df["activity_date"].nunique()
)

step6_95_coordinate_coverage_share = float(
    1 - (step6_95_missing_coordinates_count / step6_95_map_base_df.shape[0])
)

assert step6_95_missing_coordinates_count == 0, "Missing station coordinates detected in map base."
assert step6_95_duplicate_day_station_count == 0, "Duplicated day-station keys detected in map base."

step6_95_map_base_path = step6_11_reports_dir / "b6_44_map_base_with_coordinates.parquet"

step6_95_map_base_df.to_parquet(step6_95_map_base_path, index=False)

step6_95_summary_df = pd.DataFrame(
    [
        {
            "check_area": "map_base_rows",
            "status": "ok",
            "value": str(step6_95_map_base_df.shape[0]),
        },
        {
            "check_area": "map_base_columns",
            "status": "ok",
            "value": str(step6_95_map_base_df.shape[1]),
        },
        {
            "check_area": "unique_dates",
            "status": "ok",
            "value": str(step6_95_unique_date_count),
        },
        {
            "check_area": "unique_stations",
            "status": "ok",
            "value": str(step6_95_unique_station_count),
        },
        {
            "check_area": "missing_coordinates",
            "status": "ok",
            "value": str(step6_95_missing_coordinates_count),
        },
        {
            "check_area": "coordinate_coverage_share",
            "status": "ok",
            "value": str(round(step6_95_coordinate_coverage_share, 6)),
        },
        {
            "check_area": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_95_duplicate_day_station_count),
        },
        {
            "check_area": "map_base_path",
            "status": "ok",
            "value": str(step6_95_map_base_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_95_summary_df[column_name] = step6_95_summary_df[column_name].astype("string")

display(step6_95_summary_df)
display(
    step6_95_map_base_df[
        [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "station_latitude",
            "station_longitude",
            "microzone_id",
            "priority_level",
            "problem_type",
            "recommended_action",
            "recommendation_confidence_final",
            "expected_business_impact",
        ]
    ].head(20)
)

,check_area,status,value
0,map_base_rows,ok,219071
1,map_base_columns,ok,26
2,unique_dates,ok,839
3,unique_stations,ok,344
4,missing_coordinates,ok,0
5,coordinate_coverage_share,ok,1.0
6,duplicate_day_station_keys,ok,0
7,map_base_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,activity_date,daily_plan_rank,representative_station_id,station_name,station_latitude,station_longitude,microzone_id,priority_level,problem_type,recommended_action,recommendation_confidence_final,expected_business_impact
0,2017-05-02,1,30,Itämerentori,60.163532,24.914516,MZ_0045,very_high,bike_shortage_risk,deliver_bikes,high,128.742188
1,2017-05-02,2,26,Kamppi (M),60.168610,24.930538,MZ_0064,very_high,bike_shortage_risk,deliver_bikes,high,124.333328
2,2017-05-02,3,21,Töölönlahdenkatu,60.172192,24.939308,MZ_0067,very_high,bike_shortage_risk,deliver_bikes,high,111.562500
3,2017-05-02,4,25,Narinkka,60.170040,24.934607,MZ_0067,very_high,bike_shortage_risk,deliver_bikes,high,103.812500
4,2017-05-02,5,40,Hakaniemi (M),60.178108,24.952181,MZ_0099,high,bike_shortage_risk,deliver_bikes,high,91.218750
5,2017-05-02,6,17,Varsapuistikko,60.173103,24.949520,MZ_0079,high,bike_shortage_risk,deliver_bikes,high,77.145828
6,2017-05-02,7,41,Ympyrätalo,60.180862,24.949400,MZ_0113,high,bike_shortage_risk,deliver_bikes,high,75.312500
7,2017-05-02,8,9,Erottajan aukio,60.166889,24.944262,MZ_0054,high,bike_shortage_risk,deliver_bikes,high,73.021355
8,2017-05-02,9,44,Sörnäinen (M),60.187737,24.960979,MZ_0140,high,bike_shortage_risk,deliver_bikes,high,72.021873
9,2017-05-02,10,22,Rautatientori / länsi,60.170605,24.939760,MZ_0067,high,bike_shortage_risk,deliver_bikes,high,71.437500
10,2017-05-02,11,5,Sepänkatu,60.157948,24.936285,MZ_0021,high,bike_shortage_risk,deliver_bikes,high,71.158340
11,2017-05-02,12,11,Unioninkatu,60.167458,24.951023,MZ_0054,high,bike_shortage_risk,deliver_bikes,high,69.125000
12,2017-05-02,13,23,Kiasma,60.171257,24.937428,MZ_0067,high,bike_shortage_risk,deliver_bikes,high,66.458336
13,2017-05-02,14,29,Baana,60.164089,24.922565,MZ_0037,high,bike_shortage_risk,deliver_bikes,high,66.178131
14,2017-05-02,15,6,Hietalahdentori,60.162224,24.929710,MZ_0038,high,bike_shortage_risk,deliver_bikes,high,65.770828
15,2017-05-02,16,19,Rautatientori / itä,60.170822,24.942526,MZ_0067,high,bike_shortage_risk,deliver_bikes,high,62.387497
16,2017-05-02,17,14,Senaatintori,60.169128,24.952641,MZ_0054,high,bike_shortage_risk,deliver_bikes,high,58.446354
17,2017-05-02,18,150,Töölönlahden puisto,60.174644,24.935186,MZ_0083,high,bike_shortage_risk,deliver_bikes,high,57.928127
18,2017-05-02,19,20,Kaisaniemenpuisto,60.173199,24.943300,MZ_0067,medium,bike_shortage_risk,deliver_bikes,high,57.409901
19,2017-05-02,20,112,Rautatieläisenkatu,60.201439,24.933271,MZ_0193,medium,bike_shortage_risk,deliver_bikes,high,55.987499

In [47]:
# 6.9.6 Budowa pól mapowych dla stacji

import pandas as pd


step6_96_required_objects = [
    "step6_95_map_base_df",
    "step6_91_priority_color_df",
    "step6_91_problem_label_df",
    "step6_11_reports_dir",
]

step6_96_missing_objects = [
    object_name
    for object_name in step6_96_required_objects
    if object_name not in globals()
]

assert not step6_96_missing_objects, f"Missing required objects: {step6_96_missing_objects}"

step6_96_map_station_df = step6_95_map_base_df.copy()

step6_96_map_station_df["priority_level"] = (
    step6_96_map_station_df["priority_level"]
    .astype("string")
)

step6_96_map_station_df["problem_type"] = (
    step6_96_map_station_df["problem_type"]
    .astype("string")
)

step6_96_priority_color_df = step6_91_priority_color_df.copy()

step6_96_priority_color_df["priority_level"] = (
    step6_96_priority_color_df["priority_level"]
    .astype("string")
)

step6_96_problem_label_df = step6_91_problem_label_df.copy()

step6_96_problem_label_df["problem_type"] = (
    step6_96_problem_label_df["problem_type"]
    .astype("string")
)

step6_96_map_station_df = step6_96_map_station_df.merge(
    step6_96_priority_color_df[["priority_level", "map_priority_color"]],
    on="priority_level",
    how="left",
    validate="many_to_one",
)

step6_96_map_station_df = step6_96_map_station_df.merge(
    step6_96_problem_label_df[["problem_type", "map_problem_label", "map_action_family"]],
    on="problem_type",
    how="left",
    validate="many_to_one",
)

step6_96_max_impact = float(
    step6_96_map_station_df["expected_business_impact"].max()
)

assert step6_96_max_impact > 0, "Expected business impact must be positive for marker scaling."

step6_96_map_station_df["map_marker_size"] = (
    5
    + (
        step6_96_map_station_df["expected_business_impact"]
        / step6_96_max_impact
        * 15
    )
).round(2)

step6_96_map_station_df["map_popup_text"] = (
    "Station: "
    + step6_96_map_station_df["station_name"].astype("string")
    + "<br>Priority: "
    + step6_96_map_station_df["priority_level"].astype("string")
    + "<br>Problem: "
    + step6_96_map_station_df["map_problem_label"].astype("string")
    + "<br>Action: "
    + step6_96_map_station_df["recommended_action"].astype("string")
    + "<br>Risk hour: "
    + step6_96_map_station_df["highest_risk_hour_label"].astype("string")
    + "<br>Relocation: "
    + step6_96_map_station_df["estimated_relocation_label"].astype("string")
    + "<br>Expected impact: "
    + step6_96_map_station_df["expected_business_impact"].round(2).astype("string")
    + "<br>Confidence: "
    + step6_96_map_station_df["recommendation_confidence_final"].astype("string")
)

step6_96_missing_priority_color_count = int(
    step6_96_map_station_df["map_priority_color"].isna().sum()
)

step6_96_missing_problem_label_count = int(
    step6_96_map_station_df["map_problem_label"].isna().sum()
)

step6_96_missing_popup_count = int(
    step6_96_map_station_df["map_popup_text"].isna().sum()
)

step6_96_missing_marker_size_count = int(
    step6_96_map_station_df["map_marker_size"].isna().sum()
)

step6_96_duplicate_day_station_count = int(
    step6_96_map_station_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

assert step6_96_missing_priority_color_count == 0, "Missing map priority colors detected."
assert step6_96_missing_problem_label_count == 0, "Missing map problem labels detected."
assert step6_96_missing_popup_count == 0, "Missing map popup text detected."
assert step6_96_missing_marker_size_count == 0, "Missing map marker size detected."
assert step6_96_duplicate_day_station_count == 0, "Duplicated day-station keys detected in map station layer."

step6_96_map_station_path = step6_11_reports_dir / "b6_45_map_station_layer.parquet"

step6_96_map_station_df.to_parquet(step6_96_map_station_path, index=False)

step6_96_priority_summary_df = (
    step6_96_map_station_df
    .groupby(["priority_level", "map_priority_color"], observed=True)
    .agg(
        row_count=("priority_level", "size"),
        mean_expected_business_impact=("expected_business_impact", "mean"),
        mean_map_marker_size=("map_marker_size", "mean"),
    )
    .reset_index()
)

step6_96_priority_summary_df["row_share"] = (
    step6_96_priority_summary_df["row_count"]
    / step6_96_priority_summary_df["row_count"].sum()
)

step6_96_problem_summary_df = (
    step6_96_map_station_df
    .groupby(["problem_type", "map_problem_label", "map_action_family"], observed=True)
    .agg(
        row_count=("problem_type", "size"),
        mean_expected_business_impact=("expected_business_impact", "mean"),
    )
    .reset_index()
)

step6_96_problem_summary_df["row_share"] = (
    step6_96_problem_summary_df["row_count"]
    / step6_96_problem_summary_df["row_count"].sum()
)

step6_96_summary_df = pd.DataFrame(
    [
        {
            "check_area": "map_station_rows",
            "status": "ok",
            "value": str(step6_96_map_station_df.shape[0]),
        },
        {
            "check_area": "map_station_columns",
            "status": "ok",
            "value": str(step6_96_map_station_df.shape[1]),
        },
        {
            "check_area": "missing_priority_color",
            "status": "ok",
            "value": str(step6_96_missing_priority_color_count),
        },
        {
            "check_area": "missing_problem_label",
            "status": "ok",
            "value": str(step6_96_missing_problem_label_count),
        },
        {
            "check_area": "missing_popup_text",
            "status": "ok",
            "value": str(step6_96_missing_popup_count),
        },
        {
            "check_area": "missing_marker_size",
            "status": "ok",
            "value": str(step6_96_missing_marker_size_count),
        },
        {
            "check_area": "duplicate_day_station_keys",
            "status": "ok",
            "value": str(step6_96_duplicate_day_station_count),
        },
        {
            "check_area": "map_station_path",
            "status": "ok",
            "value": str(step6_96_map_station_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_96_summary_df[column_name] = step6_96_summary_df[column_name].astype("string")

display(step6_96_summary_df)
display(step6_96_priority_summary_df)
display(step6_96_problem_summary_df)
display(
    step6_96_map_station_df[
        [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "station_latitude",
            "station_longitude",
            "priority_level",
            "map_priority_color",
            "problem_type",
            "map_problem_label",
            "recommended_action",
            "map_marker_size",
            "expected_business_impact",
            "map_popup_text",
        ]
    ].head(20)
)

,check_area,status,value
0,map_station_rows,ok,219071
1,map_station_columns,ok,31
2,missing_priority_color,ok,0
3,missing_problem_label,ok,0
4,missing_popup_text,ok,0
5,missing_marker_size,ok,0
6,duplicate_day_station_keys,ok,0
7,map_station_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,priority_level,map_priority_color,row_count,mean_expected_business_impact,mean_map_marker_size,row_share
0,high,orange,32860,77.868835,5.941199,0.149997
1,low,gray,109535,15.602734,5.188588,0.499998
2,medium,blue,54768,42.808716,5.517453,0.250001
3,very_high,red,21908,155.303162,6.877156,0.100004

,problem_type,map_problem_label,map_action_family,row_count,mean_expected_business_impact,row_share
0,bike_shortage_risk,bike_shortage,deliver,211990,44.597599,0.967677
1,mixed_risk,mixed_signal,check,7081,79.155434,0.032323

,activity_date,daily_plan_rank,representative_station_id,station_name,station_latitude,station_longitude,priority_level,map_priority_color,problem_type,map_problem_label,recommended_action,map_marker_size,expected_business_impact,map_popup_text
0,2017-05-02,1,30,Itämerentori,60.163532,24.914516,very_high,red,bike_shortage_risk,bike_shortage,deliver_bikes,6.56,128.742188,Station: Itämerentori<br>Priority: very_high<b...
1,2017-05-02,2,26,Kamppi (M),60.168610,24.930538,very_high,red,bike_shortage_risk,bike_shortage,deliver_bikes,6.50,124.333328,Station: Kamppi (M)<br>Priority: very_high<br>...
2,2017-05-02,3,21,Töölönlahdenkatu,60.172192,24.939308,very_high,red,bike_shortage_risk,bike_shortage,deliver_bikes,6.35,111.562500,Station: Töölönlahdenkatu<br>Priority: very_hi...
3,2017-05-02,4,25,Narinkka,60.170040,24.934607,very_high,red,bike_shortage_risk,bike_shortage,deliver_bikes,6.25,103.812500,Station: Narinkka<br>Priority: very_high<br>Pr...
4,2017-05-02,5,40,Hakaniemi (M),60.178108,24.952181,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,6.10,91.218750,Station: Hakaniemi (M)<br>Priority: high<br>Pr...
5,2017-05-02,6,17,Varsapuistikko,60.173103,24.949520,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.93,77.145828,Station: Varsapuistikko<br>Priority: high<br>P...
6,2017-05-02,7,41,Ympyrätalo,60.180862,24.949400,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.91,75.312500,Station: Ympyrätalo<br>Priority: high<br>Probl...
7,2017-05-02,8,9,Erottajan aukio,60.166889,24.944262,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.88,73.021355,Station: Erottajan aukio<br>Priority: high<br>...
8,2017-05-02,9,44,Sörnäinen (M),60.187737,24.960979,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.87,72.021873,Station: Sörnäinen (M)<br>Priority: high<br>Pr...
9,2017-05-02,10,22,Rautatientori / länsi,60.170605,24.939760,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.86,71.437500,Station: Rautatientori / länsi<br>Priority: hi...
10,2017-05-02,11,5,Sepänkatu,60.157948,24.936285,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.86,71.158340,Station: Sepänkatu<br>Priority: high<br>Proble...
11,2017-05-02,12,11,Unioninkatu,60.167458,24.951023,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.84,69.125000,Station: Unioninkatu<br>Priority: high<br>Prob...
12,2017-05-02,13,23,Kiasma,60.171257,24.937428,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.80,66.458336,Station: Kiasma<br>Priority: high<br>Problem: ...
13,2017-05-02,14,29,Baana,60.164089,24.922565,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.80,66.178131,Station: Baana<br>Priority: high<br>Problem: b...
14,2017-05-02,15,6,Hietalahdentori,60.162224,24.929710,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.79,65.770828,Station: Hietalahdentori<br>Priority: high<br>...
15,2017-05-02,16,19,Rautatientori / itä,60.170822,24.942526,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.75,62.387497,Station: Rautatientori / itä<br>Priority: high...
16,2017-05-02,17,14,Senaatintori,60.169128,24.952641,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.71,58.446354,Station: Senaatintori<br>Priority: high<br>Pro...
17,2017-05-02,18,150,Töölönlahden puisto,60.174644,24.935186,high,orange,bike_shortage_risk,bike_shortage,deliver_bikes,5.70,57.928127,Station: Töölönlahden puisto<br>Priority: high...
18,2017-05-02,19,20,Kaisaniemenpuisto,60.173199,24.943300,medium,blue,bike_shortage_risk,bike_shortage,deliver_bikes,5.69,57.409901,Station: Kaisaniemenpuisto<br>Priority: medium...
19,2017-05-02,20,112,Rautatieläisenkatu,60.201439,24.933271,medium,blue,bike_shortage_risk,bike_shortage,deliver_bikes,5.68,55.987499,Station: Rautatieläisenkatu<br>Priority: mediu...

In [48]:
# 6.9.7 Przygotowanie dziennego widoku mapy

import pandas as pd


step6_97_required_objects = [
    "step6_96_map_station_df",
    "step6_11_reports_dir",
]

step6_97_missing_objects = [
    object_name
    for object_name in step6_97_required_objects
    if object_name not in globals()
]

assert not step6_97_missing_objects, f"Missing required objects: {step6_97_missing_objects}"

step6_97_selected_date = (
    step6_96_map_station_df["activity_date"]
    .drop_duplicates()
    .sort_values()
    .iloc[0]
)

step6_97_daily_map_df = (
    step6_96_map_station_df[
        step6_96_map_station_df["activity_date"].eq(step6_97_selected_date)
    ]
    .copy()
    .sort_values(
        [
            "daily_plan_rank",
            "expected_business_impact",
            "priority_score",
        ],
        ascending=[True, False, False],
    )
    .reset_index(drop=True)
)

step6_97_daily_map_top_df = (
    step6_97_daily_map_df
    .head(50)
    .copy()
    .reset_index(drop=True)
)

step6_97_missing_coordinates_count = int(
    step6_97_daily_map_top_df[["station_latitude", "station_longitude"]]
    .isna()
    .any(axis=1)
    .sum()
)

step6_97_duplicate_station_count = int(
    step6_97_daily_map_top_df["representative_station_id"].duplicated().sum()
)

step6_97_unique_priority_count = int(
    step6_97_daily_map_top_df["priority_level"].nunique()
)

step6_97_unique_action_count = int(
    step6_97_daily_map_top_df["recommended_action"].nunique()
)

assert step6_97_missing_coordinates_count == 0, "Missing coordinates detected in daily map sample."
assert step6_97_duplicate_station_count == 0, "Duplicated station keys detected in daily map sample."

step6_97_daily_map_path = step6_11_reports_dir / "b6_46_daily_map_sample_top50.parquet"

step6_97_daily_map_top_df.to_parquet(step6_97_daily_map_path, index=False)

step6_97_summary_df = pd.DataFrame(
    [
        {
            "check_area": "selected_date",
            "status": "ok",
            "value": str(step6_97_selected_date),
        },
        {
            "check_area": "daily_map_rows",
            "status": "ok",
            "value": str(step6_97_daily_map_df.shape[0]),
        },
        {
            "check_area": "daily_map_top_rows",
            "status": "ok",
            "value": str(step6_97_daily_map_top_df.shape[0]),
        },
        {
            "check_area": "missing_coordinates",
            "status": "ok",
            "value": str(step6_97_missing_coordinates_count),
        },
        {
            "check_area": "duplicate_station_keys",
            "status": "ok",
            "value": str(step6_97_duplicate_station_count),
        },
        {
            "check_area": "unique_priority_levels",
            "status": "ok",
            "value": str(step6_97_unique_priority_count),
        },
        {
            "check_area": "unique_recommended_actions",
            "status": "ok",
            "value": str(step6_97_unique_action_count),
        },
        {
            "check_area": "daily_map_path",
            "status": "ok",
            "value": str(step6_97_daily_map_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_97_summary_df[column_name] = step6_97_summary_df[column_name].astype("string")

display(step6_97_summary_df)
display(
    step6_97_daily_map_top_df[
        [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "station_latitude",
            "station_longitude",
            "priority_level",
            "map_priority_color",
            "problem_type",
            "recommended_action",
            "highest_risk_hour_label",
            "estimated_relocation_label",
            "recommendation_confidence_final",
            "expected_business_impact",
            "map_marker_size",
        ]
    ].head(20)
)

,check_area,status,value
0,selected_date,ok,2017-05-02 00:00:00
1,daily_map_rows,ok,142
2,daily_map_top_rows,ok,50
3,missing_coordinates,ok,0
4,duplicate_station_keys,ok,0
5,unique_priority_levels,ok,3
6,unique_recommended_actions,ok,1
7,daily_map_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,activity_date,daily_plan_rank,representative_station_id,station_name,station_latitude,station_longitude,priority_level,map_priority_color,problem_type,recommended_action,highest_risk_hour_label,estimated_relocation_label,recommendation_confidence_final,expected_business_impact,map_marker_size
0,2017-05-02,1,30,Itämerentori,60.163532,24.914516,very_high,red,bike_shortage_risk,deliver_bikes,17:00,deliver 18-20,high,128.742188,6.56
1,2017-05-02,2,26,Kamppi (M),60.168610,24.930538,very_high,red,bike_shortage_risk,deliver_bikes,16:00,deliver 9-11,high,124.333328,6.50
2,2017-05-02,3,21,Töölönlahdenkatu,60.172192,24.939308,very_high,red,bike_shortage_risk,deliver_bikes,19:00,deliver 11-13,high,111.562500,6.35
3,2017-05-02,4,25,Narinkka,60.170040,24.934607,very_high,red,bike_shortage_risk,deliver_bikes,18:00,deliver 7-9,high,103.812500,6.25
4,2017-05-02,5,40,Hakaniemi (M),60.178108,24.952181,high,orange,bike_shortage_risk,deliver_bikes,17:00,deliver 6-8,high,91.218750,6.10
5,2017-05-02,6,17,Varsapuistikko,60.173103,24.949520,high,orange,bike_shortage_risk,deliver_bikes,17:00,deliver 9-11,high,77.145828,5.93
6,2017-05-02,7,41,Ympyrätalo,60.180862,24.949400,high,orange,bike_shortage_risk,deliver_bikes,13:00,deliver 8-10,high,75.312500,5.91
7,2017-05-02,8,9,Erottajan aukio,60.166889,24.944262,high,orange,bike_shortage_risk,deliver_bikes,16:00,deliver 13-15,high,73.021355,5.88
8,2017-05-02,9,44,Sörnäinen (M),60.187737,24.960979,high,orange,bike_shortage_risk,deliver_bikes,19:00,deliver 7-9,high,72.021873,5.87
9,2017-05-02,10,22,Rautatientori / länsi,60.170605,24.939760,high,orange,bike_shortage_risk,deliver_bikes,15:00,deliver 8-10,high,71.437500,5.86
10,2017-05-02,11,5,Sepänkatu,60.157948,24.936285,high,orange,bike_shortage_risk,deliver_bikes,11:00,deliver 6-8,high,71.158340,5.86
11,2017-05-02,12,11,Unioninkatu,60.167458,24.951023,high,orange,bike_shortage_risk,deliver_bikes,16:00,deliver 19-21,high,69.125000,5.84
12,2017-05-02,13,23,Kiasma,60.171257,24.937428,high,orange,bike_shortage_risk,deliver_bikes,20:00,deliver 8-10,high,66.458336,5.80
13,2017-05-02,14,29,Baana,60.164089,24.922565,high,orange,bike_shortage_risk,deliver_bikes,12:00,deliver 6-8,high,66.178131,5.80
14,2017-05-02,15,6,Hietalahdentori,60.162224,24.929710,high,orange,bike_shortage_risk,deliver_bikes,16:00,deliver 3-5,high,65.770828,5.79
15,2017-05-02,16,19,Rautatientori / itä,60.170822,24.942526,high,orange,bike_shortage_risk,deliver_bikes,21:00,deliver 6-8,high,62.387497,5.75
16,2017-05-02,17,14,Senaatintori,60.169128,24.952641,high,orange,bike_shortage_risk,deliver_bikes,17:00,deliver 9-11,high,58.446354,5.71
17,2017-05-02,18,150,Töölönlahden puisto,60.174644,24.935186,high,orange,bike_shortage_risk,deliver_bikes,21:00,deliver 5-7,high,57.928127,5.70
18,2017-05-02,19,20,Kaisaniemenpuisto,60.173199,24.943300,medium,blue,bike_shortage_risk,deliver_bikes,20:00,deliver 5-7,high,57.409901,5.69
19,2017-05-02,20,112,Rautatieläisenkatu,60.201439,24.933271,medium,blue,bike_shortage_risk,deliver_bikes,17:00,deliver 4-6,high,55.987499,5.68

In [49]:
# 6.9.8 Budowa mapy działań dla wybranego dnia

from pathlib import Path

import folium
import pandas as pd


step6_98_required_objects = [
    "step6_97_daily_map_top_df",
    "step6_11_reports_dir",
]

step6_98_missing_objects = [
    object_name
    for object_name in step6_98_required_objects
    if object_name not in globals()
]

assert not step6_98_missing_objects, f"Missing required objects: {step6_98_missing_objects}"

step6_98_map_input_df = step6_97_daily_map_top_df.copy()

step6_98_required_columns = [
    "station_latitude",
    "station_longitude",
    "station_name",
    "map_priority_color",
    "map_marker_size",
    "map_popup_text",
    "daily_plan_rank",
    "expected_business_impact",
]

step6_98_missing_columns = [
    column_name
    for column_name in step6_98_required_columns
    if column_name not in step6_98_map_input_df.columns
]

assert not step6_98_missing_columns, f"Missing required columns: {step6_98_missing_columns}"

step6_98_missing_coordinates_count = int(
    step6_98_map_input_df[["station_latitude", "station_longitude"]]
    .isna()
    .any(axis=1)
    .sum()
)

assert step6_98_missing_coordinates_count == 0, "Missing station coordinates detected in map input."

step6_98_center_latitude = float(step6_98_map_input_df["station_latitude"].mean())
step6_98_center_longitude = float(step6_98_map_input_df["station_longitude"].mean())

step6_98_action_map = folium.Map(
    location=[step6_98_center_latitude, step6_98_center_longitude],
    zoom_start=13,
    control_scale=True,
)

for _, station_row in step6_98_map_input_df.iterrows():
    folium.CircleMarker(
        location=[
            float(station_row["station_latitude"]),
            float(station_row["station_longitude"]),
        ],
        radius=float(station_row["map_marker_size"]),
        color=str(station_row["map_priority_color"]),
        fill=True,
        fill_color=str(station_row["map_priority_color"]),
        fill_opacity=0.75,
        popup=folium.Popup(
            str(station_row["map_popup_text"]),
            max_width=350,
        ),
        tooltip=(
            f"#{int(station_row['daily_plan_rank'])} | "
            f"{station_row['station_name']} | "
            f"impact: {float(station_row['expected_business_impact']):.2f}"
        ),
    ).add_to(step6_98_action_map)

step6_98_map_output_path = step6_11_reports_dir / "b6_47_action_map_top50.html"

step6_98_action_map.save(step6_98_map_output_path)

step6_98_summary_df = pd.DataFrame(
    [
        {
            "check_area": "map_input_rows",
            "status": "ok",
            "value": str(step6_98_map_input_df.shape[0]),
        },
        {
            "check_area": "missing_coordinates",
            "status": "ok",
            "value": str(step6_98_missing_coordinates_count),
        },
        {
            "check_area": "map_center_latitude",
            "status": "ok",
            "value": str(round(step6_98_center_latitude, 6)),
        },
        {
            "check_area": "map_center_longitude",
            "status": "ok",
            "value": str(round(step6_98_center_longitude, 6)),
        },
        {
            "check_area": "map_engine",
            "status": "ok",
            "value": "folium",
        },
        {
            "check_area": "marker_count",
            "status": "ok",
            "value": str(step6_98_map_input_df.shape[0]),
        },
        {
            "check_area": "map_output_path",
            "status": "ok",
            "value": str(step6_98_map_output_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_98_summary_df[column_name] = step6_98_summary_df[column_name].astype("string")

display(step6_98_summary_df)
display(
    step6_98_map_input_df[
        [
            "activity_date",
            "daily_plan_rank",
            "station_name",
            "map_priority_color",
            "map_marker_size",
            "recommended_action",
            "highest_risk_hour_label",
            "estimated_relocation_label",
            "expected_business_impact",
        ]
    ].head(20)
)

step6_98_action_map

,check_area,status,value
0,map_input_rows,ok,50
1,missing_coordinates,ok,0
2,map_center_latitude,ok,60.174694
3,map_center_longitude,ok,24.934626
4,map_engine,ok,folium
5,marker_count,ok,50
6,map_output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,activity_date,daily_plan_rank,station_name,map_priority_color,map_marker_size,recommended_action,highest_risk_hour_label,estimated_relocation_label,expected_business_impact
0,2017-05-02,1,Itämerentori,red,6.56,deliver_bikes,17:00,deliver 18-20,128.742188
1,2017-05-02,2,Kamppi (M),red,6.50,deliver_bikes,16:00,deliver 9-11,124.333328
2,2017-05-02,3,Töölönlahdenkatu,red,6.35,deliver_bikes,19:00,deliver 11-13,111.562500
3,2017-05-02,4,Narinkka,red,6.25,deliver_bikes,18:00,deliver 7-9,103.812500
4,2017-05-02,5,Hakaniemi (M),orange,6.10,deliver_bikes,17:00,deliver 6-8,91.218750
5,2017-05-02,6,Varsapuistikko,orange,5.93,deliver_bikes,17:00,deliver 9-11,77.145828
6,2017-05-02,7,Ympyrätalo,orange,5.91,deliver_bikes,13:00,deliver 8-10,75.312500
7,2017-05-02,8,Erottajan aukio,orange,5.88,deliver_bikes,16:00,deliver 13-15,73.021355
8,2017-05-02,9,Sörnäinen (M),orange,5.87,deliver_bikes,19:00,deliver 7-9,72.021873
9,2017-05-02,10,Rautatientori / länsi,orange,5.86,deliver_bikes,15:00,deliver 8-10,71.437500
10,2017-05-02,11,Sepänkatu,orange,5.86,deliver_bikes,11:00,deliver 6-8,71.158340
11,2017-05-02,12,Unioninkatu,orange,5.84,deliver_bikes,16:00,deliver 19-21,69.125000
12,2017-05-02,13,Kiasma,orange,5.80,deliver_bikes,20:00,deliver 8-10,66.458336
13,2017-05-02,14,Baana,orange,5.80,deliver_bikes,12:00,deliver 6-8,66.178131
14,2017-05-02,15,Hietalahdentori,orange,5.79,deliver_bikes,16:00,deliver 3-5,65.770828
15,2017-05-02,16,Rautatientori / itä,orange,5.75,deliver_bikes,21:00,deliver 6-8,62.387497
16,2017-05-02,17,Senaatintori,orange,5.71,deliver_bikes,17:00,deliver 9-11,58.446354
17,2017-05-02,18,Töölönlahden puisto,orange,5.70,deliver_bikes,21:00,deliver 5-7,57.928127
18,2017-05-02,19,Kaisaniemenpuisto,blue,5.69,deliver_bikes,20:00,deliver 5-7,57.409901
19,2017-05-02,20,Rautatieläisenkatu,blue,5.68,deliver_bikes,17:00,deliver 4-6,55.987499

In [50]:
# 6.9.9 Weryfikacja zapisanego pliku mapy działań

from pathlib import Path

import pandas as pd


step6_99_required_objects = [
    "step6_98_map_output_path",
    "step6_98_map_input_df",
]

step6_99_missing_objects = [
    object_name
    for object_name in step6_99_required_objects
    if object_name not in globals()
]

assert not step6_99_missing_objects, f"Missing required objects: {step6_99_missing_objects}"

step6_99_map_output_path = Path(step6_98_map_output_path)

step6_99_map_file_exists = bool(step6_99_map_output_path.exists())
step6_99_map_file_size_bytes = int(step6_99_map_output_path.stat().st_size) if step6_99_map_file_exists else 0
step6_99_marker_count = int(step6_98_map_input_df.shape[0])

assert step6_99_map_file_exists, "Map HTML file was not created."
assert step6_99_map_file_size_bytes > 0, "Map HTML file is empty."
assert step6_99_marker_count > 0, "Map input contains no station markers."

step6_99_summary_df = pd.DataFrame(
    [
        {
            "check_area": "map_file_exists",
            "status": "ok",
            "value": str(step6_99_map_file_exists).lower(),
        },
        {
            "check_area": "map_file_size_bytes",
            "status": "ok",
            "value": str(step6_99_map_file_size_bytes),
        },
        {
            "check_area": "marker_count",
            "status": "ok",
            "value": str(step6_99_marker_count),
        },
        {
            "check_area": "map_engine",
            "status": "ok",
            "value": "folium",
        },
        {
            "check_area": "uses_google_maps_api",
            "status": "ok",
            "value": "false",
        },
        {
            "check_area": "map_output_path",
            "status": "ok",
            "value": str(step6_99_map_output_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_99_summary_df[column_name] = step6_99_summary_df[column_name].astype("string")

display(step6_99_summary_df)

,check_area,status,value
0,map_file_exists,ok,true
1,map_file_size_bytes,ok,77149
2,marker_count,ok,50
3,map_engine,ok,folium
4,uses_google_maps_api,ok,false
5,map_output_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

In [51]:
# 6.9.10 Przygotowanie warstwy linii relokacji

from pathlib import Path

import pandas as pd


step6_910_required_objects = [
    "step6_11_reports_dir",
    "step6_95_station_coordinates_df",
]

step6_910_missing_objects = [
    object_name
    for object_name in step6_910_required_objects
    if object_name not in globals()
]

assert not step6_910_missing_objects, f"Missing required objects: {step6_910_missing_objects}"

step6_910_reports_dir = Path(step6_11_reports_dir)
step6_910_local_pair_path = step6_910_reports_dir / "b6_35_microzone_local_pairs.parquet"

assert step6_910_local_pair_path.exists(), "Required local pair file is missing."

step6_910_local_pair_df = pd.read_parquet(step6_910_local_pair_path)
step6_910_coordinates_df = step6_95_station_coordinates_df.copy()

step6_910_required_pair_columns = [
    "activity_date",
    "microzone_id",
    "local_pair_order",
    "donor_station_id",
    "donor_station_name",
    "receiver_station_id",
    "receiver_station_name",
    "paired_relocation_units",
    "pair_expected_business_impact",
    "pairing_reason",
]

step6_910_missing_pair_columns = [
    column_name
    for column_name in step6_910_required_pair_columns
    if column_name not in step6_910_local_pair_df.columns
]

assert not step6_910_missing_pair_columns, f"Missing required pair columns: {step6_910_missing_pair_columns}"

step6_910_required_coordinate_columns = [
    "representative_station_id",
    "station_latitude",
    "station_longitude",
]

step6_910_missing_coordinate_columns = [
    column_name
    for column_name in step6_910_required_coordinate_columns
    if column_name not in step6_910_coordinates_df.columns
]

assert not step6_910_missing_coordinate_columns, f"Missing coordinate columns: {step6_910_missing_coordinate_columns}"

step6_910_coordinates_df = (
    step6_910_coordinates_df[
        [
            "representative_station_id",
            "station_latitude",
            "station_longitude",
        ]
    ]
    .drop_duplicates(subset=["representative_station_id"])
    .copy()
)

step6_910_relocation_line_df = step6_910_local_pair_df.merge(
    step6_910_coordinates_df.rename(
        columns={
            "representative_station_id": "donor_station_id",
            "station_latitude": "donor_latitude",
            "station_longitude": "donor_longitude",
        }
    ),
    on="donor_station_id",
    how="left",
    validate="many_to_one",
)

step6_910_relocation_line_df = step6_910_relocation_line_df.merge(
    step6_910_coordinates_df.rename(
        columns={
            "representative_station_id": "receiver_station_id",
            "station_latitude": "receiver_latitude",
            "station_longitude": "receiver_longitude",
        }
    ),
    on="receiver_station_id",
    how="left",
    validate="many_to_one",
)

if step6_910_relocation_line_df.shape[0] > 0:
    step6_910_relocation_line_df["relocation_line_available"] = True
    step6_910_relocation_line_df["relocation_line_units"] = (
        step6_910_relocation_line_df["paired_relocation_units"]
        .clip(lower=1)
        .astype("int64")
    )
    step6_910_relocation_line_df["relocation_line_popup_text"] = (
        "Microzone: "
        + step6_910_relocation_line_df["microzone_id"].astype("string")
        + "<br>Donor: "
        + step6_910_relocation_line_df["donor_station_name"].astype("string")
        + "<br>Receiver: "
        + step6_910_relocation_line_df["receiver_station_name"].astype("string")
        + "<br>Units: "
        + step6_910_relocation_line_df["paired_relocation_units"].astype("string")
        + "<br>Expected impact: "
        + step6_910_relocation_line_df["pair_expected_business_impact"].round(2).astype("string")
        + "<br>Reason: "
        + step6_910_relocation_line_df["pairing_reason"].astype("string")
    )
else:
    step6_910_relocation_line_df["relocation_line_available"] = pd.Series(dtype="bool")
    step6_910_relocation_line_df["relocation_line_units"] = pd.Series(dtype="int64")
    step6_910_relocation_line_df["relocation_line_popup_text"] = pd.Series(dtype="string")

step6_910_missing_donor_coordinates_count = int(
    step6_910_relocation_line_df[["donor_latitude", "donor_longitude"]]
    .isna()
    .any(axis=1)
    .sum()
) if step6_910_relocation_line_df.shape[0] > 0 else 0

step6_910_missing_receiver_coordinates_count = int(
    step6_910_relocation_line_df[["receiver_latitude", "receiver_longitude"]]
    .isna()
    .any(axis=1)
    .sum()
) if step6_910_relocation_line_df.shape[0] > 0 else 0

step6_910_non_positive_units_count = int(
    step6_910_relocation_line_df["relocation_line_units"].le(0).sum()
) if step6_910_relocation_line_df.shape[0] > 0 else 0

assert step6_910_missing_donor_coordinates_count == 0, "Missing donor coordinates detected."
assert step6_910_missing_receiver_coordinates_count == 0, "Missing receiver coordinates detected."
assert step6_910_non_positive_units_count == 0, "Non-positive relocation line units detected."

step6_910_relocation_line_path = step6_910_reports_dir / "b6_48_relocation_line_layer.parquet"

step6_910_relocation_line_df.to_parquet(step6_910_relocation_line_path, index=False)

step6_910_summary_df = pd.DataFrame(
    [
        {
            "check_area": "local_pair_rows",
            "status": "ok",
            "value": str(step6_910_local_pair_df.shape[0]),
        },
        {
            "check_area": "relocation_line_rows",
            "status": "ok",
            "value": str(step6_910_relocation_line_df.shape[0]),
        },
        {
            "check_area": "missing_donor_coordinates",
            "status": "ok",
            "value": str(step6_910_missing_donor_coordinates_count),
        },
        {
            "check_area": "missing_receiver_coordinates",
            "status": "ok",
            "value": str(step6_910_missing_receiver_coordinates_count),
        },
        {
            "check_area": "non_positive_line_units",
            "status": "ok",
            "value": str(step6_910_non_positive_units_count),
        },
        {
            "check_area": "uses_local_pairing_heuristic",
            "status": "ok",
            "value": "true",
        },
        {
            "check_area": "uses_global_fleet_optimization",
            "status": "ok",
            "value": "false",
        },
        {
            "check_area": "relocation_line_path",
            "status": "ok",
            "value": str(step6_910_relocation_line_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_910_summary_df[column_name] = step6_910_summary_df[column_name].astype("string")

display(step6_910_summary_df)
display(step6_910_relocation_line_df.head(20))

,check_area,status,value
0,local_pair_rows,ok,0
1,relocation_line_rows,ok,0
2,missing_donor_coordinates,ok,0
3,missing_receiver_coordinates,ok,0
4,non_positive_line_units,ok,0
5,uses_local_pairing_heuristic,ok,true
6,uses_global_fleet_optimization,ok,false
7,relocation_line_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

Empty DataFrame
Columns: [activity_date, microzone_id, local_pair_order, donor_station_id, donor_station_name, receiver_station_id, receiver_station_name, donor_available_units, receiver_needed_units, paired_relocation_units, pair_expected_business_impact, pairing_reason, donor_latitude, donor_longitude, receiver_latitude, receiver_longitude, relocation_line_available, relocation_line_units, relocation_line_popup_text]
Index: []

## Podsumowanie działu 6.9 Mapa działań i mapa relokacji

**Kontekst inżynieryjny:** W dziale `6.9` przygotowano warstwę mapową dla panelu dyspozytora jako rozszerzenie finalnego planu dnia, warstwy mikrostref oraz warstwy pewności rekomendacji. Najpierw zdefiniowano kontrakt mapy działań i mapy relokacji, zakładający wykorzystanie biblioteki `folium` jako silnika mapowego, bez używania Google Maps API, kluczy dostępowych i dodatkowych zależności wdrożeniowych. Następnie przygotowano źródło współrzędnych stacji. Spośród dostępnych źródeł wybrano plik `station_location_master.parquet`, który zawierał wymagane kolumny identyfikatora stacji oraz parę współrzędnych `latitude + longitude`. Na tej podstawie zbudowano mapowanie `representative_station_id -> station_latitude + station_longitude` i dołączono współrzędne do dziennego planu działań. W kolejnych krokach przygotowano pola mapowe: kolor markera zależny od poziomu priorytetu, etykietę typu problemu, rozmiar markera oraz tekst popupu zawierający informacje operacyjne. Dla przykładowego dnia testowego `2017-05-02` przygotowano lekki widok mapy obejmujący TOP 50 stacji, a następnie wygenerowano i zapisano mapę jako plik HTML. Mechanizm bazuje jednak na pełnej warstwie mapowej obejmującej `839` dni, dlatego może być zastosowany do dowolnej daty dostępnej w danych. Na końcu przygotowano strukturę warstwy linii relokacji dawca–biorca na podstawie lokalnych par mikrostrefowych.

**Interpretacja wyniku:** Warstwa współrzędnych objęła `344` stacje i zapewniła `100%` pokrycia względem stacji występujących w planie dnia. Po dołączeniu współrzędnych finalna baza mapowa obejmowała `219 071` rekordów na poziomie `day_station`, `839` dni oraz `344` unikalne stacje. Nie wystąpiły braki współrzędnych ani duplikaty klucza `activity_date + representative_station_id`. Warstwa mapowa stacji zawierała `31` kolumn, w tym `map_priority_color`, `map_problem_label`, `map_marker_size` oraz `map_popup_text`. Kolor markera został przypisany według poziomu priorytetu: `very_high -> red`, `high -> orange`, `medium -> blue`, `low -> gray`. Dla przykładowego dnia testowego `2017-05-02` przygotowano mapę TOP 50 stacji. Mapa zawiera `50` markerów, została wygenerowana silnikiem `folium`, zapisana jako plik HTML i nie korzysta z Google Maps API. Kontrola zapisanego pliku potwierdziła, że plik istnieje, nie jest pusty i ma rozmiar `77 149` bajtów. Warstwa linii relokacji została przygotowana na podstawie pliku `b6_35_microzone_local_pairs.parquet`, ale liczba par relokacyjnych wynosi `0`, ponieważ w aktualnych danych nie występują stacje-dawcy typu `remove`.

**Znaczenie biznesowe:** Dział `6.9` rozszerza panel dyspozytora o czytelną warstwę przestrzenną. Dyspozytor nie widzi już tylko tabeli z rankingiem stacji, ale może zobaczyć priorytetowe problemy bezpośrednio na mapie miasta. Kolor punktu wskazuje poziom pilności, rozmiar markera wzmacnia sygnał operacyjny, a popup pokazuje najważniejsze informacje potrzebne do podjęcia decyzji: nazwę stacji, priorytet, typ problemu, rekomendowaną akcję, godzinę największego ryzyka, szacowaną relokację, `Expected Business Impact` oraz pewność rekomendacji. Mapa została ograniczona do TOP 50 stacji dla przykładowego dnia testowego, co zachowuje czytelność i bezpieczeństwo pamięciowe notebooka. Ponieważ pełna warstwa mapowa obejmuje `839` dni, ten sam mechanizm może obsłużyć inne daty dostępne w danych. Warstwa linii dawca–biorca została zaprojektowana jako rozszerzenie mapy relokacji, ale w aktualnym przebiegu danych nie rysuje żadnych linii, ponieważ system nie wskazał stacji, z których można lokalnie zabrać rowery. To zachowuje uczciwą interpretację wyniku: mapa pokazuje realne rekomendacje działań, ale nie udaje globalnej optymalizacji floty ani fikcyjnych przepływów między stacjami.

**Wniosek:** Dział `6.9` został domknięty poprawnie. Przygotowano bazę mapową z pełnym pokryciem współrzędnych, zapisano warstwę markerów stacji oraz wygenerowano plik HTML z mapą działań dla TOP 50 stacji przykładowego dnia testowego `2017-05-02`. Mechanizm nie jest ograniczony do tej jednej daty — korzysta z pełnej warstwy `day_station`, dlatego może być użyty dla dowolnej daty obecnej w danych. Zapisano również strukturę warstwy linii relokacji w pliku `b6_48_relocation_line_layer.parquet`. W aktualnym wyniku liczba linii relokacji wynosi `0`, ponieważ nie występują lokalne pary dawca–biorca. Mapa działań jest gotowa jako artefakt panelu dyspozytora, a mapa relokacji pozostaje zgodna z kontraktem jako mechanizm gotowy do użycia wtedy, gdy dane będą zawierały stacje-dawców.

## 6.10 Aplikacja dyspozytorska

In [88]:
# 6.10.1 Definicja kontraktu aplikacji dyspozytorskiej

from pathlib import Path
import json
import pandas as pd


step6_101_required_objects = [
    "step6_11_reports_dir",
]

step6_101_missing_objects = [
    object_name
    for object_name in step6_101_required_objects
    if object_name not in globals()
]

assert not step6_101_missing_objects, f"Missing required objects: {step6_101_missing_objects}"

step6_101_reports_dir = Path(step6_11_reports_dir)

step6_101_app_contract = {
    "application_name": "Panel dyspozytora relokacji rowerów",
    "application_file": "aplikacja_panel_dyspozytora_rowerow.py",
    "application_role": "single_operational_application",
    "user_facing_block_labels_allowed": False,
    "technical_model_panel_role": "technical_support_tab",
    "uses_new_model_training": False,
    "uses_live_inventory_claim": False,
    "uses_google_maps_api": False,
    "map_engine": "folium",
    "main_navigation_tabs": [
        "Plan dnia",
        "Lista działań",
        "Mikrostrefy",
        "Mapa",
        "Karta kierowcy",
        "Szczegóły stacji",
        "Feedback",
        "Model i dane",
    ],
    "primary_user_language": "polish",
    "main_screen_language_style": "dispatcher_operational_language",
    "technical_language_visibility": "technical_tab_only",
    "feedback_log_file": "b6_operational_feedback_log.json",
    "driver_card_view": True,
    "station_detail_view": True,
    "operational_feedback_loop": True,
    "daily_progress_tracking": True,
}

step6_101_app_tab_contract_df = pd.DataFrame(
    [
        {
            "tab_order": 1,
            "tab_name": "Plan dnia",
            "tab_role": "daily_operational_summary",
            "main_user": "dispatcher",
            "technical_depth": "low",
        },
        {
            "tab_order": 2,
            "tab_name": "Lista działań",
            "tab_role": "full_operational_decision_table",
            "main_user": "dispatcher",
            "technical_depth": "low",
        },
        {
            "tab_order": 3,
            "tab_name": "Mikrostrefy",
            "tab_role": "microzone_summary_and_local_pairing",
            "main_user": "dispatcher",
            "technical_depth": "medium",
        },
        {
            "tab_order": 4,
            "tab_name": "Mapa",
            "tab_role": "spatial_action_view",
            "main_user": "dispatcher",
            "technical_depth": "low",
        },
        {
            "tab_order": 5,
            "tab_name": "Karta kierowcy",
            "tab_role": "driver_task_cards",
            "main_user": "driver",
            "technical_depth": "low",
        },
        {
            "tab_order": 6,
            "tab_name": "Szczegóły stacji",
            "tab_role": "station_operational_details",
            "main_user": "dispatcher",
            "technical_depth": "medium",
        },
        {
            "tab_order": 7,
            "tab_name": "Feedback",
            "tab_role": "operational_feedback_loop",
            "main_user": "dispatcher_driver",
            "technical_depth": "medium",
        },
        {
            "tab_order": 8,
            "tab_name": "Model i dane",
            "tab_role": "technical_model_and_data_support",
            "main_user": "technical_reviewer",
            "technical_depth": "high",
        },
    ]
)

step6_101_app_contract_path = step6_101_reports_dir / "b6_49_dispatcher_app_contract.json"
step6_101_app_tab_contract_path = step6_101_reports_dir / "b6_49_dispatcher_app_tab_contract.parquet"

with open(step6_101_app_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_101_app_contract, file, ensure_ascii=False, indent=2)

step6_101_app_tab_contract_df.to_parquet(step6_101_app_tab_contract_path, index=False)

step6_101_summary_df = pd.DataFrame(
    [
        {
            "check_area": "application_file",
            "status": "ok",
            "value": step6_101_app_contract["application_file"],
        },
        {
            "check_area": "application_role",
            "status": "ok",
            "value": step6_101_app_contract["application_role"],
        },
        {
            "check_area": "application_name",
            "status": "ok",
            "value": step6_101_app_contract["application_name"],
        },
        {
            "check_area": "user_facing_block_labels_allowed",
            "status": "ok",
            "value": str(step6_101_app_contract["user_facing_block_labels_allowed"]).lower(),
        },
        {
            "check_area": "main_navigation_tabs",
            "status": "ok",
            "value": str(len(step6_101_app_contract["main_navigation_tabs"])),
        },
        {
            "check_area": "station_detail_view",
            "status": "ok",
            "value": str(step6_101_app_contract["station_detail_view"]).lower(),
        },
        {
            "check_area": "uses_new_model_training",
            "status": "ok",
            "value": str(step6_101_app_contract["uses_new_model_training"]).lower(),
        },
        {
            "check_area": "uses_live_inventory_claim",
            "status": "ok",
            "value": str(step6_101_app_contract["uses_live_inventory_claim"]).lower(),
        },
        {
            "check_area": "map_engine",
            "status": "ok",
            "value": step6_101_app_contract["map_engine"],
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_101_app_contract_path),
        },
        {
            "check_area": "tab_contract_path",
            "status": "ok",
            "value": str(step6_101_app_tab_contract_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_101_summary_df[column_name] = step6_101_summary_df[column_name].astype("string")

display(step6_101_summary_df)
display(step6_101_app_tab_contract_df)

,check_area,status,value
0,application_file,ok,aplikacja_panel_dyspozytora_rowerow.py
1,application_role,ok,single_operational_application
2,application_name,ok,Panel dyspozytora relokacji rowerów
3,user_facing_block_labels_allowed,ok,false
4,main_navigation_tabs,ok,8
5,station_detail_view,ok,true
6,uses_new_model_training,ok,false
7,uses_live_inventory_claim,ok,false
8,map_engine,ok,folium
9,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
10,tab_contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,tab_order,tab_name,tab_role,main_user,technical_depth
0,1,Plan dnia,daily_operational_summary,dispatcher,low
1,2,Lista działań,full_operational_decision_table,dispatcher,low
2,3,Mikrostrefy,microzone_summary_and_local_pairing,dispatcher,medium
3,4,Mapa,spatial_action_view,dispatcher,low
4,5,Karta kierowcy,driver_task_cards,driver,low
5,6,Szczegóły stacji,station_operational_details,dispatcher,medium
6,7,Feedback,operational_feedback_loop,dispatcher_driver,medium
7,8,Model i dane,technical_model_and_data_support,technical_reviewer,high

In [89]:
# 6.10.2 Weryfikacja artefaktów wejściowych aplikacji

from pathlib import Path

import pandas as pd


step6_102_required_objects = [
    "step6_11_reports_dir",
]

step6_102_missing_objects = [
    object_name
    for object_name in step6_102_required_objects
    if object_name not in globals()
]

assert not step6_102_missing_objects, f"Missing required objects: {step6_102_missing_objects}"

step6_102_reports_dir = Path(step6_11_reports_dir)

step6_102_artifact_specs = [
    {
        "artifact_role": "operational_daily_plan",
        "required_for_tab": "Plan dnia",
        "required": True,
        "file_name": "b6_45_map_station_layer.parquet",
        "expected_grain": "day_station",
    },
    {
        "artifact_role": "action_list",
        "required_for_tab": "Lista działań",
        "required": True,
        "file_name": "b6_45_map_station_layer.parquet",
        "expected_grain": "day_station",
    },
    {
        "artifact_role": "station_details",
        "required_for_tab": "Szczegóły stacji",
        "required": True,
        "file_name": "b6_45_map_station_layer.parquet",
        "expected_grain": "day_station",
    },
    {
        "artifact_role": "driver_cards",
        "required_for_tab": "Karta kierowcy",
        "required": True,
        "file_name": "b6_45_map_station_layer.parquet",
        "expected_grain": "day_station",
    },
    {
        "artifact_role": "microzone_summary",
        "required_for_tab": "Mikrostrefy",
        "required": True,
        "file_name": "b6_34_microzone_summary.parquet",
        "expected_grain": "day_microzone",
    },
    {
        "artifact_role": "local_pairs",
        "required_for_tab": "Mikrostrefy",
        "required": True,
        "file_name": "b6_35_microzone_local_pairs.parquet",
        "expected_grain": "day_microzone_pair",
    },
    {
        "artifact_role": "relocation_line_layer",
        "required_for_tab": "Mapa",
        "required": True,
        "file_name": "b6_48_relocation_line_layer.parquet",
        "expected_grain": "day_microzone_pair",
    },
    {
        "artifact_role": "daily_action_map_html",
        "required_for_tab": "Mapa",
        "required": True,
        "file_name": "b6_47_action_map_top50.html",
        "expected_grain": "selected_day_top50",
    },
    {
        "artifact_role": "app_contract",
        "required_for_tab": "Model i dane",
        "required": True,
        "file_name": "b6_49_dispatcher_app_contract.json",
        "expected_grain": "application_contract",
    },
    {
        "artifact_role": "app_tab_contract",
        "required_for_tab": "Model i dane",
        "required": True,
        "file_name": "b6_49_dispatcher_app_tab_contract.parquet",
        "expected_grain": "application_tab_contract",
    },
]

step6_102_artifact_inventory_df = pd.DataFrame(step6_102_artifact_specs)

step6_102_artifact_inventory_df["resolved_path"] = step6_102_artifact_inventory_df["file_name"].apply(
    lambda file_name: str(step6_102_reports_dir / file_name)
)

step6_102_artifact_inventory_df["file_exists"] = step6_102_artifact_inventory_df["resolved_path"].apply(
    lambda resolved_path: Path(resolved_path).exists()
)

step6_102_artifact_inventory_df["file_size_bytes"] = step6_102_artifact_inventory_df["resolved_path"].apply(
    lambda resolved_path: int(Path(resolved_path).stat().st_size) if Path(resolved_path).exists() else 0
)

step6_102_artifact_inventory_df["row_count"] = None
step6_102_artifact_inventory_df["column_count"] = None

for row_index, row in step6_102_artifact_inventory_df.iterrows():
    artifact_path = Path(row["resolved_path"])

    if artifact_path.exists() and artifact_path.suffix == ".parquet":
        artifact_df = pd.read_parquet(artifact_path)
        step6_102_artifact_inventory_df.loc[row_index, "row_count"] = int(artifact_df.shape[0])
        step6_102_artifact_inventory_df.loc[row_index, "column_count"] = int(artifact_df.shape[1])

step6_102_artifact_inventory_df["status"] = step6_102_artifact_inventory_df.apply(
    lambda row: "ok" if bool(row["file_exists"]) and int(row["file_size_bytes"]) > 0 else "review",
    axis=1,
)

step6_102_missing_required_count = int(
    step6_102_artifact_inventory_df[
        (step6_102_artifact_inventory_df["required"] == True)
        & (step6_102_artifact_inventory_df["status"] != "ok")
    ].shape[0]
)

step6_102_available_required_count = int(
    step6_102_artifact_inventory_df[
        (step6_102_artifact_inventory_df["required"] == True)
        & (step6_102_artifact_inventory_df["status"] == "ok")
    ].shape[0]
)

assert step6_102_missing_required_count == 0, "Missing required application input artifacts."

step6_102_artifact_inventory_path = step6_102_reports_dir / "b6_50_dispatcher_app_input_artifacts.parquet"
step6_102_artifact_inventory_df.to_parquet(step6_102_artifact_inventory_path, index=False)

step6_102_summary_df = pd.DataFrame(
    [
        {
            "check_area": "required_artifacts",
            "status": "ok",
            "value": str(len(step6_102_artifact_specs)),
        },
        {
            "check_area": "available_required_artifacts",
            "status": "ok",
            "value": str(step6_102_available_required_count),
        },
        {
            "check_area": "missing_required_artifacts",
            "status": "ok",
            "value": str(step6_102_missing_required_count),
        },
        {
            "check_area": "main_operational_layer",
            "status": "ok",
            "value": "b6_45_map_station_layer.parquet",
        },
        {
            "check_area": "microzone_summary_layer",
            "status": "ok",
            "value": "b6_34_microzone_summary.parquet",
        },
        {
            "check_area": "map_html_layer",
            "status": "ok",
            "value": "b6_47_action_map_top50.html",
        },
        {
            "check_area": "artifact_inventory_path",
            "status": "ok",
            "value": str(step6_102_artifact_inventory_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_102_summary_df[column_name] = step6_102_summary_df[column_name].astype("string")

display(step6_102_summary_df)
display(step6_102_artifact_inventory_df)

,check_area,status,value
0,required_artifacts,ok,10
1,available_required_artifacts,ok,10
2,missing_required_artifacts,ok,0
3,main_operational_layer,ok,b6_45_map_station_layer.parquet
4,microzone_summary_layer,ok,b6_34_microzone_summary.parquet
5,map_html_layer,ok,b6_47_action_map_top50.html
6,artifact_inventory_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,artifact_role,required_for_tab,required,file_name,expected_grain,resolved_path,file_exists,file_size_bytes,row_count,column_count,status
0,operational_daily_plan,Plan dnia,True,b6_45_map_station_layer.parquet,day_station,/root/projects/6_samodzielny_projekt_koncowy_w...,True,11555208,219071,31,ok
1,action_list,Lista działań,True,b6_45_map_station_layer.parquet,day_station,/root/projects/6_samodzielny_projekt_koncowy_w...,True,11555208,219071,31,ok
2,station_details,Szczegóły stacji,True,b6_45_map_station_layer.parquet,day_station,/root/projects/6_samodzielny_projekt_koncowy_w...,True,11555208,219071,31,ok
3,driver_cards,Karta kierowcy,True,b6_45_map_station_layer.parquet,day_station,/root/projects/6_samodzielny_projekt_koncowy_w...,True,11555208,219071,31,ok
4,microzone_summary,Mikrostrefy,True,b6_34_microzone_summary.parquet,day_microzone,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3558017,191777,15,ok
5,local_pairs,Mikrostrefy,True,b6_35_microzone_local_pairs.parquet,day_microzone_pair,/root/projects/6_samodzielny_projekt_koncowy_w...,True,6584,0,12,ok
6,relocation_line_layer,Mapa,True,b6_48_relocation_line_layer.parquet,day_microzone_pair,/root/projects/6_samodzielny_projekt_koncowy_w...,True,10109,0,19,ok
7,daily_action_map_html,Mapa,True,b6_47_action_map_top50.html,selected_day_top50,/root/projects/6_samodzielny_projekt_koncowy_w...,True,77149,None,None,ok
8,app_contract,Model i dane,True,b6_49_dispatcher_app_contract.json,application_contract,/root/projects/6_samodzielny_projekt_koncowy_w...,True,957,None,None,ok
9,app_tab_contract,Model i dane,True,b6_49_dispatcher_app_tab_contract.parquet,application_tab_contract,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3914,8,5,ok

In [54]:
# 6.10.3 Definicja pól widocznych w aplikacji

from pathlib import Path

import pandas as pd


step6_103_required_objects = [
    "step6_11_reports_dir",
]

step6_103_missing_objects = [
    object_name
    for object_name in step6_103_required_objects
    if object_name not in globals()
]

assert not step6_103_missing_objects, f"Missing required objects: {step6_103_missing_objects}"

step6_103_reports_dir = Path(step6_11_reports_dir)

step6_103_main_layer_path = step6_103_reports_dir / "b6_45_map_station_layer.parquet"
step6_103_microzone_layer_path = step6_103_reports_dir / "b6_34_microzone_summary.parquet"
step6_103_local_pairs_path = step6_103_reports_dir / "b6_35_microzone_local_pairs.parquet"
step6_103_relocation_line_path = step6_103_reports_dir / "b6_48_relocation_line_layer.parquet"

assert step6_103_main_layer_path.exists(), "Main operational layer does not exist."
assert step6_103_microzone_layer_path.exists(), "Microzone summary layer does not exist."
assert step6_103_local_pairs_path.exists(), "Local pairs layer does not exist."
assert step6_103_relocation_line_path.exists(), "Relocation line layer does not exist."

step6_103_main_columns = set(pd.read_parquet(step6_103_main_layer_path).columns)
step6_103_microzone_columns = set(pd.read_parquet(step6_103_microzone_layer_path).columns)
step6_103_local_pairs_columns = set(pd.read_parquet(step6_103_local_pairs_path).columns)
step6_103_relocation_line_columns = set(pd.read_parquet(step6_103_relocation_line_path).columns)

step6_103_tab_field_specs = [
    {
        "tab_name": "Plan dnia",
        "source_file": "b6_45_map_station_layer.parquet",
        "required_fields": [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "microzone_id",
            "priority_level",
            "problem_type",
            "recommended_action",
            "highest_risk_hour_label",
            "estimated_relocation_label",
            "recommendation_confidence_final",
            "expected_business_impact",
        ],
    },
    {
        "tab_name": "Lista działań",
        "source_file": "b6_45_map_station_layer.parquet",
        "required_fields": [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "microzone_id",
            "priority_level",
            "problem_type",
            "recommended_action",
            "highest_risk_hour_label",
            "estimated_relocation_units",
            "estimated_relocation_min",
            "estimated_relocation_max",
            "estimated_relocation_label",
            "recommendation_confidence_final",
            "confidence_score",
            "expected_business_impact",
        ],
    },
    {
        "tab_name": "Mikrostrefy",
        "source_file": "b6_34_microzone_summary.parquet",
        "required_fields": [
            "activity_date",
            "microzone_id",
            "station_count",
            "stations_to_deliver",
            "stations_to_remove",
            "stations_to_check",
            "estimated_deliver_units",
            "estimated_remove_units",
            "microzone_balance",
            "microzone_balance_direction",
            "microzone_expected_business_impact",
            "top_priority_score",
            "top_daily_plan_rank",
        ],
    },
    {
        "tab_name": "Mapa",
        "source_file": "b6_45_map_station_layer.parquet",
        "required_fields": [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "station_latitude",
            "station_longitude",
            "priority_level",
            "map_priority_color",
            "problem_type",
            "map_problem_label",
            "recommended_action",
            "map_marker_size",
            "map_popup_text",
            "expected_business_impact",
        ],
    },
    {
        "tab_name": "Karta kierowcy",
        "source_file": "b6_45_map_station_layer.parquet",
        "required_fields": [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "microzone_id",
            "priority_level",
            "problem_type",
            "recommended_action",
            "highest_risk_hour_label",
            "estimated_relocation_label",
            "recommendation_confidence_final",
            "expected_business_impact",
        ],
    },
    {
        "tab_name": "Szczegóły stacji",
        "source_file": "b6_45_map_station_layer.parquet",
        "required_fields": [
            "activity_date",
            "representative_station_id",
            "station_name",
            "microzone_id",
            "priority_level",
            "problem_type",
            "recommended_action",
            "highest_risk_hour_label",
            "estimated_relocation_label",
            "recommendation_confidence_final",
            "confidence_reason",
            "low_confidence_action",
            "expected_business_impact",
            "total_departures",
            "total_returns",
            "daily_net_flow",
        ],
    },
    {
        "tab_name": "Feedback",
        "source_file": "b6_45_map_station_layer.parquet",
        "required_fields": [
            "activity_date",
            "daily_plan_rank",
            "representative_station_id",
            "station_name",
            "microzone_id",
            "recommended_action",
            "recommendation_confidence_final",
            "expected_business_impact",
        ],
    },
    {
        "tab_name": "Model i dane",
        "source_file": "b6_50_dispatcher_app_input_artifacts.parquet",
        "required_fields": [
            "artifact_role",
            "required_for_tab",
            "file_name",
            "expected_grain",
            "file_exists",
            "file_size_bytes",
            "row_count",
            "column_count",
            "status",
        ],
    },
]

step6_103_source_columns = {
    "b6_45_map_station_layer.parquet": step6_103_main_columns,
    "b6_34_microzone_summary.parquet": step6_103_microzone_columns,
    "b6_35_microzone_local_pairs.parquet": step6_103_local_pairs_columns,
    "b6_48_relocation_line_layer.parquet": step6_103_relocation_line_columns,
    "b6_50_dispatcher_app_input_artifacts.parquet": set(
        pd.read_parquet(step6_103_reports_dir / "b6_50_dispatcher_app_input_artifacts.parquet").columns
    ),
}

step6_103_field_rows = []

for tab_spec in step6_103_tab_field_specs:
    source_file = tab_spec["source_file"]
    available_columns = step6_103_source_columns[source_file]

    for field_order, field_name in enumerate(tab_spec["required_fields"], start=1):
        step6_103_field_rows.append(
            {
                "tab_name": tab_spec["tab_name"],
                "source_file": source_file,
                "field_order": field_order,
                "field_name": field_name,
                "field_exists": field_name in available_columns,
                "field_role": "display_field",
            }
        )

step6_103_app_fields_df = pd.DataFrame(step6_103_field_rows)

step6_103_missing_fields_df = step6_103_app_fields_df[
    step6_103_app_fields_df["field_exists"] == False
].copy()

step6_103_missing_field_count = int(step6_103_missing_fields_df.shape[0])

step6_103_app_fields_path = step6_103_reports_dir / "b6_51_dispatcher_app_display_fields.parquet"
step6_103_missing_fields_path = step6_103_reports_dir / "b6_51_dispatcher_app_missing_fields.parquet"

step6_103_app_fields_df.to_parquet(step6_103_app_fields_path, index=False)
step6_103_missing_fields_df.to_parquet(step6_103_missing_fields_path, index=False)

step6_103_summary_df = pd.DataFrame(
    [
        {
            "check_area": "application_tabs",
            "status": "ok",
            "value": str(len(step6_103_tab_field_specs)),
        },
        {
            "check_area": "display_fields",
            "status": "ok",
            "value": str(step6_103_app_fields_df.shape[0]),
        },
        {
            "check_area": "missing_display_fields",
            "status": "ok" if step6_103_missing_field_count == 0 else "review",
            "value": str(step6_103_missing_field_count),
        },
        {
            "check_area": "display_fields_path",
            "status": "ok",
            "value": str(step6_103_app_fields_path),
        },
        {
            "check_area": "missing_fields_path",
            "status": "ok",
            "value": str(step6_103_missing_fields_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_103_summary_df[column_name] = step6_103_summary_df[column_name].astype("string")

display(step6_103_summary_df)
display(step6_103_app_fields_df)
display(step6_103_missing_fields_df)

,check_area,status,value
0,application_tabs,ok,8
1,display_fields,ok,100
2,missing_display_fields,ok,0
3,display_fields_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
4,missing_fields_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,tab_name,source_file,field_order,field_name,field_exists,field_role
0,Plan dnia,b6_45_map_station_layer.parquet,1,activity_date,True,display_field
1,Plan dnia,b6_45_map_station_layer.parquet,2,daily_plan_rank,True,display_field
2,Plan dnia,b6_45_map_station_layer.parquet,3,representative_station_id,True,display_field
3,Plan dnia,b6_45_map_station_layer.parquet,4,station_name,True,display_field
4,Plan dnia,b6_45_map_station_layer.parquet,5,microzone_id,True,display_field
...,...,...,...,...,...,...
95,Model i dane,b6_50_dispatcher_app_input_artifacts.parquet,5,file_exists,True,display_field
96,Model i dane,b6_50_dispatcher_app_input_artifacts.parquet,6,file_size_bytes,True,display_field
97,Model i dane,b6_50_dispatcher_app_input_artifacts.parquet,7,row_count,True,display_field
98,Model i dane,b6_50_dispatcher_app_input_artifacts.parquet,8,column_count,True,display_field
99,Model i dane,b6_50_dispatcher_app_input_artifacts.parquet,9,status,True,display_field

Empty DataFrame
Columns: [tab_name, source_file, field_order, field_name, field_exists, field_role]
Index: []

In [55]:
# 6.10.4 Definicja etykiet użytkownika aplikacji

from pathlib import Path

import pandas as pd


step6_104_required_objects = [
    "step6_11_reports_dir",
]

step6_104_missing_objects = [
    object_name
    for object_name in step6_104_required_objects
    if object_name not in globals()
]

assert not step6_104_missing_objects, f"Missing required objects: {step6_104_missing_objects}"

step6_104_reports_dir = Path(step6_11_reports_dir)

step6_104_label_specs = [
    {
        "source_field": "activity_date",
        "display_label": "Data",
        "display_group": "Filtry",
        "technical_visibility": "main",
    },
    {
        "source_field": "daily_plan_rank",
        "display_label": "Priorytet dnia",
        "display_group": "Plan dnia",
        "technical_visibility": "main",
    },
    {
        "source_field": "representative_station_id",
        "display_label": "ID stacji",
        "display_group": "Stacja",
        "technical_visibility": "technical",
    },
    {
        "source_field": "station_name",
        "display_label": "Stacja",
        "display_group": "Stacja",
        "technical_visibility": "main",
    },
    {
        "source_field": "microzone_id",
        "display_label": "Mikrostrefa",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "priority_level",
        "display_label": "Pilność",
        "display_group": "Decyzja",
        "technical_visibility": "main",
    },
    {
        "source_field": "problem_type",
        "display_label": "Typ problemu",
        "display_group": "Decyzja",
        "technical_visibility": "main",
    },
    {
        "source_field": "recommended_action",
        "display_label": "Zalecane działanie",
        "display_group": "Decyzja",
        "technical_visibility": "main",
    },
    {
        "source_field": "highest_risk_hour_label",
        "display_label": "Godzina największego ryzyka",
        "display_group": "Czas",
        "technical_visibility": "main",
    },
    {
        "source_field": "estimated_relocation_units",
        "display_label": "Szacowana liczba rowerów",
        "display_group": "Relokacja",
        "technical_visibility": "main",
    },
    {
        "source_field": "estimated_relocation_min",
        "display_label": "Minimum relokacji",
        "display_group": "Relokacja",
        "technical_visibility": "technical",
    },
    {
        "source_field": "estimated_relocation_max",
        "display_label": "Maksimum relokacji",
        "display_group": "Relokacja",
        "technical_visibility": "technical",
    },
    {
        "source_field": "estimated_relocation_label",
        "display_label": "Szacowana relokacja",
        "display_group": "Relokacja",
        "technical_visibility": "main",
    },
    {
        "source_field": "recommendation_confidence_final",
        "display_label": "Pewność rekomendacji",
        "display_group": "Pewność",
        "technical_visibility": "main",
    },
    {
        "source_field": "confidence_score",
        "display_label": "Wynik pewności",
        "display_group": "Pewność",
        "technical_visibility": "technical",
    },
    {
        "source_field": "confidence_reason",
        "display_label": "Uzasadnienie pewności",
        "display_group": "Pewność",
        "technical_visibility": "main",
    },
    {
        "source_field": "low_confidence_action",
        "display_label": "Działanie przy niskiej pewności",
        "display_group": "Pewność",
        "technical_visibility": "main",
    },
    {
        "source_field": "expected_business_impact",
        "display_label": "Szacowany potencjał uratowanych wypożyczeń",
        "display_group": "Wpływ operacyjny",
        "technical_visibility": "main",
    },
    {
        "source_field": "priority_score",
        "display_label": "Wynik priorytetu",
        "display_group": "Wpływ operacyjny",
        "technical_visibility": "technical",
    },
    {
        "source_field": "station_business_scale",
        "display_label": "Skala ruchu stacji",
        "display_group": "Wpływ operacyjny",
        "technical_visibility": "technical",
    },
    {
        "source_field": "total_departures",
        "display_label": "Wypożyczenia",
        "display_group": "Ruch dzienny",
        "technical_visibility": "technical",
    },
    {
        "source_field": "total_returns",
        "display_label": "Zwroty",
        "display_group": "Ruch dzienny",
        "technical_visibility": "technical",
    },
    {
        "source_field": "daily_net_flow",
        "display_label": "Bilans dzienny",
        "display_group": "Ruch dzienny",
        "technical_visibility": "technical",
    },
    {
        "source_field": "station_latitude",
        "display_label": "Szerokość geograficzna",
        "display_group": "Mapa",
        "technical_visibility": "technical",
    },
    {
        "source_field": "station_longitude",
        "display_label": "Długość geograficzna",
        "display_group": "Mapa",
        "technical_visibility": "technical",
    },
    {
        "source_field": "map_priority_color",
        "display_label": "Kolor priorytetu",
        "display_group": "Mapa",
        "technical_visibility": "technical",
    },
    {
        "source_field": "map_problem_label",
        "display_label": "Opis problemu na mapie",
        "display_group": "Mapa",
        "technical_visibility": "main",
    },
    {
        "source_field": "map_marker_size",
        "display_label": "Rozmiar punktu",
        "display_group": "Mapa",
        "technical_visibility": "technical",
    },
    {
        "source_field": "map_popup_text",
        "display_label": "Opis punktu mapy",
        "display_group": "Mapa",
        "technical_visibility": "technical",
    },
    {
        "source_field": "station_count",
        "display_label": "Liczba stacji",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "stations_to_deliver",
        "display_label": "Stacje wymagające dowozu",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "stations_to_remove",
        "display_label": "Stacje wymagające zabrania",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "stations_to_check",
        "display_label": "Stacje do sprawdzenia",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "estimated_deliver_units",
        "display_label": "Szacowany dowóz rowerów",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "estimated_remove_units",
        "display_label": "Szacowane zabranie rowerów",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "microzone_balance",
        "display_label": "Bilans mikrostrefy",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "microzone_balance_direction",
        "display_label": "Kierunek bilansu",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "microzone_expected_business_impact",
        "display_label": "Potencjał mikrostrefy",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "top_priority_score",
        "display_label": "Najwyższy priorytet w mikrostrefie",
        "display_group": "Mikrostrefa",
        "technical_visibility": "technical",
    },
    {
        "source_field": "top_daily_plan_rank",
        "display_label": "Najwyższa pozycja w planie",
        "display_group": "Mikrostrefa",
        "technical_visibility": "main",
    },
    {
        "source_field": "artifact_role",
        "display_label": "Rola artefaktu",
        "display_group": "Model i dane",
        "technical_visibility": "technical",
    },
    {
        "source_field": "required_for_tab",
        "display_label": "Zakładka",
        "display_group": "Model i dane",
        "technical_visibility": "technical",
    },
    {
        "source_field": "file_name",
        "display_label": "Plik",
        "display_group": "Model i dane",
        "technical_visibility": "technical",
    },
    {
        "source_field": "expected_grain",
        "display_label": "Poziom danych",
        "display_group": "Model i dane",
        "technical_visibility": "technical",
    },
    {
        "source_field": "file_exists",
        "display_label": "Plik istnieje",
        "display_group": "Model i dane",
        "technical_visibility": "technical",
    },
    {
        "source_field": "file_size_bytes",
        "display_label": "Rozmiar pliku",
        "display_group": "Model i dane",
        "technical_visibility": "technical",
    },
    {
        "source_field": "row_count",
        "display_label": "Liczba wierszy",
        "display_group": "Model i dane",
        "technical_visibility": "technical",
    },
    {
        "source_field": "column_count",
        "display_label": "Liczba kolumn",
        "display_group": "Model i dane",
        "technical_visibility": "technical",
    },
    {
        "source_field": "status",
        "display_label": "Status",
        "display_group": "Model i dane",
        "technical_visibility": "technical",
    },
]

step6_104_labels_df = pd.DataFrame(step6_104_label_specs)

step6_104_duplicate_source_fields = int(step6_104_labels_df["source_field"].duplicated().sum())
step6_104_missing_labels = int(step6_104_labels_df["display_label"].isna().sum())
step6_104_invalid_visibility = int(
    (~step6_104_labels_df["technical_visibility"].isin(["main", "technical"])).sum()
)

step6_104_labels_path = step6_104_reports_dir / "b6_52_dispatcher_app_user_labels.parquet"
step6_104_labels_df.to_parquet(step6_104_labels_path, index=False)

step6_104_summary_df = pd.DataFrame(
    [
        {
            "check_area": "user_label_rows",
            "status": "ok",
            "value": str(step6_104_labels_df.shape[0]),
        },
        {
            "check_area": "duplicate_source_fields",
            "status": "ok" if step6_104_duplicate_source_fields == 0 else "review",
            "value": str(step6_104_duplicate_source_fields),
        },
        {
            "check_area": "missing_display_labels",
            "status": "ok" if step6_104_missing_labels == 0 else "review",
            "value": str(step6_104_missing_labels),
        },
        {
            "check_area": "invalid_visibility_values",
            "status": "ok" if step6_104_invalid_visibility == 0 else "review",
            "value": str(step6_104_invalid_visibility),
        },
        {
            "check_area": "main_visible_labels",
            "status": "ok",
            "value": str(int((step6_104_labels_df["technical_visibility"] == "main").sum())),
        },
        {
            "check_area": "technical_labels",
            "status": "ok",
            "value": str(int((step6_104_labels_df["technical_visibility"] == "technical").sum())),
        },
        {
            "check_area": "labels_path",
            "status": "ok",
            "value": str(step6_104_labels_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_104_summary_df[column_name] = step6_104_summary_df[column_name].astype("string")

display(step6_104_summary_df)
display(step6_104_labels_df)

,check_area,status,value
0,user_label_rows,ok,49
1,duplicate_source_fields,ok,0
2,missing_display_labels,ok,0
3,invalid_visibility_values,ok,0
4,main_visible_labels,ok,25
5,technical_labels,ok,24
6,labels_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,source_field,display_label,display_group,technical_visibility
0,activity_date,Data,Filtry,main
1,daily_plan_rank,Priorytet dnia,Plan dnia,main
2,representative_station_id,ID stacji,Stacja,technical
3,station_name,Stacja,Stacja,main
4,microzone_id,Mikrostrefa,Mikrostrefa,main
5,priority_level,Pilność,Decyzja,main
6,problem_type,Typ problemu,Decyzja,main
7,recommended_action,Zalecane działanie,Decyzja,main
8,highest_risk_hour_label,Godzina największego ryzyka,Czas,main
9,estimated_relocation_units,Szacowana liczba rowerów,Relokacja,main
10,estimated_relocation_min,Minimum relokacji,Relokacja,technical
11,estimated_relocation_max,Maksimum relokacji,Relokacja,technical
12,estimated_relocation_label,Szacowana relokacja,Relokacja,main
13,recommendation_confidence_final,Pewność rekomendacji,Pewność,main
14,confidence_score,Wynik pewności,Pewność,technical
15,confidence_reason,Uzasadnienie pewności,Pewność,main
16,low_confidence_action,Działanie przy niskiej pewności,Pewność,main
17,expected_business_impact,Szacowany potencjał uratowanych wypożyczeń,Wpływ operacyjny,main
18,priority_score,Wynik priorytetu,Wpływ operacyjny,technical
19,station_business_scale,Skala ruchu stacji,Wpływ operacyjny,technical
20,total_departures,Wypożyczenia,Ruch dzienny,technical
21,total_returns,Zwroty,Ruch dzienny,technical
22,daily_net_flow,Bilans dzienny,Ruch dzienny,technical
23,station_latitude,Szerokość geograficzna,Mapa,technical
24,station_longitude,Długość geograficzna,Mapa,technical
25,map_priority_color,Kolor priorytetu,Mapa,technical
26,map_problem_label,Opis problemu na mapie,Mapa,main
27,map_marker_size,Rozmiar punktu,Mapa,technical
28,map_popup_text,Opis punktu mapy,Mapa,technical
29,station_count,Liczba stacji,Mikrostrefa,main
30,stations_to_deliver,Stacje wymagające dowozu,Mikrostrefa,main
31,stations_to_remove,Stacje wymagające zabrania,Mikrostrefa,main
32,stations_to_check,Stacje do sprawdzenia,Mikrostrefa,main
33,estimated_deliver_units,Szacowany dowóz rowerów,Mikrostrefa,main
34,estimated_remove_units,Szacowane zabranie rowerów,Mikrostrefa,main
35,microzone_balance,Bilans mikrostrefy,Mikrostrefa,main
36,microzone_balance_direction,Kierunek bilansu,Mikrostrefa,main
37,microzone_expected_business_impact,Potencjał mikrostrefy,Mikrostrefa,main
38,top_priority_score,Najwyższy priorytet w mikrostrefie,Mikrostrefa,technical
39,top_daily_plan_rank,Najwyższa pozycja w planie,Mikrostrefa,main
40,artifact_role,Rola artefaktu,Model i dane,technical
41,required_for_tab,Zakładka,Model i dane,technical
42,file_name,Plik,Model i dane,technical
43,expected_grain,Poziom danych,Model i dane,technical
44,file_exists,Plik istnieje,Model i dane,technical
45,file_size_bytes,Rozmiar pliku,Model i dane,technical
46,row_count,Liczba wierszy,Model i dane,technical
47,column_count,Liczba kolumn,Model i dane,technical
48,status,Status,Model i dane,technical

In [56]:
# 6.10.5 Definicja statusów i komunikatów aplikacji

from pathlib import Path

import pandas as pd


step6_105_required_objects = [
    "step6_11_reports_dir",
]

step6_105_missing_objects = [
    object_name
    for object_name in step6_105_required_objects
    if object_name not in globals()
]

assert not step6_105_missing_objects, f"Missing required objects: {step6_105_missing_objects}"

step6_105_reports_dir = Path(step6_11_reports_dir)

step6_105_message_specs = [
    {
        "message_key": "app_title",
        "message_text": "Panel dyspozytora relokacji rowerów",
        "message_scope": "application_header",
        "message_type": "title",
    },
    {
        "message_key": "app_subtitle",
        "message_text": "Operacyjny plan dnia, mapa działań, mikrostrefy i karta pracy kierowcy.",
        "message_scope": "application_header",
        "message_type": "description",
    },
    {
        "message_key": "no_selected_date",
        "message_text": "Wybierz datę planu dnia.",
        "message_scope": "filters",
        "message_type": "info",
    },
    {
        "message_key": "no_actions_for_filters",
        "message_text": "Brak działań dla wybranych filtrów.",
        "message_scope": "filters",
        "message_type": "info",
    },
    {
        "message_key": "low_confidence_instruction",
        "message_text": "Zalecane sprawdzenie stanu stacji przed wykonaniem działania.",
        "message_scope": "recommendation_confidence",
        "message_type": "warning",
    },
    {
        "message_key": "no_local_pairs",
        "message_text": "Brak lokalnych par dawca–biorca dla wybranego dnia.",
        "message_scope": "microzone_pairing",
        "message_type": "info",
    },
    {
        "message_key": "no_relocation_lines",
        "message_text": "Brak linii relokacji do pokazania na mapie dla wybranego dnia.",
        "message_scope": "map",
        "message_type": "info",
    },
    {
        "message_key": "map_loaded",
        "message_text": "Mapa działań została wczytana.",
        "message_scope": "map",
        "message_type": "success",
    },
    {
        "message_key": "feedback_saved",
        "message_text": "Zapisano informację zwrotną.",
        "message_scope": "feedback",
        "message_type": "success",
    },
    {
        "message_key": "feedback_comment_optional",
        "message_text": "Komentarz jest opcjonalny.",
        "message_scope": "feedback",
        "message_type": "info",
    },
    {
        "message_key": "driver_task_accepted",
        "message_text": "Zadanie oznaczono jako przyjęte.",
        "message_scope": "driver_card",
        "message_type": "success",
    },
    {
        "message_key": "driver_task_done",
        "message_text": "Zadanie oznaczono jako wykonane.",
        "message_scope": "driver_card",
        "message_type": "success",
    },
    {
        "message_key": "driver_task_field_issue",
        "message_text": "Zgłoszono błąd w terenie.",
        "message_scope": "driver_card",
        "message_type": "warning",
    },
    {
        "message_key": "technical_view_info",
        "message_text": "Widok techniczny pokazuje źródła danych, artefakty i statusy wejściowe aplikacji.",
        "message_scope": "technical_view",
        "message_type": "info",
    },
]

step6_105_status_specs = [
    {
        "status_key": "accepted",
        "status_label": "Przyjęte",
        "status_scope": "driver_task",
        "allowed_in_feedback": True,
        "progress_completed": False,
    },
    {
        "status_key": "done",
        "status_label": "Wykonane",
        "status_scope": "driver_task",
        "allowed_in_feedback": True,
        "progress_completed": True,
    },
    {
        "status_key": "field_issue",
        "status_label": "Błąd w terenie",
        "status_scope": "driver_task",
        "allowed_in_feedback": True,
        "progress_completed": False,
    },
    {
        "status_key": "rejected_wrong_state",
        "status_label": "Odrzucono — błędny stan",
        "status_scope": "feedback",
        "allowed_in_feedback": True,
        "progress_completed": False,
    },
    {
        "status_key": "relocation_completed",
        "status_label": "Wykonano relokację",
        "status_scope": "feedback",
        "allowed_in_feedback": True,
        "progress_completed": True,
    },
]

step6_105_messages_df = pd.DataFrame(step6_105_message_specs)
step6_105_statuses_df = pd.DataFrame(step6_105_status_specs)

step6_105_duplicate_messages = int(step6_105_messages_df["message_key"].duplicated().sum())
step6_105_duplicate_statuses = int(step6_105_statuses_df["status_key"].duplicated().sum())
step6_105_missing_message_text = int(step6_105_messages_df["message_text"].isna().sum())
step6_105_invalid_feedback_flags = int(step6_105_statuses_df["allowed_in_feedback"].isna().sum())

step6_105_messages_path = step6_105_reports_dir / "b6_53_dispatcher_app_messages.parquet"
step6_105_statuses_path = step6_105_reports_dir / "b6_53_dispatcher_app_feedback_statuses.parquet"

step6_105_messages_df.to_parquet(step6_105_messages_path, index=False)
step6_105_statuses_df.to_parquet(step6_105_statuses_path, index=False)

step6_105_summary_df = pd.DataFrame(
    [
        {
            "check_area": "message_rows",
            "status": "ok",
            "value": str(step6_105_messages_df.shape[0]),
        },
        {
            "check_area": "status_rows",
            "status": "ok",
            "value": str(step6_105_statuses_df.shape[0]),
        },
        {
            "check_area": "duplicate_message_keys",
            "status": "ok" if step6_105_duplicate_messages == 0 else "review",
            "value": str(step6_105_duplicate_messages),
        },
        {
            "check_area": "duplicate_status_keys",
            "status": "ok" if step6_105_duplicate_statuses == 0 else "review",
            "value": str(step6_105_duplicate_statuses),
        },
        {
            "check_area": "missing_message_text",
            "status": "ok" if step6_105_missing_message_text == 0 else "review",
            "value": str(step6_105_missing_message_text),
        },
        {
            "check_area": "invalid_feedback_flags",
            "status": "ok" if step6_105_invalid_feedback_flags == 0 else "review",
            "value": str(step6_105_invalid_feedback_flags),
        },
        {
            "check_area": "messages_path",
            "status": "ok",
            "value": str(step6_105_messages_path),
        },
        {
            "check_area": "statuses_path",
            "status": "ok",
            "value": str(step6_105_statuses_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_105_summary_df[column_name] = step6_105_summary_df[column_name].astype("string")

display(step6_105_summary_df)
display(step6_105_messages_df)
display(step6_105_statuses_df)

,check_area,status,value
0,message_rows,ok,14
1,status_rows,ok,5
2,duplicate_message_keys,ok,0
3,duplicate_status_keys,ok,0
4,missing_message_text,ok,0
5,invalid_feedback_flags,ok,0
6,messages_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,statuses_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,message_key,message_text,message_scope,message_type
0,app_title,Panel dyspozytora relokacji rowerów,application_header,title
1,app_subtitle,"Operacyjny plan dnia, mapa działań, mikrostref...",application_header,description
2,no_selected_date,Wybierz datę planu dnia.,filters,info
3,no_actions_for_filters,Brak działań dla wybranych filtrów.,filters,info
4,low_confidence_instruction,Zalecane sprawdzenie stanu stacji przed wykona...,recommendation_confidence,warning
5,no_local_pairs,Brak lokalnych par dawca–biorca dla wybranego ...,microzone_pairing,info
6,no_relocation_lines,Brak linii relokacji do pokazania na mapie dla...,map,info
7,map_loaded,Mapa działań została wczytana.,map,success
8,feedback_saved,Zapisano informację zwrotną.,feedback,success
9,feedback_comment_optional,Komentarz jest opcjonalny.,feedback,info
10,driver_task_accepted,Zadanie oznaczono jako przyjęte.,driver_card,success
11,driver_task_done,Zadanie oznaczono jako wykonane.,driver_card,success
12,driver_task_field_issue,Zgłoszono błąd w terenie.,driver_card,warning
13,technical_view_info,"Widok techniczny pokazuje źródła danych, artef...",technical_view,info

,status_key,status_label,status_scope,allowed_in_feedback,progress_completed
0,accepted,Przyjęte,driver_task,True,False
1,done,Wykonane,driver_task,True,True
2,field_issue,Błąd w terenie,driver_task,True,False
3,rejected_wrong_state,Odrzucono — błędny stan,feedback,True,False
4,relocation_completed,Wykonano relokację,feedback,True,True

In [57]:
# 6.10.6 Definicja filtrów i KPI aplikacji

from pathlib import Path

import pandas as pd


step6_106_required_objects = [
    "step6_11_reports_dir",
]

step6_106_missing_objects = [
    object_name
    for object_name in step6_106_required_objects
    if object_name not in globals()
]

assert not step6_106_missing_objects, f"Missing required objects: {step6_106_missing_objects}"

step6_106_reports_dir = Path(step6_11_reports_dir)
step6_106_main_layer_path = step6_106_reports_dir / "b6_45_map_station_layer.parquet"
step6_106_microzone_layer_path = step6_106_reports_dir / "b6_34_microzone_summary.parquet"

assert step6_106_main_layer_path.exists(), "Main operational layer does not exist."
assert step6_106_microzone_layer_path.exists(), "Microzone summary layer does not exist."

step6_106_main_columns = set(pd.read_parquet(step6_106_main_layer_path).columns)
step6_106_microzone_columns = set(pd.read_parquet(step6_106_microzone_layer_path).columns)

step6_106_filter_specs = [
    {
        "filter_key": "activity_date",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "activity_date",
        "filter_type": "date_select",
        "default_behavior": "latest_available_date",
        "required": True,
    },
    {
        "filter_key": "priority_level",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "priority_level",
        "filter_type": "multi_select",
        "default_behavior": "all_values",
        "required": True,
    },
    {
        "filter_key": "problem_type",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "problem_type",
        "filter_type": "multi_select",
        "default_behavior": "all_values",
        "required": True,
    },
    {
        "filter_key": "recommended_action",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "recommended_action",
        "filter_type": "multi_select",
        "default_behavior": "all_values",
        "required": True,
    },
    {
        "filter_key": "recommendation_confidence_final",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "recommendation_confidence_final",
        "filter_type": "multi_select",
        "default_behavior": "all_values",
        "required": True,
    },
    {
        "filter_key": "microzone_id",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "microzone_id",
        "filter_type": "multi_select",
        "default_behavior": "all_values",
        "required": True,
    },
    {
        "filter_key": "station_name",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "station_name",
        "filter_type": "text_search",
        "default_behavior": "empty_search",
        "required": True,
    },
]

step6_106_kpi_specs = [
    {
        "kpi_key": "urgent_station_count",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "priority_level",
        "calculation_type": "count_rows_where_priority_in",
        "calculation_condition": "very_high_or_high",
        "target_tab": "Plan dnia",
    },
    {
        "kpi_key": "bike_shortage_station_count",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "problem_type",
        "calculation_type": "count_rows_where_equals",
        "calculation_condition": "bike_shortage_risk",
        "target_tab": "Plan dnia",
    },
    {
        "kpi_key": "dock_shortage_station_count",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "problem_type",
        "calculation_type": "count_rows_where_equals",
        "calculation_condition": "dock_shortage_risk",
        "target_tab": "Plan dnia",
    },
    {
        "kpi_key": "station_check_count",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "recommended_action",
        "calculation_type": "count_rows_where_equals",
        "calculation_condition": "check_station_state",
        "target_tab": "Plan dnia",
    },
    {
        "kpi_key": "estimated_relocation_units_sum",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "estimated_relocation_units",
        "calculation_type": "sum",
        "calculation_condition": "selected_date_filtered_rows",
        "target_tab": "Plan dnia",
    },
    {
        "kpi_key": "expected_business_impact_sum",
        "source_file": "b6_45_map_station_layer.parquet",
        "source_field": "expected_business_impact",
        "calculation_type": "sum",
        "calculation_condition": "selected_date_filtered_rows",
        "target_tab": "Plan dnia",
    },
    {
        "kpi_key": "microzone_count",
        "source_file": "b6_34_microzone_summary.parquet",
        "source_field": "microzone_id",
        "calculation_type": "nunique",
        "calculation_condition": "selected_date_filtered_rows",
        "target_tab": "Mikrostrefy",
    },
    {
        "kpi_key": "microzone_expected_business_impact_sum",
        "source_file": "b6_34_microzone_summary.parquet",
        "source_field": "microzone_expected_business_impact",
        "calculation_type": "sum",
        "calculation_condition": "selected_date_filtered_rows",
        "target_tab": "Mikrostrefy",
    },
]

step6_106_source_columns = {
    "b6_45_map_station_layer.parquet": step6_106_main_columns,
    "b6_34_microzone_summary.parquet": step6_106_microzone_columns,
}

step6_106_filters_df = pd.DataFrame(step6_106_filter_specs)
step6_106_kpis_df = pd.DataFrame(step6_106_kpi_specs)

step6_106_filters_df["source_field_exists"] = step6_106_filters_df.apply(
    lambda row: row["source_field"] in step6_106_source_columns[row["source_file"]],
    axis=1,
)

step6_106_kpis_df["source_field_exists"] = step6_106_kpis_df.apply(
    lambda row: row["source_field"] in step6_106_source_columns[row["source_file"]],
    axis=1,
)

step6_106_missing_filter_fields = int((step6_106_filters_df["source_field_exists"] == False).sum())
step6_106_missing_kpi_fields = int((step6_106_kpis_df["source_field_exists"] == False).sum())

step6_106_filters_path = step6_106_reports_dir / "b6_54_dispatcher_app_filters.parquet"
step6_106_kpis_path = step6_106_reports_dir / "b6_54_dispatcher_app_kpis.parquet"

step6_106_filters_df.to_parquet(step6_106_filters_path, index=False)
step6_106_kpis_df.to_parquet(step6_106_kpis_path, index=False)

step6_106_summary_df = pd.DataFrame(
    [
        {
            "check_area": "filter_rows",
            "status": "ok",
            "value": str(step6_106_filters_df.shape[0]),
        },
        {
            "check_area": "kpi_rows",
            "status": "ok",
            "value": str(step6_106_kpis_df.shape[0]),
        },
        {
            "check_area": "missing_filter_fields",
            "status": "ok" if step6_106_missing_filter_fields == 0 else "review",
            "value": str(step6_106_missing_filter_fields),
        },
        {
            "check_area": "missing_kpi_fields",
            "status": "ok" if step6_106_missing_kpi_fields == 0 else "review",
            "value": str(step6_106_missing_kpi_fields),
        },
        {
            "check_area": "filters_path",
            "status": "ok",
            "value": str(step6_106_filters_path),
        },
        {
            "check_area": "kpis_path",
            "status": "ok",
            "value": str(step6_106_kpis_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_106_summary_df[column_name] = step6_106_summary_df[column_name].astype("string")

display(step6_106_summary_df)
display(step6_106_filters_df)
display(step6_106_kpis_df)

,check_area,status,value
0,filter_rows,ok,7
1,kpi_rows,ok,8
2,missing_filter_fields,ok,0
3,missing_kpi_fields,ok,0
4,filters_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,kpis_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,filter_key,source_file,source_field,filter_type,default_behavior,required,source_field_exists
0,activity_date,b6_45_map_station_layer.parquet,activity_date,date_select,latest_available_date,True,True
1,priority_level,b6_45_map_station_layer.parquet,priority_level,multi_select,all_values,True,True
2,problem_type,b6_45_map_station_layer.parquet,problem_type,multi_select,all_values,True,True
3,recommended_action,b6_45_map_station_layer.parquet,recommended_action,multi_select,all_values,True,True
4,recommendation_confidence_final,b6_45_map_station_layer.parquet,recommendation_confidence_final,multi_select,all_values,True,True
5,microzone_id,b6_45_map_station_layer.parquet,microzone_id,multi_select,all_values,True,True
6,station_name,b6_45_map_station_layer.parquet,station_name,text_search,empty_search,True,True

,kpi_key,source_file,source_field,calculation_type,calculation_condition,target_tab,source_field_exists
0,urgent_station_count,b6_45_map_station_layer.parquet,priority_level,count_rows_where_priority_in,very_high_or_high,Plan dnia,True
1,bike_shortage_station_count,b6_45_map_station_layer.parquet,problem_type,count_rows_where_equals,bike_shortage_risk,Plan dnia,True
2,dock_shortage_station_count,b6_45_map_station_layer.parquet,problem_type,count_rows_where_equals,dock_shortage_risk,Plan dnia,True
3,station_check_count,b6_45_map_station_layer.parquet,recommended_action,count_rows_where_equals,check_station_state,Plan dnia,True
4,estimated_relocation_units_sum,b6_45_map_station_layer.parquet,estimated_relocation_units,sum,selected_date_filtered_rows,Plan dnia,True
5,expected_business_impact_sum,b6_45_map_station_layer.parquet,expected_business_impact,sum,selected_date_filtered_rows,Plan dnia,True
6,microzone_count,b6_34_microzone_summary.parquet,microzone_id,nunique,selected_date_filtered_rows,Mikrostrefy,True
7,microzone_expected_business_impact_sum,b6_34_microzone_summary.parquet,microzone_expected_business_impact,sum,selected_date_filtered_rows,Mikrostrefy,True

## Podsumowanie działu 6.10 Aplikacja dyspozytorska

**Kontekst inżynieryjny:** W dziale `6.10` przygotowano kontrakt aplikacji dyspozytorskiej jako warstwy operacyjnej nad artefaktami BLOKU 6. Zdefiniowano strukturę przyszłej aplikacji, zakładki, artefakty wejściowe, pola widoczne w aplikacji, etykiety prezentacyjne, komunikaty, statusy, filtry oraz KPI. Główną warstwą operacyjną wskazano `b6_45_map_station_layer.parquet`, ponieważ zawiera pełny poziom `day_station` z rankingiem dziennym, nazwą stacji, mikrostrefą, priorytetem, typem problemu, rekomendowaną akcją, godziną największego ryzyka, szacowaną relokacją, pewnością rekomendacji, współrzędnymi oraz `expected_business_impact`.

**Interpretacja wyniku:** Kontrakt aplikacji został zdefiniowany poprawnie. Zdefiniowano `8` głównych zakładek nawigacyjnych: `Plan dnia`, `Lista działań`, `Mikrostrefy`, `Mapa`, `Karta kierowcy`, `Szczegóły stacji`, `Feedback` oraz `Model i dane`. Weryfikacja artefaktów wejściowych potwierdziła dostępność wszystkich `10` wymaganych plików, przy `0` brakujących artefaktach. Główna warstwa `b6_45_map_station_layer.parquet` zawiera `219 071` rekordów i `31` kolumn na poziomie `day_station`, dlatego zasila widoki `Plan dnia`, `Lista działań`, `Szczegóły stacji` oraz `Karta kierowcy`. Warstwa mikrostref `b6_34_microzone_summary.parquet` zawiera `191 777` rekordów i `15` kolumn na poziomie `day_microzone`. Pliki `b6_35_microzone_local_pairs.parquet` oraz `b6_48_relocation_line_layer.parquet` istnieją i mają poprawną strukturę, ale zawierają `0` rekordów, ponieważ w aktualnym przebiegu danych nie występują lokalne pary dawca–biorca. Plik mapy `b6_47_action_map_top50.html` istnieje i stanowi gotowy artefakt HTML dla zakładki mapowej. Zdefiniowano również `100` pól widocznych w zakładkach aplikacji i potwierdzono, że liczba brakujących pól wynosi `0`.

**Znaczenie biznesowe:** Dział `6.10` przekłada techniczne artefakty projektu na strukturę aplikacji operacyjnej dla pracy dyspozytora i kierowcy. Główne widoki aplikacji obejmują plan dnia, listę działań, mikrostrefy, mapę, kartę kierowcy, szczegóły stacji, feedback oraz widok techniczny modelu i danych. Osobna zakładka `Szczegóły stacji` zapewnia dyspozytorowi szybki dostęp do uzasadnienia rekomendacji dla konkretnej stacji, bez konieczności przenoszenia tej informacji do widoku technicznego. Przygotowano `49` etykiet prezentacyjnych, które zamieniają nazwy techniczne na czytelne nazwy widoczne w aplikacji, np. `station_name` jako `Stacja`, `priority_level` jako `Pilność`, `recommended_action` jako `Zalecane działanie`, `estimated_relocation_label` jako `Szacowana relokacja`, a `expected_business_impact` jako `Szacowany potencjał uratowanych wypożyczeń`. Zdefiniowano `14` komunikatów aplikacji oraz `5` statusów operacyjnych, obejmujących m.in. przyjęcie zadania, wykonanie zadania, błąd w terenie, odrzucenie z powodu błędnego stanu oraz wykonanie relokacji. Przygotowano także `7` filtrów oraz `8` KPI, dzięki czemu aplikacja może pełnić funkcję operacyjnego panelu decyzyjnego, a nie wyłącznie statycznej tabeli danych.

**Wniosek:** Dział `6.10` został domknięty poprawnie. Przygotowano kontrakt aplikacji dyspozytorskiej dla pliku `aplikacja_panel_dyspozytora_rowerow.py`, zweryfikowano komplet artefaktów wejściowych, zdefiniowano pola widoczne w aplikacji, słownik etykiet, komunikaty, statusy, filtry oraz KPI. Warstwa aplikacyjna jest zgodna z wcześniejszymi założeniami BLOKU 6: nie tworzy nowego modelu, nie deklaruje dokładnego stanu live inventory i nie generuje fikcyjnych linii relokacji, gdy dane nie zawierają par dawca–biorca. Dział jest gotowy do przejścia do etapu `6.11 Karta pracy dla kierowcy`.

## 6.11 Karta pracy dla kierowcy

In [58]:
# 6.11.1 Kontrakt karty pracy kierowcy

from pathlib import Path

import pandas as pd


step6_111_required_objects = [
    "step6_11_reports_dir",
]

step6_111_missing_objects = [
    object_name
    for object_name in step6_111_required_objects
    if object_name not in globals()
]

assert not step6_111_missing_objects, f"Missing required objects: {step6_111_missing_objects}"

step6_111_reports_dir = Path(step6_11_reports_dir)

step6_111_driver_card_contract = {
    "section": "6.11",
    "section_name": "driver_task_card_view",
    "view_role": "driver_operational_task_view",
    "primary_user": "driver",
    "display_mode": "cards",
    "table_as_primary_view": False,
    "technical_view_included": False,
    "streamlit_container_pattern": True,
    "streamlit_columns_pattern": True,
    "feedback_buttons_included": True,
    "uses_new_model_training": False,
    "uses_live_inventory_claim": False,
    "source_layer": "b6_45_map_station_layer.parquet",
    "optional_pair_layer": "b6_35_microzone_local_pairs.parquet",
    "expected_task_grain": "selected_day_station_task",
}

step6_111_driver_card_fields = [
    {
        "field_name": "task_number",
        "field_role": "driver_task_order",
        "source_field": "daily_plan_rank",
        "display_scope": "card_header",
        "required": True,
    },
    {
        "field_name": "microzone_id",
        "field_role": "local_operational_area",
        "source_field": "microzone_id",
        "display_scope": "card_body",
        "required": True,
    },
    {
        "field_name": "station_name",
        "field_role": "task_station_name",
        "source_field": "station_name",
        "display_scope": "card_body",
        "required": True,
    },
    {
        "field_name": "recommended_action",
        "field_role": "driver_action_type",
        "source_field": "recommended_action",
        "display_scope": "card_body",
        "required": True,
    },
    {
        "field_name": "estimated_relocation_label",
        "field_role": "estimated_relocation_instruction",
        "source_field": "estimated_relocation_label",
        "display_scope": "card_body",
        "required": True,
    },
    {
        "field_name": "highest_risk_hour_label",
        "field_role": "risk_time_hint",
        "source_field": "highest_risk_hour_label",
        "display_scope": "card_body",
        "required": True,
    },
    {
        "field_name": "expected_business_impact",
        "field_role": "estimated_saved_rentals_potential",
        "source_field": "expected_business_impact",
        "display_scope": "card_body",
        "required": True,
    },
    {
        "field_name": "recommendation_confidence_final",
        "field_role": "recommendation_confidence",
        "source_field": "recommendation_confidence_final",
        "display_scope": "card_footer",
        "required": True,
    },
]

step6_111_driver_card_actions = [
    {
        "button_key": "accepted",
        "button_label": "Przyjęte",
        "feedback_status": "accepted",
        "progress_completed": False,
        "display_order": 1,
    },
    {
        "button_key": "done",
        "button_label": "Wykonane",
        "feedback_status": "done",
        "progress_completed": True,
        "display_order": 2,
    },
    {
        "button_key": "field_issue",
        "button_label": "Błąd w terenie",
        "feedback_status": "field_issue",
        "progress_completed": False,
        "display_order": 3,
    },
]

step6_111_driver_card_contract_path = step6_111_reports_dir / "b6_55_driver_card_contract.json"
step6_111_driver_card_fields_path = step6_111_reports_dir / "b6_55_driver_card_fields.parquet"
step6_111_driver_card_actions_path = step6_111_reports_dir / "b6_55_driver_card_actions.parquet"

step6_111_driver_card_fields_df = pd.DataFrame(step6_111_driver_card_fields)
step6_111_driver_card_actions_df = pd.DataFrame(step6_111_driver_card_actions)

pd.Series(step6_111_driver_card_contract).to_json(
    step6_111_driver_card_contract_path,
    force_ascii=False,
    indent=2,
)

step6_111_driver_card_fields_df.to_parquet(step6_111_driver_card_fields_path, index=False)
step6_111_driver_card_actions_df.to_parquet(step6_111_driver_card_actions_path, index=False)

step6_111_duplicate_fields = int(step6_111_driver_card_fields_df["field_name"].duplicated().sum())
step6_111_duplicate_actions = int(step6_111_driver_card_actions_df["button_key"].duplicated().sum())
step6_111_missing_required_fields = int(step6_111_driver_card_fields_df["required"].isna().sum())

step6_111_summary_df = pd.DataFrame(
    [
        {
            "check_area": "driver_card_display_mode",
            "status": "ok",
            "value": step6_111_driver_card_contract["display_mode"],
        },
        {
            "check_area": "table_as_primary_view",
            "status": "ok",
            "value": str(step6_111_driver_card_contract["table_as_primary_view"]).lower(),
        },
        {
            "check_area": "technical_view_included",
            "status": "ok",
            "value": str(step6_111_driver_card_contract["technical_view_included"]).lower(),
        },
        {
            "check_area": "driver_card_fields",
            "status": "ok",
            "value": str(step6_111_driver_card_fields_df.shape[0]),
        },
        {
            "check_area": "driver_card_actions",
            "status": "ok",
            "value": str(step6_111_driver_card_actions_df.shape[0]),
        },
        {
            "check_area": "duplicate_fields",
            "status": "ok" if step6_111_duplicate_fields == 0 else "review",
            "value": str(step6_111_duplicate_fields),
        },
        {
            "check_area": "duplicate_actions",
            "status": "ok" if step6_111_duplicate_actions == 0 else "review",
            "value": str(step6_111_duplicate_actions),
        },
        {
            "check_area": "missing_required_flags",
            "status": "ok" if step6_111_missing_required_fields == 0 else "review",
            "value": str(step6_111_missing_required_fields),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_111_driver_card_contract_path),
        },
        {
            "check_area": "fields_path",
            "status": "ok",
            "value": str(step6_111_driver_card_fields_path),
        },
        {
            "check_area": "actions_path",
            "status": "ok",
            "value": str(step6_111_driver_card_actions_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_111_summary_df[column_name] = step6_111_summary_df[column_name].astype("string")

display(step6_111_summary_df)
display(step6_111_driver_card_fields_df)
display(step6_111_driver_card_actions_df)

,check_area,status,value
0,driver_card_display_mode,ok,cards
1,table_as_primary_view,ok,false
2,technical_view_included,ok,false
3,driver_card_fields,ok,8
4,driver_card_actions,ok,3
5,duplicate_fields,ok,0
6,duplicate_actions,ok,0
7,missing_required_flags,ok,0
8,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
9,fields_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
10,actions_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,field_name,field_role,source_field,display_scope,required
0,task_number,driver_task_order,daily_plan_rank,card_header,True
1,microzone_id,local_operational_area,microzone_id,card_body,True
2,station_name,task_station_name,station_name,card_body,True
3,recommended_action,driver_action_type,recommended_action,card_body,True
4,estimated_relocation_label,estimated_relocation_instruction,estimated_relocation_label,card_body,True
5,highest_risk_hour_label,risk_time_hint,highest_risk_hour_label,card_body,True
6,expected_business_impact,estimated_saved_rentals_potential,expected_business_impact,card_body,True
7,recommendation_confidence_final,recommendation_confidence,recommendation_confidence_final,card_footer,True

,button_key,button_label,feedback_status,progress_completed,display_order
0,accepted,Przyjęte,accepted,False,1
1,done,Wykonane,done,True,2
2,field_issue,Błąd w terenie,field_issue,False,3

In [59]:
# 6.11.2 Weryfikacja źródła danych karty kierowcy

from pathlib import Path

import pandas as pd


step6_112_required_objects = [
    "step6_11_reports_dir",
]

step6_112_missing_objects = [
    object_name
    for object_name in step6_112_required_objects
    if object_name not in globals()
]

assert not step6_112_missing_objects, f"Missing required objects: {step6_112_missing_objects}"

step6_112_reports_dir = Path(step6_11_reports_dir)

step6_112_source_path = step6_112_reports_dir / "b6_45_map_station_layer.parquet"
step6_112_fields_path = step6_112_reports_dir / "b6_55_driver_card_fields.parquet"
step6_112_actions_path = step6_112_reports_dir / "b6_55_driver_card_actions.parquet"

assert step6_112_source_path.exists(), "Driver card source layer does not exist."
assert step6_112_fields_path.exists(), "Driver card fields contract does not exist."
assert step6_112_actions_path.exists(), "Driver card actions contract does not exist."

step6_112_source_df = pd.read_parquet(step6_112_source_path)
step6_112_fields_df = pd.read_parquet(step6_112_fields_path)
step6_112_actions_df = pd.read_parquet(step6_112_actions_path)

step6_112_required_source_fields = step6_112_fields_df["source_field"].dropna().unique().tolist()

step6_112_missing_source_fields = [
    field_name
    for field_name in step6_112_required_source_fields
    if field_name not in step6_112_source_df.columns
]

step6_112_duplicate_day_station_keys = int(
    step6_112_source_df.duplicated(
        subset=["activity_date", "representative_station_id"]
    ).sum()
)

step6_112_missing_task_rank = int(step6_112_source_df["daily_plan_rank"].isna().sum())
step6_112_missing_station_name = int(step6_112_source_df["station_name"].isna().sum())
step6_112_missing_action = int(step6_112_source_df["recommended_action"].isna().sum())
step6_112_missing_relocation_label = int(step6_112_source_df["estimated_relocation_label"].isna().sum())
step6_112_missing_risk_hour = int(step6_112_source_df["highest_risk_hour_label"].isna().sum())
step6_112_missing_impact = int(step6_112_source_df["expected_business_impact"].isna().sum())

step6_112_profile_df = pd.DataFrame(
    [
        {
            "profile_area": "source_rows",
            "status": "ok",
            "value": str(step6_112_source_df.shape[0]),
        },
        {
            "profile_area": "source_columns",
            "status": "ok",
            "value": str(step6_112_source_df.shape[1]),
        },
        {
            "profile_area": "unique_dates",
            "status": "ok",
            "value": str(step6_112_source_df["activity_date"].nunique()),
        },
        {
            "profile_area": "unique_stations",
            "status": "ok",
            "value": str(step6_112_source_df["representative_station_id"].nunique()),
        },
        {
            "profile_area": "duplicate_day_station_keys",
            "status": "ok" if step6_112_duplicate_day_station_keys == 0 else "review",
            "value": str(step6_112_duplicate_day_station_keys),
        },
        {
            "profile_area": "missing_required_source_fields",
            "status": "ok" if len(step6_112_missing_source_fields) == 0 else "review",
            "value": str(len(step6_112_missing_source_fields)),
        },
        {
            "profile_area": "driver_card_field_contract_rows",
            "status": "ok",
            "value": str(step6_112_fields_df.shape[0]),
        },
        {
            "profile_area": "driver_card_action_rows",
            "status": "ok",
            "value": str(step6_112_actions_df.shape[0]),
        },
        {
            "profile_area": "missing_task_rank",
            "status": "ok" if step6_112_missing_task_rank == 0 else "review",
            "value": str(step6_112_missing_task_rank),
        },
        {
            "profile_area": "missing_station_name",
            "status": "ok" if step6_112_missing_station_name == 0 else "review",
            "value": str(step6_112_missing_station_name),
        },
        {
            "profile_area": "missing_action",
            "status": "ok" if step6_112_missing_action == 0 else "review",
            "value": str(step6_112_missing_action),
        },
        {
            "profile_area": "missing_relocation_label",
            "status": "ok" if step6_112_missing_relocation_label == 0 else "review",
            "value": str(step6_112_missing_relocation_label),
        },
        {
            "profile_area": "missing_risk_hour",
            "status": "ok" if step6_112_missing_risk_hour == 0 else "review",
            "value": str(step6_112_missing_risk_hour),
        },
        {
            "profile_area": "missing_expected_business_impact",
            "status": "ok" if step6_112_missing_impact == 0 else "review",
            "value": str(step6_112_missing_impact),
        },
    ]
)

step6_112_missing_fields_df = pd.DataFrame(
    {
        "missing_source_field": step6_112_missing_source_fields,
    }
)

step6_112_profile_path = step6_112_reports_dir / "b6_56_driver_card_source_profile.parquet"
step6_112_missing_fields_path = step6_112_reports_dir / "b6_56_driver_card_missing_source_fields.parquet"

step6_112_profile_df.to_parquet(step6_112_profile_path, index=False)
step6_112_missing_fields_df.to_parquet(step6_112_missing_fields_path, index=False)

for column_name in ["profile_area", "status", "value"]:
    step6_112_profile_df[column_name] = step6_112_profile_df[column_name].astype("string")

display(step6_112_profile_df)
display(step6_112_missing_fields_df)

                        profile_area status   value
0                        source_rows     ok  219071
1                     source_columns     ok      31
2                       unique_dates     ok     839
3                    unique_stations     ok     344
4         duplicate_day_station_keys     ok       0
5     missing_required_source_fields     ok       0
6    driver_card_field_contract_rows     ok       8
7            driver_card_action_rows     ok       3
8                  missing_task_rank     ok       0
9               missing_station_name     ok       0
10                    missing_action     ok       0
11          missing_relocation_label     ok       0
12                 missing_risk_hour     ok       0
13  missing_expected_business_impact     ok       0

Empty DataFrame
Columns: [missing_source_field]
Index: []

In [60]:
# 6.11.3 Budowa warstwy zadań kierowcy

from pathlib import Path

import pandas as pd


step6_113_required_objects = [
    "step6_11_reports_dir",
]

step6_113_missing_objects = [
    object_name
    for object_name in step6_113_required_objects
    if object_name not in globals()
]

assert not step6_113_missing_objects, f"Missing required objects: {step6_113_missing_objects}"

step6_113_reports_dir = Path(step6_11_reports_dir)

step6_113_source_path = step6_113_reports_dir / "b6_45_map_station_layer.parquet"
step6_113_fields_path = step6_113_reports_dir / "b6_55_driver_card_fields.parquet"

assert step6_113_source_path.exists(), "Driver card source layer does not exist."
assert step6_113_fields_path.exists(), "Driver card fields contract does not exist."

step6_113_source_df = pd.read_parquet(step6_113_source_path)
step6_113_fields_df = pd.read_parquet(step6_113_fields_path)

step6_113_source_fields = step6_113_fields_df["source_field"].dropna().unique().tolist()

step6_113_driver_tasks_df = step6_113_source_df[
    [
        "activity_date",
        "representative_station_id",
        *step6_113_source_fields,
    ]
].copy()

step6_113_driver_tasks_df = step6_113_driver_tasks_df.loc[
    :,
    ~step6_113_driver_tasks_df.columns.duplicated(),
].copy()

step6_113_driver_tasks_df["driver_task_id"] = (
    step6_113_driver_tasks_df["activity_date"].astype("string")
    + "_station_"
    + step6_113_driver_tasks_df["representative_station_id"].astype("string")
)

step6_113_driver_tasks_df["driver_task_title"] = (
    "Task "
    + step6_113_driver_tasks_df["daily_plan_rank"].astype("int64").astype("string")
)

step6_113_driver_tasks_df["driver_task_primary_text"] = (
    step6_113_driver_tasks_df["recommended_action"].astype("string")
    + " | "
    + step6_113_driver_tasks_df["estimated_relocation_label"].astype("string")
)

step6_113_driver_tasks_df["driver_task_secondary_text"] = (
    "Risk hour: "
    + step6_113_driver_tasks_df["highest_risk_hour_label"].astype("string")
    + " | Impact: "
    + step6_113_driver_tasks_df["expected_business_impact"].round(2).astype("string")
)

step6_113_driver_tasks_df["driver_task_status_default"] = "not_started"
step6_113_driver_tasks_df["driver_task_completed_default"] = False

step6_113_driver_tasks_df = step6_113_driver_tasks_df.sort_values(
    by=["activity_date", "daily_plan_rank", "representative_station_id"],
    ascending=[True, True, True],
).reset_index(drop=True)

step6_113_duplicate_task_ids = int(step6_113_driver_tasks_df["driver_task_id"].duplicated().sum())
step6_113_missing_task_titles = int(step6_113_driver_tasks_df["driver_task_title"].isna().sum())
step6_113_missing_primary_text = int(step6_113_driver_tasks_df["driver_task_primary_text"].isna().sum())
step6_113_missing_secondary_text = int(step6_113_driver_tasks_df["driver_task_secondary_text"].isna().sum())

step6_113_driver_tasks_path = step6_113_reports_dir / "b6_57_driver_task_card_layer.parquet"

step6_113_driver_tasks_df.to_parquet(step6_113_driver_tasks_path, index=False)

step6_113_summary_df = pd.DataFrame(
    [
        {
            "check_area": "driver_task_rows",
            "status": "ok",
            "value": str(step6_113_driver_tasks_df.shape[0]),
        },
        {
            "check_area": "driver_task_columns",
            "status": "ok",
            "value": str(step6_113_driver_tasks_df.shape[1]),
        },
        {
            "check_area": "unique_dates",
            "status": "ok",
            "value": str(step6_113_driver_tasks_df["activity_date"].nunique()),
        },
        {
            "check_area": "unique_stations",
            "status": "ok",
            "value": str(step6_113_driver_tasks_df["representative_station_id"].nunique()),
        },
        {
            "check_area": "duplicate_driver_task_ids",
            "status": "ok" if step6_113_duplicate_task_ids == 0 else "review",
            "value": str(step6_113_duplicate_task_ids),
        },
        {
            "check_area": "missing_task_titles",
            "status": "ok" if step6_113_missing_task_titles == 0 else "review",
            "value": str(step6_113_missing_task_titles),
        },
        {
            "check_area": "missing_primary_text",
            "status": "ok" if step6_113_missing_primary_text == 0 else "review",
            "value": str(step6_113_missing_primary_text),
        },
        {
            "check_area": "missing_secondary_text",
            "status": "ok" if step6_113_missing_secondary_text == 0 else "review",
            "value": str(step6_113_missing_secondary_text),
        },
        {
            "check_area": "driver_tasks_path",
            "status": "ok",
            "value": str(step6_113_driver_tasks_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_113_summary_df[column_name] = step6_113_summary_df[column_name].astype("string")

display(step6_113_summary_df)
display(step6_113_driver_tasks_df.head(20))

,check_area,status,value
0,driver_task_rows,ok,219071
1,driver_task_columns,ok,16
2,unique_dates,ok,839
3,unique_stations,ok,344
4,duplicate_driver_task_ids,ok,0
5,missing_task_titles,ok,0
6,missing_primary_text,ok,0
7,missing_secondary_text,ok,0
8,driver_tasks_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,activity_date,representative_station_id,daily_plan_rank,microzone_id,station_name,recommended_action,estimated_relocation_label,highest_risk_hour_label,expected_business_impact,recommendation_confidence_final,driver_task_id,driver_task_title,driver_task_primary_text,driver_task_secondary_text,driver_task_status_default,driver_task_completed_default
0,2017-05-02,30,1,MZ_0045,Itämerentori,deliver_bikes,deliver 18-20,17:00,128.742188,high,2017-05-02_station_30,Task 1,deliver_bikes | deliver 18-20,Risk hour: 17:00 | Impact: 128.74,not_started,False
1,2017-05-02,26,2,MZ_0064,Kamppi (M),deliver_bikes,deliver 9-11,16:00,124.333328,high,2017-05-02_station_26,Task 2,deliver_bikes | deliver 9-11,Risk hour: 16:00 | Impact: 124.33,not_started,False
2,2017-05-02,21,3,MZ_0067,Töölönlahdenkatu,deliver_bikes,deliver 11-13,19:00,111.562500,high,2017-05-02_station_21,Task 3,deliver_bikes | deliver 11-13,Risk hour: 19:00 | Impact: 111.56,not_started,False
3,2017-05-02,25,4,MZ_0067,Narinkka,deliver_bikes,deliver 7-9,18:00,103.812500,high,2017-05-02_station_25,Task 4,deliver_bikes | deliver 7-9,Risk hour: 18:00 | Impact: 103.81,not_started,False
4,2017-05-02,40,5,MZ_0099,Hakaniemi (M),deliver_bikes,deliver 6-8,17:00,91.218750,high,2017-05-02_station_40,Task 5,deliver_bikes | deliver 6-8,Risk hour: 17:00 | Impact: 91.22,not_started,False
5,2017-05-02,17,6,MZ_0079,Varsapuistikko,deliver_bikes,deliver 9-11,17:00,77.145828,high,2017-05-02_station_17,Task 6,deliver_bikes | deliver 9-11,Risk hour: 17:00 | Impact: 77.15,not_started,False
6,2017-05-02,41,7,MZ_0113,Ympyrätalo,deliver_bikes,deliver 8-10,13:00,75.312500,high,2017-05-02_station_41,Task 7,deliver_bikes | deliver 8-10,Risk hour: 13:00 | Impact: 75.31,not_started,False
7,2017-05-02,9,8,MZ_0054,Erottajan aukio,deliver_bikes,deliver 13-15,16:00,73.021355,high,2017-05-02_station_9,Task 8,deliver_bikes | deliver 13-15,Risk hour: 16:00 | Impact: 73.02,not_started,False
8,2017-05-02,44,9,MZ_0140,Sörnäinen (M),deliver_bikes,deliver 7-9,19:00,72.021873,high,2017-05-02_station_44,Task 9,deliver_bikes | deliver 7-9,Risk hour: 19:00 | Impact: 72.02,not_started,False
9,2017-05-02,22,10,MZ_0067,Rautatientori / länsi,deliver_bikes,deliver 8-10,15:00,71.437500,high,2017-05-02_station_22,Task 10,deliver_bikes | deliver 8-10,Risk hour: 15:00 | Impact: 71.44,not_started,False
10,2017-05-02,5,11,MZ_0021,Sepänkatu,deliver_bikes,deliver 6-8,11:00,71.158340,high,2017-05-02_station_5,Task 11,deliver_bikes | deliver 6-8,Risk hour: 11:00 | Impact: 71.16,not_started,False
11,2017-05-02,11,12,MZ_0054,Unioninkatu,deliver_bikes,deliver 19-21,16:00,69.125000,high,2017-05-02_station_11,Task 12,deliver_bikes | deliver 19-21,Risk hour: 16:00 | Impact: 69.12,not_started,False
12,2017-05-02,23,13,MZ_0067,Kiasma,deliver_bikes,deliver 8-10,20:00,66.458336,high,2017-05-02_station_23,Task 13,deliver_bikes | deliver 8-10,Risk hour: 20:00 | Impact: 66.46,not_started,False
13,2017-05-02,29,14,MZ_0037,Baana,deliver_bikes,deliver 6-8,12:00,66.178131,high,2017-05-02_station_29,Task 14,deliver_bikes | deliver 6-8,Risk hour: 12:00 | Impact: 66.18,not_started,False
14,2017-05-02,6,15,MZ_0038,Hietalahdentori,deliver_bikes,deliver 3-5,16:00,65.770828,high,2017-05-02_station_6,Task 15,deliver_bikes | deliver 3-5,Risk hour: 16:00 | Impact: 65.77,not_started,False
15,2017-05-02,19,16,MZ_0067,Rautatientori / itä,deliver_bikes,deliver 6-8,21:00,62.387497,high,2017-05-02_station_19,Task 16,deliver_bikes | deliver 6-8,Risk hour: 21:00 | Impact: 62.39,not_started,False
16,2017-05-02,14,17,MZ_0054,Senaatintori,deliver_bikes,deliver 9-11,17:00,58.446354,high,2017-05-02_station_14,Task 17,deliver_bikes | deliver 9-11,Risk hour: 17:00 | Impact: 58.45,not_started,False
17,2017-05-02,150,18,MZ_0083,Töölönlahden puisto,deliver_bikes,deliver 5-7,21:00,57.928127,high,2017-05-02_station_150,Task 18,deliver_bikes | deliver 5-7,Risk hour: 21:00 | Impact: 57.93,not_started,False
18,2017-05-02,20,19,MZ_0067,Kaisaniemenpuisto,deliver_bikes,deliver 5-7,20:00,57.409901,high,2017-05-02_station_20,Task 19,deliver_bikes | deliver 5-7,Risk hour: 20:00 | Impact: 57.41,not_started,False
19,2017-05-02,112,20,MZ_0193,Rautatieläisenkatu,deliver_bikes,deliver 4-6,17:00,55.987499,high,2017-05-02_station_112,Task 20,deliver_bikes | deliver 4-6,Risk hour: 17:00 | Impact: 55.99,not_started,False

In [61]:
# 6.11.4 Przygotowanie dziennego widoku kart kierowcy

from pathlib import Path

import pandas as pd


step6_114_required_objects = [
    "step6_11_reports_dir",
]

step6_114_missing_objects = [
    object_name
    for object_name in step6_114_required_objects
    if object_name not in globals()
]

assert not step6_114_missing_objects, f"Missing required objects: {step6_114_missing_objects}"

step6_114_reports_dir = Path(step6_11_reports_dir)

step6_114_driver_tasks_path = step6_114_reports_dir / "b6_57_driver_task_card_layer.parquet"
step6_114_actions_path = step6_114_reports_dir / "b6_55_driver_card_actions.parquet"

assert step6_114_driver_tasks_path.exists(), "Driver task card layer does not exist."
assert step6_114_actions_path.exists(), "Driver card actions layer does not exist."

step6_114_driver_tasks_df = pd.read_parquet(step6_114_driver_tasks_path)
step6_114_actions_df = pd.read_parquet(step6_114_actions_path)

step6_114_selected_date = step6_114_driver_tasks_df["activity_date"].min()

step6_114_daily_driver_tasks_df = step6_114_driver_tasks_df[
    step6_114_driver_tasks_df["activity_date"] == step6_114_selected_date
].copy()

step6_114_daily_driver_tasks_df = step6_114_daily_driver_tasks_df.sort_values(
    by=["daily_plan_rank", "representative_station_id"],
    ascending=[True, True],
).reset_index(drop=True)

step6_114_daily_driver_tasks_df["driver_card_order"] = range(
    1,
    step6_114_daily_driver_tasks_df.shape[0] + 1,
)

step6_114_daily_driver_tasks_df["driver_card_header"] = (
    "Zadanie "
    + step6_114_daily_driver_tasks_df["driver_card_order"].astype("string")
)

step6_114_daily_driver_tasks_df["driver_card_location_line"] = (
    "Mikrostrefa: "
    + step6_114_daily_driver_tasks_df["microzone_id"].astype("string")
    + " | Stacja: "
    + step6_114_daily_driver_tasks_df["station_name"].astype("string")
)

step6_114_daily_driver_tasks_df["driver_card_action_line"] = (
    "Akcja: "
    + step6_114_daily_driver_tasks_df["recommended_action"].astype("string")
    + " | "
    + step6_114_daily_driver_tasks_df["estimated_relocation_label"].astype("string")
)

step6_114_daily_driver_tasks_df["driver_card_time_line"] = (
    "Godzina ryzyka: "
    + step6_114_daily_driver_tasks_df["highest_risk_hour_label"].astype("string")
)

step6_114_daily_driver_tasks_df["driver_card_impact_line"] = (
    "Szacowany potencjał: "
    + step6_114_daily_driver_tasks_df["expected_business_impact"].round(2).astype("string")
)

step6_114_daily_driver_tasks_df["driver_card_confidence_line"] = (
    "Pewność rekomendacji: "
    + step6_114_daily_driver_tasks_df["recommendation_confidence_final"].astype("string")
)

step6_114_daily_driver_tasks_df["available_action_buttons"] = ", ".join(
    step6_114_actions_df.sort_values("display_order")["button_label"].astype("string").tolist()
)

step6_114_duplicate_daily_task_ids = int(step6_114_daily_driver_tasks_df["driver_task_id"].duplicated().sum())
step6_114_missing_card_headers = int(step6_114_daily_driver_tasks_df["driver_card_header"].isna().sum())
step6_114_missing_location_lines = int(step6_114_daily_driver_tasks_df["driver_card_location_line"].isna().sum())
step6_114_missing_action_lines = int(step6_114_daily_driver_tasks_df["driver_card_action_line"].isna().sum())
step6_114_missing_time_lines = int(step6_114_daily_driver_tasks_df["driver_card_time_line"].isna().sum())
step6_114_missing_impact_lines = int(step6_114_daily_driver_tasks_df["driver_card_impact_line"].isna().sum())

step6_114_daily_driver_cards_path = step6_114_reports_dir / "b6_58_daily_driver_task_cards.parquet"

step6_114_daily_driver_tasks_df.to_parquet(step6_114_daily_driver_cards_path, index=False)

step6_114_summary_df = pd.DataFrame(
    [
        {
            "check_area": "selected_date",
            "status": "ok",
            "value": str(step6_114_selected_date),
        },
        {
            "check_area": "daily_driver_card_rows",
            "status": "ok",
            "value": str(step6_114_daily_driver_tasks_df.shape[0]),
        },
        {
            "check_area": "daily_driver_card_columns",
            "status": "ok",
            "value": str(step6_114_daily_driver_tasks_df.shape[1]),
        },
        {
            "check_area": "duplicate_daily_task_ids",
            "status": "ok" if step6_114_duplicate_daily_task_ids == 0 else "review",
            "value": str(step6_114_duplicate_daily_task_ids),
        },
        {
            "check_area": "missing_card_headers",
            "status": "ok" if step6_114_missing_card_headers == 0 else "review",
            "value": str(step6_114_missing_card_headers),
        },
        {
            "check_area": "missing_location_lines",
            "status": "ok" if step6_114_missing_location_lines == 0 else "review",
            "value": str(step6_114_missing_location_lines),
        },
        {
            "check_area": "missing_action_lines",
            "status": "ok" if step6_114_missing_action_lines == 0 else "review",
            "value": str(step6_114_missing_action_lines),
        },
        {
            "check_area": "missing_time_lines",
            "status": "ok" if step6_114_missing_time_lines == 0 else "review",
            "value": str(step6_114_missing_time_lines),
        },
        {
            "check_area": "missing_impact_lines",
            "status": "ok" if step6_114_missing_impact_lines == 0 else "review",
            "value": str(step6_114_missing_impact_lines),
        },
        {
            "check_area": "available_action_buttons",
            "status": "ok",
            "value": step6_114_daily_driver_tasks_df["available_action_buttons"].iloc[0],
        },
        {
            "check_area": "daily_driver_cards_path",
            "status": "ok",
            "value": str(step6_114_daily_driver_cards_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_114_summary_df[column_name] = step6_114_summary_df[column_name].astype("string")

step6_114_preview_columns = [
    "activity_date",
    "driver_card_order",
    "driver_task_id",
    "driver_card_header",
    "driver_card_location_line",
    "driver_card_action_line",
    "driver_card_time_line",
    "driver_card_impact_line",
    "driver_card_confidence_line",
    "available_action_buttons",
]

display(step6_114_summary_df)
display(step6_114_daily_driver_tasks_df[step6_114_preview_columns].head(20))

,check_area,status,value
0,selected_date,ok,2017-05-02 00:00:00
1,daily_driver_card_rows,ok,142
2,daily_driver_card_columns,ok,24
3,duplicate_daily_task_ids,ok,0
4,missing_card_headers,ok,0
5,missing_location_lines,ok,0
6,missing_action_lines,ok,0
7,missing_time_lines,ok,0
8,missing_impact_lines,ok,0
9,available_action_buttons,ok,"Przyjęte, Wykonane, Błąd w terenie"
10,daily_driver_cards_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,activity_date,driver_card_order,driver_task_id,driver_card_header,driver_card_location_line,driver_card_action_line,driver_card_time_line,driver_card_impact_line,driver_card_confidence_line,available_action_buttons
0,2017-05-02,1,2017-05-02_station_30,Zadanie 1,Mikrostrefa: MZ_0045 | Stacja: Itämerentori,Akcja: deliver_bikes | deliver 18-20,Godzina ryzyka: 17:00,Szacowany potencjał: 128.74,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
1,2017-05-02,2,2017-05-02_station_26,Zadanie 2,Mikrostrefa: MZ_0064 | Stacja: Kamppi (M),Akcja: deliver_bikes | deliver 9-11,Godzina ryzyka: 16:00,Szacowany potencjał: 124.33,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
2,2017-05-02,3,2017-05-02_station_21,Zadanie 3,Mikrostrefa: MZ_0067 | Stacja: Töölönlahdenkatu,Akcja: deliver_bikes | deliver 11-13,Godzina ryzyka: 19:00,Szacowany potencjał: 111.56,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
3,2017-05-02,4,2017-05-02_station_25,Zadanie 4,Mikrostrefa: MZ_0067 | Stacja: Narinkka,Akcja: deliver_bikes | deliver 7-9,Godzina ryzyka: 18:00,Szacowany potencjał: 103.81,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
4,2017-05-02,5,2017-05-02_station_40,Zadanie 5,Mikrostrefa: MZ_0099 | Stacja: Hakaniemi (M),Akcja: deliver_bikes | deliver 6-8,Godzina ryzyka: 17:00,Szacowany potencjał: 91.22,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
5,2017-05-02,6,2017-05-02_station_17,Zadanie 6,Mikrostrefa: MZ_0079 | Stacja: Varsapuistikko,Akcja: deliver_bikes | deliver 9-11,Godzina ryzyka: 17:00,Szacowany potencjał: 77.15,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
6,2017-05-02,7,2017-05-02_station_41,Zadanie 7,Mikrostrefa: MZ_0113 | Stacja: Ympyrätalo,Akcja: deliver_bikes | deliver 8-10,Godzina ryzyka: 13:00,Szacowany potencjał: 75.31,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
7,2017-05-02,8,2017-05-02_station_9,Zadanie 8,Mikrostrefa: MZ_0054 | Stacja: Erottajan aukio,Akcja: deliver_bikes | deliver 13-15,Godzina ryzyka: 16:00,Szacowany potencjał: 73.02,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
8,2017-05-02,9,2017-05-02_station_44,Zadanie 9,Mikrostrefa: MZ_0140 | Stacja: Sörnäinen (M),Akcja: deliver_bikes | deliver 7-9,Godzina ryzyka: 19:00,Szacowany potencjał: 72.02,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
9,2017-05-02,10,2017-05-02_station_22,Zadanie 10,Mikrostrefa: MZ_0067 | Stacja: Rautatientori /...,Akcja: deliver_bikes | deliver 8-10,Godzina ryzyka: 15:00,Szacowany potencjał: 71.44,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
10,2017-05-02,11,2017-05-02_station_5,Zadanie 11,Mikrostrefa: MZ_0021 | Stacja: Sepänkatu,Akcja: deliver_bikes | deliver 6-8,Godzina ryzyka: 11:00,Szacowany potencjał: 71.16,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
11,2017-05-02,12,2017-05-02_station_11,Zadanie 12,Mikrostrefa: MZ_0054 | Stacja: Unioninkatu,Akcja: deliver_bikes | deliver 19-21,Godzina ryzyka: 16:00,Szacowany potencjał: 69.12,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
12,2017-05-02,13,2017-05-02_station_23,Zadanie 13,Mikrostrefa: MZ_0067 | Stacja: Kiasma,Akcja: deliver_bikes | deliver 8-10,Godzina ryzyka: 20:00,Szacowany potencjał: 66.46,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
13,2017-05-02,14,2017-05-02_station_29,Zadanie 14,Mikrostrefa: MZ_0037 | Stacja: Baana,Akcja: deliver_bikes | deliver 6-8,Godzina ryzyka: 12:00,Szacowany potencjał: 66.18,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
14,2017-05-02,15,2017-05-02_station_6,Zadanie 15,Mikrostrefa: MZ_0038 | Stacja: Hietalahdentori,Akcja: deliver_bikes | deliver 3-5,Godzina ryzyka: 16:00,Szacowany potencjał: 65.77,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
15,2017-05-02,16,2017-05-02_station_19,Zadanie 16,Mikrostrefa: MZ_0067 | Stacja: Rautatientori /...,Akcja: deliver_bikes | deliver 6-8,Godzina ryzyka: 21:00,Szacowany potencjał: 62.39,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
16,2017-05-02,17,2017-05-02_station_14,Zadanie 17,Mikrostrefa: MZ_0054 | Stacja: Senaatintori,Akcja: deliver_bikes | deliver 9-11,Godzina ryzyka: 17:00,Szacowany potencjał: 58.45,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
17,2017-05-02,18,2017-05-02_station_150,Zadanie 18,Mikrostrefa: MZ_0083 | Stacja: Töölönlahden pu...,Akcja: deliver_bikes | deliver 5-7,Godzina ryzyka: 21:00,Szacowany potencjał: 57.93,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
18,2017-05-02,19,2017-05-02_station_20,Zadanie 19,Mikrostrefa: MZ_0067 | Stacja: Kaisaniemenpuisto,Akcja: deliver_bikes | deliver 5-7,Godzina ryzyka: 20:00,Szacowany potencjał: 57.41,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
19,2017-05-02,20,2017-05-02_station_112,Zadanie 20,Mikrostrefa: MZ_0193 | Stacja: Rautatieläisenkatu,Akcja: deliver_bikes | deliver 4-6,Godzina ryzyka: 17:00,Szacowany potencjał: 55.99,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"

## Podsumowanie działu 6.11 Karta pracy dla kierowcy

**Kontekst inżynieryjny:** W dziale `6.11` przygotowano warstwę karty pracy kierowcy jako widok operacyjny oparty na artefaktach aplikacji dyspozytorskiej. Widok został zaprojektowany jako układ kart, a nie jako główna tabela danych. Zdefiniowano kontrakt karty kierowcy, pola widoczne na karcie, dostępne akcje operacyjne oraz źródło danych dla zadań. Głównym źródłem danych jest `b6_45_map_station_layer.parquet`, natomiast finalna warstwa zadań kierowcy została zapisana jako `b6_57_driver_task_card_layer.parquet`. Dzienny widok kart dla wybranej daty zapisano jako `b6_58_daily_driver_task_cards.parquet`.

**Interpretacja wyniku:** Kontrakt karty kierowcy został zdefiniowany poprawnie. Widok ma tryb `cards`, `table_as_primary_view = false` oraz `technical_view_included = false`, co potwierdza, że karta kierowcy jest oddzielnym widokiem operacyjnym, a nie techniczną tabelą. Zdefiniowano `8` pól karty: numer zadania, mikrostrefę, nazwę stacji, rekomendowane działanie, szacowaną relokację, godzinę największego ryzyka, szacowany potencjał operacyjny oraz pewność rekomendacji. Zdefiniowano również `3` akcje: `Przyjęte`, `Wykonane` oraz `Błąd w terenie`. Weryfikacja źródła danych potwierdziła `219 071` rekordów, `31` kolumn, `839` dat, `344` stacje, `0` duplikatów klucza dzień–stacja oraz `0` brakujących pól wymaganych do budowy kart.

**Znaczenie biznesowe:** Dział `6.11` przygotowuje praktyczny widok dla pracy terenowej. Karta kierowcy zawiera tylko najważniejsze informacje potrzebne do wykonania zadania: kolejność, lokalizację, stację, typ działania, szacowaną relokację, godzinę ryzyka, potencjalny wpływ oraz status zadania. Dzięki temu widok może być używany na mniejszym ekranie, np. telefonie lub tablecie, bez konieczności pracy na szerokiej tabeli operacyjnej. Przyciski `Przyjęte`, `Wykonane` i `Błąd w terenie` tworzą podstawę do późniejszego feedback loop oraz kontroli postępu dnia.

**Wniosek:** Dział `6.11` został domknięty poprawnie. Zbudowano kontrakt karty kierowcy, zweryfikowano kompletność źródła danych, przygotowano pełną warstwę `b6_57_driver_task_card_layer.parquet` oraz dzienny widok `b6_58_daily_driver_task_cards.parquet`. Dla przykładowej daty `2017-05-02` utworzono `142` karty zadań, bez duplikatów i bez brakujących tekstów kart. Warstwa jest gotowa do późniejszego wykorzystania w aplikacji jako widok kafelkowy dla kierowcy.

## 6.12 Feedback loop / data flywheel

In [62]:
# 6.12.1 Kontrakt pętli zwrotnej z operacji

from pathlib import Path

import pandas as pd


step6_121_required_objects = [
    "step6_11_reports_dir",
]

step6_121_missing_objects = [
    object_name
    for object_name in step6_121_required_objects
    if object_name not in globals()
]

assert not step6_121_missing_objects, f"Missing required objects: {step6_121_missing_objects}"

step6_121_reports_dir = Path(step6_11_reports_dir)

step6_121_feedback_contract = {
    "section": "6.12",
    "section_name": "operational_feedback_loop",
    "feedback_role": "field_operation_feedback_capture",
    "feedback_scope": "driver_task_and_relocation_feedback",
    "feedback_storage_type": "json_log",
    "feedback_log_file_name": "b6_operational_feedback_log.json",
    "uses_new_model_training": False,
    "uses_automatic_retraining": False,
    "human_in_the_loop_ready": True,
    "data_flywheel_ready": True,
    "feedback_is_collected_only": True,
    "source_task_layer": "b6_57_driver_task_card_layer.parquet",
    "daily_task_layer": "b6_58_daily_driver_task_cards.parquet",
    "feedback_status_layer": "b6_53_dispatcher_app_feedback_statuses.parquet",
}

step6_121_feedback_fields = [
    {
        "field_name": "feedback_timestamp",
        "field_role": "event_time",
        "required": True,
        "data_type": "datetime_string",
    },
    {
        "field_name": "activity_date",
        "field_role": "task_date",
        "required": True,
        "data_type": "date_string",
    },
    {
        "field_name": "driver_task_id",
        "field_role": "task_identifier",
        "required": True,
        "data_type": "string",
    },
    {
        "field_name": "representative_station_id",
        "field_role": "station_identifier",
        "required": True,
        "data_type": "integer",
    },
    {
        "field_name": "station_name",
        "field_role": "station_label",
        "required": True,
        "data_type": "string",
    },
    {
        "field_name": "microzone_id",
        "field_role": "local_operational_area",
        "required": True,
        "data_type": "string",
    },
    {
        "field_name": "recommended_action",
        "field_role": "recommendation_type",
        "required": True,
        "data_type": "string",
    },
    {
        "field_name": "estimated_relocation_label",
        "field_role": "estimated_relocation_instruction",
        "required": True,
        "data_type": "string",
    },
    {
        "field_name": "feedback_status",
        "field_role": "field_operation_status",
        "required": True,
        "data_type": "string",
    },
    {
        "field_name": "feedback_comment",
        "field_role": "optional_field_comment",
        "required": False,
        "data_type": "string",
    },
    {
        "field_name": "feedback_source",
        "field_role": "application_source",
        "required": True,
        "data_type": "string",
    },
]

step6_121_feedback_status_specs = [
    {
        "feedback_status": "accepted",
        "display_label": "Przyjęte",
        "status_scope": "driver_task",
        "completed_task": False,
        "field_issue_flag": False,
    },
    {
        "feedback_status": "done",
        "display_label": "Wykonane",
        "status_scope": "driver_task",
        "completed_task": True,
        "field_issue_flag": False,
    },
    {
        "feedback_status": "field_issue",
        "display_label": "Błąd w terenie",
        "status_scope": "driver_task",
        "completed_task": False,
        "field_issue_flag": True,
    },
    {
        "feedback_status": "relocation_completed",
        "display_label": "Wykonano relokację",
        "status_scope": "relocation",
        "completed_task": True,
        "field_issue_flag": False,
    },
    {
        "feedback_status": "rejected_wrong_state",
        "display_label": "Odrzucono — błędny stan",
        "status_scope": "relocation",
        "completed_task": False,
        "field_issue_flag": True,
    },
]

step6_121_feedback_fields_df = pd.DataFrame(step6_121_feedback_fields)
step6_121_feedback_statuses_df = pd.DataFrame(step6_121_feedback_status_specs)

step6_121_contract_path = step6_121_reports_dir / "b6_59_feedback_loop_contract.json"
step6_121_fields_path = step6_121_reports_dir / "b6_59_feedback_log_fields.parquet"
step6_121_statuses_path = step6_121_reports_dir / "b6_59_feedback_status_values.parquet"

pd.Series(step6_121_feedback_contract).to_json(
    step6_121_contract_path,
    force_ascii=False,
    indent=2,
)

step6_121_feedback_fields_df.to_parquet(step6_121_fields_path, index=False)
step6_121_feedback_statuses_df.to_parquet(step6_121_statuses_path, index=False)

step6_121_duplicate_fields = int(step6_121_feedback_fields_df["field_name"].duplicated().sum())
step6_121_duplicate_statuses = int(step6_121_feedback_statuses_df["feedback_status"].duplicated().sum())
step6_121_missing_required_flags = int(step6_121_feedback_fields_df["required"].isna().sum())
step6_121_missing_status_labels = int(step6_121_feedback_statuses_df["display_label"].isna().sum())

step6_121_summary_df = pd.DataFrame(
    [
        {
            "check_area": "feedback_storage_type",
            "status": "ok",
            "value": step6_121_feedback_contract["feedback_storage_type"],
        },
        {
            "check_area": "feedback_log_file_name",
            "status": "ok",
            "value": step6_121_feedback_contract["feedback_log_file_name"],
        },
        {
            "check_area": "feedback_fields",
            "status": "ok",
            "value": str(step6_121_feedback_fields_df.shape[0]),
        },
        {
            "check_area": "feedback_statuses",
            "status": "ok",
            "value": str(step6_121_feedback_statuses_df.shape[0]),
        },
        {
            "check_area": "uses_automatic_retraining",
            "status": "ok",
            "value": str(step6_121_feedback_contract["uses_automatic_retraining"]).lower(),
        },
        {
            "check_area": "feedback_is_collected_only",
            "status": "ok",
            "value": str(step6_121_feedback_contract["feedback_is_collected_only"]).lower(),
        },
        {
            "check_area": "duplicate_fields",
            "status": "ok" if step6_121_duplicate_fields == 0 else "review",
            "value": str(step6_121_duplicate_fields),
        },
        {
            "check_area": "duplicate_statuses",
            "status": "ok" if step6_121_duplicate_statuses == 0 else "review",
            "value": str(step6_121_duplicate_statuses),
        },
        {
            "check_area": "missing_required_flags",
            "status": "ok" if step6_121_missing_required_flags == 0 else "review",
            "value": str(step6_121_missing_required_flags),
        },
        {
            "check_area": "missing_status_labels",
            "status": "ok" if step6_121_missing_status_labels == 0 else "review",
            "value": str(step6_121_missing_status_labels),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_121_contract_path),
        },
        {
            "check_area": "fields_path",
            "status": "ok",
            "value": str(step6_121_fields_path),
        },
        {
            "check_area": "statuses_path",
            "status": "ok",
            "value": str(step6_121_statuses_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_121_summary_df[column_name] = step6_121_summary_df[column_name].astype("string")

display(step6_121_summary_df)
display(step6_121_feedback_fields_df)
display(step6_121_feedback_statuses_df)

,check_area,status,value
0,feedback_storage_type,ok,json_log
1,feedback_log_file_name,ok,b6_operational_feedback_log.json
2,feedback_fields,ok,11
3,feedback_statuses,ok,5
4,uses_automatic_retraining,ok,false
5,feedback_is_collected_only,ok,true
6,duplicate_fields,ok,0
7,duplicate_statuses,ok,0
8,missing_required_flags,ok,0
9,missing_status_labels,ok,0
10,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
11,fields_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
12,statuses_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,field_name,field_role,required,data_type
0,feedback_timestamp,event_time,True,datetime_string
1,activity_date,task_date,True,date_string
2,driver_task_id,task_identifier,True,string
3,representative_station_id,station_identifier,True,integer
4,station_name,station_label,True,string
5,microzone_id,local_operational_area,True,string
6,recommended_action,recommendation_type,True,string
7,estimated_relocation_label,estimated_relocation_instruction,True,string
8,feedback_status,field_operation_status,True,string
9,feedback_comment,optional_field_comment,False,string
10,feedback_source,application_source,True,string

,feedback_status,display_label,status_scope,completed_task,field_issue_flag
0,accepted,Przyjęte,driver_task,False,False
1,done,Wykonane,driver_task,True,False
2,field_issue,Błąd w terenie,driver_task,False,True
3,relocation_completed,Wykonano relokację,relocation,True,False
4,rejected_wrong_state,Odrzucono — błędny stan,relocation,False,True

In [63]:
# 6.12.2 Weryfikacja źródła zadań i statusów feedbacku

from pathlib import Path

import pandas as pd


step6_122_required_objects = [
    "step6_11_reports_dir",
]

step6_122_missing_objects = [
    object_name
    for object_name in step6_122_required_objects
    if object_name not in globals()
]

assert not step6_122_missing_objects, f"Missing required objects: {step6_122_missing_objects}"

step6_122_reports_dir = Path(step6_11_reports_dir)

step6_122_driver_tasks_path = step6_122_reports_dir / "b6_57_driver_task_card_layer.parquet"
step6_122_daily_cards_path = step6_122_reports_dir / "b6_58_daily_driver_task_cards.parquet"
step6_122_feedback_statuses_path = step6_122_reports_dir / "b6_59_feedback_status_values.parquet"
step6_122_feedback_fields_path = step6_122_reports_dir / "b6_59_feedback_log_fields.parquet"

assert step6_122_driver_tasks_path.exists(), "Driver task card layer does not exist."
assert step6_122_daily_cards_path.exists(), "Daily driver task card layer does not exist."
assert step6_122_feedback_statuses_path.exists(), "Feedback status values layer does not exist."
assert step6_122_feedback_fields_path.exists(), "Feedback log fields layer does not exist."

step6_122_driver_tasks_df = pd.read_parquet(step6_122_driver_tasks_path)
step6_122_daily_cards_df = pd.read_parquet(step6_122_daily_cards_path)
step6_122_feedback_statuses_df = pd.read_parquet(step6_122_feedback_statuses_path)
step6_122_feedback_fields_df = pd.read_parquet(step6_122_feedback_fields_path)

step6_122_required_task_fields = [
    "activity_date",
    "driver_task_id",
    "representative_station_id",
    "station_name",
    "microzone_id",
    "recommended_action",
    "estimated_relocation_label",
]

step6_122_missing_task_fields = [
    field_name
    for field_name in step6_122_required_task_fields
    if field_name not in step6_122_driver_tasks_df.columns
]

step6_122_required_feedback_fields = step6_122_feedback_fields_df[
    step6_122_feedback_fields_df["required"] == True
]["field_name"].tolist()

step6_122_status_values = step6_122_feedback_statuses_df["feedback_status"].dropna().astype("string").tolist()

step6_122_duplicate_task_ids = int(step6_122_driver_tasks_df["driver_task_id"].duplicated().sum())
step6_122_duplicate_daily_task_ids = int(step6_122_daily_cards_df["driver_task_id"].duplicated().sum())
step6_122_duplicate_feedback_statuses = int(step6_122_feedback_statuses_df["feedback_status"].duplicated().sum())
step6_122_missing_status_labels = int(step6_122_feedback_statuses_df["display_label"].isna().sum())

step6_122_source_profile_df = pd.DataFrame(
    [
        {
            "check_area": "driver_task_rows",
            "status": "ok",
            "value": str(step6_122_driver_tasks_df.shape[0]),
        },
        {
            "check_area": "daily_card_rows",
            "status": "ok",
            "value": str(step6_122_daily_cards_df.shape[0]),
        },
        {
            "check_area": "feedback_status_rows",
            "status": "ok",
            "value": str(step6_122_feedback_statuses_df.shape[0]),
        },
        {
            "check_area": "feedback_field_rows",
            "status": "ok",
            "value": str(step6_122_feedback_fields_df.shape[0]),
        },
        {
            "check_area": "missing_task_fields",
            "status": "ok" if len(step6_122_missing_task_fields) == 0 else "review",
            "value": str(len(step6_122_missing_task_fields)),
        },
        {
            "check_area": "required_feedback_fields",
            "status": "ok",
            "value": str(len(step6_122_required_feedback_fields)),
        },
        {
            "check_area": "duplicate_task_ids",
            "status": "ok" if step6_122_duplicate_task_ids == 0 else "review",
            "value": str(step6_122_duplicate_task_ids),
        },
        {
            "check_area": "duplicate_daily_task_ids",
            "status": "ok" if step6_122_duplicate_daily_task_ids == 0 else "review",
            "value": str(step6_122_duplicate_daily_task_ids),
        },
        {
            "check_area": "duplicate_feedback_statuses",
            "status": "ok" if step6_122_duplicate_feedback_statuses == 0 else "review",
            "value": str(step6_122_duplicate_feedback_statuses),
        },
        {
            "check_area": "missing_status_labels",
            "status": "ok" if step6_122_missing_status_labels == 0 else "review",
            "value": str(step6_122_missing_status_labels),
        },
        {
            "check_area": "available_feedback_statuses",
            "status": "ok",
            "value": ", ".join(step6_122_status_values),
        },
    ]
)

step6_122_missing_task_fields_df = pd.DataFrame(
    {
        "missing_task_field": step6_122_missing_task_fields,
    }
)

step6_122_source_profile_path = step6_122_reports_dir / "b6_60_feedback_source_profile.parquet"
step6_122_missing_task_fields_path = step6_122_reports_dir / "b6_60_feedback_missing_task_fields.parquet"

step6_122_source_profile_df.to_parquet(step6_122_source_profile_path, index=False)
step6_122_missing_task_fields_df.to_parquet(step6_122_missing_task_fields_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_122_source_profile_df[column_name] = step6_122_source_profile_df[column_name].astype("string")

display(step6_122_source_profile_df)
display(step6_122_missing_task_fields_df)

,check_area,status,value
0,driver_task_rows,ok,219071
1,daily_card_rows,ok,142
2,feedback_status_rows,ok,5
3,feedback_field_rows,ok,11
4,missing_task_fields,ok,0
5,required_feedback_fields,ok,10
6,duplicate_task_ids,ok,0
7,duplicate_daily_task_ids,ok,0
8,duplicate_feedback_statuses,ok,0
9,missing_status_labels,ok,0
10,available_feedback_statuses,ok,"accepted, done, field_issue, relocation_comple..."

Empty DataFrame
Columns: [missing_task_field]
Index: []

In [65]:
# 6.12.3 Budowa przykładowego wpisu feedbacku

from datetime import datetime, timezone
from pathlib import Path

import json
import pandas as pd


step6_123_required_objects = [
    "step6_11_reports_dir",
]

step6_123_missing_objects = [
    object_name
    for object_name in step6_123_required_objects
    if object_name not in globals()
]

assert not step6_123_missing_objects, f"Missing required objects: {step6_123_missing_objects}"

step6_123_reports_dir = Path(step6_11_reports_dir)

step6_123_daily_cards_path = step6_123_reports_dir / "b6_58_daily_driver_task_cards.parquet"
step6_123_feedback_fields_path = step6_123_reports_dir / "b6_59_feedback_log_fields.parquet"
step6_123_feedback_statuses_path = step6_123_reports_dir / "b6_59_feedback_status_values.parquet"

assert step6_123_daily_cards_path.exists(), "Daily driver task card layer does not exist."
assert step6_123_feedback_fields_path.exists(), "Feedback log fields layer does not exist."
assert step6_123_feedback_statuses_path.exists(), "Feedback status values layer does not exist."

step6_123_daily_cards_df = pd.read_parquet(step6_123_daily_cards_path)
step6_123_feedback_fields_df = pd.read_parquet(step6_123_feedback_fields_path)
step6_123_feedback_statuses_df = pd.read_parquet(step6_123_feedback_statuses_path)

step6_123_selected_task = step6_123_daily_cards_df.sort_values(
    by=["driver_card_order", "driver_task_id"],
    ascending=[True, True],
).iloc[0]

step6_123_allowed_statuses = set(
    step6_123_feedback_statuses_df["feedback_status"].dropna().astype("string").tolist()
)

step6_123_feedback_entry = {
    "feedback_timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
    "activity_date": str(step6_123_selected_task["activity_date"]),
    "driver_task_id": str(step6_123_selected_task["driver_task_id"]),
    "representative_station_id": int(step6_123_selected_task["representative_station_id"]),
    "station_name": str(step6_123_selected_task["station_name"]),
    "microzone_id": str(step6_123_selected_task["microzone_id"]),
    "recommended_action": str(step6_123_selected_task["recommended_action"]),
    "estimated_relocation_label": str(step6_123_selected_task["estimated_relocation_label"]),
    "feedback_status": "accepted",
    "feedback_comment": "",
    "feedback_source": "dispatcher_app_driver_card",
}

step6_123_required_feedback_fields = step6_123_feedback_fields_df[
    step6_123_feedback_fields_df["required"] == True
]["field_name"].tolist()

step6_123_missing_entry_fields = [
    field_name
    for field_name in step6_123_required_feedback_fields
    if field_name not in step6_123_feedback_entry
]

step6_123_empty_required_fields = [
    field_name
    for field_name in step6_123_required_feedback_fields
    if str(step6_123_feedback_entry.get(field_name, "")).strip() == ""
]

step6_123_feedback_status_valid = step6_123_feedback_entry["feedback_status"] in step6_123_allowed_statuses

step6_123_feedback_log_path = step6_123_reports_dir / "b6_operational_feedback_log.json"
step6_123_feedback_preview_path = step6_123_reports_dir / "b6_61_feedback_entry_preview.json"

step6_123_feedback_log_payload = {
    "feedback_log_version": "1.0",
    "feedback_entries": [
        step6_123_feedback_entry,
    ],
}

with open(step6_123_feedback_preview_path, "w", encoding="utf-8") as file:
    json.dump(step6_123_feedback_log_payload, file, ensure_ascii=False, indent=2)

if not step6_123_feedback_log_path.exists():
    with open(step6_123_feedback_log_path, "w", encoding="utf-8") as file:
        json.dump(
            {
                "feedback_log_version": "1.0",
                "feedback_entries": [],
            },
            file,
            ensure_ascii=False,
            indent=2,
        )

step6_123_feedback_entry_df = pd.DataFrame([step6_123_feedback_entry])

step6_123_summary_df = pd.DataFrame(
    [
        {
            "check_area": "feedback_entry_fields",
            "status": "ok",
            "value": str(len(step6_123_feedback_entry)),
        },
        {
            "check_area": "missing_required_entry_fields",
            "status": "ok" if len(step6_123_missing_entry_fields) == 0 else "review",
            "value": str(len(step6_123_missing_entry_fields)),
        },
        {
            "check_area": "empty_required_entry_fields",
            "status": "ok" if len(step6_123_empty_required_fields) == 0 else "review",
            "value": str(len(step6_123_empty_required_fields)),
        },
        {
            "check_area": "feedback_status_valid",
            "status": "ok" if step6_123_feedback_status_valid else "review",
            "value": str(step6_123_feedback_status_valid).lower(),
        },
        {
            "check_area": "feedback_log_exists",
            "status": "ok" if step6_123_feedback_log_path.exists() else "review",
            "value": str(step6_123_feedback_log_path.exists()).lower(),
        },
        {
            "check_area": "feedback_log_path",
            "status": "ok",
            "value": str(step6_123_feedback_log_path),
        },
        {
            "check_area": "feedback_preview_path",
            "status": "ok",
            "value": str(step6_123_feedback_preview_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_123_summary_df[column_name] = step6_123_summary_df[column_name].astype("string")

display(step6_123_summary_df)
display(step6_123_feedback_entry_df)

,check_area,status,value
0,feedback_entry_fields,ok,11
1,missing_required_entry_fields,ok,0
2,empty_required_entry_fields,ok,0
3,feedback_status_valid,ok,true
4,feedback_log_exists,ok,true
5,feedback_log_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,feedback_preview_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,feedback_timestamp,activity_date,driver_task_id,representative_station_id,station_name,microzone_id,recommended_action,estimated_relocation_label,feedback_status,feedback_comment,feedback_source
0,2026-05-05T09:11:41Z,2017-05-02 00:00:00,2017-05-02_station_30,30,Itämerentori,MZ_0045,deliver_bikes,deliver 18-20,accepted,,dispatcher_app_driver_card

In [66]:
# 6.12.4 Walidacja zapisu logu feedbacku

from pathlib import Path

import json
import pandas as pd


step6_124_required_objects = [
    "step6_11_reports_dir",
]

step6_124_missing_objects = [
    object_name
    for object_name in step6_124_required_objects
    if object_name not in globals()
]

assert not step6_124_missing_objects, f"Missing required objects: {step6_124_missing_objects}"

step6_124_reports_dir = Path(step6_11_reports_dir)

step6_124_feedback_log_path = step6_124_reports_dir / "b6_operational_feedback_log.json"
step6_124_feedback_preview_path = step6_124_reports_dir / "b6_61_feedback_entry_preview.json"
step6_124_feedback_fields_path = step6_124_reports_dir / "b6_59_feedback_log_fields.parquet"
step6_124_feedback_statuses_path = step6_124_reports_dir / "b6_59_feedback_status_values.parquet"

assert step6_124_feedback_log_path.exists(), "Feedback log file does not exist."
assert step6_124_feedback_preview_path.exists(), "Feedback preview file does not exist."
assert step6_124_feedback_fields_path.exists(), "Feedback log fields layer does not exist."
assert step6_124_feedback_statuses_path.exists(), "Feedback status values layer does not exist."

with open(step6_124_feedback_log_path, "r", encoding="utf-8") as file:
    step6_124_feedback_log_payload = json.load(file)

with open(step6_124_feedback_preview_path, "r", encoding="utf-8") as file:
    step6_124_feedback_preview_payload = json.load(file)

step6_124_feedback_fields_df = pd.read_parquet(step6_124_feedback_fields_path)
step6_124_feedback_statuses_df = pd.read_parquet(step6_124_feedback_statuses_path)

step6_124_required_feedback_fields = step6_124_feedback_fields_df[
    step6_124_feedback_fields_df["required"] == True
]["field_name"].tolist()

step6_124_allowed_statuses = set(
    step6_124_feedback_statuses_df["feedback_status"].dropna().astype("string").tolist()
)

step6_124_log_entries = step6_124_feedback_log_payload.get("feedback_entries", [])
step6_124_preview_entries = step6_124_feedback_preview_payload.get("feedback_entries", [])

step6_124_log_has_version = "feedback_log_version" in step6_124_feedback_log_payload
step6_124_log_entries_is_list = isinstance(step6_124_log_entries, list)
step6_124_preview_entries_is_list = isinstance(step6_124_preview_entries, list)

step6_124_preview_entry = step6_124_preview_entries[0] if step6_124_preview_entries else {}

step6_124_preview_missing_required_fields = [
    field_name
    for field_name in step6_124_required_feedback_fields
    if field_name not in step6_124_preview_entry
]

step6_124_preview_empty_required_fields = [
    field_name
    for field_name in step6_124_required_feedback_fields
    if str(step6_124_preview_entry.get(field_name, "")).strip() == ""
]

step6_124_preview_status_valid = (
    step6_124_preview_entry.get("feedback_status") in step6_124_allowed_statuses
)

step6_124_log_file_size_bytes = step6_124_feedback_log_path.stat().st_size
step6_124_preview_file_size_bytes = step6_124_feedback_preview_path.stat().st_size

step6_124_validation_df = pd.DataFrame(
    [
        {
            "check_area": "feedback_log_has_version",
            "status": "ok" if step6_124_log_has_version else "review",
            "value": str(step6_124_log_has_version).lower(),
        },
        {
            "check_area": "feedback_log_entries_is_list",
            "status": "ok" if step6_124_log_entries_is_list else "review",
            "value": str(step6_124_log_entries_is_list).lower(),
        },
        {
            "check_area": "feedback_log_entry_count",
            "status": "ok",
            "value": str(len(step6_124_log_entries)),
        },
        {
            "check_area": "feedback_preview_entries_is_list",
            "status": "ok" if step6_124_preview_entries_is_list else "review",
            "value": str(step6_124_preview_entries_is_list).lower(),
        },
        {
            "check_area": "feedback_preview_entry_count",
            "status": "ok",
            "value": str(len(step6_124_preview_entries)),
        },
        {
            "check_area": "preview_missing_required_fields",
            "status": "ok" if len(step6_124_preview_missing_required_fields) == 0 else "review",
            "value": str(len(step6_124_preview_missing_required_fields)),
        },
        {
            "check_area": "preview_empty_required_fields",
            "status": "ok" if len(step6_124_preview_empty_required_fields) == 0 else "review",
            "value": str(len(step6_124_preview_empty_required_fields)),
        },
        {
            "check_area": "preview_status_valid",
            "status": "ok" if step6_124_preview_status_valid else "review",
            "value": str(step6_124_preview_status_valid).lower(),
        },
        {
            "check_area": "feedback_log_file_size_bytes",
            "status": "ok",
            "value": str(step6_124_log_file_size_bytes),
        },
        {
            "check_area": "feedback_preview_file_size_bytes",
            "status": "ok",
            "value": str(step6_124_preview_file_size_bytes),
        },
    ]
)

step6_124_preview_entry_df = pd.DataFrame([step6_124_preview_entry])

step6_124_validation_path = step6_124_reports_dir / "b6_62_feedback_log_validation.parquet"
step6_124_preview_entry_path = step6_124_reports_dir / "b6_62_feedback_preview_entry.parquet"

step6_124_validation_df.to_parquet(step6_124_validation_path, index=False)
step6_124_preview_entry_df.to_parquet(step6_124_preview_entry_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_124_validation_df[column_name] = step6_124_validation_df[column_name].astype("string")

display(step6_124_validation_df)
display(step6_124_preview_entry_df)

                         check_area status value
0          feedback_log_has_version     ok  true
1      feedback_log_entries_is_list     ok  true
2          feedback_log_entry_count     ok     0
3  feedback_preview_entries_is_list     ok  true
4      feedback_preview_entry_count     ok     1
5   preview_missing_required_fields     ok     0
6     preview_empty_required_fields     ok     0
7              preview_status_valid     ok  true
8      feedback_log_file_size_bytes     ok    61
9  feedback_preview_file_size_bytes     ok   553

,feedback_timestamp,activity_date,driver_task_id,representative_station_id,station_name,microzone_id,recommended_action,estimated_relocation_label,feedback_status,feedback_comment,feedback_source
0,2026-05-05T09:11:41Z,2017-05-02 00:00:00,2017-05-02_station_30,30,Itämerentori,MZ_0045,deliver_bikes,deliver 18-20,accepted,,dispatcher_app_driver_card

In [67]:
# 6.12.5 Przygotowanie agregacji feedbacku operacyjnego

from pathlib import Path

import json
import pandas as pd


step6_125_required_objects = [
    "step6_11_reports_dir",
]

step6_125_missing_objects = [
    object_name
    for object_name in step6_125_required_objects
    if object_name not in globals()
]

assert not step6_125_missing_objects, f"Missing required objects: {step6_125_missing_objects}"

step6_125_reports_dir = Path(step6_11_reports_dir)

step6_125_feedback_log_path = step6_125_reports_dir / "b6_operational_feedback_log.json"
step6_125_feedback_preview_path = step6_125_reports_dir / "b6_61_feedback_entry_preview.json"
step6_125_feedback_fields_path = step6_125_reports_dir / "b6_59_feedback_log_fields.parquet"
step6_125_feedback_statuses_path = step6_125_reports_dir / "b6_59_feedback_status_values.parquet"

assert step6_125_feedback_log_path.exists(), "Feedback log file does not exist."
assert step6_125_feedback_preview_path.exists(), "Feedback preview file does not exist."
assert step6_125_feedback_fields_path.exists(), "Feedback log fields layer does not exist."
assert step6_125_feedback_statuses_path.exists(), "Feedback status values layer does not exist."

with open(step6_125_feedback_log_path, "r", encoding="utf-8") as file:
    step6_125_feedback_log_payload = json.load(file)

with open(step6_125_feedback_preview_path, "r", encoding="utf-8") as file:
    step6_125_feedback_preview_payload = json.load(file)

step6_125_feedback_fields_df = pd.read_parquet(step6_125_feedback_fields_path)
step6_125_feedback_statuses_df = pd.read_parquet(step6_125_feedback_statuses_path)

step6_125_feedback_log_entries = step6_125_feedback_log_payload.get("feedback_entries", [])
step6_125_feedback_preview_entries = step6_125_feedback_preview_payload.get("feedback_entries", [])

step6_125_feedback_column_order = step6_125_feedback_fields_df["field_name"].tolist()

step6_125_feedback_log_df = pd.DataFrame(
    step6_125_feedback_log_entries,
    columns=step6_125_feedback_column_order,
)

step6_125_feedback_preview_df = pd.DataFrame(
    step6_125_feedback_preview_entries,
    columns=step6_125_feedback_column_order,
)

step6_125_feedback_for_aggregation_df = step6_125_feedback_log_df.copy()

if step6_125_feedback_for_aggregation_df.empty:
    step6_125_feedback_status_summary_df = pd.DataFrame(
        columns=[
            "feedback_status",
            "feedback_count",
            "completed_task",
            "field_issue_flag",
        ]
    )
    step6_125_feedback_station_summary_df = pd.DataFrame(
        columns=[
            "activity_date",
            "representative_station_id",
            "station_name",
            "feedback_count",
            "completed_feedback_count",
            "field_issue_feedback_count",
        ]
    )
else:
    step6_125_feedback_for_aggregation_df = step6_125_feedback_for_aggregation_df.merge(
        step6_125_feedback_statuses_df[
            [
                "feedback_status",
                "completed_task",
                "field_issue_flag",
            ]
        ],
        on="feedback_status",
        how="left",
    )

    step6_125_feedback_status_summary_df = (
        step6_125_feedback_for_aggregation_df
        .groupby(
            [
                "feedback_status",
                "completed_task",
                "field_issue_flag",
            ],
            dropna=False,
        )
        .size()
        .reset_index(name="feedback_count")
        .sort_values(
            by=["feedback_count", "feedback_status"],
            ascending=[False, True],
        )
        .reset_index(drop=True)
    )

    step6_125_feedback_station_summary_df = (
        step6_125_feedback_for_aggregation_df
        .groupby(
            [
                "activity_date",
                "representative_station_id",
                "station_name",
            ],
            dropna=False,
        )
        .agg(
            feedback_count=("feedback_status", "size"),
            completed_feedback_count=("completed_task", "sum"),
            field_issue_feedback_count=("field_issue_flag", "sum"),
        )
        .reset_index()
        .sort_values(
            by=["feedback_count", "activity_date", "representative_station_id"],
            ascending=[False, True, True],
        )
        .reset_index(drop=True)
    )

step6_125_feedback_status_summary_path = step6_125_reports_dir / "b6_63_feedback_status_summary.parquet"
step6_125_feedback_station_summary_path = step6_125_reports_dir / "b6_63_feedback_station_summary.parquet"
step6_125_feedback_preview_flat_path = step6_125_reports_dir / "b6_63_feedback_preview_flat.parquet"

step6_125_feedback_status_summary_df.to_parquet(step6_125_feedback_status_summary_path, index=False)
step6_125_feedback_station_summary_df.to_parquet(step6_125_feedback_station_summary_path, index=False)
step6_125_feedback_preview_df.to_parquet(step6_125_feedback_preview_flat_path, index=False)

step6_125_log_entry_count = len(step6_125_feedback_log_entries)
step6_125_preview_entry_count = len(step6_125_feedback_preview_entries)
step6_125_status_summary_rows = step6_125_feedback_status_summary_df.shape[0]
step6_125_station_summary_rows = step6_125_feedback_station_summary_df.shape[0]

step6_125_summary_df = pd.DataFrame(
    [
        {
            "check_area": "feedback_log_entry_count",
            "status": "ok",
            "value": str(step6_125_log_entry_count),
        },
        {
            "check_area": "feedback_preview_entry_count",
            "status": "ok",
            "value": str(step6_125_preview_entry_count),
        },
        {
            "check_area": "status_summary_rows",
            "status": "ok",
            "value": str(step6_125_status_summary_rows),
        },
        {
            "check_area": "station_summary_rows",
            "status": "ok",
            "value": str(step6_125_station_summary_rows),
        },
        {
            "check_area": "empty_log_is_valid",
            "status": "ok",
            "value": str(step6_125_log_entry_count == 0).lower(),
        },
        {
            "check_area": "status_summary_path",
            "status": "ok",
            "value": str(step6_125_feedback_status_summary_path),
        },
        {
            "check_area": "station_summary_path",
            "status": "ok",
            "value": str(step6_125_feedback_station_summary_path),
        },
        {
            "check_area": "preview_flat_path",
            "status": "ok",
            "value": str(step6_125_feedback_preview_flat_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_125_summary_df[column_name] = step6_125_summary_df[column_name].astype("string")

display(step6_125_summary_df)
display(step6_125_feedback_status_summary_df)
display(step6_125_feedback_station_summary_df)
display(step6_125_feedback_preview_df)

,check_area,status,value
0,feedback_log_entry_count,ok,0
1,feedback_preview_entry_count,ok,1
2,status_summary_rows,ok,0
3,station_summary_rows,ok,0
4,empty_log_is_valid,ok,true
5,status_summary_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
6,station_summary_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
7,preview_flat_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

Empty DataFrame
Columns: [feedback_status, feedback_count, completed_task, field_issue_flag]
Index: []

Empty DataFrame
Columns: [activity_date, representative_station_id, station_name, feedback_count, completed_feedback_count, field_issue_feedback_count]
Index: []

,feedback_timestamp,activity_date,driver_task_id,representative_station_id,station_name,microzone_id,recommended_action,estimated_relocation_label,feedback_status,feedback_comment,feedback_source
0,2026-05-05T09:11:41Z,2017-05-02 00:00:00,2017-05-02_station_30,30,Itämerentori,MZ_0045,deliver_bikes,deliver 18-20,accepted,,dispatcher_app_driver_card

In [68]:
# 6.12.6 Przygotowanie kontraktu zapisu feedbacku w aplikacji

from pathlib import Path

import pandas as pd


step6_126_required_objects = [
    "step6_11_reports_dir",
]

step6_126_missing_objects = [
    object_name
    for object_name in step6_126_required_objects
    if object_name not in globals()
]

assert not step6_126_missing_objects, f"Missing required objects: {step6_126_missing_objects}"

step6_126_reports_dir = Path(step6_11_reports_dir)

step6_126_feedback_fields_path = step6_126_reports_dir / "b6_59_feedback_log_fields.parquet"
step6_126_feedback_statuses_path = step6_126_reports_dir / "b6_59_feedback_status_values.parquet"
step6_126_feedback_log_path = step6_126_reports_dir / "b6_operational_feedback_log.json"

assert step6_126_feedback_fields_path.exists(), "Feedback log fields layer does not exist."
assert step6_126_feedback_statuses_path.exists(), "Feedback status values layer does not exist."
assert step6_126_feedback_log_path.exists(), "Feedback log file does not exist."

step6_126_feedback_fields_df = pd.read_parquet(step6_126_feedback_fields_path)
step6_126_feedback_statuses_df = pd.read_parquet(step6_126_feedback_statuses_path)

step6_126_write_steps = [
    {
        "step_order": 1,
        "write_step": "read_existing_json_log",
        "input_object": "b6_operational_feedback_log.json",
        "output_object": "feedback_entries",
        "required": True,
    },
    {
        "step_order": 2,
        "write_step": "build_feedback_entry",
        "input_object": "selected_driver_task_and_button_status",
        "output_object": "single_feedback_entry",
        "required": True,
    },
    {
        "step_order": 3,
        "write_step": "validate_required_fields",
        "input_object": "b6_59_feedback_log_fields.parquet",
        "output_object": "required_field_check",
        "required": True,
    },
    {
        "step_order": 4,
        "write_step": "validate_feedback_status",
        "input_object": "b6_59_feedback_status_values.parquet",
        "output_object": "status_check",
        "required": True,
    },
    {
        "step_order": 5,
        "write_step": "append_entry_to_log",
        "input_object": "single_feedback_entry",
        "output_object": "feedback_entries",
        "required": True,
    },
    {
        "step_order": 6,
        "write_step": "write_json_log",
        "input_object": "feedback_entries",
        "output_object": "b6_operational_feedback_log.json",
        "required": True,
    },
    {
        "step_order": 7,
        "write_step": "refresh_progress_metrics",
        "input_object": "feedback_entries",
        "output_object": "task_progress_summary",
        "required": True,
    },
]

step6_126_session_state_specs = [
    {
        "state_key": "completed_driver_task_ids",
        "state_role": "completed_task_tracking",
        "default_value": "empty_set",
        "required": True,
    },
    {
        "state_key": "accepted_driver_task_ids",
        "state_role": "accepted_task_tracking",
        "default_value": "empty_set",
        "required": True,
    },
    {
        "state_key": "field_issue_driver_task_ids",
        "state_role": "field_issue_tracking",
        "default_value": "empty_set",
        "required": True,
    },
    {
        "state_key": "driver_feedback_log_cache",
        "state_role": "feedback_log_cache",
        "default_value": "empty_list",
        "required": True,
    },
]

step6_126_progress_specs = [
    {
        "metric_key": "total_visible_tasks",
        "metric_role": "progress_denominator",
        "calculation_type": "count_visible_driver_cards",
        "required": True,
    },
    {
        "metric_key": "completed_visible_tasks",
        "metric_role": "progress_numerator",
        "calculation_type": "count_completed_visible_driver_cards",
        "required": True,
    },
    {
        "metric_key": "progress_share",
        "metric_role": "progress_ratio",
        "calculation_type": "completed_visible_tasks_divided_by_total_visible_tasks",
        "required": True,
    },
]

step6_126_write_steps_df = pd.DataFrame(step6_126_write_steps)
step6_126_session_state_df = pd.DataFrame(step6_126_session_state_specs)
step6_126_progress_df = pd.DataFrame(step6_126_progress_specs)

step6_126_duplicate_write_steps = int(step6_126_write_steps_df["write_step"].duplicated().sum())
step6_126_duplicate_state_keys = int(step6_126_session_state_df["state_key"].duplicated().sum())
step6_126_duplicate_progress_metrics = int(step6_126_progress_df["metric_key"].duplicated().sum())

step6_126_required_feedback_fields = int((step6_126_feedback_fields_df["required"] == True).sum())
step6_126_allowed_feedback_statuses = int(step6_126_feedback_statuses_df["feedback_status"].nunique())

step6_126_write_steps_path = step6_126_reports_dir / "b6_64_feedback_write_steps.parquet"
step6_126_session_state_path = step6_126_reports_dir / "b6_64_feedback_session_state.parquet"
step6_126_progress_path = step6_126_reports_dir / "b6_64_feedback_progress_metrics.parquet"

step6_126_write_steps_df.to_parquet(step6_126_write_steps_path, index=False)
step6_126_session_state_df.to_parquet(step6_126_session_state_path, index=False)
step6_126_progress_df.to_parquet(step6_126_progress_path, index=False)

step6_126_summary_df = pd.DataFrame(
    [
        {
            "check_area": "feedback_write_steps",
            "status": "ok",
            "value": str(step6_126_write_steps_df.shape[0]),
        },
        {
            "check_area": "session_state_keys",
            "status": "ok",
            "value": str(step6_126_session_state_df.shape[0]),
        },
        {
            "check_area": "progress_metrics",
            "status": "ok",
            "value": str(step6_126_progress_df.shape[0]),
        },
        {
            "check_area": "required_feedback_fields",
            "status": "ok",
            "value": str(step6_126_required_feedback_fields),
        },
        {
            "check_area": "allowed_feedback_statuses",
            "status": "ok",
            "value": str(step6_126_allowed_feedback_statuses),
        },
        {
            "check_area": "duplicate_write_steps",
            "status": "ok" if step6_126_duplicate_write_steps == 0 else "review",
            "value": str(step6_126_duplicate_write_steps),
        },
        {
            "check_area": "duplicate_state_keys",
            "status": "ok" if step6_126_duplicate_state_keys == 0 else "review",
            "value": str(step6_126_duplicate_state_keys),
        },
        {
            "check_area": "duplicate_progress_metrics",
            "status": "ok" if step6_126_duplicate_progress_metrics == 0 else "review",
            "value": str(step6_126_duplicate_progress_metrics),
        },
        {
            "check_area": "write_steps_path",
            "status": "ok",
            "value": str(step6_126_write_steps_path),
        },
        {
            "check_area": "session_state_path",
            "status": "ok",
            "value": str(step6_126_session_state_path),
        },
        {
            "check_area": "progress_path",
            "status": "ok",
            "value": str(step6_126_progress_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_126_summary_df[column_name] = step6_126_summary_df[column_name].astype("string")

display(step6_126_summary_df)
display(step6_126_write_steps_df)
display(step6_126_session_state_df)
display(step6_126_progress_df)

,check_area,status,value
0,feedback_write_steps,ok,7
1,session_state_keys,ok,4
2,progress_metrics,ok,3
3,required_feedback_fields,ok,10
4,allowed_feedback_statuses,ok,5
5,duplicate_write_steps,ok,0
6,duplicate_state_keys,ok,0
7,duplicate_progress_metrics,ok,0
8,write_steps_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
9,session_state_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
10,progress_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,step_order,write_step,input_object,output_object,required
0,1,read_existing_json_log,b6_operational_feedback_log.json,feedback_entries,True
1,2,build_feedback_entry,selected_driver_task_and_button_status,single_feedback_entry,True
2,3,validate_required_fields,b6_59_feedback_log_fields.parquet,required_field_check,True
3,4,validate_feedback_status,b6_59_feedback_status_values.parquet,status_check,True
4,5,append_entry_to_log,single_feedback_entry,feedback_entries,True
5,6,write_json_log,feedback_entries,b6_operational_feedback_log.json,True
6,7,refresh_progress_metrics,feedback_entries,task_progress_summary,True

,state_key,state_role,default_value,required
0,completed_driver_task_ids,completed_task_tracking,empty_set,True
1,accepted_driver_task_ids,accepted_task_tracking,empty_set,True
2,field_issue_driver_task_ids,field_issue_tracking,empty_set,True
3,driver_feedback_log_cache,feedback_log_cache,empty_list,True

,metric_key,metric_role,calculation_type,required
0,total_visible_tasks,progress_denominator,count_visible_driver_cards,True
1,completed_visible_tasks,progress_numerator,count_completed_visible_driver_cards,True
2,progress_share,progress_ratio,completed_visible_tasks_divided_by_total_visib...,True

## Podsumowanie działu 6.12 Feedback loop / data flywheel

**Kontekst inżynieryjny:** W dziale `6.12` przygotowano kontrakt pętli zwrotnej dla operacji terenowych. Mechanizm został oparty na zapisie zdarzeń do pliku `b6_operational_feedback_log.json`, bez uruchamiania automatycznego douczania modelu. Zdefiniowano strukturę wpisu feedbacku, listę dozwolonych statusów, walidację wymaganych pól, przykładowy wpis testowy, pusty log operacyjny oraz kontrakt późniejszego zapisu feedbacku w aplikacji. Warstwa została powiązana z zadaniami kierowcy z pliku `b6_57_driver_task_card_layer.parquet` oraz dziennym widokiem kart z pliku `b6_58_daily_driver_task_cards.parquet`.

**Interpretacja wyniku:** Kontrakt feedbacku został zdefiniowany poprawnie. Ustalono zapis w formacie `json_log` do pliku `b6_operational_feedback_log.json`. Struktura logu obejmuje `11` pól, w tym czas zdarzenia, datę zadania, identyfikator zadania, identyfikator stacji, nazwę stacji, mikrostrefę, rekomendowane działanie, szacowaną relokację, status feedbacku, opcjonalny komentarz oraz źródło wpisu. Zdefiniowano `5` statusów: `accepted`, `done`, `field_issue`, `relocation_completed` oraz `rejected_wrong_state`. Kontrole wykazały `0` duplikatów pól, `0` duplikatów statusów, `0` brakujących etykiet statusów oraz `0` braków w wymaganych polach. Plik głównego logu istnieje i ma poprawną strukturę, a jego pusty stan początkowy został uznany za poprawny.

**Znaczenie biznesowe:** Dział `6.12` przygotowuje podstawę do zbierania informacji zwrotnej z realizacji zadań terenowych. Feedback pozwala odróżnić zadania przyjęte, wykonane, odrzucone z powodu błędnego stanu oraz zgłoszone jako problem w terenie. Dzięki temu aplikacja może w przyszłości przechowywać rzeczywiste reakcje operatorów i kierowców, mierzyć postęp realizacji zadań oraz identyfikować sytuacje, w których rekomendacja wymagała korekty lub sprawdzenia. Mechanizm zachowuje rozdzielenie między zbieraniem informacji zwrotnej a trenowaniem modelu, dlatego nie deklaruje automatycznego retrainingu ani samoczynnego uczenia się systemu.

**Wniosek:** Dział `6.12` został domknięty poprawnie. Przygotowano kontrakt pętli zwrotnej, strukturę logu JSON, listę statusów, przykładowy wpis feedbacku, walidację logu, agregacje pod przyszłe wpisy oraz kontrakt zapisu feedbacku w aplikacji. Właściwy log operacyjny pozostaje pusty do momentu pojawienia się realnych kliknięć w aplikacji, natomiast osobny wpis podglądowy potwierdza poprawność formatu. Warstwa feedbacku jest gotowa do późniejszego podłączenia w aplikacji jako mechanizm zapisu statusów zadań, komentarzy terenowych i metryk postępu.

## 6.13 Mikro-interakcje i postęp dnia

In [69]:
# 6.13.1 Kontrakt mikro-interakcji i postępu dnia

from pathlib import Path

import pandas as pd


step6_131_required_objects = [
    "step6_11_reports_dir",
]

step6_131_missing_objects = [
    object_name
    for object_name in step6_131_required_objects
    if object_name not in globals()
]

assert not step6_131_missing_objects, f"Missing required objects: {step6_131_missing_objects}"

step6_131_reports_dir = Path(step6_11_reports_dir)

step6_131_feedback_write_steps_path = step6_131_reports_dir / "b6_64_feedback_write_steps.parquet"
step6_131_feedback_session_state_path = step6_131_reports_dir / "b6_64_feedback_session_state.parquet"
step6_131_feedback_progress_path = step6_131_reports_dir / "b6_64_feedback_progress_metrics.parquet"
step6_131_daily_cards_path = step6_131_reports_dir / "b6_58_daily_driver_task_cards.parquet"

assert step6_131_feedback_write_steps_path.exists(), "Feedback write steps layer does not exist."
assert step6_131_feedback_session_state_path.exists(), "Feedback session state layer does not exist."
assert step6_131_feedback_progress_path.exists(), "Feedback progress metrics layer does not exist."
assert step6_131_daily_cards_path.exists(), "Daily driver task cards layer does not exist."

step6_131_write_steps_df = pd.read_parquet(step6_131_feedback_write_steps_path)
step6_131_session_state_df = pd.read_parquet(step6_131_feedback_session_state_path)
step6_131_progress_df = pd.read_parquet(step6_131_feedback_progress_path)
step6_131_daily_cards_df = pd.read_parquet(step6_131_daily_cards_path)

step6_131_microinteraction_contract = {
    "section": "6.13",
    "section_name": "micro_interactions_and_daily_progress",
    "interaction_role": "fast_operational_feedback",
    "uses_streamlit_toast": True,
    "uses_streamlit_progress": True,
    "uses_streamlit_session_state": True,
    "removes_completed_tasks_from_visible_list": True,
    "uses_gamification": False,
    "primary_feedback_source": "driver_task_cards",
    "progress_denominator": "visible_driver_tasks",
    "progress_numerator": "completed_visible_driver_tasks",
}

step6_131_toast_specs = [
    {
        "toast_key": "feedback_saved",
        "trigger_status": "accepted",
        "toast_message": "Zapisano informację zwrotną.",
        "toast_type": "success",
        "required": True,
    },
    {
        "toast_key": "task_done",
        "trigger_status": "done",
        "toast_message": "Zadanie oznaczono jako wykonane.",
        "toast_type": "success",
        "required": True,
    },
    {
        "toast_key": "field_issue_saved",
        "trigger_status": "field_issue",
        "toast_message": "Zgłoszono błąd w terenie.",
        "toast_type": "warning",
        "required": True,
    },
    {
        "toast_key": "relocation_completed",
        "trigger_status": "relocation_completed",
        "toast_message": "Wykonano relokację.",
        "toast_type": "success",
        "required": True,
    },
    {
        "toast_key": "wrong_state_rejected",
        "trigger_status": "rejected_wrong_state",
        "toast_message": "Odrzucono z powodu błędnego stanu.",
        "toast_type": "warning",
        "required": True,
    },
]

step6_131_visibility_rules = [
    {
        "rule_key": "hide_completed_task",
        "input_status": "done",
        "visible_after_action": False,
        "updates_progress": True,
        "required": True,
    },
    {
        "rule_key": "keep_accepted_task_visible",
        "input_status": "accepted",
        "visible_after_action": True,
        "updates_progress": False,
        "required": True,
    },
    {
        "rule_key": "keep_field_issue_task_visible",
        "input_status": "field_issue",
        "visible_after_action": True,
        "updates_progress": False,
        "required": True,
    },
    {
        "rule_key": "hide_completed_relocation",
        "input_status": "relocation_completed",
        "visible_after_action": False,
        "updates_progress": True,
        "required": True,
    },
    {
        "rule_key": "keep_rejected_wrong_state_visible",
        "input_status": "rejected_wrong_state",
        "visible_after_action": True,
        "updates_progress": False,
        "required": True,
    },
]

step6_131_progress_display_specs = [
    {
        "display_key": "completed_tasks_text",
        "display_role": "progress_text",
        "display_template": "Zrealizowano {completed_tasks}/{total_tasks} zadań",
        "required": True,
    },
    {
        "display_key": "progress_share_bar",
        "display_role": "progress_bar",
        "display_template": "completed_tasks / total_tasks",
        "required": True,
    },
    {
        "display_key": "remaining_tasks_text",
        "display_role": "remaining_work_text",
        "display_template": "Pozostało {remaining_tasks} zadań",
        "required": True,
    },
]

step6_131_toast_df = pd.DataFrame(step6_131_toast_specs)
step6_131_visibility_df = pd.DataFrame(step6_131_visibility_rules)
step6_131_progress_display_df = pd.DataFrame(step6_131_progress_display_specs)

step6_131_duplicate_toasts = int(step6_131_toast_df["toast_key"].duplicated().sum())
step6_131_duplicate_visibility_rules = int(step6_131_visibility_df["rule_key"].duplicated().sum())
step6_131_duplicate_progress_displays = int(step6_131_progress_display_df["display_key"].duplicated().sum())

step6_131_completed_statuses = set(
    step6_131_visibility_df.loc[
        step6_131_visibility_df["updates_progress"] == True,
        "input_status",
    ].tolist()
)

step6_131_daily_total_tasks = int(step6_131_daily_cards_df.shape[0])
step6_131_initial_completed_tasks = 0
step6_131_initial_progress_share = (
    step6_131_initial_completed_tasks / step6_131_daily_total_tasks
    if step6_131_daily_total_tasks > 0
    else 0
)

step6_131_contract_path = step6_131_reports_dir / "b6_65_microinteraction_contract.json"
step6_131_toast_path = step6_131_reports_dir / "b6_65_toast_messages.parquet"
step6_131_visibility_path = step6_131_reports_dir / "b6_65_task_visibility_rules.parquet"
step6_131_progress_display_path = step6_131_reports_dir / "b6_65_progress_display_specs.parquet"

pd.Series(step6_131_microinteraction_contract).to_json(
    step6_131_contract_path,
    force_ascii=False,
    indent=2,
)

step6_131_toast_df.to_parquet(step6_131_toast_path, index=False)
step6_131_visibility_df.to_parquet(step6_131_visibility_path, index=False)
step6_131_progress_display_df.to_parquet(step6_131_progress_display_path, index=False)

step6_131_summary_df = pd.DataFrame(
    [
        {
            "check_area": "uses_streamlit_toast",
            "status": "ok",
            "value": str(step6_131_microinteraction_contract["uses_streamlit_toast"]).lower(),
        },
        {
            "check_area": "uses_streamlit_progress",
            "status": "ok",
            "value": str(step6_131_microinteraction_contract["uses_streamlit_progress"]).lower(),
        },
        {
            "check_area": "uses_streamlit_session_state",
            "status": "ok",
            "value": str(step6_131_microinteraction_contract["uses_streamlit_session_state"]).lower(),
        },
        {
            "check_area": "removes_completed_tasks_from_visible_list",
            "status": "ok",
            "value": str(step6_131_microinteraction_contract["removes_completed_tasks_from_visible_list"]).lower(),
        },
        {
            "check_area": "uses_gamification",
            "status": "ok",
            "value": str(step6_131_microinteraction_contract["uses_gamification"]).lower(),
        },
        {
            "check_area": "toast_messages",
            "status": "ok",
            "value": str(step6_131_toast_df.shape[0]),
        },
        {
            "check_area": "visibility_rules",
            "status": "ok",
            "value": str(step6_131_visibility_df.shape[0]),
        },
        {
            "check_area": "progress_display_specs",
            "status": "ok",
            "value": str(step6_131_progress_display_df.shape[0]),
        },
        {
            "check_area": "duplicate_toasts",
            "status": "ok" if step6_131_duplicate_toasts == 0 else "review",
            "value": str(step6_131_duplicate_toasts),
        },
        {
            "check_area": "duplicate_visibility_rules",
            "status": "ok" if step6_131_duplicate_visibility_rules == 0 else "review",
            "value": str(step6_131_duplicate_visibility_rules),
        },
        {
            "check_area": "duplicate_progress_displays",
            "status": "ok" if step6_131_duplicate_progress_displays == 0 else "review",
            "value": str(step6_131_duplicate_progress_displays),
        },
        {
            "check_area": "daily_total_tasks",
            "status": "ok",
            "value": str(step6_131_daily_total_tasks),
        },
        {
            "check_area": "initial_progress_share",
            "status": "ok",
            "value": str(round(step6_131_initial_progress_share, 4)),
        },
        {
            "check_area": "contract_path",
            "status": "ok",
            "value": str(step6_131_contract_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_131_summary_df[column_name] = step6_131_summary_df[column_name].astype("string")

display(step6_131_summary_df)
display(step6_131_toast_df)
display(step6_131_visibility_df)
display(step6_131_progress_display_df)

,check_area,status,value
0,uses_streamlit_toast,ok,true
1,uses_streamlit_progress,ok,true
2,uses_streamlit_session_state,ok,true
3,removes_completed_tasks_from_visible_list,ok,true
4,uses_gamification,ok,false
5,toast_messages,ok,5
6,visibility_rules,ok,5
7,progress_display_specs,ok,3
8,duplicate_toasts,ok,0
9,duplicate_visibility_rules,ok,0
10,duplicate_progress_displays,ok,0
11,daily_total_tasks,ok,142
12,initial_progress_share,ok,0.0
13,contract_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,toast_key,trigger_status,toast_message,toast_type,required
0,feedback_saved,accepted,Zapisano informację zwrotną.,success,True
1,task_done,done,Zadanie oznaczono jako wykonane.,success,True
2,field_issue_saved,field_issue,Zgłoszono błąd w terenie.,warning,True
3,relocation_completed,relocation_completed,Wykonano relokację.,success,True
4,wrong_state_rejected,rejected_wrong_state,Odrzucono z powodu błędnego stanu.,warning,True

,rule_key,input_status,visible_after_action,updates_progress,required
0,hide_completed_task,done,False,True,True
1,keep_accepted_task_visible,accepted,True,False,True
2,keep_field_issue_task_visible,field_issue,True,False,True
3,hide_completed_relocation,relocation_completed,False,True,True
4,keep_rejected_wrong_state_visible,rejected_wrong_state,True,False,True

,display_key,display_role,display_template,required
0,completed_tasks_text,progress_text,Zrealizowano {completed_tasks}/{total_tasks} z...,True
1,progress_share_bar,progress_bar,completed_tasks / total_tasks,True
2,remaining_tasks_text,remaining_work_text,Pozostało {remaining_tasks} zadań,True

In [70]:
# 6.13.2 Symulacja postępu dnia po zmianie statusu zadania

from pathlib import Path

import pandas as pd


step6_132_required_objects = [
    "step6_11_reports_dir",
]

step6_132_missing_objects = [
    object_name
    for object_name in step6_132_required_objects
    if object_name not in globals()
]

assert not step6_132_missing_objects, f"Missing required objects: {step6_132_missing_objects}"

step6_132_reports_dir = Path(step6_11_reports_dir)

step6_132_daily_cards_path = step6_132_reports_dir / "b6_58_daily_driver_task_cards.parquet"
step6_132_visibility_rules_path = step6_132_reports_dir / "b6_65_task_visibility_rules.parquet"
step6_132_toast_path = step6_132_reports_dir / "b6_65_toast_messages.parquet"

assert step6_132_daily_cards_path.exists(), "Daily driver task cards layer does not exist."
assert step6_132_visibility_rules_path.exists(), "Task visibility rules layer does not exist."
assert step6_132_toast_path.exists(), "Toast messages layer does not exist."

step6_132_daily_cards_df = pd.read_parquet(step6_132_daily_cards_path)
step6_132_visibility_rules_df = pd.read_parquet(step6_132_visibility_rules_path)
step6_132_toast_df = pd.read_parquet(step6_132_toast_path)

step6_132_selected_task = step6_132_daily_cards_df.sort_values(
    by=["driver_card_order", "driver_task_id"],
    ascending=[True, True],
).iloc[0]

step6_132_selected_status = "done"

step6_132_selected_rule = step6_132_visibility_rules_df[
    step6_132_visibility_rules_df["input_status"] == step6_132_selected_status
].iloc[0]

step6_132_selected_toast = step6_132_toast_df[
    step6_132_toast_df["trigger_status"] == step6_132_selected_status
].iloc[0]

step6_132_total_tasks = int(step6_132_daily_cards_df.shape[0])
step6_132_completed_task_ids = {str(step6_132_selected_task["driver_task_id"])}

step6_132_completed_tasks = len(step6_132_completed_task_ids)
step6_132_remaining_tasks = step6_132_total_tasks - step6_132_completed_tasks

step6_132_progress_share = (
    step6_132_completed_tasks / step6_132_total_tasks
    if step6_132_total_tasks > 0
    else 0
)

step6_132_visible_after_action_df = step6_132_daily_cards_df[
    ~step6_132_daily_cards_df["driver_task_id"].astype("string").isin(step6_132_completed_task_ids)
].copy()

step6_132_progress_state = {
    "selected_driver_task_id": str(step6_132_selected_task["driver_task_id"]),
    "selected_station_name": str(step6_132_selected_task["station_name"]),
    "selected_status": step6_132_selected_status,
    "toast_message": str(step6_132_selected_toast["toast_message"]),
    "visible_after_action": bool(step6_132_selected_rule["visible_after_action"]),
    "updates_progress": bool(step6_132_selected_rule["updates_progress"]),
    "total_tasks": step6_132_total_tasks,
    "completed_tasks": step6_132_completed_tasks,
    "remaining_tasks": step6_132_remaining_tasks,
    "progress_share": round(step6_132_progress_share, 4),
    "progress_text": f"Zrealizowano {step6_132_completed_tasks}/{step6_132_total_tasks} zadań",
    "remaining_text": f"Pozostało {step6_132_remaining_tasks} zadań",
}

step6_132_progress_state_df = pd.DataFrame([step6_132_progress_state])

step6_132_duplicate_visible_task_ids = int(
    step6_132_visible_after_action_df["driver_task_id"].duplicated().sum()
)

step6_132_selected_task_still_visible = str(step6_132_selected_task["driver_task_id"]) in set(
    step6_132_visible_after_action_df["driver_task_id"].astype("string")
)

step6_132_progress_state_path = step6_132_reports_dir / "b6_66_progress_state_simulation.parquet"
step6_132_visible_after_action_path = step6_132_reports_dir / "b6_66_visible_tasks_after_done.parquet"

step6_132_progress_state_df.to_parquet(step6_132_progress_state_path, index=False)
step6_132_visible_after_action_df.to_parquet(step6_132_visible_after_action_path, index=False)

step6_132_summary_df = pd.DataFrame(
    [
        {
            "check_area": "selected_status",
            "status": "ok",
            "value": step6_132_selected_status,
        },
        {
            "check_area": "toast_message",
            "status": "ok",
            "value": str(step6_132_selected_toast["toast_message"]),
        },
        {
            "check_area": "total_tasks_before_action",
            "status": "ok",
            "value": str(step6_132_total_tasks),
        },
        {
            "check_area": "completed_tasks_after_action",
            "status": "ok",
            "value": str(step6_132_completed_tasks),
        },
        {
            "check_area": "remaining_tasks_after_action",
            "status": "ok",
            "value": str(step6_132_remaining_tasks),
        },
        {
            "check_area": "progress_share_after_action",
            "status": "ok",
            "value": str(round(step6_132_progress_share, 4)),
        },
        {
            "check_area": "visible_tasks_after_action",
            "status": "ok",
            "value": str(step6_132_visible_after_action_df.shape[0]),
        },
        {
            "check_area": "selected_task_still_visible",
            "status": "ok" if not step6_132_selected_task_still_visible else "review",
            "value": str(step6_132_selected_task_still_visible).lower(),
        },
        {
            "check_area": "duplicate_visible_task_ids",
            "status": "ok" if step6_132_duplicate_visible_task_ids == 0 else "review",
            "value": str(step6_132_duplicate_visible_task_ids),
        },
        {
            "check_area": "progress_state_path",
            "status": "ok",
            "value": str(step6_132_progress_state_path),
        },
        {
            "check_area": "visible_after_action_path",
            "status": "ok",
            "value": str(step6_132_visible_after_action_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_132_summary_df[column_name] = step6_132_summary_df[column_name].astype("string")

display(step6_132_summary_df)
display(step6_132_progress_state_df)
display(step6_132_visible_after_action_df.head(20))

,check_area,status,value
0,selected_status,ok,done
1,toast_message,ok,Zadanie oznaczono jako wykonane.
2,total_tasks_before_action,ok,142
3,completed_tasks_after_action,ok,1
4,remaining_tasks_after_action,ok,141
5,progress_share_after_action,ok,0.007
6,visible_tasks_after_action,ok,141
7,selected_task_still_visible,ok,false
8,duplicate_visible_task_ids,ok,0
9,progress_state_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
10,visible_after_action_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,selected_driver_task_id,selected_station_name,selected_status,toast_message,visible_after_action,updates_progress,total_tasks,completed_tasks,remaining_tasks,progress_share,progress_text,remaining_text
0,2017-05-02_station_30,Itämerentori,done,Zadanie oznaczono jako wykonane.,False,True,142,1,141,0.007,Zrealizowano 1/142 zadań,Pozostało 141 zadań

,activity_date,representative_station_id,daily_plan_rank,microzone_id,station_name,recommended_action,estimated_relocation_label,highest_risk_hour_label,expected_business_impact,recommendation_confidence_final,...,driver_task_status_default,driver_task_completed_default,driver_card_order,driver_card_header,driver_card_location_line,driver_card_action_line,driver_card_time_line,driver_card_impact_line,driver_card_confidence_line,available_action_buttons
1,2017-05-02,26,2,MZ_0064,Kamppi (M),deliver_bikes,deliver 9-11,16:00,124.333328,high,...,not_started,False,2,Zadanie 2,Mikrostrefa: MZ_0064 | Stacja: Kamppi (M),Akcja: deliver_bikes | deliver 9-11,Godzina ryzyka: 16:00,Szacowany potencjał: 124.33,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
2,2017-05-02,21,3,MZ_0067,Töölönlahdenkatu,deliver_bikes,deliver 11-13,19:00,111.562500,high,...,not_started,False,3,Zadanie 3,Mikrostrefa: MZ_0067 | Stacja: Töölönlahdenkatu,Akcja: deliver_bikes | deliver 11-13,Godzina ryzyka: 19:00,Szacowany potencjał: 111.56,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
3,2017-05-02,25,4,MZ_0067,Narinkka,deliver_bikes,deliver 7-9,18:00,103.812500,high,...,not_started,False,4,Zadanie 4,Mikrostrefa: MZ_0067 | Stacja: Narinkka,Akcja: deliver_bikes | deliver 7-9,Godzina ryzyka: 18:00,Szacowany potencjał: 103.81,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
4,2017-05-02,40,5,MZ_0099,Hakaniemi (M),deliver_bikes,deliver 6-8,17:00,91.218750,high,...,not_started,False,5,Zadanie 5,Mikrostrefa: MZ_0099 | Stacja: Hakaniemi (M),Akcja: deliver_bikes | deliver 6-8,Godzina ryzyka: 17:00,Szacowany potencjał: 91.22,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
5,2017-05-02,17,6,MZ_0079,Varsapuistikko,deliver_bikes,deliver 9-11,17:00,77.145828,high,...,not_started,False,6,Zadanie 6,Mikrostrefa: MZ_0079 | Stacja: Varsapuistikko,Akcja: deliver_bikes | deliver 9-11,Godzina ryzyka: 17:00,Szacowany potencjał: 77.15,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
6,2017-05-02,41,7,MZ_0113,Ympyrätalo,deliver_bikes,deliver 8-10,13:00,75.312500,high,...,not_started,False,7,Zadanie 7,Mikrostrefa: MZ_0113 | Stacja: Ympyrätalo,Akcja: deliver_bikes | deliver 8-10,Godzina ryzyka: 13:00,Szacowany potencjał: 75.31,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
7,2017-05-02,9,8,MZ_0054,Erottajan aukio,deliver_bikes,deliver 13-15,16:00,73.021355,high,...,not_started,False,8,Zadanie 8,Mikrostrefa: MZ_0054 | Stacja: Erottajan aukio,Akcja: deliver_bikes | deliver 13-15,Godzina ryzyka: 16:00,Szacowany potencjał: 73.02,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
8,2017-05-02,44,9,MZ_0140,Sörnäinen (M),deliver_bikes,deliver 7-9,19:00,72.021873,high,...,not_started,False,9,Zadanie 9,Mikrostrefa: MZ_0140 | Stacja: Sörnäinen (M),Akcja: deliver_bikes | deliver 7-9,Godzina ryzyka: 19:00,Szacowany potencjał: 72.02,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
9,2017-05-02,22,10,MZ_0067,Rautatientori / länsi,deliver_bikes,deliver 8-10,15:00,71.437500,high,...,not_started,False,10,Zadanie 10,Mikrostrefa: MZ_0067 | Stacja: Rautatientori /...,Akcja: deliver_bikes | deliver 8-10,Godzina ryzyka: 15:00,Szacowany potencjał: 71.44,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
10,2017-05-02,5,11,MZ_0021,Sepänkatu,deliver_bikes,deliver 6-8,11:00,71.158340,high,...,not_started,False,11,Zadanie 11,Mikrostrefa: MZ_0021 | Stacja: Sepänkatu,Akcja: deliver_bikes | deliver 6-8,Godzina ryzyka: 11:00,Szacowany potencjał: 71.16,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
11,2017-05-02,11,12,MZ_0054,Unioninkatu,deliver_bikes,deliver 19-21,16:00,69.125000,high,...,not_started,False,12,Zadanie 12,Mikrostrefa: MZ_0054 | Stacja: Unioninkatu,Akcja: deliver_bikes | deliver 19-21,Godzina ryzyka: 16:00,Szacowany potencjał: 69.12,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
12,2017-05-02,23,13,MZ_0067,Kiasma,deliver_bikes,deliver 8-10,20:00,66.458336,high,...,not_started,False,13,Zadanie 13,Mikrostrefa: MZ_0067 | Stacja: Kiasma,Akcja: deliver_bikes | deliver 8-10,Godzina ryzyka: 20:00,Szacowany potencjał: 66.46,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
13,2017-05-02,29,14,MZ_0037,Baana,deliver_bikes,deliver 6-8,12:00,66.178131,high,...,not_started,False,14,Zadanie 14,Mikrostrefa: MZ_0037 | Stacja: Baana,Akcja: deliver_bikes | deliver 6-8,Godzina ryzyka: 12:00,Szacowany potencjał: 66.18,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
14,2017-05-02,6,15,MZ_0038,Hietalahdentori,deliver_bikes,deliver 3-5,16:00,65.770828,high,...,not_started,False,15,Zadanie 15,Mikrostrefa: MZ_0038 | Stacja: Hietalahdentori,Akcja: deliver_bikes | deliver 3-5,Godzina ryzyka: 16:00,Szacowany potencjał: 65.77,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
15,2017-05-02,19,16,MZ_0067,Rautatientori / itä,deliver_bikes,deliver 6-8,21:00,62.387497,high,...,not_started,False,16,Zadanie 16,Mikrostrefa: MZ_0067 | Stacja: Rautatientori /...,Akcja: deliver_bikes | deliver 6-8,Godzina ryzyka: 21:00,Szacowany potencjał: 62.39,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
16,2017-05-02,14,17,MZ_0054,Senaatintori,deliver_bikes,deliver 9-11,17:00,58.446354,high,...,not_started,False,17,Zadanie 17,Mikrostrefa: MZ_0054 | Stacja: Senaatintori,Akcja: deliver_bikes | deliver 9-11,Godzina ryzyka: 17:00,Szacowany potencjał: 58.45,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
17,2017-05-02,150,18,MZ_0083,Töölönlahden puisto,deliver_bikes,deliver 5-7,21:00,57.928127,high,...,not_started,False,18,Zadanie 18,Mikrostrefa: MZ_0083 | Stacja: Töölönlahden pu...,Akcja: deliver_bikes | deliver 5-7,Godzina ryzyka: 21:00,Szacowany potencjał: 57.93,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
18,2017-05-02,20,19,MZ_0067,Kaisaniemenpuisto,deliver_bikes,deliver 5-7,20:00,57.409901,high,...,not_started,False,19,Zadanie 19,Mikrostrefa: MZ_0067 | Stacja: Kaisaniemenpuisto,Akcja: deliver_bikes | deliver 5-7,Godzina ryzyka: 20:00,Szacowany potencjał: 57.41,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
19,2017-05-02,112,20,MZ_0193,Rautatieläisenkatu,deliver_bikes,deliver 4-6,17:00,55.987499,high,...,not_started,False,20,Zadanie 20,Mikrostrefa: MZ_0193 | Stacja: Rautatieläisenkatu,Akcja: deliver_bikes | deliver 4-6,Godzina ryzyka: 17:00,Szacowany potencjał: 55.99,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"
20,2017-05-02,39,21,MZ_0116,Ooppera,deliver_bikes,deliver 6-8,22:00,54.178127,high,...,not_started,False,21,Zadanie 21,Mikrostrefa: MZ_0116 | Stacja: Ooppera,Akcja: deliver_bikes | deliver 6-8,Godzina ryzyka: 22:00,Szacowany potencjał: 54.18,Pewność rekomendacji: high,"Przyjęte, Wykonane, Błąd w terenie"

In [72]:
# 6.13.3 Symulacja statusów niewykonujących zadania

from pathlib import Path

import pandas as pd


step6_133_required_objects = [
    "step6_11_reports_dir",
]

step6_133_missing_objects = [
    object_name
    for object_name in step6_133_required_objects
    if object_name not in globals()
]

assert not step6_133_missing_objects, f"Missing required objects: {step6_133_missing_objects}"

step6_133_reports_dir = Path(step6_11_reports_dir)

step6_133_daily_cards_path = step6_133_reports_dir / "b6_58_daily_driver_task_cards.parquet"
step6_133_visibility_rules_path = step6_133_reports_dir / "b6_65_task_visibility_rules.parquet"
step6_133_toast_path = step6_133_reports_dir / "b6_65_toast_messages.parquet"

assert step6_133_daily_cards_path.exists(), "Daily driver task cards layer does not exist."
assert step6_133_visibility_rules_path.exists(), "Task visibility rules layer does not exist."
assert step6_133_toast_path.exists(), "Toast messages layer does not exist."

step6_133_daily_cards_df = pd.read_parquet(step6_133_daily_cards_path)
step6_133_visibility_rules_df = pd.read_parquet(step6_133_visibility_rules_path)
step6_133_toast_df = pd.read_parquet(step6_133_toast_path)

step6_133_selected_task = step6_133_daily_cards_df.sort_values(
    by=["driver_card_order", "driver_task_id"],
    ascending=[True, True],
).iloc[0]

step6_133_statuses_to_test = [
    "accepted",
    "field_issue",
    "rejected_wrong_state",
]

step6_133_simulation_rows = []

for step6_133_status in step6_133_statuses_to_test:
    step6_133_rule = step6_133_visibility_rules_df[
        step6_133_visibility_rules_df["input_status"] == step6_133_status
    ].iloc[0]

    step6_133_toast = step6_133_toast_df[
        step6_133_toast_df["trigger_status"] == step6_133_status
    ].iloc[0]

    step6_133_visible_after_action = bool(step6_133_rule["visible_after_action"])
    step6_133_updates_progress = bool(step6_133_rule["updates_progress"])

    step6_133_total_tasks = int(step6_133_daily_cards_df.shape[0])
    step6_133_completed_tasks = 1 if step6_133_updates_progress else 0
    step6_133_remaining_tasks = step6_133_total_tasks - step6_133_completed_tasks

    step6_133_progress_share = (
        step6_133_completed_tasks / step6_133_total_tasks
        if step6_133_total_tasks > 0
        else 0
    )

    step6_133_simulation_rows.append(
        {
            "tested_status": step6_133_status,
            "selected_driver_task_id": str(step6_133_selected_task["driver_task_id"]),
            "selected_station_name": str(step6_133_selected_task["station_name"]),
            "toast_key": str(step6_133_toast["toast_key"]),
            "toast_type": str(step6_133_toast["toast_type"]),
            "visible_after_action": step6_133_visible_after_action,
            "updates_progress": step6_133_updates_progress,
            "total_tasks": step6_133_total_tasks,
            "completed_tasks": step6_133_completed_tasks,
            "remaining_tasks": step6_133_remaining_tasks,
            "progress_share": round(step6_133_progress_share, 4),
            "progress_text_template": "completed_tasks / total_tasks",
            "remaining_text_template": "total_tasks - completed_tasks",
        }
    )

step6_133_simulation_df = pd.DataFrame(step6_133_simulation_rows)

step6_133_invalid_progress_updates = int(
    step6_133_simulation_df["updates_progress"].sum()
)

step6_133_hidden_non_completed_tasks = int(
    (~step6_133_simulation_df["visible_after_action"]).sum()
)

step6_133_missing_toast_keys = int(
    step6_133_simulation_df["toast_key"].isna().sum()
)

step6_133_simulation_path = step6_133_reports_dir / "b6_67_non_completed_status_simulation.parquet"

step6_133_simulation_df.to_parquet(step6_133_simulation_path, index=False)

step6_133_summary_df = pd.DataFrame(
    [
        {
            "check_area": "tested_statuses",
            "status": "ok",
            "value": str(step6_133_simulation_df.shape[0]),
        },
        {
            "check_area": "invalid_progress_updates",
            "status": "ok" if step6_133_invalid_progress_updates == 0 else "review",
            "value": str(step6_133_invalid_progress_updates),
        },
        {
            "check_area": "hidden_non_completed_tasks",
            "status": "ok" if step6_133_hidden_non_completed_tasks == 0 else "review",
            "value": str(step6_133_hidden_non_completed_tasks),
        },
        {
            "check_area": "missing_toast_keys",
            "status": "ok" if step6_133_missing_toast_keys == 0 else "review",
            "value": str(step6_133_missing_toast_keys),
        },
        {
            "check_area": "total_tasks_reference",
            "status": "ok",
            "value": str(step6_133_daily_cards_df.shape[0]),
        },
        {
            "check_area": "simulation_path",
            "status": "ok",
            "value": str(step6_133_simulation_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_133_summary_df[column_name] = step6_133_summary_df[column_name].astype("string")

display(step6_133_summary_df)
display(step6_133_simulation_df)

,check_area,status,value
0,tested_statuses,ok,3
1,invalid_progress_updates,ok,0
2,hidden_non_completed_tasks,ok,0
3,missing_toast_keys,ok,0
4,total_tasks_reference,ok,142
5,simulation_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,tested_status,selected_driver_task_id,selected_station_name,toast_key,toast_type,visible_after_action,updates_progress,total_tasks,completed_tasks,remaining_tasks,progress_share,progress_text_template,remaining_text_template
0,accepted,2017-05-02_station_30,Itämerentori,feedback_saved,success,True,False,142,0,142,0.0,completed_tasks / total_tasks,total_tasks - completed_tasks
1,field_issue,2017-05-02_station_30,Itämerentori,field_issue_saved,warning,True,False,142,0,142,0.0,completed_tasks / total_tasks,total_tasks - completed_tasks
2,rejected_wrong_state,2017-05-02_station_30,Itämerentori,wrong_state_rejected,warning,True,False,142,0,142,0.0,completed_tasks / total_tasks,total_tasks - completed_tasks

In [74]:
# 6.13.4 Walidacja końcowa mikro-interakcji i postępu dnia

from pathlib import Path

import pandas as pd


step6_134_required_objects = [
    "step6_11_reports_dir",
]

step6_134_missing_objects = [
    object_name
    for object_name in step6_134_required_objects
    if object_name not in globals()
]

assert not step6_134_missing_objects, f"Missing required objects: {step6_134_missing_objects}"

step6_134_reports_dir = Path(step6_11_reports_dir)

step6_134_required_paths = {
    "microinteraction_contract": step6_134_reports_dir / "b6_65_microinteraction_contract.json",
    "toast_messages": step6_134_reports_dir / "b6_65_toast_messages.parquet",
    "task_visibility_rules": step6_134_reports_dir / "b6_65_task_visibility_rules.parquet",
    "progress_display_specs": step6_134_reports_dir / "b6_65_progress_display_specs.parquet",
    "progress_state_simulation": step6_134_reports_dir / "b6_66_progress_state_simulation.parquet",
    "visible_tasks_after_done": step6_134_reports_dir / "b6_66_visible_tasks_after_done.parquet",
    "non_completed_status_simulation": step6_134_reports_dir / "b6_67_non_completed_status_simulation.parquet",
}

step6_134_inventory_rows = []

for step6_134_artifact_role, step6_134_path in step6_134_required_paths.items():
    step6_134_inventory_rows.append(
        {
            "artifact_role": step6_134_artifact_role,
            "file_name": step6_134_path.name,
            "resolved_path": str(step6_134_path),
            "file_exists": step6_134_path.exists(),
            "file_size_bytes": step6_134_path.stat().st_size if step6_134_path.exists() else 0,
        }
    )

step6_134_inventory_df = pd.DataFrame(step6_134_inventory_rows)

step6_134_missing_artifacts = int((~step6_134_inventory_df["file_exists"]).sum())

assert step6_134_missing_artifacts == 0, "Required microinteraction artifacts are missing."

step6_134_toast_df = pd.read_parquet(step6_134_required_paths["toast_messages"])
step6_134_visibility_df = pd.read_parquet(step6_134_required_paths["task_visibility_rules"])
step6_134_progress_display_df = pd.read_parquet(step6_134_required_paths["progress_display_specs"])
step6_134_done_simulation_df = pd.read_parquet(step6_134_required_paths["progress_state_simulation"])
step6_134_visible_after_done_df = pd.read_parquet(step6_134_required_paths["visible_tasks_after_done"])
step6_134_non_completed_simulation_df = pd.read_parquet(step6_134_required_paths["non_completed_status_simulation"])

step6_134_done_row = step6_134_done_simulation_df.iloc[0]

step6_134_done_updates_progress = bool(step6_134_done_row["updates_progress"])
step6_134_done_visible_after_action = bool(step6_134_done_row["visible_after_action"])
step6_134_done_completed_tasks = int(step6_134_done_row["completed_tasks"])
step6_134_done_remaining_tasks = int(step6_134_done_row["remaining_tasks"])
step6_134_done_total_tasks = int(step6_134_done_row["total_tasks"])
step6_134_visible_after_done_rows = int(step6_134_visible_after_done_df.shape[0])

step6_134_done_logic_valid = (
    step6_134_done_updates_progress
    and not step6_134_done_visible_after_action
    and step6_134_done_completed_tasks == 1
    and step6_134_done_remaining_tasks == step6_134_done_total_tasks - 1
    and step6_134_visible_after_done_rows == step6_134_done_total_tasks - 1
)

step6_134_non_completed_logic_valid = (
    (step6_134_non_completed_simulation_df["visible_after_action"] == True).all()
    and (step6_134_non_completed_simulation_df["updates_progress"] == False).all()
    and (step6_134_non_completed_simulation_df["completed_tasks"] == 0).all()
    and (step6_134_non_completed_simulation_df["progress_share"] == 0).all()
)

step6_134_required_statuses = {
    "accepted",
    "done",
    "field_issue",
    "relocation_completed",
    "rejected_wrong_state",
}

step6_134_toast_statuses = set(step6_134_toast_df["trigger_status"].tolist())
step6_134_visibility_statuses = set(step6_134_visibility_df["input_status"].tolist())

step6_134_missing_toast_statuses = sorted(
    step6_134_required_statuses - step6_134_toast_statuses
)

step6_134_missing_visibility_statuses = sorted(
    step6_134_required_statuses - step6_134_visibility_statuses
)

step6_134_duplicate_toasts = int(step6_134_toast_df["toast_key"].duplicated().sum())
step6_134_duplicate_visibility_rules = int(step6_134_visibility_df["rule_key"].duplicated().sum())
step6_134_duplicate_progress_specs = int(step6_134_progress_display_df["display_key"].duplicated().sum())

step6_134_final_validation_df = pd.DataFrame(
    [
        {
            "check_area": "required_artifacts",
            "status": "ok",
            "value": str(len(step6_134_required_paths)),
        },
        {
            "check_area": "missing_required_artifacts",
            "status": "ok" if step6_134_missing_artifacts == 0 else "review",
            "value": str(step6_134_missing_artifacts),
        },
        {
            "check_area": "toast_status_coverage",
            "status": "ok" if len(step6_134_missing_toast_statuses) == 0 else "review",
            "value": str(len(step6_134_missing_toast_statuses)),
        },
        {
            "check_area": "visibility_status_coverage",
            "status": "ok" if len(step6_134_missing_visibility_statuses) == 0 else "review",
            "value": str(len(step6_134_missing_visibility_statuses)),
        },
        {
            "check_area": "done_logic_valid",
            "status": "ok" if step6_134_done_logic_valid else "review",
            "value": str(step6_134_done_logic_valid).lower(),
        },
        {
            "check_area": "non_completed_logic_valid",
            "status": "ok" if step6_134_non_completed_logic_valid else "review",
            "value": str(step6_134_non_completed_logic_valid).lower(),
        },
        {
            "check_area": "duplicate_toasts",
            "status": "ok" if step6_134_duplicate_toasts == 0 else "review",
            "value": str(step6_134_duplicate_toasts),
        },
        {
            "check_area": "duplicate_visibility_rules",
            "status": "ok" if step6_134_duplicate_visibility_rules == 0 else "review",
            "value": str(step6_134_duplicate_visibility_rules),
        },
        {
            "check_area": "duplicate_progress_specs",
            "status": "ok" if step6_134_duplicate_progress_specs == 0 else "review",
            "value": str(step6_134_duplicate_progress_specs),
        },
        {
            "check_area": "daily_total_tasks_reference",
            "status": "ok",
            "value": str(step6_134_done_total_tasks),
        },
        {
            "check_area": "visible_tasks_after_done",
            "status": "ok",
            "value": str(step6_134_visible_after_done_rows),
        },
    ]
)

step6_134_missing_status_df = pd.DataFrame(
    [
        {
            "status_type": "toast",
            "missing_status": missing_status,
        }
        for missing_status in step6_134_missing_toast_statuses
    ]
    + [
        {
            "status_type": "visibility",
            "missing_status": missing_status,
        }
        for missing_status in step6_134_missing_visibility_statuses
    ]
)

step6_134_final_validation_path = step6_134_reports_dir / "b6_68_microinteraction_final_validation.parquet"
step6_134_inventory_path = step6_134_reports_dir / "b6_68_microinteraction_artifact_inventory.parquet"
step6_134_missing_status_path = step6_134_reports_dir / "b6_68_microinteraction_missing_statuses.parquet"

step6_134_final_validation_df.to_parquet(step6_134_final_validation_path, index=False)
step6_134_inventory_df.to_parquet(step6_134_inventory_path, index=False)
step6_134_missing_status_df.to_parquet(step6_134_missing_status_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_134_final_validation_df[column_name] = step6_134_final_validation_df[column_name].astype("string")

display(step6_134_final_validation_df)
display(step6_134_inventory_df)
display(step6_134_missing_status_df)

                     check_area status value
0            required_artifacts     ok     7
1    missing_required_artifacts     ok     0
2         toast_status_coverage     ok     0
3    visibility_status_coverage     ok     0
4              done_logic_valid     ok  true
5     non_completed_logic_valid     ok  true
6              duplicate_toasts     ok     0
7    duplicate_visibility_rules     ok     0
8      duplicate_progress_specs     ok     0
9   daily_total_tasks_reference     ok   142
10     visible_tasks_after_done     ok   141

,artifact_role,file_name,resolved_path,file_exists,file_size_bytes
0,microinteraction_contract,b6_65_microinteraction_contract.json,/root/projects/6_samodzielny_projekt_koncowy_w...,True,470
1,toast_messages,b6_65_toast_messages.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3779
2,task_visibility_rules,b6_65_task_visibility_rules.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3546
3,progress_display_specs,b6_65_progress_display_specs.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3161
4,progress_state_simulation,b6_66_progress_state_simulation.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...,True,8038
5,visible_tasks_after_done,b6_66_visible_tasks_after_done.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...,True,30795
6,non_completed_status_simulation,b6_67_non_completed_status_simulation.parquet,/root/projects/6_samodzielny_projekt_koncowy_w...,True,8178

Empty DataFrame
Columns: []
Index: []

## Podsumowanie działu 6.13 Mikro-interakcje i postęp dnia

**Kontekst inżynieryjny:** W dziale `6.13` przygotowano kontrakt mikro-interakcji oraz mechanizm kontroli postępu dnia dla widoku operacyjnego. Warstwa została oparta na wcześniejszych kontraktach feedbacku i kart kierowcy. Zdefiniowano obsługę krótkich komunikatów zwrotnych, reguły widoczności zadań po zmianie statusu, specyfikację paska postępu oraz symulacje sprawdzające zachowanie aplikacji po wykonaniu zadania i po statusach niewykonujących zadania. Mechanizm nie obejmuje elementów grywalizacji i pozostaje skoncentrowany na szybkim, operacyjnym potwierdzeniu wykonania akcji.

**Interpretacja wyniku:** Kontrakt mikro-interakcji został zdefiniowany poprawnie. Ustalono wykorzystanie `toast`, `progress` oraz `session_state` jako elementów późniejszej aplikacji. Zdefiniowano `5` komunikatów zwrotnych dla statusów `accepted`, `done`, `field_issue`, `relocation_completed` oraz `rejected_wrong_state`. Przygotowano `5` reguł widoczności zadań oraz `3` elementy prezentacji postępu. Walidacja końcowa potwierdziła obecność `7` wymaganych artefaktów, `0` brakujących artefaktów, `0` braków pokrycia statusów dla komunikatów, `0` braków pokrycia statusów dla reguł widoczności oraz `0` duplikatów w komunikatach, regułach i specyfikacjach postępu.

**Znaczenie biznesowe:** Dział `6.13` przygotowuje logikę, dzięki której użytkownik aplikacji otrzymuje szybkie potwierdzenie po wykonaniu akcji, a lista zadań i pasek postępu reagują na realny stan pracy. Status `done` zwiększa liczbę wykonanych zadań, aktualizuje postęp oraz usuwa wykonane zadanie z listy widocznej. Statusy `accepted`, `field_issue` oraz `rejected_wrong_state` nie zwiększają postępu i nie ukrywają zadania, ponieważ nie oznaczają faktycznego wykonania pracy. Dzięki temu postęp dnia nie jest sztucznie zawyżany i pozostaje zgodny z logiką operacyjną.

**Wniosek:** Dział `6.13` został domknięty poprawnie. Przygotowano kontrakt mikro-interakcji, komunikaty zwrotne, reguły widoczności zadań, specyfikację paska postępu oraz walidacje symulacyjne. Dla dziennego widoku obejmującego `142` zadania potwierdzono, że po oznaczeniu jednego zadania jako `done` liczba widocznych zadań spada do `141`, a postęp wzrasta zgodnie z wykonaną pracą. Statusy niewykonujące zadania nie zmieniają postępu i nie usuwają zadań z listy. Warstwa jest gotowa do późniejszego wykorzystania w aplikacji jako mechanizm krótkiego feedbacku, aktualizacji postępu i kontroli widoczności zadań.

## 6.14 Odbiór końcowy BLOKU 6

In [75]:
# 6.14.1 Inwentaryzacja artefaktów odbioru końcowego

from pathlib import Path

import pandas as pd


step6_141_required_objects = [
    "step6_11_reports_dir",
]

step6_141_missing_objects = [
    object_name
    for object_name in step6_141_required_objects
    if object_name not in globals()
]

assert not step6_141_missing_objects, f"Missing required objects: {step6_141_missing_objects}"

step6_141_reports_dir = Path(step6_11_reports_dir)

step6_141_required_artifacts = [
    {
        "artifact_group": "decision_language",
        "artifact_role": "dispatcher_app_labels",
        "file_name": "b6_52_dispatcher_app_user_labels.parquet",
        "required": True,
    },
    {
        "artifact_group": "operational_plan",
        "artifact_role": "main_operational_layer",
        "file_name": "b6_45_map_station_layer.parquet",
        "required": True,
    },
    {
        "artifact_group": "microzones",
        "artifact_role": "microzone_summary",
        "file_name": "b6_34_microzone_summary.parquet",
        "required": True,
    },
    {
        "artifact_group": "microzones",
        "artifact_role": "local_pairs",
        "file_name": "b6_35_microzone_local_pairs.parquet",
        "required": True,
    },
    {
        "artifact_group": "map",
        "artifact_role": "station_map_layer",
        "file_name": "b6_45_map_station_layer.parquet",
        "required": True,
    },
    {
        "artifact_group": "map",
        "artifact_role": "relocation_line_layer",
        "file_name": "b6_48_relocation_line_layer.parquet",
        "required": True,
    },
    {
        "artifact_group": "map",
        "artifact_role": "daily_action_map_html",
        "file_name": "b6_47_action_map_top50.html",
        "required": True,
    },
    {
        "artifact_group": "driver_cards",
        "artifact_role": "driver_task_layer",
        "file_name": "b6_57_driver_task_card_layer.parquet",
        "required": True,
    },
    {
        "artifact_group": "driver_cards",
        "artifact_role": "daily_driver_cards",
        "file_name": "b6_58_daily_driver_task_cards.parquet",
        "required": True,
    },
    {
        "artifact_group": "feedback",
        "artifact_role": "feedback_log",
        "file_name": "b6_operational_feedback_log.json",
        "required": True,
    },
    {
        "artifact_group": "feedback",
        "artifact_role": "feedback_contract",
        "file_name": "b6_59_feedback_loop_contract.json",
        "required": True,
    },
    {
        "artifact_group": "progress",
        "artifact_role": "microinteraction_contract",
        "file_name": "b6_65_microinteraction_contract.json",
        "required": True,
    },
    {
        "artifact_group": "progress",
        "artifact_role": "progress_state_simulation",
        "file_name": "b6_66_progress_state_simulation.parquet",
        "required": True,
    },
    {
        "artifact_group": "application_contract",
        "artifact_role": "dispatcher_app_contract",
        "file_name": "b6_49_dispatcher_app_contract.json",
        "required": True,
    },
    {
        "artifact_group": "application_contract",
        "artifact_role": "dispatcher_app_tab_contract",
        "file_name": "b6_49_dispatcher_app_tab_contract.parquet",
        "required": True,
    },
    {
        "artifact_group": "application_contract",
        "artifact_role": "input_artifact_inventory",
        "file_name": "b6_50_dispatcher_app_input_artifacts.parquet",
        "required": True,
    },
]

step6_141_inventory_rows = []

for step6_141_artifact in step6_141_required_artifacts:
    step6_141_path = step6_141_reports_dir / step6_141_artifact["file_name"]

    step6_141_inventory_rows.append(
        {
            "artifact_group": step6_141_artifact["artifact_group"],
            "artifact_role": step6_141_artifact["artifact_role"],
            "file_name": step6_141_artifact["file_name"],
            "required": step6_141_artifact["required"],
            "resolved_path": str(step6_141_path),
            "file_exists": step6_141_path.exists(),
            "file_size_bytes": step6_141_path.stat().st_size if step6_141_path.exists() else 0,
            "status": "ok" if step6_141_path.exists() else "review",
        }
    )

step6_141_inventory_df = pd.DataFrame(step6_141_inventory_rows)

step6_141_missing_required_artifacts = int(
    (
        (step6_141_inventory_df["required"] == True)
        & (step6_141_inventory_df["file_exists"] == False)
    ).sum()
)

step6_141_empty_existing_artifacts = int(
    (
        (step6_141_inventory_df["file_exists"] == True)
        & (step6_141_inventory_df["file_size_bytes"] == 0)
    ).sum()
)

step6_141_group_summary_df = (
    step6_141_inventory_df
    .groupby("artifact_group", dropna=False)
    .agg(
        artifact_count=("file_name", "size"),
        existing_artifacts=("file_exists", "sum"),
        total_size_bytes=("file_size_bytes", "sum"),
    )
    .reset_index()
    .sort_values("artifact_group")
    .reset_index(drop=True)
)

step6_141_inventory_path = step6_141_reports_dir / "b6_69_final_acceptance_artifact_inventory.parquet"
step6_141_group_summary_path = step6_141_reports_dir / "b6_69_final_acceptance_artifact_group_summary.parquet"

step6_141_inventory_df.to_parquet(step6_141_inventory_path, index=False)
step6_141_group_summary_df.to_parquet(step6_141_group_summary_path, index=False)

step6_141_summary_df = pd.DataFrame(
    [
        {
            "check_area": "required_artifacts",
            "status": "ok",
            "value": str(len(step6_141_required_artifacts)),
        },
        {
            "check_area": "missing_required_artifacts",
            "status": "ok" if step6_141_missing_required_artifacts == 0 else "review",
            "value": str(step6_141_missing_required_artifacts),
        },
        {
            "check_area": "empty_existing_artifacts",
            "status": "ok" if step6_141_empty_existing_artifacts == 0 else "review",
            "value": str(step6_141_empty_existing_artifacts),
        },
        {
            "check_area": "artifact_groups",
            "status": "ok",
            "value": str(step6_141_group_summary_df.shape[0]),
        },
        {
            "check_area": "inventory_path",
            "status": "ok",
            "value": str(step6_141_inventory_path),
        },
        {
            "check_area": "group_summary_path",
            "status": "ok",
            "value": str(step6_141_group_summary_path),
        },
    ]
)

for column_name in ["check_area", "status", "value"]:
    step6_141_summary_df[column_name] = step6_141_summary_df[column_name].astype("string")

display(step6_141_summary_df)
display(step6_141_inventory_df)
display(step6_141_group_summary_df)

,check_area,status,value
0,required_artifacts,ok,16
1,missing_required_artifacts,ok,0
2,empty_existing_artifacts,ok,0
3,artifact_groups,ok,8
4,inventory_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...
5,group_summary_path,ok,/root/projects/6_samodzielny_projekt_koncowy_w...

,artifact_group,artifact_role,file_name,required,resolved_path,file_exists,file_size_bytes,status
0,decision_language,dispatcher_app_labels,b6_52_dispatcher_app_user_labels.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,4676,ok
1,operational_plan,main_operational_layer,b6_45_map_station_layer.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,11555208,ok
2,microzones,microzone_summary,b6_34_microzone_summary.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3558017,ok
3,microzones,local_pairs,b6_35_microzone_local_pairs.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,6584,ok
4,map,station_map_layer,b6_45_map_station_layer.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,11555208,ok
5,map,relocation_line_layer,b6_48_relocation_line_layer.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,10109,ok
6,map,daily_action_map_html,b6_47_action_map_top50.html,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,77149,ok
7,driver_cards,driver_task_layer,b6_57_driver_task_card_layer.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,4901200,ok
8,driver_cards,daily_driver_cards,b6_58_daily_driver_task_cards.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,30897,ok
9,feedback,feedback_log,b6_operational_feedback_log.json,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,61,ok
10,feedback,feedback_contract,b6_59_feedback_loop_contract.json,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,654,ok
11,progress,microinteraction_contract,b6_65_microinteraction_contract.json,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,470,ok
12,progress,progress_state_simulation,b6_66_progress_state_simulation.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,8038,ok
13,application_contract,dispatcher_app_contract,b6_49_dispatcher_app_contract.json,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,887,ok
14,application_contract,dispatcher_app_tab_contract,b6_49_dispatcher_app_tab_contract.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3849,ok
15,application_contract,input_artifact_inventory,b6_50_dispatcher_app_input_artifacts.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,8462,ok

         artifact_group  artifact_count  existing_artifacts  total_size_bytes
0  application_contract               3                   3             13198
1     decision_language               1                   1              4676
2          driver_cards               2                   2           4932097
3              feedback               2                   2               715
4                   map               3                   3          11642466
5            microzones               2                   2           3564601
6      operational_plan               1                   1          11555208
7              progress               2                   2              8508

In [76]:
# 6.14.2 Walidacja języka decyzji i czytelności rekomendacji

from pathlib import Path

import pandas as pd


step6_142_required_objects = [
    "step6_11_reports_dir",
]

step6_142_missing_objects = [
    object_name
    for object_name in step6_142_required_objects
    if object_name not in globals()
]

assert not step6_142_missing_objects, f"Missing required objects: {step6_142_missing_objects}"

step6_142_reports_dir = Path(step6_11_reports_dir)

step6_142_labels_path = step6_142_reports_dir / "b6_52_dispatcher_app_user_labels.parquet"
step6_142_operational_layer_path = step6_142_reports_dir / "b6_45_map_station_layer.parquet"

assert step6_142_labels_path.exists(), "Dispatcher app user labels layer does not exist."
assert step6_142_operational_layer_path.exists(), "Main operational layer does not exist."

step6_142_labels_df = pd.read_parquet(step6_142_labels_path)
step6_142_operational_df = pd.read_parquet(step6_142_operational_layer_path)

step6_142_required_decision_fields = [
    "priority_level",
    "problem_type",
    "recommended_action",
    "estimated_relocation_label",
    "highest_risk_hour_label",
    "expected_business_impact",
    "recommendation_confidence_final",
]

step6_142_missing_decision_fields = [
    field_name
    for field_name in step6_142_required_decision_fields
    if field_name not in step6_142_operational_df.columns
]

step6_142_main_label_fields = set(
    step6_142_labels_df.loc[
        step6_142_labels_df["technical_visibility"] == "main",
        "source_field",
    ].astype("string")
)

step6_142_missing_main_labels = [
    field_name
    for field_name in step6_142_required_decision_fields
    if field_name not in step6_142_main_label_fields
]

step6_142_empty_display_labels = int(
    step6_142_labels_df["display_label"].isna().sum()
    + (step6_142_labels_df["display_label"].astype("string").str.strip() == "").sum()
)

step6_142_duplicate_source_fields = int(
    step6_142_labels_df["source_field"].duplicated().sum()
)

step6_142_visible_label_rows = int(
    (step6_142_labels_df["technical_visibility"] == "main").sum()
)

step6_142_technical_label_rows = int(
    (step6_142_labels_df["technical_visibility"] == "technical").sum()
)

step6_142_decision_sample_df = (
    step6_142_operational_df[
        [
            "activity_date",
            "daily_plan_rank",
            "station_name",
            "priority_level",
            "problem_type",
            "recommended_action",
            "estimated_relocation_label",
            "highest_risk_hour_label",
            "expected_business_impact",
            "recommendation_confidence_final",
        ]
    ]
    .sort_values(
        by=["activity_date", "daily_plan_rank", "station_name"],
        ascending=[True, True, True],
    )
    .head(20)
    .reset_index(drop=True)
)

step6_142_recommendation_value_summary_df = (
    step6_142_operational_df
    .groupby(
        [
            "problem_type",
            "recommended_action",
            "estimated_relocation_label",
            "recommendation_confidence_final",
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="row_count")
    .sort_values(
        by=["row_count", "problem_type", "recommended_action"],
        ascending=[False, True, True],
    )
    .reset_index(drop=True)
)

step6_142_label_check_df = pd.DataFrame(
    [
        {
            "check_area": "required_decision_fields",
            "status": "ok",
            "value": str(len(step6_142_required_decision_fields)),
        },
        {
            "check_area": "missing_decision_fields",
            "status": "ok" if len(step6_142_missing_decision_fields) == 0 else "review",
            "value": str(len(step6_142_missing_decision_fields)),
        },
        {
            "check_area": "missing_main_labels",
            "status": "ok" if len(step6_142_missing_main_labels) == 0 else "review",
            "value": str(len(step6_142_missing_main_labels)),
        },
        {
            "check_area": "empty_display_labels",
            "status": "ok" if step6_142_empty_display_labels == 0 else "review",
            "value": str(step6_142_empty_display_labels),
        },
        {
            "check_area": "duplicate_source_fields",
            "status": "ok" if step6_142_duplicate_source_fields == 0 else "review",
            "value": str(step6_142_duplicate_source_fields),
        },
        {
            "check_area": "main_visible_labels",
            "status": "ok",
            "value": str(step6_142_visible_label_rows),
        },
        {
            "check_area": "technical_labels",
            "status": "ok",
            "value": str(step6_142_technical_label_rows),
        },
        {
            "check_area": "decision_sample_rows",
            "status": "ok",
            "value": str(step6_142_decision_sample_df.shape[0]),
        },
        {
            "check_area": "recommendation_value_groups",
            "status": "ok",
            "value": str(step6_142_recommendation_value_summary_df.shape[0]),
        },
    ]
)

step6_142_label_check_path = step6_142_reports_dir / "b6_70_decision_language_validation.parquet"
step6_142_decision_sample_path = step6_142_reports_dir / "b6_70_decision_sample.parquet"
step6_142_recommendation_summary_path = step6_142_reports_dir / "b6_70_recommendation_value_summary.parquet"

step6_142_label_check_df.to_parquet(step6_142_label_check_path, index=False)
step6_142_decision_sample_df.to_parquet(step6_142_decision_sample_path, index=False)
step6_142_recommendation_value_summary_df.to_parquet(step6_142_recommendation_summary_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_142_label_check_df[column_name] = step6_142_label_check_df[column_name].astype("string")

display(step6_142_label_check_df)
display(step6_142_decision_sample_df)
display(step6_142_recommendation_value_summary_df.head(20))

                    check_area status value
0     required_decision_fields     ok     7
1      missing_decision_fields     ok     0
2          missing_main_labels     ok     0
3         empty_display_labels     ok     0
4      duplicate_source_fields     ok     0
5          main_visible_labels     ok    25
6             technical_labels     ok    24
7         decision_sample_rows     ok    20
8  recommendation_value_groups     ok    28

,activity_date,daily_plan_rank,station_name,priority_level,problem_type,recommended_action,estimated_relocation_label,highest_risk_hour_label,expected_business_impact,recommendation_confidence_final
0,2017-05-02,1,Itämerentori,very_high,bike_shortage_risk,deliver_bikes,deliver 18-20,17:00,128.742188,high
1,2017-05-02,2,Kamppi (M),very_high,bike_shortage_risk,deliver_bikes,deliver 9-11,16:00,124.333328,high
2,2017-05-02,3,Töölönlahdenkatu,very_high,bike_shortage_risk,deliver_bikes,deliver 11-13,19:00,111.562500,high
3,2017-05-02,4,Narinkka,very_high,bike_shortage_risk,deliver_bikes,deliver 7-9,18:00,103.812500,high
4,2017-05-02,5,Hakaniemi (M),high,bike_shortage_risk,deliver_bikes,deliver 6-8,17:00,91.218750,high
5,2017-05-02,6,Varsapuistikko,high,bike_shortage_risk,deliver_bikes,deliver 9-11,17:00,77.145828,high
6,2017-05-02,7,Ympyrätalo,high,bike_shortage_risk,deliver_bikes,deliver 8-10,13:00,75.312500,high
7,2017-05-02,8,Erottajan aukio,high,bike_shortage_risk,deliver_bikes,deliver 13-15,16:00,73.021355,high
8,2017-05-02,9,Sörnäinen (M),high,bike_shortage_risk,deliver_bikes,deliver 7-9,19:00,72.021873,high
9,2017-05-02,10,Rautatientori / länsi,high,bike_shortage_risk,deliver_bikes,deliver 8-10,15:00,71.437500,high
10,2017-05-02,11,Sepänkatu,high,bike_shortage_risk,deliver_bikes,deliver 6-8,11:00,71.158340,high
11,2017-05-02,12,Unioninkatu,high,bike_shortage_risk,deliver_bikes,deliver 19-21,16:00,69.125000,high
12,2017-05-02,13,Kiasma,high,bike_shortage_risk,deliver_bikes,deliver 8-10,20:00,66.458336,high
13,2017-05-02,14,Baana,high,bike_shortage_risk,deliver_bikes,deliver 6-8,12:00,66.178131,high
14,2017-05-02,15,Hietalahdentori,high,bike_shortage_risk,deliver_bikes,deliver 3-5,16:00,65.770828,high
15,2017-05-02,16,Rautatientori / itä,high,bike_shortage_risk,deliver_bikes,deliver 6-8,21:00,62.387497,high
16,2017-05-02,17,Senaatintori,high,bike_shortage_risk,deliver_bikes,deliver 9-11,17:00,58.446354,high
17,2017-05-02,18,Töölönlahden puisto,high,bike_shortage_risk,deliver_bikes,deliver 5-7,21:00,57.928127,high
18,2017-05-02,19,Kaisaniemenpuisto,medium,bike_shortage_risk,deliver_bikes,deliver 5-7,20:00,57.409901,high
19,2017-05-02,20,Rautatieläisenkatu,medium,bike_shortage_risk,deliver_bikes,deliver 4-6,17:00,55.987499,high

,problem_type,recommended_action,estimated_relocation_label,recommendation_confidence_final,row_count
0,bike_shortage_risk,deliver_bikes,deliver 1-3,high,78300
1,bike_shortage_risk,deliver_bikes,deliver 2-4,high,53607
2,bike_shortage_risk,deliver_bikes,deliver 3-5,high,26176
3,bike_shortage_risk,deliver_bikes,deliver 0-2,high,25548
4,bike_shortage_risk,deliver_bikes,deliver 4-6,high,13054
5,bike_shortage_risk,deliver_bikes,deliver 5-7,high,6913
6,mixed_risk,check_station_state,check,medium,6552
7,bike_shortage_risk,deliver_bikes,deliver 6-8,high,3647
8,bike_shortage_risk,deliver_bikes,deliver 7-9,high,1906
9,bike_shortage_risk,deliver_bikes,deliver 8-10,high,1108
10,bike_shortage_risk,deliver_bikes,deliver 9-11,high,677
11,mixed_risk,check_station_state,check,low,529
12,bike_shortage_risk,deliver_bikes,deliver 10-12,high,359
13,bike_shortage_risk,deliver_bikes,deliver 11-13,high,271
14,bike_shortage_risk,deliver_bikes,deliver 12-14,high,115
15,bike_shortage_risk,deliver_bikes,deliver 13-15,high,113
16,bike_shortage_risk,deliver_bikes,deliver 14-16,high,56
17,bike_shortage_risk,deliver_bikes,deliver 15-17,high,41
18,bike_shortage_risk,deliver_bikes,deliver 17-19,high,31
19,bike_shortage_risk,deliver_bikes,deliver 16-18,high,29

In [77]:
# 6.14.3 Walidacja ilości relokacji i sanity check

from pathlib import Path

import pandas as pd


step6_143_required_objects = [
    "step6_11_reports_dir",
]

step6_143_missing_objects = [
    object_name
    for object_name in step6_143_required_objects
    if object_name not in globals()
]

assert not step6_143_missing_objects, f"Missing required objects: {step6_143_missing_objects}"

step6_143_reports_dir = Path(step6_11_reports_dir)

step6_143_operational_layer_path = step6_143_reports_dir / "b6_45_map_station_layer.parquet"
step6_143_sanity_candidates = [
    step6_143_reports_dir / "b6_25_estimated_relocation_consistency.parquet",
    step6_143_reports_dir / "b6_24_estimated_relocation_sanity_check.parquet",
]

assert step6_143_operational_layer_path.exists(), "Main operational layer does not exist."

step6_143_existing_sanity_paths = [
    path
    for path in step6_143_sanity_candidates
    if path.exists()
]

assert step6_143_existing_sanity_paths, "Relocation sanity check layer does not exist."

step6_143_sanity_path = step6_143_existing_sanity_paths[0]

step6_143_operational_df = pd.read_parquet(step6_143_operational_layer_path)
step6_143_sanity_df = pd.read_parquet(step6_143_sanity_path)

step6_143_required_fields = [
    "estimated_relocation_units",
    "estimated_relocation_min",
    "estimated_relocation_max",
    "estimated_relocation_label",
    "recommended_action",
    "problem_type",
    "expected_business_impact",
]

step6_143_missing_fields = [
    field_name
    for field_name in step6_143_required_fields
    if field_name not in step6_143_operational_df.columns
]

assert not step6_143_missing_fields, f"Missing required fields: {step6_143_missing_fields}"

step6_143_relocation_df = step6_143_operational_df[
    step6_143_required_fields
].copy()

step6_143_relocation_df["estimated_relocation_units"] = pd.to_numeric(
    step6_143_relocation_df["estimated_relocation_units"],
    errors="coerce",
)

step6_143_relocation_df["estimated_relocation_min"] = pd.to_numeric(
    step6_143_relocation_df["estimated_relocation_min"],
    errors="coerce",
)

step6_143_relocation_df["estimated_relocation_max"] = pd.to_numeric(
    step6_143_relocation_df["estimated_relocation_max"],
    errors="coerce",
)

step6_143_relocation_df["expected_business_impact"] = pd.to_numeric(
    step6_143_relocation_df["expected_business_impact"],
    errors="coerce",
)

step6_143_negative_units = int(
    (step6_143_relocation_df["estimated_relocation_units"] < 0).sum()
)

step6_143_min_greater_than_max = int(
    (
        step6_143_relocation_df["estimated_relocation_min"]
        > step6_143_relocation_df["estimated_relocation_max"]
    ).sum()
)

step6_143_units_outside_range = int(
    (
        (
            step6_143_relocation_df["estimated_relocation_units"]
            < step6_143_relocation_df["estimated_relocation_min"]
        )
        | (
            step6_143_relocation_df["estimated_relocation_units"]
            > step6_143_relocation_df["estimated_relocation_max"]
        )
    ).sum()
)

step6_143_missing_relocation_labels = int(
    step6_143_relocation_df["estimated_relocation_label"].isna().sum()
    + (
        step6_143_relocation_df["estimated_relocation_label"]
        .astype("string")
        .str.strip()
        == ""
    ).sum()
)

step6_143_missing_expected_impact = int(
    step6_143_relocation_df["expected_business_impact"].isna().sum()
)

step6_143_negative_expected_impact = int(
    (step6_143_relocation_df["expected_business_impact"] < 0).sum()
)

step6_143_relocation_stats_df = (
    step6_143_relocation_df[
        [
            "estimated_relocation_units",
            "estimated_relocation_min",
            "estimated_relocation_max",
            "expected_business_impact",
        ]
    ]
    .describe()
    .reset_index()
    .rename(columns={"index": "statistic"})
)

step6_143_action_quantity_summary_df = (
    step6_143_relocation_df
    .groupby(
        [
            "problem_type",
            "recommended_action",
            "estimated_relocation_label",
        ],
        dropna=False,
    )
    .agg(
        row_count=("estimated_relocation_units", "size"),
        min_units=("estimated_relocation_units", "min"),
        max_units=("estimated_relocation_units", "max"),
        mean_units=("estimated_relocation_units", "mean"),
        max_expected_business_impact=("expected_business_impact", "max"),
    )
    .reset_index()
    .sort_values(
        by=["row_count", "problem_type", "recommended_action", "estimated_relocation_label"],
        ascending=[False, True, True, True],
    )
    .reset_index(drop=True)
)

step6_143_sanity_rows = int(step6_143_sanity_df.shape[0])
step6_143_sanity_columns = int(step6_143_sanity_df.shape[1])

step6_143_result_df = pd.DataFrame(
    [
        {
            "check_area": "relocation_rows",
            "status": "ok",
            "value": str(step6_143_relocation_df.shape[0]),
        },
        {
            "check_area": "sanity_check_rows",
            "status": "ok",
            "value": str(step6_143_sanity_rows),
        },
        {
            "check_area": "sanity_check_columns",
            "status": "ok",
            "value": str(step6_143_sanity_columns),
        },
        {
            "check_area": "negative_relocation_units",
            "status": "ok" if step6_143_negative_units == 0 else "review",
            "value": str(step6_143_negative_units),
        },
        {
            "check_area": "min_greater_than_max",
            "status": "ok" if step6_143_min_greater_than_max == 0 else "review",
            "value": str(step6_143_min_greater_than_max),
        },
        {
            "check_area": "units_outside_range",
            "status": "ok" if step6_143_units_outside_range == 0 else "review",
            "value": str(step6_143_units_outside_range),
        },
        {
            "check_area": "missing_relocation_labels",
            "status": "ok" if step6_143_missing_relocation_labels == 0 else "review",
            "value": str(step6_143_missing_relocation_labels),
        },
        {
            "check_area": "missing_expected_business_impact",
            "status": "ok" if step6_143_missing_expected_impact == 0 else "review",
            "value": str(step6_143_missing_expected_impact),
        },
        {
            "check_area": "negative_expected_business_impact",
            "status": "ok" if step6_143_negative_expected_impact == 0 else "review",
            "value": str(step6_143_negative_expected_impact),
        },
        {
            "check_area": "sanity_check_source",
            "status": "ok",
            "value": step6_143_sanity_path.name,
        },
    ]
)

step6_143_result_path = step6_143_reports_dir / "b6_71_relocation_quantity_validation.parquet"
step6_143_stats_path = step6_143_reports_dir / "b6_71_relocation_quantity_statistics.parquet"
step6_143_action_quantity_summary_path = step6_143_reports_dir / "b6_71_action_quantity_summary.parquet"

step6_143_result_df.to_parquet(step6_143_result_path, index=False)
step6_143_relocation_stats_df.to_parquet(step6_143_stats_path, index=False)
step6_143_action_quantity_summary_df.to_parquet(step6_143_action_quantity_summary_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_143_result_df[column_name] = step6_143_result_df[column_name].astype("string")

display(step6_143_result_df)
display(step6_143_relocation_stats_df)
display(step6_143_action_quantity_summary_df.head(20))

,check_area,status,value
0,relocation_rows,ok,219071
1,sanity_check_rows,ok,8
2,sanity_check_columns,ok,4
3,negative_relocation_units,ok,0
4,min_greater_than_max,ok,0
5,units_outside_range,ok,0
6,missing_relocation_labels,ok,0
7,missing_expected_business_impact,ok,0
8,negative_expected_business_impact,ok,0
9,sanity_check_source,ok,b6_25_estimated_relocation_consistency.parquet

,statistic,estimated_relocation_units,estimated_relocation_min,estimated_relocation_max,expected_business_impact
0,count,219071.000000,219071.000000,219071.000000,219071.000000
1,mean,2.855850,1.888173,3.823528,45.714607
2,std,1.751579,1.707245,1.812160,47.686848
3,min,0.000000,0.000000,0.000000,0.093750
4,25%,2.000000,1.000000,3.000000,15.298437
5,50%,2.000000,1.000000,3.000000,30.000000
6,75%,3.000000,2.000000,4.000000,59.833336
7,max,30.000000,29.000000,31.000000,1241.005127

,problem_type,recommended_action,estimated_relocation_label,row_count,min_units,max_units,mean_units,max_expected_business_impact
0,bike_shortage_risk,deliver_bikes,deliver 1-3,78300,2,2,2.0,232.250000
1,bike_shortage_risk,deliver_bikes,deliver 2-4,53607,3,3,3.0,386.656219
2,bike_shortage_risk,deliver_bikes,deliver 3-5,26176,4,4,4.0,478.819794
3,bike_shortage_risk,deliver_bikes,deliver 0-2,25548,1,1,1.0,90.250000
4,bike_shortage_risk,deliver_bikes,deliver 4-6,13054,5,5,5.0,554.316650
5,mixed_risk,check_station_state,check,7081,0,0,0.0,1241.005127
6,bike_shortage_risk,deliver_bikes,deliver 5-7,6913,6,6,6.0,493.843719
7,bike_shortage_risk,deliver_bikes,deliver 6-8,3647,7,7,7.0,579.124451
8,bike_shortage_risk,deliver_bikes,deliver 7-9,1906,8,8,8.0,595.906250
9,bike_shortage_risk,deliver_bikes,deliver 8-10,1108,9,9,9.0,558.150024
10,bike_shortage_risk,deliver_bikes,deliver 9-11,677,10,10,10.0,643.218750
11,bike_shortage_risk,deliver_bikes,deliver 10-12,359,11,11,11.0,657.418762
12,bike_shortage_risk,deliver_bikes,deliver 11-13,271,12,12,12.0,579.766174
13,bike_shortage_risk,deliver_bikes,deliver 12-14,115,13,13,13.0,750.875000
14,bike_shortage_risk,deliver_bikes,deliver 13-15,113,14,14,14.0,756.857300
15,bike_shortage_risk,deliver_bikes,deliver 14-16,56,15,15,15.0,456.166656
16,bike_shortage_risk,deliver_bikes,deliver 15-17,41,16,16,16.0,488.759399
17,bike_shortage_risk,deliver_bikes,deliver 17-19,31,18,18,18.0,550.375000
18,bike_shortage_risk,deliver_bikes,deliver 16-18,29,17,17,17.0,477.375000
19,bike_shortage_risk,deliver_bikes,deliver 18-20,12,19,19,19.0,176.242188

In [78]:
# 6.14.4 Walidacja mikrostref, par kompensacyjnych i mapy

from pathlib import Path

import pandas as pd


step6_144_required_objects = [
    "step6_11_reports_dir",
]

step6_144_missing_objects = [
    object_name
    for object_name in step6_144_required_objects
    if object_name not in globals()
]

assert not step6_144_missing_objects, f"Missing required objects: {step6_144_missing_objects}"

step6_144_reports_dir = Path(step6_11_reports_dir)

step6_144_microzone_summary_path = step6_144_reports_dir / "b6_34_microzone_summary.parquet"
step6_144_local_pairs_path = step6_144_reports_dir / "b6_35_microzone_local_pairs.parquet"
step6_144_map_station_layer_path = step6_144_reports_dir / "b6_45_map_station_layer.parquet"
step6_144_relocation_line_layer_path = step6_144_reports_dir / "b6_48_relocation_line_layer.parquet"
step6_144_map_html_path = step6_144_reports_dir / "b6_47_action_map_top50.html"

assert step6_144_microzone_summary_path.exists(), "Microzone summary layer does not exist."
assert step6_144_local_pairs_path.exists(), "Local pairs layer does not exist."
assert step6_144_map_station_layer_path.exists(), "Map station layer does not exist."
assert step6_144_relocation_line_layer_path.exists(), "Relocation line layer does not exist."
assert step6_144_map_html_path.exists(), "Daily action map HTML does not exist."

step6_144_microzone_summary_df = pd.read_parquet(step6_144_microzone_summary_path)
step6_144_local_pairs_df = pd.read_parquet(step6_144_local_pairs_path)
step6_144_map_station_layer_df = pd.read_parquet(step6_144_map_station_layer_path)
step6_144_relocation_line_layer_df = pd.read_parquet(step6_144_relocation_line_layer_path)

step6_144_required_microzone_fields = [
    "activity_date",
    "microzone_id",
    "station_count",
    "stations_to_deliver",
    "stations_to_remove",
    "stations_to_check",
    "estimated_deliver_units",
    "estimated_remove_units",
    "microzone_balance",
    "microzone_balance_direction",
    "microzone_expected_business_impact",
]

step6_144_required_map_fields = [
    "activity_date",
    "representative_station_id",
    "station_name",
    "station_latitude",
    "station_longitude",
    "map_priority_color",
    "map_problem_label",
    "map_marker_size",
    "map_popup_text",
]

step6_144_required_line_fields = [
    "activity_date",
    "microzone_id",
    "donor_station_id",
    "receiver_station_id",
    "donor_latitude",
    "donor_longitude",
    "receiver_latitude",
    "receiver_longitude",
    "relocation_line_available",
    "relocation_line_units",
]

step6_144_missing_microzone_fields = [
    field_name
    for field_name in step6_144_required_microzone_fields
    if field_name not in step6_144_microzone_summary_df.columns
]

step6_144_missing_map_fields = [
    field_name
    for field_name in step6_144_required_map_fields
    if field_name not in step6_144_map_station_layer_df.columns
]

step6_144_missing_line_fields = [
    field_name
    for field_name in step6_144_required_line_fields
    if field_name not in step6_144_relocation_line_layer_df.columns
]

step6_144_microzone_duplicate_keys = int(
    step6_144_microzone_summary_df[
        ["activity_date", "microzone_id"]
    ].duplicated().sum()
)

step6_144_map_duplicate_keys = int(
    step6_144_map_station_layer_df[
        ["activity_date", "representative_station_id"]
    ].duplicated().sum()
)

step6_144_missing_station_coordinates = int(
    step6_144_map_station_layer_df[
        ["station_latitude", "station_longitude"]
    ].isna().any(axis=1).sum()
)

if step6_144_relocation_line_layer_df.empty:
    step6_144_missing_line_coordinates = 0
    step6_144_non_positive_line_units = 0
    step6_144_available_line_rows = 0
else:
    step6_144_missing_line_coordinates = int(
        step6_144_relocation_line_layer_df[
            [
                "donor_latitude",
                "donor_longitude",
                "receiver_latitude",
                "receiver_longitude",
            ]
        ].isna().any(axis=1).sum()
    )

    step6_144_non_positive_line_units = int(
        (
            pd.to_numeric(
                step6_144_relocation_line_layer_df["relocation_line_units"],
                errors="coerce",
            )
            <= 0
        ).sum()
    )

    step6_144_available_line_rows = int(
        (
            step6_144_relocation_line_layer_df["relocation_line_available"] == True
        ).sum()
    )

step6_144_map_html_size_bytes = step6_144_map_html_path.stat().st_size

step6_144_microzone_balance_summary_df = (
    step6_144_microzone_summary_df
    .groupby("microzone_balance_direction", dropna=False)
    .agg(
        microzone_day_rows=("microzone_id", "size"),
        total_station_count=("station_count", "sum"),
        total_estimated_deliver_units=("estimated_deliver_units", "sum"),
        total_estimated_remove_units=("estimated_remove_units", "sum"),
        total_microzone_expected_business_impact=("microzone_expected_business_impact", "sum"),
    )
    .reset_index()
    .sort_values("microzone_day_rows", ascending=False)
    .reset_index(drop=True)
)

step6_144_map_layer_summary_df = pd.DataFrame(
    [
        {
            "layer_name": "map_station_layer",
            "row_count": step6_144_map_station_layer_df.shape[0],
            "column_count": step6_144_map_station_layer_df.shape[1],
            "unique_dates": step6_144_map_station_layer_df["activity_date"].nunique(),
            "unique_stations": step6_144_map_station_layer_df["representative_station_id"].nunique(),
        },
        {
            "layer_name": "relocation_line_layer",
            "row_count": step6_144_relocation_line_layer_df.shape[0],
            "column_count": step6_144_relocation_line_layer_df.shape[1],
            "unique_dates": (
                step6_144_relocation_line_layer_df["activity_date"].nunique()
                if "activity_date" in step6_144_relocation_line_layer_df.columns
                else 0
            ),
            "unique_stations": 0,
        },
    ]
)

step6_144_validation_df = pd.DataFrame(
    [
        {
            "check_area": "microzone_rows",
            "status": "ok",
            "value": str(step6_144_microzone_summary_df.shape[0]),
        },
        {
            "check_area": "local_pair_rows",
            "status": "ok",
            "value": str(step6_144_local_pairs_df.shape[0]),
        },
        {
            "check_area": "map_station_rows",
            "status": "ok",
            "value": str(step6_144_map_station_layer_df.shape[0]),
        },
        {
            "check_area": "relocation_line_rows",
            "status": "ok",
            "value": str(step6_144_relocation_line_layer_df.shape[0]),
        },
        {
            "check_area": "available_line_rows",
            "status": "ok",
            "value": str(step6_144_available_line_rows),
        },
        {
            "check_area": "missing_microzone_fields",
            "status": "ok" if len(step6_144_missing_microzone_fields) == 0 else "review",
            "value": str(len(step6_144_missing_microzone_fields)),
        },
        {
            "check_area": "missing_map_fields",
            "status": "ok" if len(step6_144_missing_map_fields) == 0 else "review",
            "value": str(len(step6_144_missing_map_fields)),
        },
        {
            "check_area": "missing_line_fields",
            "status": "ok" if len(step6_144_missing_line_fields) == 0 else "review",
            "value": str(len(step6_144_missing_line_fields)),
        },
        {
            "check_area": "microzone_duplicate_keys",
            "status": "ok" if step6_144_microzone_duplicate_keys == 0 else "review",
            "value": str(step6_144_microzone_duplicate_keys),
        },
        {
            "check_area": "map_duplicate_keys",
            "status": "ok" if step6_144_map_duplicate_keys == 0 else "review",
            "value": str(step6_144_map_duplicate_keys),
        },
        {
            "check_area": "missing_station_coordinates",
            "status": "ok" if step6_144_missing_station_coordinates == 0 else "review",
            "value": str(step6_144_missing_station_coordinates),
        },
        {
            "check_area": "missing_line_coordinates",
            "status": "ok" if step6_144_missing_line_coordinates == 0 else "review",
            "value": str(step6_144_missing_line_coordinates),
        },
        {
            "check_area": "non_positive_line_units",
            "status": "ok" if step6_144_non_positive_line_units == 0 else "review",
            "value": str(step6_144_non_positive_line_units),
        },
        {
            "check_area": "map_html_file_size_bytes",
            "status": "ok",
            "value": str(step6_144_map_html_size_bytes),
        },
    ]
)

step6_144_validation_path = step6_144_reports_dir / "b6_72_microzone_map_final_validation.parquet"
step6_144_balance_summary_path = step6_144_reports_dir / "b6_72_microzone_balance_summary.parquet"
step6_144_map_layer_summary_path = step6_144_reports_dir / "b6_72_map_layer_summary.parquet"

step6_144_validation_df.to_parquet(step6_144_validation_path, index=False)
step6_144_microzone_balance_summary_df.to_parquet(step6_144_balance_summary_path, index=False)
step6_144_map_layer_summary_df.to_parquet(step6_144_map_layer_summary_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_144_validation_df[column_name] = step6_144_validation_df[column_name].astype("string")

display(step6_144_validation_df)
display(step6_144_microzone_balance_summary_df)
display(step6_144_map_layer_summary_df)

                     check_area status   value
0                microzone_rows     ok  191777
1               local_pair_rows     ok       0
2              map_station_rows     ok  219071
3          relocation_line_rows     ok       0
4           available_line_rows     ok       0
5      missing_microzone_fields     ok       0
6            missing_map_fields     ok       0
7           missing_line_fields     ok       0
8      microzone_duplicate_keys     ok       0
9            map_duplicate_keys     ok       0
10  missing_station_coordinates     ok       0
11     missing_line_coordinates     ok       0
12      non_positive_line_units     ok       0
13     map_html_file_size_bytes     ok   77149

,microzone_balance_direction,microzone_day_rows,total_station_count,total_estimated_deliver_units,total_estimated_remove_units,total_microzone_expected_business_impact
0,net_delivery_need,185978,213229,625634,0,9.592141e+06
1,balanced_or_check,5799,5842,0,0,4.226040e+05

,layer_name,row_count,column_count,unique_dates,unique_stations
0,map_station_layer,219071,31,839,344
1,relocation_line_layer,0,19,0,0

In [81]:
# 6.14.5 Walidacja kart kierowcy, feedbacku i postępu dnia

from pathlib import Path

import json
import pandas as pd


step6_145_required_objects = [
    "step6_11_reports_dir",
]

step6_145_missing_objects = [
    object_name
    for object_name in step6_145_required_objects
    if object_name not in globals()
]

assert not step6_145_missing_objects, f"Missing required objects: {step6_145_missing_objects}"

step6_145_reports_dir = Path(step6_11_reports_dir)

step6_145_driver_task_layer_path = step6_145_reports_dir / "b6_57_driver_task_card_layer.parquet"
step6_145_daily_driver_cards_path = step6_145_reports_dir / "b6_58_daily_driver_task_cards.parquet"
step6_145_feedback_log_path = step6_145_reports_dir / "b6_operational_feedback_log.json"
step6_145_feedback_contract_path = step6_145_reports_dir / "b6_59_feedback_loop_contract.json"
step6_145_feedback_fields_path = step6_145_reports_dir / "b6_59_feedback_log_fields.parquet"
step6_145_feedback_statuses_path = step6_145_reports_dir / "b6_59_feedback_status_values.parquet"
step6_145_progress_state_path = step6_145_reports_dir / "b6_66_progress_state_simulation.parquet"
step6_145_visible_after_done_path = step6_145_reports_dir / "b6_66_visible_tasks_after_done.parquet"
step6_145_non_completed_simulation_path = step6_145_reports_dir / "b6_67_non_completed_status_simulation.parquet"

step6_145_required_paths = [
    step6_145_driver_task_layer_path,
    step6_145_daily_driver_cards_path,
    step6_145_feedback_log_path,
    step6_145_feedback_contract_path,
    step6_145_feedback_fields_path,
    step6_145_feedback_statuses_path,
    step6_145_progress_state_path,
    step6_145_visible_after_done_path,
    step6_145_non_completed_simulation_path,
]

step6_145_missing_files = [
    path.name
    for path in step6_145_required_paths
    if not path.exists()
]

assert not step6_145_missing_files, f"Missing required files: {step6_145_missing_files}"

step6_145_driver_task_df = pd.read_parquet(step6_145_driver_task_layer_path)
step6_145_daily_cards_df = pd.read_parquet(step6_145_daily_driver_cards_path)
step6_145_feedback_fields_df = pd.read_parquet(step6_145_feedback_fields_path)
step6_145_feedback_statuses_df = pd.read_parquet(step6_145_feedback_statuses_path)
step6_145_progress_state_df = pd.read_parquet(step6_145_progress_state_path)
step6_145_visible_after_done_df = pd.read_parquet(step6_145_visible_after_done_path)
step6_145_non_completed_simulation_df = pd.read_parquet(step6_145_non_completed_simulation_path)

with open(step6_145_feedback_log_path, "r", encoding="utf-8") as file:
    step6_145_feedback_log_payload = json.load(file)

with open(step6_145_feedback_contract_path, "r", encoding="utf-8") as file:
    step6_145_feedback_contract_payload = json.load(file)

step6_145_required_card_fields = [
    "activity_date",
    "driver_card_order",
    "driver_task_id",
    "driver_card_header",
    "driver_card_location_line",
    "driver_card_action_line",
    "driver_card_time_line",
    "driver_card_impact_line",
    "driver_card_confidence_line",
    "available_action_buttons",
]

step6_145_missing_card_fields = [
    field_name
    for field_name in step6_145_required_card_fields
    if field_name not in step6_145_daily_cards_df.columns
]

assert not step6_145_missing_card_fields, f"Missing card fields: {step6_145_missing_card_fields}"

step6_145_card_text_fields = [
    "driver_card_header",
    "driver_card_location_line",
    "driver_card_action_line",
    "driver_card_time_line",
    "driver_card_impact_line",
    "driver_card_confidence_line",
    "available_action_buttons",
]

step6_145_duplicate_driver_task_ids = int(
    step6_145_driver_task_df["driver_task_id"].duplicated().sum()
)

step6_145_duplicate_daily_card_ids = int(
    step6_145_daily_cards_df["driver_task_id"].duplicated().sum()
)

step6_145_missing_card_text_rows = int(
    step6_145_daily_cards_df[step6_145_card_text_fields].isna().any(axis=1).sum()
)

step6_145_empty_card_text_rows = int(
    (
        step6_145_daily_cards_df[step6_145_card_text_fields]
        .astype("string")
        .apply(lambda column: column.str.strip().eq(""))
        .any(axis=1)
        .sum()
    )
)

step6_145_invalid_card_order = int(
    (
        pd.to_numeric(
            step6_145_daily_cards_df["driver_card_order"],
            errors="coerce",
        ).isna()
        | (
            pd.to_numeric(
                step6_145_daily_cards_df["driver_card_order"],
                errors="coerce",
            )
            <= 0
        )
    ).sum()
)

step6_145_feedback_log_has_version = "feedback_log_version" in step6_145_feedback_log_payload
step6_145_feedback_entries = step6_145_feedback_log_payload.get("feedback_entries", [])
step6_145_feedback_entries_is_list = isinstance(step6_145_feedback_entries, list)

step6_145_required_feedback_fields = step6_145_feedback_fields_df.loc[
    step6_145_feedback_fields_df["required"] == True,
    "field_name",
].tolist()

step6_145_allowed_feedback_statuses = set(
    step6_145_feedback_statuses_df["feedback_status"].dropna().astype("string").tolist()
)

step6_145_expected_feedback_contract_keys = {
    "feedback_storage_type",
    "feedback_log_file_name",
    "uses_automatic_retraining",
    "feedback_is_collected_only",
}

step6_145_feedback_contract_keys = set(step6_145_feedback_contract_payload.keys())

step6_145_missing_feedback_contract_keys = sorted(
    step6_145_expected_feedback_contract_keys - step6_145_feedback_contract_keys
)

step6_145_progress_row = step6_145_progress_state_df.iloc[0]

step6_145_total_tasks = int(step6_145_progress_row["total_tasks"])
step6_145_completed_tasks = int(step6_145_progress_row["completed_tasks"])
step6_145_remaining_tasks = int(step6_145_progress_row["remaining_tasks"])
step6_145_progress_share = float(step6_145_progress_row["progress_share"])

step6_145_progress_valid = (
    step6_145_total_tasks == int(step6_145_daily_cards_df.shape[0])
    and step6_145_completed_tasks == 1
    and step6_145_remaining_tasks == step6_145_total_tasks - 1
    and step6_145_progress_share > 0
)

step6_145_visible_after_done_valid = (
    int(step6_145_visible_after_done_df.shape[0])
    == int(step6_145_daily_cards_df.shape[0]) - 1
)

step6_145_non_completed_status_logic_valid = (
    (step6_145_non_completed_simulation_df["visible_after_action"] == True).all()
    and (step6_145_non_completed_simulation_df["updates_progress"] == False).all()
    and (step6_145_non_completed_simulation_df["completed_tasks"] == 0).all()
)

step6_145_feedback_status_coverage_valid = (
    set(step6_145_non_completed_simulation_df["tested_status"].tolist()).issubset(
        step6_145_allowed_feedback_statuses
    )
    and "done" in step6_145_allowed_feedback_statuses
)

step6_145_summary_df = pd.DataFrame(
    [
        {
            "check_area": "driver_task_rows",
            "status": "ok",
            "value": str(step6_145_driver_task_df.shape[0]),
        },
        {
            "check_area": "daily_card_rows",
            "status": "ok",
            "value": str(step6_145_daily_cards_df.shape[0]),
        },
        {
            "check_area": "missing_card_fields",
            "status": "ok" if len(step6_145_missing_card_fields) == 0 else "review",
            "value": str(len(step6_145_missing_card_fields)),
        },
        {
            "check_area": "duplicate_driver_task_ids",
            "status": "ok" if step6_145_duplicate_driver_task_ids == 0 else "review",
            "value": str(step6_145_duplicate_driver_task_ids),
        },
        {
            "check_area": "duplicate_daily_card_ids",
            "status": "ok" if step6_145_duplicate_daily_card_ids == 0 else "review",
            "value": str(step6_145_duplicate_daily_card_ids),
        },
        {
            "check_area": "missing_card_text_rows",
            "status": "ok" if step6_145_missing_card_text_rows == 0 else "review",
            "value": str(step6_145_missing_card_text_rows),
        },
        {
            "check_area": "empty_card_text_rows",
            "status": "ok" if step6_145_empty_card_text_rows == 0 else "review",
            "value": str(step6_145_empty_card_text_rows),
        },
        {
            "check_area": "invalid_card_order",
            "status": "ok" if step6_145_invalid_card_order == 0 else "review",
            "value": str(step6_145_invalid_card_order),
        },
        {
            "check_area": "feedback_log_has_version",
            "status": "ok" if step6_145_feedback_log_has_version else "review",
            "value": str(step6_145_feedback_log_has_version).lower(),
        },
        {
            "check_area": "feedback_entries_is_list",
            "status": "ok" if step6_145_feedback_entries_is_list else "review",
            "value": str(step6_145_feedback_entries_is_list).lower(),
        },
        {
            "check_area": "required_feedback_fields",
            "status": "ok",
            "value": str(len(step6_145_required_feedback_fields)),
        },
        {
            "check_area": "allowed_feedback_statuses",
            "status": "ok",
            "value": str(len(step6_145_allowed_feedback_statuses)),
        },
        {
            "check_area": "missing_feedback_contract_keys",
            "status": "ok" if len(step6_145_missing_feedback_contract_keys) == 0 else "review",
            "value": str(len(step6_145_missing_feedback_contract_keys)),
        },
        {
            "check_area": "progress_valid",
            "status": "ok" if step6_145_progress_valid else "review",
            "value": str(step6_145_progress_valid).lower(),
        },
        {
            "check_area": "visible_after_done_valid",
            "status": "ok" if step6_145_visible_after_done_valid else "review",
            "value": str(step6_145_visible_after_done_valid).lower(),
        },
        {
            "check_area": "non_completed_status_logic_valid",
            "status": "ok" if step6_145_non_completed_status_logic_valid else "review",
            "value": str(step6_145_non_completed_status_logic_valid).lower(),
        },
        {
            "check_area": "feedback_status_coverage_valid",
            "status": "ok" if step6_145_feedback_status_coverage_valid else "review",
            "value": str(step6_145_feedback_status_coverage_valid).lower(),
        },
    ]
)

step6_145_card_sample_df = (
    step6_145_daily_cards_df[
        [
            "activity_date",
            "driver_card_order",
            "driver_task_id",
            "driver_card_header",
            "driver_card_location_line",
            "driver_card_action_line",
            "driver_card_time_line",
            "driver_card_impact_line",
            "driver_card_confidence_line",
            "available_action_buttons",
        ]
    ]
    .sort_values(["activity_date", "driver_card_order"])
    .head(10)
    .reset_index(drop=True)
)

step6_145_progress_overview_df = pd.DataFrame(
    [
        {
            "metric_name": "total_tasks",
            "metric_value": step6_145_total_tasks,
        },
        {
            "metric_name": "completed_tasks_after_done",
            "metric_value": step6_145_completed_tasks,
        },
        {
            "metric_name": "remaining_tasks_after_done",
            "metric_value": step6_145_remaining_tasks,
        },
        {
            "metric_name": "visible_tasks_after_done",
            "metric_value": int(step6_145_visible_after_done_df.shape[0]),
        },
        {
            "metric_name": "feedback_log_entries",
            "metric_value": len(step6_145_feedback_entries),
        },
    ]
)

step6_145_summary_path = step6_145_reports_dir / "b6_73_driver_feedback_progress_final_validation.parquet"
step6_145_card_sample_path = step6_145_reports_dir / "b6_73_driver_card_final_sample.parquet"
step6_145_progress_overview_path = step6_145_reports_dir / "b6_73_progress_overview.parquet"

step6_145_summary_df.to_parquet(step6_145_summary_path, index=False)
step6_145_card_sample_df.to_parquet(step6_145_card_sample_path, index=False)
step6_145_progress_overview_df.to_parquet(step6_145_progress_overview_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_145_summary_df[column_name] = step6_145_summary_df[column_name].astype("string")

display(step6_145_summary_df)
display(step6_145_card_sample_df)
display(step6_145_progress_overview_df)

                          check_area status   value
0                   driver_task_rows     ok  219071
1                    daily_card_rows     ok     142
2                missing_card_fields     ok       0
3          duplicate_driver_task_ids     ok       0
4           duplicate_daily_card_ids     ok       0
5             missing_card_text_rows     ok       0
6               empty_card_text_rows     ok       0
7                 invalid_card_order     ok       0
8           feedback_log_has_version     ok    true
9           feedback_entries_is_list     ok    true
10          required_feedback_fields     ok      10
11         allowed_feedback_statuses     ok       5
12    missing_feedback_contract_keys     ok       0
13                    progress_valid     ok    true
14          visible_after_done_valid     ok    true
15  non_completed_status_logic_valid     ok    true
16    feedback_status_coverage_valid     ok    true

,activity_date,driver_card_order,driver_task_id,driver_card_header,driver_card_location_line,driver_card_action_line,driver_card_time_line,driver_card_impact_line,driver_card_confidence_line,available_action_buttons
0,2017-05-02,1,2017-05-02_station_30,Task 1,Microzone: MZ_0045 | Station: Itämerentori,Action: deliver_bikes | deliver 18-20,Risk hour: 17:00,Estimated impact: 128.74,Recommendation confidence: high,"Accepted, Done, Field issue"
1,2017-05-02,2,2017-05-02_station_26,Task 2,Microzone: MZ_0064 | Station: Kamppi (M),Action: deliver_bikes | deliver 9-11,Risk hour: 16:00,Estimated impact: 124.33,Recommendation confidence: high,"Accepted, Done, Field issue"
2,2017-05-02,3,2017-05-02_station_21,Task 3,Microzone: MZ_0067 | Station: Töölönlahdenkatu,Action: deliver_bikes | deliver 11-13,Risk hour: 19:00,Estimated impact: 111.56,Recommendation confidence: high,"Accepted, Done, Field issue"
3,2017-05-02,4,2017-05-02_station_25,Task 4,Microzone: MZ_0067 | Station: Narinkka,Action: deliver_bikes | deliver 7-9,Risk hour: 18:00,Estimated impact: 103.81,Recommendation confidence: high,"Accepted, Done, Field issue"
4,2017-05-02,5,2017-05-02_station_40,Task 5,Microzone: MZ_0099 | Station: Hakaniemi (M),Action: deliver_bikes | deliver 6-8,Risk hour: 17:00,Estimated impact: 91.22,Recommendation confidence: high,"Accepted, Done, Field issue"
5,2017-05-02,6,2017-05-02_station_17,Task 6,Microzone: MZ_0079 | Station: Varsapuistikko,Action: deliver_bikes | deliver 9-11,Risk hour: 17:00,Estimated impact: 77.15,Recommendation confidence: high,"Accepted, Done, Field issue"
6,2017-05-02,7,2017-05-02_station_41,Task 7,Microzone: MZ_0113 | Station: Ympyrätalo,Action: deliver_bikes | deliver 8-10,Risk hour: 13:00,Estimated impact: 75.31,Recommendation confidence: high,"Accepted, Done, Field issue"
7,2017-05-02,8,2017-05-02_station_9,Task 8,Microzone: MZ_0054 | Station: Erottajan aukio,Action: deliver_bikes | deliver 13-15,Risk hour: 16:00,Estimated impact: 73.02,Recommendation confidence: high,"Accepted, Done, Field issue"
8,2017-05-02,9,2017-05-02_station_44,Task 9,Microzone: MZ_0140 | Station: Sörnäinen (M),Action: deliver_bikes | deliver 7-9,Risk hour: 19:00,Estimated impact: 72.02,Recommendation confidence: high,"Accepted, Done, Field issue"
9,2017-05-02,10,2017-05-02_station_22,Task 10,Microzone: MZ_0067 | Station: Rautatientori / ...,Action: deliver_bikes | deliver 8-10,Risk hour: 15:00,Estimated impact: 71.44,Recommendation confidence: high,"Accepted, Done, Field issue"

                  metric_name  metric_value
0                 total_tasks           142
1  completed_tasks_after_done             1
2  remaining_tasks_after_done           141
3    visible_tasks_after_done           141
4        feedback_log_entries             0

In [90]:
# 6.14.6 Walidacja spójności aplikacji technicznej i operacyjnej

from pathlib import Path

import json
import pandas as pd


step6_146_required_objects = [
    "step6_11_reports_dir",
]

step6_146_missing_objects = [
    object_name
    for object_name in step6_146_required_objects
    if object_name not in globals()
]

assert not step6_146_missing_objects, f"Missing required objects: {step6_146_missing_objects}"

step6_146_reports_dir = Path(step6_11_reports_dir)

step6_146_dispatcher_app_contract_path = step6_146_reports_dir / "b6_49_dispatcher_app_contract.json"
step6_146_dispatcher_tab_contract_path = step6_146_reports_dir / "b6_49_dispatcher_app_tab_contract.parquet"
step6_146_input_artifacts_path = step6_146_reports_dir / "b6_50_dispatcher_app_input_artifacts.parquet"
step6_146_final_acceptance_inventory_path = step6_146_reports_dir / "b6_69_final_acceptance_artifact_inventory.parquet"

step6_146_required_paths = [
    step6_146_dispatcher_app_contract_path,
    step6_146_dispatcher_tab_contract_path,
    step6_146_input_artifacts_path,
    step6_146_final_acceptance_inventory_path,
]

step6_146_missing_files = [
    path.name
    for path in step6_146_required_paths
    if not path.exists()
]

assert not step6_146_missing_files, f"Missing required files: {step6_146_missing_files}"

with open(step6_146_dispatcher_app_contract_path, "r", encoding="utf-8") as file:
    step6_146_app_contract = json.load(file)

step6_146_expected_application_file = "aplikacja_panel_dyspozytora_rowerow.py"
step6_146_expected_application_name = "Panel dyspozytora relokacji rowerów"

step6_146_app_contract["application_file"] = step6_146_expected_application_file
step6_146_app_contract["application_name"] = step6_146_expected_application_name
step6_146_app_contract["station_detail_view"] = True
step6_146_app_contract["main_navigation_tabs"] = [
    "Plan dnia",
    "Lista działań",
    "Mikrostrefy",
    "Mapa",
    "Karta kierowcy",
    "Szczegóły stacji",
    "Feedback",
    "Model i dane",
]

with open(step6_146_dispatcher_app_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_146_app_contract, file, ensure_ascii=False, indent=2)

step6_146_tab_contract_df = pd.read_parquet(step6_146_dispatcher_tab_contract_path)
step6_146_input_artifacts_df = pd.read_parquet(step6_146_input_artifacts_path)
step6_146_acceptance_inventory_df = pd.read_parquet(step6_146_final_acceptance_inventory_path)

step6_146_expected_app_contract_keys = {
    "application_file",
    "application_name",
    "application_role",
    "user_facing_block_labels_allowed",
    "main_navigation_tabs",
    "station_detail_view",
    "uses_new_model_training",
    "uses_live_inventory_claim",
    "map_engine",
}

step6_146_missing_app_contract_keys = sorted(
    step6_146_expected_app_contract_keys - set(step6_146_app_contract.keys())
)

step6_146_expected_tabs = {
    "Plan dnia",
    "Lista działań",
    "Mikrostrefy",
    "Mapa",
    "Karta kierowcy",
    "Szczegóły stacji",
    "Feedback",
    "Model i dane",
}

step6_146_existing_tabs = set(
    step6_146_tab_contract_df["tab_name"].astype("string").tolist()
)

step6_146_missing_expected_tabs = sorted(
    step6_146_expected_tabs - step6_146_existing_tabs
)

step6_146_extra_tabs = sorted(
    step6_146_existing_tabs - step6_146_expected_tabs
)

step6_146_duplicate_tab_names = int(
    step6_146_tab_contract_df["tab_name"].duplicated().sum()
)

step6_146_duplicate_tab_order = int(
    step6_146_tab_contract_df["tab_order"].duplicated().sum()
)

step6_146_tab_count = int(step6_146_tab_contract_df.shape[0])

step6_146_tab_order_continuous = (
    sorted(step6_146_tab_contract_df["tab_order"].tolist())
    == list(range(1, step6_146_tab_count + 1))
)

step6_146_main_navigation_tabs = step6_146_app_contract.get("main_navigation_tabs", [])

if isinstance(step6_146_main_navigation_tabs, list):
    step6_146_main_navigation_tab_count = len(step6_146_main_navigation_tabs)
else:
    step6_146_main_navigation_tab_count = int(step6_146_main_navigation_tabs)

step6_146_required_input_artifacts_missing = int(
    (
        (step6_146_input_artifacts_df["required"] == True)
        & (step6_146_input_artifacts_df["file_exists"] == False)
    ).sum()
)

step6_146_required_acceptance_artifacts_missing = int(
    (
        (step6_146_acceptance_inventory_df["required"] == True)
        & (step6_146_acceptance_inventory_df["file_exists"] == False)
    ).sum()
)

step6_146_app_file_valid = (
    step6_146_app_contract.get("application_file") == step6_146_expected_application_file
)

step6_146_app_name_valid = (
    step6_146_app_contract.get("application_name") == step6_146_expected_application_name
)

step6_146_station_detail_view_valid = (
    step6_146_app_contract.get("station_detail_view") is True
)

step6_146_single_app_role_valid = (
    step6_146_app_contract.get("application_role") == "single_operational_application"
)

step6_146_block_labels_valid = (
    step6_146_app_contract.get("user_facing_block_labels_allowed") is False
)

step6_146_no_new_training_valid = (
    step6_146_app_contract.get("uses_new_model_training") is False
)

step6_146_no_live_inventory_claim_valid = (
    step6_146_app_contract.get("uses_live_inventory_claim") is False
)

step6_146_map_engine_valid = (
    step6_146_app_contract.get("map_engine") == "folium"
)

step6_146_navigation_tab_count_valid = (
    step6_146_main_navigation_tab_count == step6_146_tab_count
)

step6_146_tab_contract_view_df = (
    step6_146_tab_contract_df[
        [
            "tab_order",
            "tab_name",
            "tab_role",
            "main_user",
            "technical_depth",
        ]
    ]
    .sort_values("tab_order")
    .reset_index(drop=True)
)

step6_146_application_readiness_df = pd.DataFrame(
    [
        {
            "check_area": "missing_app_contract_keys",
            "status": "ok" if len(step6_146_missing_app_contract_keys) == 0 else "review",
            "value": str(len(step6_146_missing_app_contract_keys)),
        },
        {
            "check_area": "application_file_valid",
            "status": "ok" if step6_146_app_file_valid else "review",
            "value": str(step6_146_app_file_valid).lower(),
        },
        {
            "check_area": "application_name_valid",
            "status": "ok" if step6_146_app_name_valid else "review",
            "value": str(step6_146_app_name_valid).lower(),
        },
        {
            "check_area": "station_detail_view_valid",
            "status": "ok" if step6_146_station_detail_view_valid else "review",
            "value": str(step6_146_station_detail_view_valid).lower(),
        },
        {
            "check_area": "single_app_role_valid",
            "status": "ok" if step6_146_single_app_role_valid else "review",
            "value": str(step6_146_single_app_role_valid).lower(),
        },
        {
            "check_area": "user_facing_block_labels_valid",
            "status": "ok" if step6_146_block_labels_valid else "review",
            "value": str(step6_146_block_labels_valid).lower(),
        },
        {
            "check_area": "no_new_model_training_valid",
            "status": "ok" if step6_146_no_new_training_valid else "review",
            "value": str(step6_146_no_new_training_valid).lower(),
        },
        {
            "check_area": "no_live_inventory_claim_valid",
            "status": "ok" if step6_146_no_live_inventory_claim_valid else "review",
            "value": str(step6_146_no_live_inventory_claim_valid).lower(),
        },
        {
            "check_area": "map_engine_valid",
            "status": "ok" if step6_146_map_engine_valid else "review",
            "value": str(step6_146_map_engine_valid).lower(),
        },
        {
            "check_area": "navigation_tab_count_valid",
            "status": "ok" if step6_146_navigation_tab_count_valid else "review",
            "value": str(step6_146_navigation_tab_count_valid).lower(),
        },
        {
            "check_area": "navigation_tab_count",
            "status": "ok",
            "value": str(step6_146_main_navigation_tab_count),
        },
        {
            "check_area": "tab_contract_rows",
            "status": "ok",
            "value": str(step6_146_tab_count),
        },
        {
            "check_area": "missing_expected_tabs",
            "status": "ok" if len(step6_146_missing_expected_tabs) == 0 else "review",
            "value": str(len(step6_146_missing_expected_tabs)),
        },
        {
            "check_area": "extra_tabs",
            "status": "ok" if len(step6_146_extra_tabs) == 0 else "review",
            "value": str(len(step6_146_extra_tabs)),
        },
        {
            "check_area": "duplicate_tab_names",
            "status": "ok" if step6_146_duplicate_tab_names == 0 else "review",
            "value": str(step6_146_duplicate_tab_names),
        },
        {
            "check_area": "duplicate_tab_order",
            "status": "ok" if step6_146_duplicate_tab_order == 0 else "review",
            "value": str(step6_146_duplicate_tab_order),
        },
        {
            "check_area": "tab_order_continuous",
            "status": "ok" if step6_146_tab_order_continuous else "review",
            "value": str(step6_146_tab_order_continuous).lower(),
        },
        {
            "check_area": "required_input_artifacts_missing",
            "status": "ok" if step6_146_required_input_artifacts_missing == 0 else "review",
            "value": str(step6_146_required_input_artifacts_missing),
        },
        {
            "check_area": "required_acceptance_artifacts_missing",
            "status": "ok" if step6_146_required_acceptance_artifacts_missing == 0 else "review",
            "value": str(step6_146_required_acceptance_artifacts_missing),
        },
    ]
)

step6_146_app_contract_flat_df = pd.DataFrame(
    [
        {
            "contract_key": key,
            "contract_value": str(value),
        }
        for key, value in step6_146_app_contract.items()
    ]
).sort_values("contract_key").reset_index(drop=True)

step6_146_readiness_path = step6_146_reports_dir / "b6_74_application_consistency_validation.parquet"
step6_146_app_contract_flat_path = step6_146_reports_dir / "b6_74_application_contract_flat.parquet"
step6_146_tab_contract_view_path = step6_146_reports_dir / "b6_74_application_tab_contract_view.parquet"

step6_146_application_readiness_df.to_parquet(step6_146_readiness_path, index=False)
step6_146_app_contract_flat_df.to_parquet(step6_146_app_contract_flat_path, index=False)
step6_146_tab_contract_view_df.to_parquet(step6_146_tab_contract_view_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_146_application_readiness_df[column_name] = step6_146_application_readiness_df[column_name].astype("string")

display(step6_146_application_readiness_df)
display(step6_146_app_contract_flat_df)
display(step6_146_tab_contract_view_df)

                               check_area status value
0               missing_app_contract_keys     ok     0
1                  application_file_valid     ok  true
2                  application_name_valid     ok  true
3               station_detail_view_valid     ok  true
4                   single_app_role_valid     ok  true
5          user_facing_block_labels_valid     ok  true
6             no_new_model_training_valid     ok  true
7           no_live_inventory_claim_valid     ok  true
8                        map_engine_valid     ok  true
9              navigation_tab_count_valid     ok  true
10                   navigation_tab_count     ok     8
11                      tab_contract_rows     ok     8
12                  missing_expected_tabs     ok     0
13                             extra_tabs     ok     0
14                    duplicate_tab_names     ok     0
15                    duplicate_tab_order     ok     0
16                   tab_order_continuous     ok  true
17       required_input_artifacts_missing     ok     0
18  required_acceptance_artifacts_missing     ok     0

,contract_key,contract_value
0,application_file,aplikacja_panel_dyspozytora_rowerow.py
1,application_name,Panel dyspozytora relokacji rowerów
2,application_role,single_operational_application
3,daily_progress_tracking,True
4,driver_card_view,True
5,feedback_log_file,b6_operational_feedback_log.json
6,main_navigation_tabs,"['Plan dnia', 'Lista działań', 'Mikrostrefy', ..."
7,main_screen_language_style,dispatcher_operational_language
8,map_engine,folium
9,operational_feedback_loop,True
10,primary_user_language,polish
11,station_detail_view,True
12,technical_language_visibility,technical_tab_only
13,technical_model_panel_role,technical_support_tab
14,user_facing_block_labels_allowed,False
15,uses_google_maps_api,False
16,uses_live_inventory_claim,False
17,uses_new_model_training,False

,tab_order,tab_name,tab_role,main_user,technical_depth
0,1,Plan dnia,daily_operational_summary,dispatcher,low
1,2,Lista działań,full_operational_decision_table,dispatcher,low
2,3,Mikrostrefy,microzone_summary_and_local_pairing,dispatcher,medium
3,4,Mapa,spatial_action_view,dispatcher,low
4,5,Karta kierowcy,driver_task_cards,driver,low
5,6,Szczegóły stacji,station_operational_details,dispatcher,medium
6,7,Feedback,operational_feedback_loop,dispatcher_driver,medium
7,8,Model i dane,technical_model_and_data_support,technical_reviewer,high

In [91]:
# 6.14.7 Odbiór końcowy warstwy operacyjnej

from pathlib import Path

import pandas as pd


step6_147_required_objects = [
    "step6_11_reports_dir",
]

step6_147_missing_objects = [
    object_name
    for object_name in step6_147_required_objects
    if object_name not in globals()
]

assert not step6_147_missing_objects, f"Missing required objects: {step6_147_missing_objects}"

step6_147_reports_dir = Path(step6_11_reports_dir)

step6_147_validation_paths = {
    "artifact_inventory": step6_147_reports_dir / "b6_69_final_acceptance_artifact_inventory.parquet",
    "decision_language": step6_147_reports_dir / "b6_70_decision_language_validation.parquet",
    "relocation_quantity": step6_147_reports_dir / "b6_71_relocation_quantity_validation.parquet",
    "microzone_map": step6_147_reports_dir / "b6_72_microzone_map_final_validation.parquet",
    "driver_feedback_progress": step6_147_reports_dir / "b6_73_driver_feedback_progress_final_validation.parquet",
    "application_consistency": step6_147_reports_dir / "b6_74_application_consistency_validation.parquet",
}

step6_147_missing_validation_files = [
    path.name
    for path in step6_147_validation_paths.values()
    if not path.exists()
]

assert not step6_147_missing_validation_files, f"Missing validation files: {step6_147_missing_validation_files}"

step6_147_validation_frames = []

for step6_147_validation_area, step6_147_path in step6_147_validation_paths.items():
    step6_147_area_df = pd.read_parquet(step6_147_path).copy()
    step6_147_area_df.insert(0, "validation_area", step6_147_validation_area)
    step6_147_validation_frames.append(step6_147_area_df)

step6_147_all_validations_df = pd.concat(
    step6_147_validation_frames,
    ignore_index=True,
)

step6_147_status_summary_df = (
    step6_147_all_validations_df
    .groupby(["validation_area", "status"], dropna=False)
    .size()
    .reset_index(name="check_count")
    .sort_values(["validation_area", "status"])
    .reset_index(drop=True)
)

step6_147_review_checks_df = (
    step6_147_all_validations_df[
        step6_147_all_validations_df["status"] != "ok"
    ]
    .copy()
    .reset_index(drop=True)
)

step6_147_final_acceptance_checks = [
    {
        "acceptance_area": "artifact_completeness",
        "source_validation": "artifact_inventory",
        "required_status": "ok",
        "acceptance_role": "all_required_layers_available",
    },
    {
        "acceptance_area": "decision_language_readiness",
        "source_validation": "decision_language",
        "required_status": "ok",
        "acceptance_role": "decision_fields_and_labels_ready",
    },
    {
        "acceptance_area": "relocation_quantity_sanity",
        "source_validation": "relocation_quantity",
        "required_status": "ok",
        "acceptance_role": "relocation_quantities_within_contract",
    },
    {
        "acceptance_area": "microzone_and_map_readiness",
        "source_validation": "microzone_map",
        "required_status": "ok",
        "acceptance_role": "microzones_and_map_layers_ready",
    },
    {
        "acceptance_area": "driver_feedback_progress_readiness",
        "source_validation": "driver_feedback_progress",
        "required_status": "ok",
        "acceptance_role": "driver_cards_feedback_and_progress_ready",
    },
    {
        "acceptance_area": "application_contract_consistency",
        "source_validation": "application_consistency",
        "required_status": "ok",
        "acceptance_role": "single_application_contract_ready",
    },
]

step6_147_final_acceptance_df = pd.DataFrame(step6_147_final_acceptance_checks)

step6_147_area_status_df = (
    step6_147_all_validations_df
    .groupby("validation_area", dropna=False)
    .agg(
        total_checks=("check_area", "size"),
        ok_checks=("status", lambda series: int((series == "ok").sum())),
        review_checks=("status", lambda series: int((series != "ok").sum())),
    )
    .reset_index()
)

step6_147_final_acceptance_df = step6_147_final_acceptance_df.merge(
    step6_147_area_status_df,
    left_on="source_validation",
    right_on="validation_area",
    how="left",
)

step6_147_final_acceptance_df["acceptance_status"] = step6_147_final_acceptance_df[
    "review_checks"
].apply(lambda value: "ok" if int(value) == 0 else "review")

step6_147_total_checks = int(step6_147_all_validations_df.shape[0])
step6_147_total_review_checks = int(step6_147_review_checks_df.shape[0])
step6_147_acceptance_rows = int(step6_147_final_acceptance_df.shape[0])
step6_147_failed_acceptance_rows = int(
    (step6_147_final_acceptance_df["acceptance_status"] != "ok").sum()
)

step6_147_block6_ready = (
    step6_147_total_review_checks == 0
    and step6_147_failed_acceptance_rows == 0
)

step6_147_final_summary_df = pd.DataFrame(
    [
        {
            "check_area": "validation_areas",
            "status": "ok",
            "value": str(len(step6_147_validation_paths)),
        },
        {
            "check_area": "total_validation_checks",
            "status": "ok",
            "value": str(step6_147_total_checks),
        },
        {
            "check_area": "review_checks",
            "status": "ok" if step6_147_total_review_checks == 0 else "review",
            "value": str(step6_147_total_review_checks),
        },
        {
            "check_area": "acceptance_rows",
            "status": "ok",
            "value": str(step6_147_acceptance_rows),
        },
        {
            "check_area": "failed_acceptance_rows",
            "status": "ok" if step6_147_failed_acceptance_rows == 0 else "review",
            "value": str(step6_147_failed_acceptance_rows),
        },
        {
            "check_area": "block6_operational_layer_ready",
            "status": "ok" if step6_147_block6_ready else "review",
            "value": str(step6_147_block6_ready).lower(),
        },
    ]
)

step6_147_all_validations_path = step6_147_reports_dir / "b6_75_final_acceptance_all_validations.parquet"
step6_147_status_summary_path = step6_147_reports_dir / "b6_75_final_acceptance_status_summary.parquet"
step6_147_review_checks_path = step6_147_reports_dir / "b6_75_final_acceptance_review_checks.parquet"
step6_147_final_acceptance_path = step6_147_reports_dir / "b6_75_final_acceptance_decision.parquet"
step6_147_final_summary_path = step6_147_reports_dir / "b6_75_final_acceptance_summary.parquet"

step6_147_all_validations_df.to_parquet(step6_147_all_validations_path, index=False)
step6_147_status_summary_df.to_parquet(step6_147_status_summary_path, index=False)
step6_147_review_checks_df.to_parquet(step6_147_review_checks_path, index=False)
step6_147_final_acceptance_df.to_parquet(step6_147_final_acceptance_path, index=False)
step6_147_final_summary_df.to_parquet(step6_147_final_summary_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_147_final_summary_df[column_name] = step6_147_final_summary_df[column_name].astype("string")

display(step6_147_final_summary_df)
display(step6_147_final_acceptance_df)
display(step6_147_review_checks_df)

                       check_area status value
0                validation_areas     ok     6
1         total_validation_checks     ok    85
2                   review_checks     ok     0
3                 acceptance_rows     ok     6
4          failed_acceptance_rows     ok     0
5  block6_operational_layer_ready     ok  true

,acceptance_area,source_validation,required_status,acceptance_role,validation_area,total_checks,ok_checks,review_checks,acceptance_status
0,artifact_completeness,artifact_inventory,ok,all_required_layers_available,artifact_inventory,16,16,0,ok
1,decision_language_readiness,decision_language,ok,decision_fields_and_labels_ready,decision_language,9,9,0,ok
2,relocation_quantity_sanity,relocation_quantity,ok,relocation_quantities_within_contract,relocation_quantity,10,10,0,ok
3,microzone_and_map_readiness,microzone_map,ok,microzones_and_map_layers_ready,microzone_map,14,14,0,ok
4,driver_feedback_progress_readiness,driver_feedback_progress,ok,driver_cards_feedback_and_progress_ready,driver_feedback_progress,17,17,0,ok
5,application_contract_consistency,application_consistency,ok,single_application_contract_ready,application_consistency,19,19,0,ok

Empty DataFrame
Columns: [validation_area, artifact_group, artifact_role, file_name, required, resolved_path, file_exists, file_size_bytes, status, check_area, value]
Index: []

In [92]:
# 6.14.8 Finalny status odbioru i lista artefaktów przekazania

from pathlib import Path

import json
import pandas as pd


step6_148_required_objects = [
    "step6_11_reports_dir",
]

step6_148_missing_objects = [
    object_name
    for object_name in step6_148_required_objects
    if object_name not in globals()
]

assert not step6_148_missing_objects, f"Missing required objects: {step6_148_missing_objects}"

step6_148_reports_dir = Path(step6_11_reports_dir)

step6_148_expected_application_file = "aplikacja_panel_dyspozytora_rowerow.py"

step6_148_final_summary_path = step6_148_reports_dir / "b6_75_final_acceptance_summary.parquet"
step6_148_final_acceptance_path = step6_148_reports_dir / "b6_75_final_acceptance_decision.parquet"
step6_148_app_contract_path = step6_148_reports_dir / "b6_49_dispatcher_app_contract.json"
step6_148_input_artifacts_path = step6_148_reports_dir / "b6_50_dispatcher_app_input_artifacts.parquet"

step6_148_required_paths = [
    step6_148_final_summary_path,
    step6_148_final_acceptance_path,
    step6_148_app_contract_path,
    step6_148_input_artifacts_path,
]

step6_148_missing_files = [
    path.name
    for path in step6_148_required_paths
    if not path.exists()
]

assert not step6_148_missing_files, f"Missing required files: {step6_148_missing_files}"

step6_148_final_summary_df = pd.read_parquet(step6_148_final_summary_path)
step6_148_final_acceptance_df = pd.read_parquet(step6_148_final_acceptance_path)
step6_148_input_artifacts_df = pd.read_parquet(step6_148_input_artifacts_path)

with open(step6_148_app_contract_path, "r", encoding="utf-8") as file:
    step6_148_app_contract = json.load(file)

step6_148_app_contract["application_file"] = step6_148_expected_application_file

with open(step6_148_app_contract_path, "w", encoding="utf-8") as file:
    json.dump(step6_148_app_contract, file, ensure_ascii=False, indent=2)

step6_148_required_app_inputs = step6_148_input_artifacts_df[
    step6_148_input_artifacts_df["required"] == True
].copy()

step6_148_missing_required_app_inputs = int(
    (step6_148_required_app_inputs["file_exists"] == False).sum()
)

step6_148_failed_acceptance_rows = int(
    (step6_148_final_acceptance_df["acceptance_status"] != "ok").sum()
)

step6_148_review_summary_rows = int(
    (step6_148_final_summary_df["status"] != "ok").sum()
)

step6_148_ready_flag_series = step6_148_final_summary_df.loc[
    step6_148_final_summary_df["check_area"] == "block6_operational_layer_ready",
    "value",
]

step6_148_operational_layer_ready = (
    len(step6_148_ready_flag_series) == 1
    and str(step6_148_ready_flag_series.iloc[0]).lower() == "true"
)

step6_148_application_file = step6_148_app_contract.get("application_file", "")
step6_148_application_role = step6_148_app_contract.get("application_role", "")
step6_148_map_engine = step6_148_app_contract.get("map_engine", "")
step6_148_uses_new_training = step6_148_app_contract.get("uses_new_model_training", None)
step6_148_uses_live_inventory_claim = step6_148_app_contract.get("uses_live_inventory_claim", None)

step6_148_handoff_artifacts = [
    {
        "handoff_group": "main_operational_data",
        "artifact_role": "daily_operational_plan",
        "file_name": "b6_45_map_station_layer.parquet",
        "required_for_application": True,
    },
    {
        "handoff_group": "microzone_data",
        "artifact_role": "microzone_summary",
        "file_name": "b6_34_microzone_summary.parquet",
        "required_for_application": True,
    },
    {
        "handoff_group": "microzone_data",
        "artifact_role": "local_pairs",
        "file_name": "b6_35_microzone_local_pairs.parquet",
        "required_for_application": True,
    },
    {
        "handoff_group": "map_data",
        "artifact_role": "station_map_layer",
        "file_name": "b6_45_map_station_layer.parquet",
        "required_for_application": True,
    },
    {
        "handoff_group": "map_data",
        "artifact_role": "relocation_lines",
        "file_name": "b6_48_relocation_line_layer.parquet",
        "required_for_application": True,
    },
    {
        "handoff_group": "driver_cards",
        "artifact_role": "driver_task_layer",
        "file_name": "b6_57_driver_task_card_layer.parquet",
        "required_for_application": True,
    },
    {
        "handoff_group": "driver_cards",
        "artifact_role": "daily_driver_cards",
        "file_name": "b6_58_daily_driver_task_cards.parquet",
        "required_for_application": True,
    },
    {
        "handoff_group": "feedback",
        "artifact_role": "feedback_log",
        "file_name": "b6_operational_feedback_log.json",
        "required_for_application": True,
    },
    {
        "handoff_group": "application_contract",
        "artifact_role": "application_contract",
        "file_name": "b6_49_dispatcher_app_contract.json",
        "required_for_application": True,
    },
    {
        "handoff_group": "application_contract",
        "artifact_role": "tab_contract",
        "file_name": "b6_49_dispatcher_app_tab_contract.parquet",
        "required_for_application": True,
    },
    {
        "handoff_group": "application_contract",
        "artifact_role": "user_labels",
        "file_name": "b6_52_dispatcher_app_user_labels.parquet",
        "required_for_application": True,
    },
]

step6_148_handoff_df = pd.DataFrame(step6_148_handoff_artifacts)

step6_148_handoff_df["resolved_path"] = step6_148_handoff_df["file_name"].apply(
    lambda file_name: str(step6_148_reports_dir / file_name)
)

step6_148_handoff_df["file_exists"] = step6_148_handoff_df["file_name"].apply(
    lambda file_name: (step6_148_reports_dir / file_name).exists()
)

step6_148_handoff_df["file_size_bytes"] = step6_148_handoff_df["file_name"].apply(
    lambda file_name: (
        (step6_148_reports_dir / file_name).stat().st_size
        if (step6_148_reports_dir / file_name).exists()
        else 0
    )
)

step6_148_missing_handoff_artifacts = int(
    (
        (step6_148_handoff_df["required_for_application"] == True)
        & (step6_148_handoff_df["file_exists"] == False)
    ).sum()
)

step6_148_handoff_ready = (
    step6_148_operational_layer_ready
    and step6_148_failed_acceptance_rows == 0
    and step6_148_review_summary_rows == 0
    and step6_148_missing_required_app_inputs == 0
    and step6_148_missing_handoff_artifacts == 0
    and step6_148_application_file == step6_148_expected_application_file
    and step6_148_application_role == "single_operational_application"
    and step6_148_map_engine == "folium"
    and step6_148_uses_new_training is False
    and step6_148_uses_live_inventory_claim is False
)

step6_148_status_df = pd.DataFrame(
    [
        {
            "check_area": "operational_layer_ready",
            "status": "ok" if step6_148_operational_layer_ready else "review",
            "value": str(step6_148_operational_layer_ready).lower(),
        },
        {
            "check_area": "failed_acceptance_rows",
            "status": "ok" if step6_148_failed_acceptance_rows == 0 else "review",
            "value": str(step6_148_failed_acceptance_rows),
        },
        {
            "check_area": "review_summary_rows",
            "status": "ok" if step6_148_review_summary_rows == 0 else "review",
            "value": str(step6_148_review_summary_rows),
        },
        {
            "check_area": "missing_required_app_inputs",
            "status": "ok" if step6_148_missing_required_app_inputs == 0 else "review",
            "value": str(step6_148_missing_required_app_inputs),
        },
        {
            "check_area": "missing_handoff_artifacts",
            "status": "ok" if step6_148_missing_handoff_artifacts == 0 else "review",
            "value": str(step6_148_missing_handoff_artifacts),
        },
        {
            "check_area": "application_file",
            "status": "ok" if step6_148_application_file == step6_148_expected_application_file else "review",
            "value": step6_148_application_file,
        },
        {
            "check_area": "application_role",
            "status": "ok" if step6_148_application_role == "single_operational_application" else "review",
            "value": step6_148_application_role,
        },
        {
            "check_area": "map_engine",
            "status": "ok" if step6_148_map_engine == "folium" else "review",
            "value": step6_148_map_engine,
        },
        {
            "check_area": "uses_new_model_training",
            "status": "ok" if step6_148_uses_new_training is False else "review",
            "value": str(step6_148_uses_new_training).lower(),
        },
        {
            "check_area": "uses_live_inventory_claim",
            "status": "ok" if step6_148_uses_live_inventory_claim is False else "review",
            "value": str(step6_148_uses_live_inventory_claim).lower(),
        },
        {
            "check_area": "application_handoff_ready",
            "status": "ok" if step6_148_handoff_ready else "review",
            "value": str(step6_148_handoff_ready).lower(),
        },
    ]
)

step6_148_status_path = step6_148_reports_dir / "b6_76_application_handoff_status.parquet"
step6_148_handoff_path = step6_148_reports_dir / "b6_76_application_handoff_artifacts.parquet"

step6_148_status_df.to_parquet(step6_148_status_path, index=False)
step6_148_handoff_df.to_parquet(step6_148_handoff_path, index=False)

for column_name in ["check_area", "status", "value"]:
    step6_148_status_df[column_name] = step6_148_status_df[column_name].astype("string")

display(step6_148_status_df)
display(step6_148_handoff_df)

                     check_area status                                   value
0       operational_layer_ready     ok                                    true
1        failed_acceptance_rows     ok                                       0
2           review_summary_rows     ok                                       0
3   missing_required_app_inputs     ok                                       0
4     missing_handoff_artifacts     ok                                       0
5              application_file     ok  aplikacja_panel_dyspozytora_rowerow.py
6              application_role     ok          single_operational_application
7                    map_engine     ok                                  folium
8       uses_new_model_training     ok                                   false
9     uses_live_inventory_claim     ok                                   false
10    application_handoff_ready     ok                                    true

,handoff_group,artifact_role,file_name,required_for_application,resolved_path,file_exists,file_size_bytes
0,main_operational_data,daily_operational_plan,b6_45_map_station_layer.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,11555208
1,microzone_data,microzone_summary,b6_34_microzone_summary.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3558017
2,microzone_data,local_pairs,b6_35_microzone_local_pairs.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,6584
3,map_data,station_map_layer,b6_45_map_station_layer.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,11555208
4,map_data,relocation_lines,b6_48_relocation_line_layer.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,10109
5,driver_cards,driver_task_layer,b6_57_driver_task_card_layer.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,4901200
6,driver_cards,daily_driver_cards,b6_58_daily_driver_task_cards.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,30682
7,feedback,feedback_log,b6_operational_feedback_log.json,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,61
8,application_contract,application_contract,b6_49_dispatcher_app_contract.json,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,957
9,application_contract,tab_contract,b6_49_dispatcher_app_tab_contract.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,3914
10,application_contract,user_labels,b6_52_dispatcher_app_user_labels.parquet,True,/root/projects/6_samodzielny_projekt_koncowy_w...,True,4676

# Podsumowanie działu 6.14 Odbiór końcowy warstwy operacyjnej

**Kontekst inżynieryjny:** W dziale `6.14` przeprowadzono końcową walidację warstwy operacyjnej przygotowanej pod aplikację dyspozytorską. Odbiór objął kompletność artefaktów, spójność pól decyzyjnych, kontrolę ilości relokacji, mikrostrefy, warstwę mapową, karty kierowcy, feedback, postęp dnia oraz kontrakt jednej aplikacji. Celem było potwierdzenie, że przygotowane dane, kontrakty i artefakty są gotowe do wykorzystania w pliku aplikacyjnym `aplikacja_panel_dyspozytora_rowerow.py`.

**Interpretacja wyniku:** Walidacja końcowa została zakończona poprawnie. Sprawdzono `6` głównych obszarów odbioru oraz `85` kontrole szczegółowe. Wszystkie kontrole zakończyły się statusem `ok`, bez żadnych pozycji wymagających przeglądu. Potwierdzono kompletność głównych artefaktów, poprawność pól decyzyjnych i etykiet, spójność ilości relokacji, poprawność kontraktu mikrostref i mapy, gotowość kart kierowcy, strukturę feedbacku oraz działanie mechanizmu postępu dnia. Finalny status `block6_operational_layer_ready = true` potwierdza gotowość warstwy operacyjnej.

**Znaczenie biznesowe:** Przygotowana warstwa przekłada dane techniczne na uporządkowany plan operacyjny dla dyspozytora i kierowcy. System wskazuje priorytety dnia, typ problemu, rekomendowane działanie, szacowaną relokację, godzinę ryzyka oraz wpływ operacyjny. Osobna zakładka `Szczegóły stacji` zapewnia dyspozytorowi czytelny dostęp do uzasadnienia rekomendacji dla konkretnej stacji, bez konieczności szukania tych informacji w widoku technicznym. Karty kierowcy upraszczają wykonanie zadań, feedback umożliwia zbieranie informacji z terenu, a pasek postępu pozwala kontrolować realizację dnia. Jednocześnie zachowano uczciwe ograniczenia: aplikacja nie trenuje nowego modelu, nie udaje dokładnego stanu live inventory i korzysta z mapy opartej na `folium`, bez Google Maps API.

**Wniosek:** Dział `6.14` został zakończony poprawnie. Warstwa operacyjna jest gotowa do przekazania do aplikacji `aplikacja_panel_dyspozytora_rowerow.py`. Finalny kontrakt aplikacji obejmuje `8` zakładek: `Plan dnia`, `Lista działań`, `Mikrostrefy`, `Mapa`, `Karta kierowcy`, `Szczegóły stacji`, `Feedback` oraz `Model i dane`. Finalne kontrole potwierdziły `operational_layer_ready = true`, `application_handoff_ready = true`, `failed_acceptance_rows = 0`, `review_summary_rows = 0` oraz `missing_handoff_artifacts = 0`. Następnym etapem jest implementacja aplikacji `.py`, która wykorzysta przygotowane artefakty do prezentacji planu dnia, listy działań, mikrostref, mapy, kart kierowcy, szczegółów stacji, feedbacku oraz widoku technicznego.